/**
 * GENERATED by `apps/ui/scripts/generate-legal-data.mjs` from `apps/ui/legal/lv/terms-of-service.md`.
 * Do not edit by hand: edit the draft and run `pnpm generate:legal`.
 *
 * The document as DATA. The modal that shows it renders from this module and holds no legal
 * prose of its own. Square brackets are the draft's own marks for what counsel still has to
 * fill in; they are rendered verbatim so the product never claims a fact the draft does not.
 */

import type { LegalDocument, LegalJump, LegalSection } from "../../legalDocument.js";

export const TERMS_JUMP: readonly LegalJump[] = [
  { label: "KAS MĒS ESAM", target: "terms-section-01" },
  { label: "PIEKRIŠANA", target: "terms-section-03" },
  { label: "KAS TAS IR", target: "terms-section-05" },
  { label: "JŪSU KONTS", target: "terms-section-06" },
  { label: "PIEŅEMAMA LIETOŠANA", target: "terms-section-07" },
  { label: "JŪSU SATURS", target: "terms-section-08" },
  { label: "PUBLICĒŠANA", target: "terms-section-09" },
  { label: "ZIŅOŠANA", target: "terms-section-10" },
  { label: "ATBILDĪBA", target: "terms-section-15" },
  { label: "PIEMĒROJAMIE TIESĪBU AKTI", target: "terms-section-18" }
];

export const TERMS_SECTIONS: readonly LegalSection[] = [
  {
    no: "00",
    title: "Īsumā",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Jums jābūt vismaz 18 gadus vecam. DebateAI veido argumentus ar MI modeļiem, un viss, ko tas ģenerē, var būt nepareizs — tā nav konsultācija. Jūsu debates ir privātas, ja vien tās nepublicējat; ja tās publicējat, ikviens tās var lasīt. Jūsu iesniegtais teksts tiek nosūtīts mūsu Pakalpojumu sniedzēju reģistrā norādītajiem MI pakalpojumu sniedzējiem un netiek izmantots modeļu apmācīšanai. Par nelikumīgu saturu ziņojiet uz support@dezbatere.ro neatkarīgi no tā, vai jums ir konts. Piemēro Rumānijas tiesību aktus, taču jums joprojām ir vietējā patērētāju aizsardzība." }
    ]
  },
  {
    no: "01",
    title: "Kas mēs esam un kā ar mums sazināties",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "DebateAI darbību nodrošina DMS Merchandise Shop S.R.L., Rumānijā reģistrēts uzņēmums." },
      {
        kind: "list",
        items: [
        "Juridiskā adrese — Str. 1 Decembrie 1918 nr. 80A, Piatra Neamț, Rumānija",
        "Komercreģistra numurs — J2022000426271",
        "Vienotais reģistrācijas kods (CUI) — 45935221 · PVN: RO45935221",
        "Pamatkapitāls — 5000 RON",
        "Vispārīga saziņa — support@dezbatere.ro",
        "Tālrunis — +40 748 793 490",
        "Juridiski paziņojumi — support@dezbatere.ro",
        "Privātums un datu aizsardzība — privacy@dezbatere.ro",
        "Ziņošana par nelikumīgu saturu — support@dezbatere.ro — skatiet 10. sadaļu",
        "Iestāžu kontaktpunkts — office@dezbatere.ro — rumāņu un angļu valodā",
        "Teroristiska satura izņemšanas rīkojumi (Regula (ES) 2021/784) — office@dezbatere.ro — mūsu kontaktpunkts šiem rīkojumiem; rumāņu un angļu valodā; skatiet 10. sadaļu",
        "Pārstāvji citās valstīs — Norādīti A pielikumā attiecībā uz reģioniem, kuros esam tādus iecēluši"
        ]
      },
      { kind: "p", text: "Šī informācija ir arī pastāvīgi redzama vietnē dezbatere.ro/legal. Jūs vienmēr varat sazināties ar cilvēku, ne tikai ar mūsu asistentu; 10. sadaļā paskaidrots, kā to izdarīt." }
    ]
  },
  {
    no: "02",
    title: "Kur mēs piedāvājam DebateAI",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Mēs piedāvājam DebateAI personām, kuras dzīvo Eiropas Savienībā (27 valstis) un Eiropas Ekonomikas zonā (Norvēģijā, Islandē un Lihtenšteinā), Šveicē, Moldovā, Amerikas Savienotajās Valstīs (izņemot Tenesī), Kanādā, Austrālijā, Jaunzēlandē, Singapūrā, Japānā, Dienvidkorejā un Taivānā. Citviet mēs to nepiedāvājam. Ja dzīvojat ārpus šīm valstīm, iespējams, varat piekļūt vietnei, taču mēs nevēršam pakalpojumu uz jums, nepieņemam no jums maksājumus, un šie Noteikumi un mūsu Privātuma politika nav pielāgoti jūsu valsts tiesību aktiem. A pielikumā noteikts, kas attiecas uz katru mūsu apkalpoto reģionu." }
    ]
  },
  {
    no: "03",
    title: "Piekrišana šiem Noteikumiem",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Jūs piekrītat šiem Noteikumiem, atzīmējot izvēles rūtiņu „Esmu izlasījis(-usi) un piekrītu Pakalpojuma noteikumiem” un noklikšķinot uz Izveidot kontu. Tādējādi starp jums un DMS Merchandise Shop S.R.L. tiek noslēgts līgums. Noteikumos ietverti pieņemamas lietošanas noteikumi 7. sadaļā, publicēšanas noteikumi 9. sadaļā, atbildības noteikumi 15. sadaļā un piemērojamo tiesību aktu un strīdu noteikumi 18. sadaļā. Mēs glabājam informāciju par to, kurai versijai un kad piekritāt, kā paskaidrots mūsu Privātuma politikā." },
      { kind: "p", text: "Mūsu Privātuma politikā vietnē dezbatere.ro/privacy paskaidrots, kā mēs rīkojamies ar personas datiem. Tā ir informācija, kas mums jums jāsniedz, nevis līgums, kuram jūs piekrītat, un nekas šajos Noteikumos to nepārvērš par piekrišanu apstrādei. Mūsu Sīkdatņu politika vietnē dezbatere.ro/cookies un mūsu MI pakalpojumu sniedzēju reģistrs vietnē dezbatere.ro/providers ar atsauci ir šo Noteikumu sastāvdaļa." },
      { kind: "p", text: "Pirms elektroniski noslēdzat ar mums līgumu, saskarne parāda veicamās darbības, ļauj pirms iesniegšanas pārskatīt un izlabot ievadīto informāciju un informē par valodām, kurās līgumu var noslēgt. Šie Noteikumi ir pieejami formā, ko varat saglabāt un izdrukāt, iegādājoties maksas plānu, mēs pa e-pastu nosūtām jums versiju, kurai piekritāt, un jūs jebkurā laikā varat pieprasīt kopiju. Nekas šajos Noteikumos neierobežo tādas jūsu tiesības saskaņā ar Rumānijas vai ES patērētāju tiesībām vai jūsu dzīvesvietas valsts tiesībām, kuras nevar ierobežot ar līgumu." }
    ]
  },
  {
    no: "04",
    title: "Kas drīkst lietot DebateAI",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Lai izveidotu kontu, jums jābūt vismaz 18 gadus vecam, un reģistrējoties jūs to apliecināt. DebateAI nav paredzēts bērniem, un mēs apzināti to nesniedzam personām, kas jaunākas par 18 gadiem. Ja uzzinām, ka konts pieder personai, kas jaunāka par 18 gadiem, mēs to slēdzam. Dažos reģionos ar apliecinājumu vien nepietiek; A pielikumā norādīts, kas attiecīgajā vietā ir piemērojams." },
      { kind: "p", text: "Jums jābūt rīcībspējīgam, lai noslēgtu šo līgumu. Ja DebateAI lietojat kādas organizācijas vārdā, jūs apliecināt, ka esat pilnvarots uzņemties saistības tās vārdā, un tad „jūs” nozīmē šo organizāciju." },
      { kind: "p", text: "Ikviens drīkst lasīt publicētas debates. Lasīšanai konts nav vajadzīgs, taču tā ir pakalpojuma lietošana, un uz to attiecas 7., 15., 16. un 18. sadaļa." }
    ]
  },
  {
    no: "05",
    title: "Ko DebateAI dara un kas tas nav",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Jūs iesniedzat jautājumu vai apgalvojumu. DebateAI to nosūta vairākiem trešo personu MI modeļiem, kas ap to izveido argumentu grafu: apgalvojumus, pretargumentus, kritiku, atsauces uz pierādījumiem, vērtējumus un spriedumu ar ticamības pakāpi. Varat apstrīdēt atsevišķus apgalvojumus, lūgt jautājumu izpētīt sīkāk un izlemt, vai rezultātu publicēt." },
      { kind: "p", text: "Visu debašu saturu ģenerē MI. Argumentus, kritiku, atsauces uz pierādījumiem, vērtējumus, spriedumus un atbalsta asistenta atbildes ģenerē mašīna. Tie var būt nepareizi, nepilnīgi, novecojuši vai pārliecinoši kļūdaini, un tajos var izpausties modeļu aizspriedumi. Neviena persona tos nepārskata, pirms tie tiek parādīti jums vai publicēti, un neviena vārdā nosaukta persona neuzņemas par tiem redakcionālu atbildību. Ģenerētais saturs produktā, publicētajās lapās un eksportētajos materiālos ir marķēts kā MI ģenerēts." },
      { kind: "p", text: "DebateAI nav konsultācija. Tā nav juridiska, medicīniska, finanšu, nodokļu, psiholoģiska, drošības vai cita profesionāla konsultācija, un spriedums nav fakta konstatējums. Neizmantojiet debates kā pamatu lēmumam, kas ir būtisks jūsu veselībai, drošībai, naudai, tiesiskajam stāvoklim vai citu personu labklājībai, nepārbaudot pirmavotus un attiecīgā gadījumā nekonsultējoties ar kvalificētu speciālistu. Augsta ticamības pakāpe nozīmē, ka modeļi, pamatojoties uz apskatīto materiālu, uzskatīja interpretāciju par labi nostiprinātu; tas negarantē tās patiesumu." },
      { kind: "p", text: "Ko mēs apņemamies. Mēs sniegsim pakalpojumu ar pienācīgu rūpību un prasmi un atbilstoši mūsu publicētajam aprakstam. Ja tiesību akti jums piešķir garantiju, ka pakalpojums atbilst tā aprakstam un ir piemērots parastajam nolūkam, šī garantija ir spēkā un nekas šajos Noteikumos to neatceļ. Mēs neapsolām, ka konkrēts rezultāts būs precīzs: tā ir ģenerētā satura īpašība, nevis pakalpojuma darbības rādītājs." },
      { kind: "p", text: "Modeļi mainās. Mēs varam pievienot, noņemt vai aizstāt izmantotos MI modeļus un mainīt veidu, kā dzinējs veido atbildi. 14. sadaļā paskaidrots, kad izmaiņas jums piešķir tiesības." }
    ]
  },
  {
    no: "06",
    title: "Jūsu konts",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Jūs reģistrējaties, izmantojot e-pasta adresi, paroli, atkopšanas e-pasta adresi un divfaktoru autentifikāciju, kas ir obligāta. Mēs jums nejauši piešķiram pseidonīmu, kas tiek rādīts pie visa, ko publicējat. To nevar mainīt. Glabājiet drošībā savu paroli, autentifikācijas lietotni un atkopšanas kodus. Jūs atbildat par darbībām savā kontā, izņemot gadījumus, kad tās radušās mūsu vainas dēļ." },
      { kind: "p", text: "Jums drīkst būt viens konts, ja vien neesam vienojušies citādi. Nekopīgojiet, nepārdodiet un nenododiet to citai personai." },
      { kind: "p", text: "Ja zaudējat piekļuvi, konta atkopšana notiek saskaņā ar produktā publicēto procesu, kurā ietverti gaidīšanas periodi, kas paredzēti, lai apgrūtinātu konta pārņemšanu. Mēs varam noraidīt atkopšanas pieprasījumu, ja nevaram pamatoti konstatēt, ka tas nāk no jums." },
      { kind: "p", text: "Jebkurā laikā varat slēgt kontu sadaļā Iestatījumi → Konts. Slēgšana stājas spēkā pēc 7 dienu labvēlības perioda, kura laikā varat to atcelt, un mēs jūs informējam visos jūsu reģistrētajos saziņas kanālos. 11. sadaļā paskaidrots, ko slēgšana dzēš un ko tā nedzēš." }
    ]
  },
  {
    no: "07",
    title: "Pieņemama lietošana",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Šie noteikumi attiecas uz jūsu iesniegto saturu, pakalpojuma lietošanu un publicēto saturu." },
      { kind: "p", text: "Neiesniedziet citu personu datus. Jautājiet par problēmām, argumentiem un sabiedriski nozīmīgiem jautājumiem, nevis par identificējamām privātpersonām. Neiekļaujiet vārdus, kontaktinformāciju, identifikācijas numurus, attēlus, veselības, finanšu vai citus datus, kas identificē personu, un neizmantojiet DebateAI, lai izveidotu lietu, profilu vai dosjē par kādu personu. Jautājumi par publiskām personām, kas darbojas publiskā statusā, ir pieņemami; jautājumi, kas vērsti pret privātpersonu, nav pieņemami. Ja tomēr iesniedzat šādus datus, jūs par tiem atbildat, un mēs varam saturu noņemt." },
      { kind: "p", text: "Jūsu sensitīvā informācija. Jūsu uzdotie jautājumi var skart jūsu veselību, pārliecību, politiskos uzskatus vai citas sensitīvas tēmas. Šādas informācijas apstrādei jūs piekrītat atsevišķā ekrānā pirms savām pirmajām debatēm. Ja dzīvojat vietā, kur veselības datiem ir īpaši noteikumi, A pielikumā var būt norāde uz atsevišķu paziņojumu." },
      { kind: "p", text: "Neiesniedziet un nepublicējiet nelikumīgu saturu, tostarp saturu, kas ir neslavu ceļošs, mudina uz vardarbību vai naidu, aizskar vai draud, ir bez piekrišanas kopīgoti intīmi attēli, pārkāpj intelektuālā īpašuma tiesības vai konfidencialitāti, izpauž komercnoslēpumus, ir materiāls, kurā atspoguļota bērnu seksuāla izmantošana, vai pārkāpj sankcijas vai eksporta kontroli." },
      { kind: "p", text: "Neizmantojiet DebateAI maldināšanai. Neuzdodiet ģenerēto rezultātu par cilvēka rakstītu, ja tas maldinātu, nenoņemiet MI ģenerēta satura marķējumu un neizmantojiet to šķietamas vienprātības, viltotu pierādījumu vai citas personas atdarināšanas radīšanai." },
      { kind: "p", text: "Neuzbrūciet pakalpojumam. Publicētās debates drīkst ierasti indeksēt meklētājprogrammas, taču citai automatizētai piekļuvei, datu izgūšanai, pārmeklēšanai vai masveida ieguvei nepieciešama mūsu rakstiska atļauja; nav atļauts apiet pieprasījumu biežuma ierobežojumus, autentifikāciju vai publicēšanas kontroli; mēģināt iegūt uzvednes vai sistēmas norādījumus; izmantot uzvedņu injekciju, lai panāktu, ka dzinējs ignorē ierobežojumus; veikt zondēšanu vai slodzes testēšanu bez mūsu rakstiskas atļaujas." },
      { kind: "p", text: "Nepārdodiet un nepārzīmolojiet pakalpojumu un neizmantojiet to konkurējoša dzinēja izveidei, tostarp izmantojot rezultātus kā apmācības datus, bez mūsu rakstiskas vienošanās." },
      { kind: "p", text: "Neizmantojiet DebateAI lēmumiem par personas veselību, drošību, likumiskajām tiesībām, nodarbinātību, kredītu, mājokli vai imigrācijas statusu. Tas nav šim nolūkam izveidots, un tā rezultāti nav drošs pamats šādiem lēmumiem." },
      { kind: "p", text: "Vietējie tiesību akti publicēšanas vietā. Jūs atbildat par to, lai viss jūsu publicētais atbilstu tās valsts tiesību aktiem, kurā atrodaties. Dažos reģionos mēs varam ierobežot noteiktu tēmu publicēšanu." },
      { kind: "p", text: "Ja neesat pārliecināts, vai kaut kas ir atļauts, pirms publicēšanas jautājiet mums." }
    ]
  },
  {
    no: "08",
    title: "Jūsu saturs un MI pakalpojumu sniedzēji, kas to apstrādā",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Jūsu saturs paliek jūsu īpašums. Jūs saglabājat visas tiesības, kas jums ir uz iesniegtajiem jautājumiem, apgalvojumiem, piezīmēm un iebildumiem. Jūs piešķirat mums neekskluzīvu, visā pasaulē spēkā esošu bezatlīdzības licenci mitināt, glabāt, reproducēt, pielāgot un apstrādāt šo saturu pakalpojuma darbības nodrošināšanai: debašu norisei, to glabāšanai, lai jūs tās varētu atkārtoti atvērt un atskaņot, atbalsta sniegšanai, mūsu juridisko pienākumu izpildei un — tikai tad, ja izvēlaties publicēt, — 9. sadaļā minētajiem nolūkiem. Šī licence beidzas, kad saturs ir dzēsts, izņemot 9. sadaļā vai tiesību aktos noteiktos gadījumus." },
      { kind: "p", text: "Mēs neapmācām modeļus ar jūsu saturu. Mēs neapmācām modeļus ar jūsu saturu. MI pakalpojumu sniedzējus izmantojam tikai ar noteikumiem, kas neļauj tiem izmantot jūsu saturu savu modeļu apmācībai vai uzlabošanai; Reģistrā katram pakalpojumu sniedzējam ir norādīts, vai mēs to esam pārbaudījuši, un kad." },
      { kind: "p", text: "Kā jūsu saturs nonāk pie MI pakalpojumu sniedzējiem. Lai īstenotu debates, mēs nosūtām tekstu vienam vai vairākiem ārējiem modeļu pakalpojumu sniedzējiem. Pakalpojumu sniedzējs saņem jūsu jautājumu, jūsu iestatītās vadības piezīmes un apgalvojumus, ko dzinējs debašu laikā izveido, — tādēļ pakalpojumu sniedzējs redz tekstu, kas atvasināts no jūsu ievadītā un veidots ap to, ne tikai jūsu sākotnējos vārdus. Tas nekad nesaņem jūsu e-pasta adresi, konta identifikatorus, sesiju ierakstus vai maksājumu informāciju." },
      { kind: "p", text: "Ko nosūta atbalsta tērzēšana. Arī atbalsta asistents ir MI modelis. Kad jūs tam rakstāt, mēs nosūtām jūsu ziņojumu ārējam modeļu pakalpojumu sniedzējam, lai modelis varētu atbildēt, kopā ar palīdzības rakstiem, uz kuriem tas balsta atbildi. Pirms nosūtīšanas mēs maskējam visu, kas izskatās pēc paroles, vienreizēja koda vai atslēgas. Ja lūdzat sazināties ar cilvēku, mēs modelim nosūtām arī sarunu, maskētu tādā pašā veidā, lai tas uzrakstītu īsu kopsavilkumu mūsu komandas dalībniekam, kurš pārņem jūsu lietu. Mēs nepievienojam jūsu e-pasta adresi, konta identifikatorus vai maksājumu informāciju, taču modelis saņem visu pārējo, ko ierakstāt tērzēšanā, tāpēc nerakstiet tur neko, ko nevēlaties, lai tas izlasītu." },
      { kind: "p", text: "Kuri pakalpojumu sniedzēji un kur. Mūsu MI pakalpojumu sniedzēju reģistrs vietnē dezbatere.ro/providers ir šo Noteikumu sastāvdaļa. Tajā par katru iespējamo pakalpojumu sniedzēju norādīts: tā juridiskā persona un valsts; ko un kādēļ tas saņem; kur tas veic apstrādi; tā glabāšanas noteikumi; vai mūsu izmantotajam galapunktam ir ieslēgts datu neglabāšanas režīms; vai saskaņā ar mūsu līgumu tas drīkst izmantot ievaddatus apmācībai; mūsu izmantotais nosūtīšanas mehānisms; un datums, kad pēdējoreiz pārbaudījām katru ierakstu. Pakalpojumu sniedzēji var atrasties ārpus jūsu valsts un Eiropas Ekonomikas zonas. Mūsu Privātuma politikā paskaidroti aizsardzības pasākumi." },
      { kind: "p", text: "Trīs atšķirīgas lietas. „Netiek izmantots modeļu apmācīšanai”, „ierobežotu laiku tiek glabāts drošības, ļaunprātīgas izmantošanas novēršanas vai juridisku iemeslu dēļ” un „datu neglabāšanas režīms — pēc apstrādes netiek saglabāts” ir atšķirīgas lietas. Ja pakalpojumu sniedzējs uzvednes glabā ierobežotu laiku, Reģistrā ir norādīts, cik ilgi un kādēļ. Ja ir ieslēgts datu neglabāšanas režīms, Reģistrā norādīts gan tas, gan attiecīgās funkcijas. Mēs neapgalvosim, ka saturs netiek glabāts, ja tas tiek glabāts." },
      { kind: "p", text: "Rezultāti. Attiecībās starp jums un mums jūs drīkstat savu debašu rezultātu izmantot jebkuram likumīgam nolūkam, un mēs nepretendējam uz īpašumtiesībām uz ģenerēto tekstu. Ņemiet vērā, ka daudzās jurisdikcijās ģenerēto rezultātu autortiesības var neaizsargāt; ka līdzīgs rezultāts var tikt ģenerēts citiem lietotājiem; ka rezultāti var reproducēt trešo personu materiālus vai tiem līdzināties; un ka uz atsevišķiem avotu materiāliem, ko izgūst MI pakalpojumu sniedzējs, var attiekties atkārtotas izmantošanas ierobežojumi. Pirms paļaujaties uz rezultātiem vai tos pārpublicējat, jums tie jāpārbauda." }
    ]
  },
  {
    no: "09",
    title: "Debašu publicēšana",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Debates pēc noklusējuma ir privātas. Nekas no jūsu izveidotā nav redzams citām personām, ja vien to nepublicējat." },
      { kind: "p", text: "Ko dara publicēšana. Publicēšana ir apzināta darbība, ko apstiprina atsevišķi. Kad publicējat, mēs izveidojam fiksētu debašu momentuzņēmumu un ļaujam ikvienam to lasīt bez konta. Meklētājprogrammas to var indeksēt. Momentuzņēmumā redzams jūsu pseidonīms, jūsu jautājums tādā formā, kādā to uzrakstījāt, argumentu koks, vērtējumi, spriedums un ticamības pakāpe, kā arī redzams marķējums, ka saturu ģenerējis MI. Tajā nav redzama jūsu e-pasta adrese, sesiju ieraksti vai konta vēsture." },
      { kind: "p", text: "Praksē publicēšana faktiski ir neatgriezeniska. Kad debates kļūst publiskas, citas personas tās var lasīt, citēt, uzņemt to ekrānuzņēmumus, arhivēt un saglabāt kešatmiņā. Publikācijas atcelšana noņem tās no DebateAI un iznīcina mūsu kopijas atslēgu, taču nevar sasniegt kopijas, kas jau atrodas citviet. Nepublicējiet neko tādu, ko nevēlētos pastāvīgi saistīt ar savu pseidonīmu." },
      { kind: "p", text: "Publicētās debates, kad slēdzat kontu. Plānojot konta slēgšanu, jūs izvēlaties, kas notiks ar jūsu publicētajām debatēm. Ja atzīmēsiet „Dzēst arī manas publiskās debates”, slēgšanas laikā katras debates noņemsim no DebateAI un iznīcināsim savas kopijas atslēgu, kā tas notiek, atsaucot publikāciju, ja vien likums neliek saglabāt konkrētu vienumu. Ja lodziņu neatzīmēsiet, debates paliks publiskas ar jūsu vairs neizmantoto pseidonīmu. Kopijas, ko citi izveidojuši pirms noņemšanas, nav mūsu kontrolē. Ja vēlaties noņemamās debates saglabāt sev, vispirms tās lejupielādējiet." },
      { kind: "p", text: "Mēs vienmēr varam noņemt publicētu saturu. Mēs varam noņemt publicētas debates vai ierobežot piekļuvi tām, ja to prasa tiesību akti, ja to uzdod tiesa vai kompetenta iestāde vai ja tās pārkāpj šos Noteikumus vai ir nelikumīgas. Nekas šajā sadaļā neliedz mums rīkoties pēc derīga paziņojuma saskaņā ar 10. sadaļu, un nekas tajā nav solījums, ka publicētas debates paliks pieejamas." },
      { kind: "p", text: "Publicēta satura licence. Publicējot jūs piešķirat mums neekskluzīvu, visā pasaulē spēkā esošu bezatlīdzības licenci mitināt, glabāt, reproducēt, attēlot un padarīt momentuzņēmumu publiski pieejamu, kā arī ļaut citiem to lasīt un citēt tik ilgi, kamēr tas ir publicēts. Šī licence pastāv, lai mēs varētu nodrošināt publisko lapu darbību; tā neļauj mums pārdot jūsu saturu vai licencēt to citas personas produktam." },
      { kind: "p", text: "Ja debates ir par jums. Ja publicētās debatēs ir jūsu personas dati vai tās ceļ jums neslavu vai citādi ir nelikumīgas, varat lūgt tās noņemt neatkarīgi no tā, vai jums ir konts, izmantojot 10. sadaļā noteikto kārtību vai rakstot uz privacy@dezbatere.ro. Mēs rīkojamies pēc pamatotiem pieprasījumiem un neprasām jums reģistrēties, lai tādu iesniegtu." }
    ]
  },
  {
    no: "10",
    title: "Ziņošana par saturu, moderēšana un sūdzības",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Ikviens var ziņot par saturu. Konts nav vajadzīgs. Rakstiet uz support@dezbatere.ro vai izmantojiet vadīklu Ziņot pie jebkurām publicētām debatēm. Lai mēs varētu rīkoties, norādiet: kādēļ uzskatāt, ka saturs ir nelikumīgs vai pārkāpj šos Noteikumus, pietiekami detalizēti, lai varētu saprast prasījumu; precīzu atrašanās vietu — pilnu URL un, ja iespējams, fragmentu; savu vārdu un e-pasta adresi (tas nav nepieciešams ziņojumiem par materiālu, kurā atspoguļota bērnu seksuāla izmantošana); un apliecinājumu, ka labticīgi uzskatāt savu ziņojumu par precīzu un pilnīgu." },
      { kind: "p", text: "Mēs bez nepamatotas kavēšanās apstiprinām katra ziņojuma saņemšanu. Mēs izskatām ziņojumus savlaicīgi, rūpīgi, nepatvaļīgi un objektīvi, paziņojam jums savu lēmumu un izskaidrojam, kā to apstrīdēt. Ja ziņojuma apstrādei vai lēmuma pieņemšanai izmantojam automatizētus līdzekļus, mēs to norādām. Pēc derīga pieprasījuma par bez piekrišanas kopīgotiem intīmiem attēliem mēs rīkojamies 48 stundu laikā." },
      { kind: "p", text: "Divu veidu automatizēti lēmumi, kas tiek nošķirti." },
      {
        kind: "list",
        items: [
        "Lēmumi dzinēja iekšienē. Dzinējs pieņem mašīnas lēmumus par argumentiem: tas var atteikties atbildēt uz jautājumu, noslēgt debates gala stāvoklī — piemēram, ja jautājums balstīts uz nepatiesu pieņēmumu vai ir vērtību jautājums, nevis empīrisks jautājums — ierobežot ticamības pakāpi, ja nebija pieejama neatkarīga kritika, vai atzīmēt atbildi kā defektīvu, ja ģenerētais teksts neizturēja atbilstības pārbaudi. Tā ir paredzētā produkta darbība; tā jums ir redzama debatēs, un tie nav lēmumi par jums.",
        "Moderēšanas lēmumi par saturu un kontiem. Publicētu debašu noņemšana vai piekļuves ierobežošana, kā arī konta darbības apturēšana vai konta slēgšana ir lēmums, ko pieņemam saskaņā ar šiem Noteikumiem vai tiesību aktiem. Katrā šādā lēmumā, kas ietekmē jūsu kontu, piedalās persona. Šādu lēmumu pamati ir aprakstīti 11. sadaļā."
        ]
      },
      { kind: "p", text: "Pamatojums. Ikreiz, kad noņemam jūsu saturu vai ierobežojam tā redzamību vai apturam vai izbeidzam jūsu konta darbību, mēs sniedzam pamatojumu: ko izdarījām un kāds ir darbības apjoms, faktus, uz kuriem balstījāmies, un vai tie iegūti no ziņojuma vai mūsu pašu pārbaudēm, vai tika izmantoti automatizēti līdzekļi, juridisko vai līgumisko pamatu un kā varat lēmumu apstrīdēt: izmantojot tālāk aprakstīto sūdzību kārtību, vēršoties saskaņā ar ES Digitālo pakalpojumu aktu sertificētā ārpustiesas strīdu izšķiršanas iestādē vai vēršoties tiesā." },
      { kind: "p", text: "Sūdzība par lēmumu. Ja nepiekrītat moderēšanas lēmumam, atbildiet uz pamatojumu vai sešu mēnešu laikā rakstiet uz office@dezbatere.ro. Lēmumu pārskata persona, kura nepiedalījās sākotnējā lēmuma pieņemšanā, un mēs jums paziņojam iznākumu un tā pamatojumu. Tas neietekmē jūsu tiesības vērsties tiesā vai izmantot alternatīvu strīdu izšķiršanu saskaņā ar 18. sadaļu. Sūdzību kārtība attiecas arī uz sūdzībām, ka neesam rīkojušies pēc ziņojuma, saturs noņemts nepamatoti, konts ierobežots nepamatoti vai automatizēts rīks nepamatoti ietekmējis jūsu saturu." },
      { kind: "p", text: "Strīdu izšķiršana ārpustiesas kārtībā. Ja atrodaties Eiropas Savienībā, strīdu par kādu no mūsu moderēšanas lēmumiem varat nodot izšķiršanai ārpustiesas strīdu izšķiršanas iestādē, kas sertificēta saskaņā ar ES Digitālo pakalpojumu akta (Regulas (ES) 2022/2065) 21. pantu. Tas attiecas uz lēmumu par jūsu saturu vai kontu, kā arī uz mūsu lēmumu par jūsu iesniegtu ziņojumu. Iestādi izvēlaties no saraksta, ko Eiropas Komisija publicē vietnē digital-strategy.ec.europa.eu/en/policies/dsa-out-court-dispute-settlement, un jums nav vispirms jāizmanto mūsu sūdzību kārtība. Mēs piedalāmies labticīgi un atsakāmies piedalīties tikai tad, ja tas pats strīds par to pašu saturu un uz tiem pašiem pamatiem jau ir atrisināts. Iestādes lēmums nav saistošs nevienai no pusēm, un jūs saglabājat tiesības vērsties tiesā. Iestāde var iekasēt no jums nelielu maksu vai neiekasēt maksu vispār. Ja iestāde izšķir strīdu par labu jums, mēs sedzam tās maksas un atlīdzinām jūsu pamatotos izdevumus; ja tā izšķir strīdu par labu mums, jums nav jāatlīdzina mūsu maksas vai izdevumi, ja vien iestāde nekonstatē, ka jūs acīmredzami rīkojāties negodprātīgi." },
      { kind: "p", text: "Saziņa ar cilvēku. Mūsu atbalsta asistents ir MI sistēma un par to informē. Jūs jebkurā laikā varat lūgt sazināties ar cilvēku, un katrā atbalsta sarunā tiek piedāvāta šāda iespēja. Saziņā ar jums mēs nepaļaujamies tikai uz automatizētiem rīkiem." },
      { kind: "p", text: "Teroristisks saturs. Teroristisks saturs ir nelikumīgs, un DebateAI tas nav atļauts (7. sadaļa). Eiropas Savienības kompetentās iestādes var nosūtīt mums izņemšanas rīkojumus saskaņā ar Regulu (ES) 2021/784 uz 1. sadaļā norādīto kontaktpunktu. Saņēmuši šādu rīkojumu, mēs vienas stundas laikā izņemam saturu vai atspējojam piekļuvi tam visās ES valstīs. Mēs informējam personu, kura saturu publicēja, ka tas ir izņemts, un, ja tā pieprasa, kāpēc tas izņemts un kā rīkojumu var apstrīdēt, ja vien iestāde nenolemj, ka sabiedriskās drošības dēļ informāciju uz ierobežotu laiku nedrīkst izpaust. Kā to prasa Regula, izņemto saturu un ar to saistītos datus mēs glabājam sešus mēnešus, lai izņemšanu varētu pārskatīt un, ja tā bijusi nepamatota, atcelt. Persona, kura saturu publicēja, var apstrīdēt rīkojumu tās valsts tiesās, kuras iestāde rīkojumu izdevusi, kā arī izmantot mūsu sūdzību kārtību. Neviena iestāde nav pieprasījusi, lai mēs saskaņā ar šo Regulu veiktu konkrētus pasākumus pret teroristisku saturu; ja tas notiks, mēs šos pasākumus, tostarp jebkādus automatizētus rīkus, aprakstīsim šeit." },
      { kind: "p", text: "Nopietns dzīvības vai drošības apdraudējums. Ja uzzinām informāciju, kas liecina par noziedzīgu nodarījumu, kurš apdraud kādas personas dzīvību vai drošību, mēs informējam kompetentās iestādes." }
    ]
  },
  {
    no: "11",
    title: "Darbības apturēšana un izbeigšana",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "No jūsu puses. Jebkurā laikā slēdziet savu kontu sadaļā Iestatījumi, kā aprakstīts 6. sadaļā. Jums nav jānorāda iemesls. Konta slēgšana izbeidz šo Noteikumu darbību. Noteikumi zaudē spēku brīdī, kad slēgšana stājas spēkā, t. i., pēc 7 dienu labvēlības perioda; šīs sadaļas beigās minētās sadaļas pēc tam paliek spēkā." },
      { kind: "p", text: "No mūsu puses. Mēs varam apturēt vai slēgt jūsu kontu vai noņemt vai ierobežot jūsu saturu, ja: jūs būtiski pārkāpjat šos Noteikumus, jo īpaši 7. sadaļu; jūsu saturs ir nelikumīgs vai tiesību akti, tiesa vai iestāde prasa mums rīkoties; jūsu lietošana apdraud pakalpojuma drošību, integritāti vai pieejamību vai citu personu tiesības; jūsu konts nav bijis aktīvs 24 mēnešus un esam jūs par to brīdinājuši; vai mēs pārtraucam sniegt pakalpojumu vispār vai jūsu valstī." },
      { kind: "p", text: "Izņemot gadījumus, kad pārkāpums ir nopietns, tiesību akti prasa tūlītēju rīcību vai kavēšanās radītu kaitējumu, mēs informējam jūs par problēmu un dodam saprātīgu iespēju to novērst, pirms apturam vai slēdzam kontu. Mēs vienmēr sniedzam pamatojumu saskaņā ar 10. sadaļu, un jūs varat apstrīdēt lēmumu." },
      { kind: "p", text: "Ja pilnībā slēdzam pakalpojumu vai pārtraucam to sniegt jūsu valstī, mēs paziņojam vismaz 30 dienu iepriekš, atmaksājam iepriekš samaksāto summu par laiku pēc slēgšanas un vispirms nodrošinām iespēju eksportēt debates." },
      { kind: "p", text: "Slēgšanas sekas. Kad konts tiek slēgts, mēs iznīcinām jūsu konta datu un privāto debašu šifrēšanas atslēgas, tādējādi padarot tos neatgriezeniski nenolasāmus, dzēšam jūsu konta ierakstu un, ja esat to izvēlējies, noņemam publicētās debates no publiskas piekļuves, kā aprakstīts 9. sadaļā. Dažas lietas saglabājas, un jums jāzina, kuras: ieraksti mūsu audita un drošības žurnālos, kuriem datus var tikai pievienot un kurus glabājam savu juridisko un drošības pienākumu izpildei; ieraksti, kas mums jāglabā saskaņā ar tiesību aktiem, tostarp piekrišanas un akceptēšanas ieraksti; un neliels skaits vecāku debašu, kas ir senākas par mūsu šifrēšanas shēmu un kuru ierakstu dzēšanas iespējas ir ierobežotākas — mēs jums paziņosim, ja tas attiecas uz jūsu kontu. Privātuma politikā tas viss aprakstīts datu aizsardzības kontekstā un izskaidrotas jūsu tiesības uz dzēšanu." },
      { kind: "p", text: "8. sadaļa (attiecībā uz jau publicētu saturu), kā arī 15., 16. un 18. sadaļa paliek spēkā pēc līguma izbeigšanas." }
    ]
  },
  {
    no: "12",
    title: "Maksas plāni",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "[Inactive until a paid plan exists. Do not launch a paid tier without completing every bracket here and the checkout interface it describes.]" },
      { kind: "p", text: "DebateAI piedāvā bezmaksas plānu. Būs pieejams maksas Premium plāns, kas nodrošina piekļuvi pilnam modeļu klāstam un ļauj jums pašam iestatīt debašu parametrus." },
      { kind: "p", text: "Pirms maksājuma veikšanas tieši virs maksājuma pogas mēs parādām: plānu; kopējo cenu ar piemērojamiem nodokļiem; norēķinu periodu; to, ka plāns tiek automātiski atjaunots līdz atcelšanai; datumu, kad beidzas bezmaksas izmēģinājums, un pēc tam iekasējamo summu; un atcelšanas kārtību. Jūs apstiprināt atjaunošanas noteikumus, atzīmējot atsevišķu izvēles rūtiņu. Uz pogas ir teksts Abonēt un maksāt (rumāņu valodā Comandă cu obligație de plată). Mēs nosūtām jums apstiprinājumu pastāvīgā informācijas nesējā, kurā ietverta tā pati informācija, šie Noteikumi un atteikuma veidlapa." },
      { kind: "p", text: "Atgādinājumi. Mēs jums nosūtām e-pasta ziņojumu vismaz 5 dienas pirms bezmaksas izmēģinājuma pārvēršanas maksas plānā; vismaz reizi gadā attiecībā uz plāniem, kas turpinās; un 30 līdz 45 dienas pirms jebkādas divpadsmit mēnešu vai ilgāka termiņa atjaunošanas. Katrā atgādinājumā ir norādīti cena, datums un atcelšanas saite." },
      { kind: "p", text: "Atcelšana. Abonementu varat atcelt jebkurā laikā sadaļā Iestatījumi → Abonements ar vienu apstiprinājuma klikšķi vai atcelšanas lapā dezbatere.ro/cancel, kurā nav jāpierakstās. Atcelšana stājas spēkā pašreizējā norēķinu perioda beigās, un līdz tam jūs saglabājat piekļuvi. Mēs nepadarīsim atcelšanu sarežģītāku par abonēšanu." },
      { kind: "p", text: "Cenas izmaiņas stājas spēkā tikai atjaunošanas brīdī. Mēs vismaz 30 dienu iepriekš pa e-pastu paziņojam jauno cenu un nosūtām atcelšanas saiti. Ja jūsu valsts tiesību akti prasa nepārprotamu piekrišanu cenas izmaiņām, mēs to lūdzam; citādi, ja neko nedarāt, jaunā cena tiek piemērota no nākamās atjaunošanas. A pielikumā norādīti reģionālie noteikumi." },
      { kind: "p", text: "Neizdevušies maksājumi. Ja maksājums neizdodas, mēs atkārtojam mēģinājumus 7 dienas un pirms jūsu konta pazemināšanas uz bezmaksas plānu brīdinām jūs pa e-pastu. Mēs nedzēšam jūsu debates neizdevušās apmaksas dēļ." },
      { kind: "p", text: "Nodokļi un maksājuma saņēmējs. Cenās ir iekļauts PVN, GST vai tirdzniecības nodoklis atkarībā no jūsu dzīvesvietas, un tas tiek parādīts pirms maksājuma veikšanas. Kartes maksājumus apstrādā NETOPIA Payments (netopia-payments.com). Pārdevējs ir DMS Merchandise Shop S.R.L., kas izsniedz jūsu rēķinu un paliek atbildīgs par pašu pakalpojumu un šiem Noteikumiem." },
      { kind: "p", text: "Maksājumu apstrīdēšana. Ja apstrīdat maksājumu pie savas kartes izdevēja, mēs varam apturēt maksas funkcijas, kamēr strīds tiek atrisināts. Par to mēs neiekasējam maksu." },
      { kind: "p", text: "Vispirms likumā noteiktās tiesības. Ja pakalpojums neatbilst mūsu solītajam, jums ir tiesības panākt tā atbilstību vai saņemt samērīgu cenas samazinājumu vai atmaksu, kā noteikts tiesību aktos. Papildus tam, ja jūs maksas plānu izbeidzat norēķinu perioda laikā, mēs atmaksājam to perioda cenas daļu, kuru neesat izmantojis, mērot pēc plāna lietojuma, neatkarīgi no tā, cik dienu ir pagājis: ja esat izmantojis 30 %, mēs atmaksājam 70 %; ja neesat izmantojis neko, mēs atmaksājam pilnu cenu. Atmaksu varat pieprasīt, rakstot uz support@dezbatere.ro; kad atmaksa ir veikta, plāns beidzas. Ja piemēro arī 13. sadaļā noteiktās atteikuma tiesības, jūs saņemat lielāko no abām atmaksām. Abu plānu lietošanas ierobežojumi ir publicēti produktā; mēs jūs brīdinām, pirms tos pastiprinām tādā veidā, kas jūs būtiski ietekmē." }
    ]
  },
  {
    no: "13",
    title: "Jūsu atteikuma tiesības",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Ja dzīvojat ES vai EEZ, varat 14 dienu laikā pēc maksas abonementa noformēšanas atteikties no tā, nenorādot iemeslu. Izmantojiet lapu Atteikties no līguma vietnē dezbatere.ro/withdraw, apstiprinājuma e-pastā pieejamo parauga veidlapu vai rakstiet uz support@dezbatere.ro; mēs apstiprināsim saņemšanu pastāvīgā informācijas nesējā." },
      { kind: "p", text: "Ja lūdzāt mums sākt sniegt pakalpojumu nekavējoties — norēķinu laikā atzīmējot izvēles rūtiņu — un pēc tam atsakāties, jūs maksājat par līdz atteikuma dienai sniegto pakalpojuma daļu, ko aprēķina proporcionāli norēķinu perioda cenai, un mēs atmaksājam atlikušo summu. Lietojot pakalpojumu 14 dienu laikā, jūs nezaudējat atteikuma tiesības." },
      { kind: "p", text: "Ja dzīvojat citviet, A pielikumā norādītas jūsu reģionā piemērojamās atteikuma vai pārdomu perioda tiesības, ja tādas ir, un citos gadījumos mūsu atmaksas politika. Jūsu valstī likumā noteiktajām tiesībām vienmēr ir priekšroka." }
    ]
  },
  {
    no: "14",
    title: "Pakalpojuma un šo Noteikumu izmaiņas",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Pakalpojuma izmaiņas. Mēs nepārtraukti attīstām DebateAI, un kārtējie uzlabojumi, labojumi un modeļu klāsta izmaiņas notiek bez iepriekšēja paziņojuma. Ja veicam izmaiņas, kas pārsniedz pakalpojuma darbības uzturēšanu atbilstoši aprakstam, mēs to darām tikai kāda no šiem iemesliem dēļ: lai izpildītu juridisku vai regulatīvu prasību; reaģētu uz drošības vai ļaunprātīgas izmantošanas problēmu; jo modeļa pakalpojumu sniedzējs maina, ierobežo vai atsauc modeli vai funkciju, no kuras esam atkarīgi; lai pielāgotos tehniskai videi, kuru nekontrolējam; vai lai pievienotu, uzlabotu vai izbeigtu funkciju tādā veidā, kas jums nerada izmaksas." },
      { kind: "p", text: "Mēs pastāvīgā informācijas nesējā iepriekš paziņojam, kas un kad mainīsies. Ja izmaiņas vairāk nekā nebūtiski nelabvēlīgi ietekmē jūsu piekļuvi pakalpojumam vai tā lietošanu, varat bez maksas izbeigt līgumu 30 dienu laikā pēc paziņojuma saņemšanas vai izmaiņu stāšanās spēkā atkarībā no tā, kurš datums ir vēlāks, un mēs atmaksājam iepriekš samaksāto summu par neizmantoto periodu." },
      { kind: "p", text: "Šo Noteikumu izmaiņas. Mēs varam mainīt šos Noteikumus tādu pašu iemeslu dēļ. Attiecībā uz izmaiņām, kas nesamazina jūsu tiesības, mēs publicējam jauno versiju kopā ar izmaiņu kopsavilkumu un vismaz 30 dienu iepriekš nosūtām jums e-pasta ziņojumu par tās stāšanos spēkā; turpinot lietot DebateAI pēc šī datuma, jūs izmaiņām piekrītat, un pirms tam varat slēgt kontu. Attiecībā uz izmaiņām, kas samazina jūsu tiesības, — tostarp esoša plāna cenas paaugstinājumu, zemākiem ierobežojumiem, noņemtām funkcijām, jauniem jūsu satura lietošanas veidiem vai izmaiņām atbildībā, piemērojamajos tiesību aktos vai strīdu izšķiršanā — mēs lūdzam nākamajā pierakstīšanās reizē skaidri piekrist jaunajai versijai, un izmaiņas attiecas tikai uz turpmāko laiku. Mēs nekad neveicam izmaiņas ar atpakaļejošu spēku un nekad neizmantojam šo sadaļu, lai termiņa vidū mainītu jums apmaksātā pakalpojuma būtību, nepiedāvājot iespēju izstāties. Iepriekšējās versijas ir pieejamas vietnē dezbatere.ro/terms/versions." }
    ]
  },
  {
    no: "15",
    title: "Atbildība",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Ko mēs neierobežojam. Nekas šajos Noteikumos neizslēdz un neierobežo mūsu atbildību par nāvi vai miesas bojājumiem, ko izraisījusi mūsu nolaidība, par krāpšanu vai krāpniecisku sagrozīšanu, par rupju neuzmanību vai tīšu pārkāpumu vai par jebko citu, ko likumīgi nevar ierobežot. Ja esat patērētājs, nekas šeit neatceļ jūsu likumā noteiktās tiesības, tostarp tiesības panākt neatbilstoša pakalpojuma atbilstību vai saņemt cenas samazinājumu vai atmaksu, vai jebkādu garantiju, kas piemērojama saskaņā ar jūsu dzīvesvietas valsts tiesību aktiem." },
      { kind: "p", text: "Ģenerētais saturs. Pakalpojums sagatavo materiālu jūsu vērtējumam, nevis secinājumus, pēc kuriem varat rīkoties bez pārbaudes, un 5. sadaļā tas ir skaidri norādīts. Ievērojot iepriekšējo rindkopu, mēs neatbildam par lēmumiem, kurus pieņemat, pamatojoties uz ģenerētajiem argumentiem, vērtējumiem vai spriedumiem, ja neesat veicis 5. sadaļā aprakstītos saprātīgos pārbaudes pasākumus." },
      { kind: "p", text: "Jūsu saturs un lietošana. Jūs atbildat par iesniegto un publicēto, tostarp par tiesībām to iesniegt un 7. sadaļas ievērošanu." },
      { kind: "p", text: "Notikumi ārpus mūsu kontroles. Mēs nepārkāpjam līgumu, ja kaut kas ārpus mūsu saprātīgas kontroles liedz mums to izpildīt. Trešās personas modeļa pakalpojumu sniedzēja kļūme vai pakalpojuma atsaukšana automātiski nav šāds notikums; ja tās dēļ pakalpojums kļūst nepieejams, piemēro 14. sadaļu, un jūs varat izbeigt līgumu un saņemt tajā aprakstīto atmaksu." },
      { kind: "p", text: "[No monetary cap and no general exclusion of indirect loss apply to consumers. If a business tier is ever offered, negotiated allocations belong in a separate order form.]" }
    ]
  },
  {
    no: "16",
    title: "Intelektuālais īpašums",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Pats pakalpojums — programmatūra, dzinējs, vērtēšanas metode, saskarne, nosaukumi DebateAI un DebateAIRO un mūsu logotipi — pieder mums vai mūsu licences devējiem. Šie Noteikumi piešķir jums atļauju lietot pakalpojumu, nevis īpašumtiesības uz to." },
      { kind: "p", text: "Jūs drīkstat citēt publicētas debates un ievietot saites uz tām, norādot DebateAI kā avotu un pievienojot saiti uz sākotnējo lapu. Publiskā kopuma masveida kopēšana, sistemātiska reproducēšana un publicēto debašu izmantošana kā apmācības dati bez mūsu rakstiskas vienošanās nav atļautas." },
      { kind: "p", text: "8. sadaļa attiecas uz jūsu saturu un ģenerēto rezultātu statusu. Ja uzskatāt, ka kaut kas pakalpojumā DebateAI pārkāpj jūsu intelektuālā īpašuma tiesības, izmantojiet 10. sadaļā noteikto ziņošanas kārtību." }
    ]
  },
  {
    no: "17",
    title: "Personas dati",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Tas, kā mēs rīkojamies ar personas datiem, ir noteikts Privātuma politikā vietnē dezbatere.ro/privacy. Tajā paskaidrots, ko vācam, katra nolūka juridiskais pamats, cik ilgi glabājam datus, kas tos saņem, kāda nosūtīšana notiek un kā īstenot savas tiesības. Arī šeit jānorāda trīs aspekti. 7. sadaļā lūdzam neiekļaut jautājumā citu personu datus; ja tos tomēr iekļaujat, jūs par to atbildat, un mēs varam saturu noņemt. Ja pakalpojumā DebateAI publicētās debatēs ir jūsu personas dati, varat lūgt mums tos noņemt bez konta (9. sadaļa). Turklāt mēs glabājam ierakstu par jūsu piekrišanu šiem Noteikumiem — versiju, laiku un sesijas tehnisko informāciju — kā līguma pierādījumu, kā paskaidrots Privātuma politikā." }
    ]
  },
  {
    no: "18",
    title: "Piemērojamie tiesību akti un strīdu izskatīšanas vieta",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Piemērojamie tiesību akti. Šiem Noteikumiem un jebkuram no tiem vai to priekšmeta izrietošam strīdam vai prasījumam, tostarp ārpuslīgumiskiem prasījumiem, piemēro Rumānijas tiesību aktus." },
      { kind: "p", text: "Jūsu vietējā aizsardzība netiek ietekmēta. Ja esat patērētājs, Rumānijas tiesību aktu izvēle neatņem jums aizsardzību, ko sniedz jūsu pastāvīgās dzīvesvietas valsts obligātie patērētāju aizsardzības noteikumi — piemēram, noteikumi par netaisnīgiem līguma noteikumiem, atteikuma un atcelšanas tiesībām vai garantijām —, ja šie noteikumi ir piemērojami neatkarīgi no šīs izvēles, tostarp saskaņā ar Regulas (EK) Nr. 593/2008 6. panta 2. punktu, ja dzīvojat ES. Uz šiem noteikumiem varat atsaukties papildus Rumānijas tiesību aktiem." },
      { kind: "p", text: "Tiesas, ja dzīvojat ES vai EEZ. Jūs varat celt prasību pret mums Rumānijas tiesās vai savas dzīvesvietas valsts tiesās. Mēs varam celt prasību pret jums tikai jūsu dzīvesvietas valsts tiesās." },
      { kind: "p", text: "Patērētāji citviet. Ja dzīvojat ārpus ES un EEZ, nekas šajos Noteikumos neierobežo jūsu tiesības saskaņā ar savas valsts tiesību aktiem celt prasību tās tiesās vai tādas tiesības saskaņā ar šiem tiesību aktiem, no kurām nevar atteikties, — tostarp, ja dzīvojat Austrālijā vai Jaunzēlandē, jūsu patērētāja garantiju tiesības; ja dzīvojat Brazīlijā, Código de Defesa do Consumidor; un, ja dzīvojat Amerikas Savienotajās Valstīs, jūsu štata patērētāju aizsardzības tiesību aktus." },
      { kind: "p", text: "Pirms vēršanās tiesā. Sazinieties ar mums pa support@dezbatere.ro; lielāko daļu jautājumu var atrisināt, un mūsu mērķis ir atbildēt 5 darbdienu laikā. Ja esat patērētājs Rumānijā vai ES, varat izmantot alternatīvu strīdu izšķiršanu ar www.onoratainstanta.ro starpniecību; mēs neapņemamies piedalīties šajā procedūrā. Sūdzības par moderēšanas lēmumiem izskata saskaņā ar 10. sadaļu, kas ir atsevišķa kārtība." }
    ]
  },
  {
    no: "19",
    title: "Citi noteikumi",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Tiesību nodošana. Jūs nedrīkstat nodot savas tiesības saskaņā ar šiem Noteikumiem. Mēs drīkstam nodot savas tiesības uzņēmumam, kas pārņem pakalpojumu, ar nosacījumu, ka jūsu tiesības netiek samazinātas; mēs jums par to paziņosim, un jūs varēsiet slēgt savu kontu." },
      { kind: "p", text: "Atsevišķu noteikumu spēkā esība. Ja kādu šo Noteikumu normu atzīst par neizpildāmu, šo normu nepiemēro, bet pārējie Noteikumi paliek spēkā." },
      { kind: "p", text: "Neatteikšanās no tiesībām. Ja neīstenojam noteikumu nekavējoties, mēs nezaudējam tiesības to īstenot vēlāk." },
      { kind: "p", text: "Pilnīga vienošanās. Šie Noteikumi kopā ar Sīkdatņu politiku un MI pakalpojumu sniedzēju reģistru ir visa mūsu savstarpējā vienošanās par pakalpojumu. Privātuma politikā sniegtās saistības mums ir saistošas. Nekas šajā rindkopā neizslēdz atbildību par krāpniecisku sagrozīšanu." },
      { kind: "p", text: "Valoda. Šie Noteikumi ir publicēti visās vietnē piedāvātajās valodās. Līguma valoda ir valoda, kurā reģistrējāties, proti, tās versijas valoda, kurai piekritāt un kuru fiksē mūsu piekrišanas ieraksts. Ja vēlāk piekrītat jaunai versijai citā valodā, līgums turpinās šajā valodā. Citu valodu versijas ir tulkojumi. Ja jūsu dzīvesvietas valsts tiesību akti nosaka, ka noteicošā ir versija šīs valsts valodā, noteicošā ir šī versija. Ja divu valodu versijas atšķiras, mēs piemērojam to nozīmi, kas jums ir labvēlīgāka." },
      { kind: "p", text: "Kontaktinformācija. support@dezbatere.ro · DMS Merchandise Shop S.R.L., Str. 1 Decembrie 1918 nr. 80A, Piatra Neamț, Rumānija." }
    ]
  },
  {
    no: "A",
    title: "A pielikums — Reģionālie noteikumi",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Katrs ieraksts ir piemērojams personām, kuras dzīvo attiecīgajā reģionā, un tajā norādītas tikai atšķirības no vispārīgās daļas. Ja ieraksts ir pretrunā vispārīgajai daļai, attiecīgā reģiona personām piemēro ierakstu." }
    ]
  },
  {
    no: "A.1",
    title: "Eiropas Savienība un Eiropas Ekonomikas zona",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Šo Noteikumu vispārīgā daļa ir sagatavota jums. Papildus: jūs varat celt prasību savas dzīvesvietas valsts tiesās; piemēro 13. sadaļā noteiktās atteikuma tiesības; alternatīva strīdu izšķiršana ir pieejama ar www.onoratainstanta.ro starpniecību. Vācija: atcelšanas poga vietnē dezbatere.ro/cancel ļauj izbeigt abonementu bez pierakstīšanās; abonementa noteikumi, atjaunošanas periodi un paziņošanas termiņi atbilst BGB §309(9): katrs plāns ir spēkā vienu mēnesi un tiek atjaunots katru mēnesi, kamēr to neatceļat; jūs varat to atcelt jebkurā laikā, un atcelšana stājas spēkā kārtējā mēneša beigās. Francija: abonementu varat izbeigt tiešsaistē trīs darbībās vietnē dezbatere.ro/cancel. Itālija: klauzulām par atbildību (15), darbības apturēšanu (11), izmaiņām (14) un piemērojamajiem tiesību aktiem (18) ir vajadzīgs jūsu īpašs apstiprinājums, ko sniedzat, reģistrācijas laikā atsevišķi to apstiprinot. Nīderlande: pirms līguma noslēgšanas šie Noteikumi tiek sniegti saglabājamā formā. Polija: ir pieejama arī poļu valodas versija; valodas pārslēgā izvēlieties Polski." }
    ]
  },
  {
    no: "A.2",
    title: "Amerikas Savienotās Valstis",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Tenesī. Mēs nepiedāvājam DebateAI personām, kuras dzīvo Tenesī." },
      { kind: "p", text: "Paziņojumi un noņemšana. Par bez piekrišanas kopīgotiem intīmiem attēliem var ziņot, nosūtot e-pastu uz abuse@dezbatere.ro, bez konta, un pēc derīga pieprasījuma tie tiek noņemti 48 stundu laikā. Autortiesību sūdzības tiek iesniegtas, izmantojot 10. sadaļā noteikto ziņošanas kārtību." },
      { kind: "p", text: "Štatu īpašie noteikumi. Kalifornija: piemēro 12. sadaļā noteiktos automātiskās atjaunošanas noteikumus; jūs jebkurā laikā varat atcelt abonementu tiešsaistē; mēs glabājam jūsu piekrišanu atjaunošanas noteikumiem vismaz trīs gadus. Ņujorka: varat atcelt abonementu 14 dienu laikā pēc jebkura maksājuma par paaugstinātu cenu un saņemt proporcionālu atmaksu. Teksasa un Nebraska: mēs nepārdodam sensitīvus personas datus. Vašingtona: mūsu Patērētāju veselības datu privātuma paziņojums vietnē dezbatere.ro/privacy/us-health-data attiecas uz informāciju par veselību. Kolorādo: nekas pakalpojumā nepieņem par jums lēmumus ar būtiskām sekām. Jūsu datiem un jūsu štata privātuma tiesībām piemēro mūsu Privātuma politikas B.2 pielikumu." }
    ]
  },
  {
    no: "A.3",
    title: "Kanāda un Kvebeka",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Mūsu privātuma speciālists, bet Kvebekā — persona, kas atbild par personas informācijas aizsardzību, ir mūsu direktors, sasniedzams privacy@dezbatere.ro. Jūsu datiem piemēro mūsu Privātuma politikas B.3 pielikumu. Kvebeka: šie Noteikumi ir pieejami franču valodā; izvēlieties franču valodu ar valodas pārslēgu; iestatījumi, kas saglabā jūsu debates privātas, ir ieslēgti pēc noklusējuma; jūs varat pieprasīt par jums esošās personas informācijas izņemšanu no indeksiem." }
    ]
  },
  {
    no: "A.4",
    title: "Austrālija un Jaunzēlande",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Mūsu pakalpojumiem ir garantijas, ko nevar izslēgt saskaņā ar Austrālijas Patērētāju tiesību aktiem. Būtisku pakalpojuma trūkumu gadījumā jums ir tiesības atcelt līgumu un saņemt atmaksu par neizmantoto daļu vai kompensāciju par pakalpojuma vērtības samazinājumu; jums ir tiesības arī uz kompensāciju par citiem saprātīgi paredzamiem zaudējumiem vai kaitējumu. Ja trūkums nav būtisks, jums ir tiesības saprātīgā laikā saņemt pakalpojuma problēmu novēršanu un, ja tas netiek izdarīts, atcelt līgumu un saņemt atmaksu. Ciktāl to atļauj 64A sadaļa, mūsu atbildība par garantijas pārkāpumu aprobežojas ar atkārtotu pakalpojuma sniegšanu vai ar tās izmaksu segšanu. Maksas plānam nav cita pārdomu perioda kā vien 12. sadaļā jums piešķirtais; atmaksas pieprasījumi tiek izskatīti, ja tie nosūtīti uz support@dezbatere.ro. Jaunzēlande: piemēro Consumer Guarantees Act 1993, un nekas šajos Noteikumos to neizslēdz; par kaitīgu digitālo saziņu var ziņot mums saskaņā ar 10. sadaļu vai organizācijai Netsafe." }
    ]
  },
  {
    no: "A.5",
    title: "Šveice",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Jūsu datiem piemēro Šveices Federālo datu aizsardzības likumu (Privātuma politikas B.5 pielikums). Jūs varat celt prasību tās vietas tiesās Šveicē, kur dzīvojat. Maksas plānam nav likumā noteiktu atteikuma tiesību; atmaksas pieprasījumi tiek izskatīti, ja tie nosūtīti uz support@dezbatere.ro." }
    ]
  },
  {
    no: "A.6",
    title: "Moldova",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Jums ir tādas pašas tiesības saskaņā ar šiem Noteikumiem kā patērētājam Eiropas Savienībā, tostarp 13. sadaļā noteiktās 14 dienu atteikuma tiesības. Jūs varat celt prasību Moldovas tiesās. Jūsu datiem piemēro Moldovas Likumu Nr. 195/2024 par personas datu aizsardzību (Privātuma politikas B.6 pielikums)." }
    ]
  },
  {
    no: "A.7",
    title: "Āzijas un Klusā okeāna reģions",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Singapūra: mūsu datu aizsardzības speciālists ir mūsu direktors, sasniedzams privacy@dezbatere.ro; nosūtīšana balstās uz līgumiskiem aizsardzības pasākumiem, kas pielīdzināmi PDPA; maksas plānam nav likumā noteikta pārdomu perioda, un atmaksas pieprasījumi tiek izskatīti, ja tie nosūtīti uz support@dezbatere.ro. Japāna: Specified Commercial Transactions Act paredzētā informācija ir pieejama vietnē dezbatere.ro/legal; tiešsaistes abonementiem nav vispārēja pārdomu perioda, un atmaksas pieprasījumi tiek izskatīti, ja tie nosūtīti uz support@dezbatere.ro; mēs nosūtām jūsu saturu MI pakalpojumu sniedzējiem Amerikas Savienotajās Valstīs un Eiropas Savienībā, katram saskaņā ar līgumu, kas prasa aizsardzību, kura ir līdzvērtīga Japānas Act on the Protection of Personal Information prasībām, un pēc pieprasījuma mēs jums pastāstām, kādi ir šie pasākumi. Dienvidkoreja: piekrišanas neobligātai apstrādei un tirgvedībai tiek iegūtas atsevišķi no pakalpojuma darbībai nepieciešamajiem elementiem; mūsu privātuma speciālists ir mūsu direktors, sasniedzams privacy@dezbatere.ro; saskaņā ar E-Commerce Act varat atteikties no maksas plāna 7 dienu laikā pēc abonēšanas; pirms katra regulāra cenas paaugstinājuma vai bezmaksas plāna pārvēršanas maksas plānā mēs no jauna saņemam jūsu piekrišanu; pakalpojumā tiek izmantots ģeneratīvais MI, mēs jūs par to informējam, pirms to izmantojat, un marķējam MI ģenerētos rezultātus. Taivāna: saskaņā ar Consumer Protection Act varat atteikties no maksas plāna 7 dienu laikā pēc abonēšanas; jūsu datiem piemēro Taivānas Personal Data Protection Act (Privātuma politikas B.7 pielikums)." }
    ]
  }
];

export const TERMS_OF_SERVICE: LegalDocument = {
  key: "terms",
  version: "2.2",
  sha256: "9bab076e312e1e4768fe4c9894d47feab8e0f4e98a3e4703c2a1b3248310bbbc",
  eyebrow: "PAKALPOJUMA NOTEIKUMI · v2.2 · SPĒKĀ NO 2026. GADA 12. OKTOBRA",
  title: "Kam jūs piekrītat",
  lede: "Līgums starp jums un DMS Merchandise Shop S.R.L., izklāstīts vienkāršā valodā. Deviņpadsmit sadaļas un A pielikums — ritiniet līdz beigām.",
  endMarker: "NOTEIKUMU BEIGAS · v2.2",
  contact: "support@dezbatere.ro",
  bodyLabel: "Pakalpojuma noteikumu teksts",
  sectionIdPrefix: "terms-section-",
  titleId: "terms-modal-title",
  gateHintId: "terms-modal-gate-hint",
  jumps: TERMS_JUMP,
  sections: TERMS_SECTIONS
};
