import{randomBytes,randomUUID,timingSafeEqual}from"node:crypto";import{performance}from"node:perf_hooks";
import{createEmailBlindIndex,normalizeEmailForBlindIndex,decrypt,encrypt,generateVerificationToken,hashToken,verifyPassword,matchTotpStep,generateTotpSecret,encodeBase32,totpProvisioningUri,generateRecoveryCodes,hashRecoveryCode,normalizeRecoveryCode,recoveryCodeSlot,verifyRecoveryCode,type AeadAad,type Argon2Executor,type ReadableUserDekStore}from"@debateai/crypto";
import type{AuthSourceContext}from"@debateai/db";import type{AuthPolicy,MfaPolicy}from"@debateai/register";import type{BackupEmailPolicy,MfaRecoveryPolicy}from"../../../packages/register/src/email-mfa-policy.js";
import{PostgresBackupEmailRepository,PostgresMfaRecoveryRepository,type EmailRecoverySource,type EmailRecoveryChannel,type MfaRecoveryRecord,type MfaRecoverySelectorKind,type MfaRecoveryWaitPreparation}from"../../../packages/db/src/email-mfa-recovery.js";import{authenticationRiskSignalAad,type DecryptedAuthenticationRiskSignal}from"../../../packages/db/src/auth-risk.js";import{evaluateMfaRecoveryRisk}from"./email-mfa-risk.js";import{storedArgon2EnvelopeNotOverPolicy}from"./registration.js";import{RECOVERY_START_PUBLIC_RESPONSE}from"./recovery.js";
const bearer=/^[A-Za-z0-9_-]{43}$/;
export class EmailRecoveryError extends Error{constructor(readonly code:string){super(code);this.name="EmailRecoveryError";}}
export function emailRecoveryNoticeAad(flow:"backup_email"|"mfa_recovery",user:string,channel:string):AeadAad{return["identity",`${flow}_notice.payload_ciphertext`,channel,"run:none",user,`user-dek:${user}`,"1"];}
const addressAad=(u:string,type:"email"|"recovery_email"):AeadAad=>["identity",type==="email"?"user.email_ciphertext":"user.recovery_email_ciphertext",u,"run:none",u,`user-dek:${u}`,"1"];
const factorAad=(u:string,id:string):AeadAad=>["identity","mfa_factor.secret_ciphertext",id,"run:none",u,`user-dek:${u}`,"1"];
function sessionHash(token:string){if(!bearer.test(token))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return hashToken("mfa-recovery-session",token);}
async function guarded<T>(prefix:string,operation:()=>Promise<T>):Promise<T>{try{return await operation();}catch(e){if(e instanceof EmailRecoveryError)throw e;throw new EmailRecoveryError(`${prefix}_UNAVAILABLE`);}}
function passwordShape(password:string){return typeof password==="string"&&password.length>0&&Buffer.byteLength(password,"utf8")<=1024;}
function notices(flow:"backup_email"|"mfa_recovery",userId:string,key:Buffer,channels:readonly EmailRecoveryChannel[],token:string,cancelToken?:string){return channels.map(c=>{const bytes=decrypt(key,c.addressCiphertext,addressAad(userId,c.channelType));try{const recipient=bytes.toString("utf8"),aad=emailRecoveryNoticeAad(flow,userId,c.channelId);return{channelId:c.channelId,envelope:encrypt(key,Buffer.from(JSON.stringify({recipient})),aad),...(c.cancelAuthorized&&cancelToken?{cancelEnvelope:encrypt(key,Buffer.from(JSON.stringify({recipient,cancelToken})),aad)}:{}),...(c.proof?{proofEnvelope:encrypt(key,Buffer.from(JSON.stringify({recipient,token,...(cancelToken?{cancelToken}:{})})),aad)}:{})};}finally{bytes.fill(0);}});}
// Owner ruling 2026-10-09: one notice per bound address while the 24-hour wait runs. Every address that may cancel gets a
// one-click cancel link; only the address that proved this recovery gets the finish link (sent when the 24 hours are over).
function waitNotices(userId:string,key:Buffer,prepared:MfaRecoveryWaitPreparation,finishToken:string,cancelToken:string){return prepared.channels.map(c=>{const bytes=decrypt(key,c.addressCiphertext,addressAad(userId,c.channelType));try{const recipient=bytes.toString("utf8"),aad=emailRecoveryNoticeAad("mfa_recovery",userId,c.channelId);return{channelId:c.channelId,...(c.cancelAuthorized?{cancelEnvelope:encrypt(key,Buffer.from(JSON.stringify({recipient,cancelToken})),aad)}:{}),...(c.channelId===prepared.proofChannelId?{finishEnvelope:encrypt(key,Buffer.from(JSON.stringify({recipient,finishToken})),aad)}:{})};}finally{bytes.fill(0);}});}
function waitPreparationValid(p:MfaRecoveryWaitPreparation|null):p is MfaRecoveryWaitPreparation{if(!p||typeof p.userId!=="string"||!Array.isArray(p.channels)||p.channels.length===0||p.channels.length>64)return false;const ids=p.channels.map(c=>c?.channelId);return new Set(ids).size===ids.length&&ids.includes(p.proofChannelId)&&p.channels.every(c=>(c.channelType==="email"||c.channelType==="recovery_email")&&typeof c.cancelAuthorized==="boolean");}
const iso=(value:string)=>new Date(value).toISOString();
export type BackupEmailState=Readonly<{status:"pending"|"verified"|"unavailable";email:string|null}>;
export interface BackupEmailApplication{status(sessionId:string,tokenHash:string):Promise<BackupEmailState>;start(input:Readonly<{password:string;code:string}>,sessionId:string,tokenHash:string,source:AuthSourceContext):Promise<typeof RECOVERY_START_PUBLIC_RESPONSE>;confirm(input:Readonly<{token:string}>,source:AuthSourceContext):Promise<Readonly<{status:"verified"}>>;}
export class BackupEmailService implements BackupEmailApplication{
 constructor(private readonly d:Readonly<{repository:PostgresBackupEmailRepository;users:ReadableUserDekStore;argon2:Argon2Executor;authPolicy:AuthPolicy;mfaPolicy:MfaPolicy;policy:BackupEmailPolicy}>){ }
 async status(id:string,token:string){return guarded("BACKUP_EMAIL",async()=>{const self=await this.d.repository.self(id,token);if(!self||!self.backupCiphertext)return{status:"unavailable" as const,email:null};const key=await this.d.users.load(self.userId);let plain:Buffer|undefined;try{plain=decrypt(key,self.backupCiphertext,["identity","user.recovery_email_ciphertext",self.userId,"run:none",self.userId,`user-dek:${self.userId}`,"1"]);return{status:self.status,email:plain.toString("utf8")};}finally{plain?.fill(0);key.fill(0);}});}
 async start(input:Readonly<{password:string;code:string}>,id:string,tokenHash:string,source:AuthSourceContext){return guarded("BACKUP_EMAIL",async()=>{const prepared=await this.d.repository.prepareSource(source);if(!await this.d.repository.admit(id,tokenHash,prepared))throw new EmailRecoveryError("BACKUP_EMAIL_RATE_LIMITED");const self=await this.d.repository.self(id,tokenHash);if(!self||self.status!=="pending")return RECOVERY_START_PUBLIC_RESPONSE;if(!passwordShape(input.password)||!storedArgon2EnvelopeNotOverPolicy(self.passwordHash,this.d.authPolicy.password.argon2id,"password")||!await verifyPassword(this.d.argon2,self.passwordHash,input.password))throw new EmailRecoveryError("BACKUP_EMAIL_PROOF_INVALID");const key=await this.d.users.load(self.userId);let seed:Buffer|undefined;try{seed=decrypt(key,self.factorSecret,factorAad(self.userId,self.factorId));const match=matchTotpStep(seed,input.code,Math.floor(self.nowMs/30000),self.lastAcceptedStep);if(match.status!=="accepted")throw new EmailRecoveryError("BACKUP_EMAIL_PROOF_INVALID");const proof=generateVerificationToken();if(!await this.d.repository.start({sessionId:id,tokenHash,passwordHash:self.passwordHash,factorId:self.factorId,factorSecret:self.factorSecret,last:self.lastAcceptedStep,step:match.step,linkHash:hashToken("backup-email-link",proof),notices:notices("backup_email",self.userId,key,self.channels,proof),source:prepared,id:randomUUID()}))throw new EmailRecoveryError("BACKUP_EMAIL_INVALID");return RECOVERY_START_PUBLIC_RESPONSE;}finally{seed?.fill(0);key.fill(0);}});}
 async confirm(input:Readonly<{token:string}>,source:AuthSourceContext){return guarded("BACKUP_EMAIL",async()=>{if(!bearer.test(input.token)||await this.d.repository.confirm(hashToken("backup-email-link",input.token),await this.d.repository.prepareSource(source))!=="VERIFIED")throw new EmailRecoveryError("BACKUP_EMAIL_INVALID");return{status:"verified" as const};});}
}
type SessionInput=Readonly<{sessionToken:string}>;
export type MfaRecoveryState=Readonly<{status:"factor_required"|"totp_required"|"codes_required"|"ack_required"|"ready"|"waiting"|"completed"|"cancelled"|"refused";expires_at:string;not_before?:string}>;
export type MfaRecoveryFinishState=Readonly<{status:"waiting";not_before:string}>|Readonly<{status:"ready_to_finish";expires_at:string}>;
export interface MfaRecoveryApplication{
 start(input:Readonly<{email:string;destination:"primary"|"backup"}>,source:AuthSourceContext):Promise<typeof RECOVERY_START_PUBLIC_RESPONSE>;
 exchange(input:Readonly<{token:string;password:string}>,source:AuthSourceContext):Promise<Readonly<{sessionToken:string;csrfToken:string;state:MfaRecoveryState;expiresAt:Date}>>;
 assertCsrf(token:string,csrf:string):Promise<void>;status(input:SessionInput):Promise<MfaRecoveryState>;
 beginFactor(input:SessionInput,source:AuthSourceContext):Promise<Readonly<{status:"totp_required";secret:string;otpauth_uri:string;account_label:string}>>;
 verifyFactor(input:SessionInput&Readonly<{code:string}>,source:AuthSourceContext):Promise<Readonly<{status:"codes_required"}>>;
 generateCodes(input:SessionInput,source:AuthSourceContext):Promise<Readonly<{status:"ack_required";recovery_codes:readonly string[]}>>;
 acknowledge(input:SessionInput&Readonly<{code:string}>,source:AuthSourceContext):Promise<Readonly<{status:"ready"}>>;
 complete(input:SessionInput,source:AuthSourceContext):Promise<Readonly<{status:"waiting";not_before:string}>>;
 prepareFinish(input:Readonly<{token:string}>,source:AuthSourceContext):Promise<MfaRecoveryFinishState>;
 finish(input:Readonly<{token:string;password:string}>,source:AuthSourceContext):Promise<Readonly<{status:"completed"}>>;
 cancel(input:Readonly<{token:string}>,source:AuthSourceContext):Promise<Readonly<{status:"cancelled"}>>;cancelSession(input:SessionInput,source:AuthSourceContext):Promise<Readonly<{status:"cancelled"}>>;
}
export class MfaRecoveryService implements MfaRecoveryApplication{
 constructor(private readonly d:Readonly<{repository:PostgresMfaRecoveryRepository;users:ReadableUserDekStore;argon2:Argon2Executor;authPolicy:AuthPolicy;mfaPolicy:MfaPolicy;policy:MfaRecoveryPolicy;blindIndexKey:Uint8Array}>){ }
 private async admit(source:AuthSourceContext){const p=await this.d.repository.prepareSource(source);if(!await this.d.repository.admit(p))throw new EmailRecoveryError("MFA_RECOVERY_RATE_LIMITED");return p;}
 private async current(token:string,stages?:readonly string[]):Promise<MfaRecoveryRecord>{const r=await this.d.repository.read(sessionHash(token));if(!r||stages&&!stages.includes(r.stage))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return r;}
 private async risk(selector:string,kind:MfaRecoverySelectorKind,source:EmailRecoverySource){const r=await this.d.repository.risk(selector,kind);if(!r)throw new EmailRecoveryError("MFA_RECOVERY_INVALID");const key=await this.d.users.load(r.userId);try{const decoded=r.signals.map(s=>{const p=decrypt(key,s.ciphertext,authenticationRiskSignalAad(r.userId));try{return{riskSignalId:s.riskSignalId,kind:s.kind,context:JSON.parse(p.toString("utf8")),observedAt:new Date(s.observedAt),expiresAt:new Date(s.expiresAt)}as DecryptedAuthenticationRiskSignal;}finally{p.fill(0);}});try{evaluateMfaRecoveryRisk(decoded,new Date(r.evaluatedAt),source);}catch(e){if(e instanceof TypeError&&e.message==="MFA_RECOVERY_RISK_REFUSED")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");throw e;}return r.fingerprint;}finally{key.fill(0);}}
 async start(input:Readonly<{email:string;destination:"primary"|"backup"}>,source:AuthSourceContext){const began=performance.now();try{return await guarded("MFA_RECOVERY",async()=>{let email:string;try{email=normalizeEmailForBlindIndex(input.email);}catch{return RECOVERY_START_PUBLIC_RESPONSE;}const prepared=await this.d.repository.prepareSource(source);if(!await this.d.repository.admit(prepared))return RECOVERY_START_PUBLIC_RESPONSE;const index=createEmailBlindIndex(this.d.blindIndexKey,email),candidate=await this.d.repository.prepare(index,input.destination),user=candidate?.userId??randomUUID(),key=candidate?await this.d.users.load(user):randomBytes(32),token=generateVerificationToken(),cancel=generateVerificationToken();try{await this.d.repository.start({index,destination:input.destination,candidateId:candidate?.userId??null,channels:candidate?.channels.map(c=>c.channelId)??[],linkHash:hashToken("mfa-recovery-link",token),cancelHash:hashToken("mfa-recovery-cancel",cancel),notices:notices("mfa_recovery",user,key,candidate?.channels??[],token,cancel),source:prepared,id:randomUUID()});return RECOVERY_START_PUBLIC_RESPONSE;}finally{key.fill(0);}});}finally{const floor=this.d.authPolicy.verification.enumerationResponseFloorMs-(performance.now()-began);if(floor>0)await new Promise<void>(r=>setTimeout(r,floor));}}
 // Review I1 2026-10-09: a replacement already waiting its 24 hours is reported here, once the emailed link and the
 // current password are proved (never at the public start), before a second authenticator and codes are set up.
 async exchange(input:Readonly<{token:string;password:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const prepared=await this.admit(source);if(!bearer.test(input.token))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");const link=hashToken("mfa-recovery-link",input.token),candidate=await this.d.repository.prepareExchange(link);if(!candidate||!Array.isArray(candidate.bindingChannelIds)||candidate.bindingChannelIds.length===0||candidate.bindingChannelIds.length>64||new Set(candidate.bindingChannelIds).size!==candidate.bindingChannelIds.length||candidate.bindingChannelIds.some(id=>!candidate.channels.includes(id)))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");if(!passwordShape(input.password)||!storedArgon2EnvelopeNotOverPolicy(candidate.passwordHash,this.d.authPolicy.password.argon2id,"password")||!await verifyPassword(this.d.argon2,candidate.passwordHash,input.password)){await this.d.repository.failure(link,"link",prepared);throw new EmailRecoveryError("MFA_RECOVERY_PROOF_INVALID");}const risk=await this.risk(link,"link",prepared);if(await this.d.repository.linkWaiting(link)===true)throw new EmailRecoveryError("MFA_RECOVERY_ALREADY_WAITING");const key=await this.d.users.load(candidate.userId),token=generateVerificationToken(),csrf=generateVerificationToken();try{const refs=encrypt(key,Buffer.from(JSON.stringify({v:1,channelBindingIds:candidate.bindingChannelIds})),["identity","account_recovery_request.channel_refs_ciphertext",candidate.userId,"run:none",candidate.userId,`user-dek:${candidate.userId}`,"1"]);if(await this.d.repository.exchange(link,candidate.passwordHash,sessionHash(token),hashToken("mfa-recovery-csrf",csrf),refs,risk,prepared)!=="FACTOR_REQUIRED")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");const r=await this.current(token,["FACTOR_REQUIRED"]);return{sessionToken:token,csrfToken:csrf,state:{status:"factor_required" as const,expires_at:new Date(r.expiresAt).toISOString()},expiresAt:new Date(r.expiresAt)};}finally{key.fill(0);}});}
 async assertCsrf(token:string,csrf:string){return guarded("MFA_RECOVERY",async()=>{const r=await this.current(token);if(["WAITING","COMPLETED","CANCELLED","REFUSED"].includes(r.stage)||!bearer.test(csrf)||!r.csrfHash)throw new EmailRecoveryError("MFA_RECOVERY_CSRF_INVALID");const p=Buffer.from(hashToken("mfa-recovery-csrf",csrf)),stored=Buffer.from(r.csrfHash);if(p.length!==stored.length||!timingSafeEqual(p,stored))throw new EmailRecoveryError("MFA_RECOVERY_CSRF_INVALID");});}
 async status(input:SessionInput){return guarded("MFA_RECOVERY",async()=>{const r=await this.current(input.sessionToken);return{status:r.stage.toLowerCase()as MfaRecoveryState["status"],expires_at:iso(r.expiresAt),...(r.stage==="WAITING"&&r.notBefore?{not_before:iso(r.notBefore)}:{})};});}
 async beginFactor(input:SessionInput,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source),r=await this.current(input.sessionToken,["FACTOR_REQUIRED","TOTP_REQUIRED"]);if(!r.userId||!r.emailCiphertext)throw new EmailRecoveryError("MFA_RECOVERY_UNAVAILABLE");const secret=generateTotpSecret(),id=randomUUID(),key=await this.d.users.load(r.userId);let address:Buffer|undefined;try{const envelope=encrypt(key,secret,factorAad(r.userId,id));if(!await this.d.repository.stageFactor(sessionHash(input.sessionToken),id,envelope,p))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");address=decrypt(key,r.emailCiphertext,["identity","user.email_ciphertext",r.userId,"run:none",r.userId,`user-dek:${r.userId}`,"1"]);const label=`Authenticator recovery · ${address.toString("utf8")}`;return{status:"totp_required"as const,secret:encodeBase32(secret),otpauth_uri:totpProvisioningUri(secret,{issuer:this.d.mfaPolicy.issuer,accountLabel:label}),account_label:label};}finally{address?.fill(0);secret.fill(0);key.fill(0);}});}
 async verifyFactor(input:SessionInput&Readonly<{code:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source),r=await this.current(input.sessionToken,["TOTP_REQUIRED"]);if(!r.userId||!r.factorId||!r.factorSecret||r.nowMs===undefined||r.lastAcceptedStep===undefined)throw new EmailRecoveryError("MFA_RECOVERY_UNAVAILABLE");const key=await this.d.users.load(r.userId);let secret:Buffer|undefined;try{secret=decrypt(key,r.factorSecret,factorAad(r.userId,r.factorId));const match=matchTotpStep(secret,input.code,Math.floor(r.nowMs/30000),r.lastAcceptedStep);if(match.status!=="accepted"||!await this.d.repository.verifyFactor(sessionHash(input.sessionToken),r.factorId,r.factorSecret,r.lastAcceptedStep,match.step,p)){await this.d.repository.failure(sessionHash(input.sessionToken),"session",p);throw new EmailRecoveryError("MFA_RECOVERY_PROOF_INVALID");}return{status:"codes_required"as const};}finally{secret?.fill(0);key.fill(0);}});}
 async generateCodes(input:SessionInput,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source);await this.current(input.sessionToken,["CODES_REQUIRED","ACK_REQUIRED"]);const codes=generateRecoveryCodes(),hashes=await Promise.all(codes.map(async(code,i)=>({slot:i+1,hash:await hashRecoveryCode(this.d.argon2,code,this.d.mfaPolicy.recoveryCodes.argon2id)})));if(!await this.d.repository.stageCodes(sessionHash(input.sessionToken),hashes,p))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{status:"ack_required"as const,recovery_codes:codes};});}
 async acknowledge(input:SessionInput&Readonly<{code:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source);await this.current(input.sessionToken,["ACK_REQUIRED"]);let code:string;try{code=normalizeRecoveryCode(input.code);}catch{await this.d.repository.failure(sessionHash(input.sessionToken),"session",p);throw new EmailRecoveryError("MFA_RECOVERY_PROOF_INVALID");}const slot=recoveryCodeSlot(code),saved=await this.d.repository.readCode(sessionHash(input.sessionToken),slot);if(!saved||!storedArgon2EnvelopeNotOverPolicy(saved.codeHash,this.d.mfaPolicy.recoveryCodes.argon2id,"recovery-code")||!await verifyRecoveryCode(this.d.argon2,saved.codeHash,code)||!await this.d.repository.acknowledge(sessionHash(input.sessionToken),slot,saved.codeHash,p)){await this.d.repository.failure(sessionHash(input.sessionToken),"session",p);throw new EmailRecoveryError("MFA_RECOVERY_PROOF_INVALID");}return{status:"ready"as const};});}
 // Owner ruling 2026-10-09: completing starts the 24-hour wait. Nothing is replaced yet: the old authenticator, codes and
 // sessions keep working, every bound address is told (with a cancel link where it may cancel), and the proving address
 // later gets the finish link.
 async complete(input:SessionInput,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source);await this.current(input.sessionToken,["READY"]);const hash=sessionHash(input.sessionToken),risk=await this.risk(hash,"session",p),prepared=await this.d.repository.prepareWait(hash);if(!waitPreparationValid(prepared))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");const key=await this.d.users.load(prepared.userId),finish=generateVerificationToken(),cancel=generateVerificationToken();try{const started=await this.d.repository.beginWait(hash,risk,hashToken("mfa-recovery-finish",finish),hashToken("mfa-recovery-cancel",cancel),waitNotices(prepared.userId,key,prepared,finish,cancel),p);if(!started||started.status!=="WAITING")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{status:"waiting"as const,not_before:iso(started.notBefore)};}finally{key.fill(0);}});}
 private async finishCandidate(token:string){if(!bearer.test(token))throw new EmailRecoveryError("MFA_RECOVERY_INVALID");const hash=hashToken("mfa-recovery-finish",token),candidate=await this.d.repository.prepareFinish(hash);if(!candidate||typeof candidate.ready!=="boolean"||typeof candidate.passwordHash!=="string")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{hash,candidate};}
 async prepareFinish(input:Readonly<{token:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async():Promise<MfaRecoveryFinishState>=>{await this.admit(source);const{candidate}=await this.finishCandidate(input.token);return candidate.ready?{status:"ready_to_finish",expires_at:iso(candidate.expiresAt)}:{status:"waiting",not_before:iso(candidate.notBefore)};});}
 // The finish link alone replaces nothing: the current password is checked again here (a wrong one counts toward the
 // existing refusal), then the same risk check, and the database refuses before the 24 hours even if this is bypassed.
 async finish(input:Readonly<{token:string;password:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{const p=await this.admit(source),{hash,candidate}=await this.finishCandidate(input.token);if(!candidate.ready)throw new EmailRecoveryError("MFA_RECOVERY_TOO_EARLY");if(!passwordShape(input.password)||!storedArgon2EnvelopeNotOverPolicy(candidate.passwordHash,this.d.authPolicy.password.argon2id,"password")||!await verifyPassword(this.d.argon2,candidate.passwordHash,input.password)){await this.d.repository.failure(hash,"finish",p);throw new EmailRecoveryError("MFA_RECOVERY_PROOF_INVALID");}const risk=await this.risk(hash,"finish",p),result=await this.d.repository.finish(hash,candidate.passwordHash,risk,p);if(result==="TOO_EARLY")throw new EmailRecoveryError("MFA_RECOVERY_TOO_EARLY");if(result!=="COMPLETED")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{status:"completed"as const};});}
 async cancel(input:Readonly<{token:string}>,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{if(!bearer.test(input.token)||await this.d.repository.cancel(hashToken("mfa-recovery-cancel",input.token),await this.admit(source))!=="CANCELLED")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{status:"cancelled"as const};});}
 async cancelSession(input:SessionInput,source:AuthSourceContext){return guarded("MFA_RECOVERY",async()=>{if(await this.d.repository.cancelSession(sessionHash(input.sessionToken),await this.admit(source))!=="CANCELLED")throw new EmailRecoveryError("MFA_RECOVERY_INVALID");return{status:"cancelled"as const};});}
}
