import{timingSafeEqual}from"node:crypto";import type{FastifyInstance,FastifyRequest,FastifyReply,RouteShorthandOptions}from"fastify";import{z}from"zod";import type{AuthSourceContext}from"@debateai/db";import{EmailRecoveryError,type BackupEmailApplication,type MfaRecoveryApplication}from"./email-mfa-recovery.js";
export const emailMfaPolicyInventory=[
 {route:"GET /v1/account/backup-email",auth:"user",resource:"identity",action:"read-backup-email"},
 {route:"POST /v1/account/backup-email/verify/start",auth:"user",origin:"trusted",resource:"identity",action:"start-backup-email-verification"},
 {route:"POST /v1/account/backup-email/verify/confirm",auth:"public",origin:"trusted",resource:"identity",action:"confirm-backup-email-verification"},
 {route:"POST /v1/auth/mfa-recovery/start",auth:"public",origin:"trusted",resource:"identity",action:"start-mfa-recovery"},
 {route:"POST /v1/auth/mfa-recovery/exchange",auth:"public",origin:"trusted",resource:"identity",action:"exchange-mfa-recovery"},
 {route:"GET /v1/auth/mfa-recovery/status",auth:"public",resource:"identity",action:"read-mfa-recovery"},
 {route:"POST /v1/auth/mfa-recovery/totp/begin",auth:"public",origin:"trusted",resource:"identity",action:"bind-mfa-recovery-factor"},
 {route:"POST /v1/auth/mfa-recovery/totp/verify",auth:"public",origin:"trusted",resource:"identity",action:"verify-mfa-recovery-factor"},
 {route:"POST /v1/auth/mfa-recovery/codes/generate",auth:"public",origin:"trusted",resource:"identity",action:"generate-mfa-recovery-codes"},
 {route:"POST /v1/auth/mfa-recovery/codes/confirm",auth:"public",origin:"trusted",resource:"identity",action:"confirm-mfa-recovery-codes"},
 {route:"POST /v1/auth/mfa-recovery/complete",auth:"public",origin:"trusted",resource:"identity",action:"complete-mfa-recovery"},
 {route:"POST /v1/auth/mfa-recovery/cancel",auth:"public",origin:"trusted",resource:"identity",action:"cancel-mfa-recovery"},
 {route:"POST /v1/auth/mfa-recovery/cancel-current",auth:"public",origin:"trusted",resource:"identity",action:"cancel-current-mfa-recovery"},
 // Owner ruling 2026-10-09: the emailed finish link after the 24-hour wait (no cookie; the link and the current password).
 {route:"POST /v1/auth/mfa-recovery/finish/status",auth:"public",origin:"trusted",resource:"identity",action:"read-mfa-recovery-finish"},
 {route:"POST /v1/auth/mfa-recovery/finish",auth:"public",origin:"trusted",resource:"identity",action:"finish-mfa-recovery"}
]as const;
type Route=typeof emailMfaPolicyInventory[number]["route"];const bearer=/^[A-Za-z0-9_-]{43}$/,link=z.object({token:z.string().regex(bearer)}).strict(),empty=z.object({}).strict(),digits=z.object({code:z.string().regex(/^[0-9]{6}$/)}).strict(),code=z.object({code:z.string().min(1).max(128)}).strict(),password=z.string().min(1).max(1024),start=z.object({email:z.string().min(1).max(320),destination:z.enum(["primary","backup"])}).strict(),exchange=link.extend({password}),backupStart=z.object({password,code:z.string().regex(/^[0-9]{6}$/)}).strict();
function cookie(header:unknown,name:string){if(typeof header!=="string")return null;const values=header.split(";").map(v=>v.trim()).filter(v=>v.startsWith(`${name}=`));if(values.length!==1)return null;const v=values[0]!.slice(name.length+1);return bearer.test(v)?v:null;}
export function registerEmailMfaRoutes(api:FastifyInstance,o:Readonly<{backup?:BackupEmailApplication;mfa?:MfaRecoveryApplication;policy:(route:Route)=>RouteShorthandOptions;source:(request:FastifyRequest)=>AuthSourceContext;admitStart:(request:FastifyRequest,reply:FastifyReply)=>boolean}>){
 const guarded=(prefix:"BACKUP_EMAIL"|"MFA_RECOVERY",fn:(r:FastifyRequest,p:FastifyReply)=>Promise<unknown>)=>async(r:FastifyRequest,p:FastifyReply)=>{p.header("cache-control","no-store");try{return await fn(r,p);}catch(e){const code=e instanceof EmailRecoveryError?e.code:`${prefix}_UNAVAILABLE`,status=code.endsWith("CSRF_INVALID")?403:code.endsWith("RATE_LIMITED")?429:code.endsWith("TOO_EARLY")?409:code.endsWith("PROOF_INVALID")?401:code.endsWith("INPUT_INVALID")?400:code.endsWith("_INVALID")?410:503;return p.status(status).send({error:code});}};
 const parse=<T,>(schema:z.ZodType<T>,body:unknown,p:FastifyReply,prefix:string):T|null=>{const r=schema.safeParse(body);if(!r.success){void p.status(400).send({error:`${prefix}_INPUT_INVALID`});return null;}return r.data;};
 if(o.backup){const b=o.backup;api.get("/v1/account/backup-email",o.policy("GET /v1/account/backup-email"),guarded("BACKUP_EMAIL",async(r,p)=>{const s=r.authenticatedSession;if(!s)return p.status(401).send({error:"SESSION_REQUIRED"});return p.send(await b.status(s.session.session_id,s.tokenHash));}));api.post("/v1/account/backup-email/verify/start",o.policy("POST /v1/account/backup-email/verify/start"),guarded("BACKUP_EMAIL",async(r,p)=>{const input=parse(backupStart,r.body,p,"BACKUP_EMAIL");if(!input)return p;const s=r.authenticatedSession;if(!s)return p.status(401).send({error:"SESSION_REQUIRED"});return p.status(202).send(await b.start(input,s.session.session_id,s.tokenHash,o.source(r)));}));api.post("/v1/account/backup-email/verify/confirm",o.policy("POST /v1/account/backup-email/verify/confirm"),guarded("BACKUP_EMAIL",async(r,p)=>{const input=parse(link,r.body,p,"BACKUP_EMAIL");if(!input)return p;return p.send(await b.confirm(input,o.source(r)));}));}
 if(!o.mfa)return;const m=o.mfa,n="__Host-debateai-mfa-recovery",csrfName=`${n}-csrf`,header="x-mfa-recovery-csrf-token";
 const session=async(r:FastifyRequest,p:FastifyReply,write:boolean)=>{const token=cookie(r.headers.cookie,n);if(!token){void p.status(401).send({error:"MFA_RECOVERY_INVALID"});return null;}if(write){const supplied=r.headers[header],stored=cookie(r.headers.cookie,csrfName);if(typeof supplied!=="string"||!stored||!bearer.test(supplied)||!timingSafeEqual(Buffer.from(supplied),Buffer.from(stored))){void p.status(403).send({error:"MFA_RECOVERY_CSRF_INVALID"});return null;}await m.assertCsrf(token,supplied);}return token;};
 api.post("/v1/auth/mfa-recovery/start",o.policy("POST /v1/auth/mfa-recovery/start"),guarded("MFA_RECOVERY",async(r,p)=>{const input=parse(start,r.body,p,"MFA_RECOVERY");if(!input||!o.admitStart(r,p))return p;return p.status(202).send(await m.start(input,o.source(r)));}));
 api.post("/v1/auth/mfa-recovery/exchange",o.policy("POST /v1/auth/mfa-recovery/exchange"),guarded("MFA_RECOVERY",async(r,p)=>{const input=parse(exchange,r.body,p,"MFA_RECOVERY");if(!input)return p;const value=await m.exchange(input,o.source(r)),age=Math.min(299,Math.max(0,Math.floor((value.expiresAt.getTime()-Date.now())/1000)));p.header("set-cookie",[`${n}=${value.sessionToken}; Path=/; Max-Age=${age}; HttpOnly; Secure; SameSite=Strict`,`${csrfName}=${value.csrfToken}; Path=/; Max-Age=${age}; Secure; SameSite=Strict`]);return p.send(value.state);}));
 api.get("/v1/auth/mfa-recovery/status",o.policy("GET /v1/auth/mfa-recovery/status"),guarded("MFA_RECOVERY",async(r,p)=>{const token=await session(r,p,false);if(!token)return p;return p.send(await m.status({sessionToken:token}));}));
 const post=<T,>(route:Route,schema:z.ZodType<T>,fn:(body:T,token:string,source:AuthSourceContext)=>Promise<unknown>)=>api.post(route.slice(5),o.policy(route),guarded("MFA_RECOVERY",async(r,p)=>{const body=parse(schema,r.body,p,"MFA_RECOVERY");if(body===null)return p;const token=await session(r,p,true);if(!token)return p;return p.send(await fn(body,token,o.source(r)));}));
 post("POST /v1/auth/mfa-recovery/totp/begin",empty,(_,token,s)=>m.beginFactor({sessionToken:token},s));post("POST /v1/auth/mfa-recovery/totp/verify",digits,(body,token,s)=>m.verifyFactor({...body,sessionToken:token},s));post("POST /v1/auth/mfa-recovery/codes/generate",empty,(_,token,s)=>m.generateCodes({sessionToken:token},s));post("POST /v1/auth/mfa-recovery/codes/confirm",code,(body,token,s)=>m.acknowledge({...body,sessionToken:token},s));post("POST /v1/auth/mfa-recovery/complete",empty,(_,token,s)=>m.complete({sessionToken:token},s));post("POST /v1/auth/mfa-recovery/cancel-current",empty,(_,token,s)=>m.cancelSession({sessionToken:token},s));
 api.post("/v1/auth/mfa-recovery/finish/status",o.policy("POST /v1/auth/mfa-recovery/finish/status"),guarded("MFA_RECOVERY",async(r,p)=>{const input=parse(link,r.body,p,"MFA_RECOVERY");if(!input)return p;return p.send(await m.prepareFinish(input,o.source(r)));}));
 api.post("/v1/auth/mfa-recovery/finish",o.policy("POST /v1/auth/mfa-recovery/finish"),guarded("MFA_RECOVERY",async(r,p)=>{const input=parse(exchange,r.body,p,"MFA_RECOVERY");if(!input)return p;return p.send(await m.finish(input,o.source(r)));}));
 api.post("/v1/auth/mfa-recovery/cancel",o.policy("POST /v1/auth/mfa-recovery/cancel"),guarded("MFA_RECOVERY",async(r,p)=>{const input=parse(link,r.body,p,"MFA_RECOVERY");if(!input)return p;return p.send(await m.cancel(input,o.source(r)));}));
}
