import { randomUUID, createHash } from "node:crypto";
import { beforeAll, afterAll, expect, it } from "vitest";
import { encrypt, createEmailBlindIndex } from "@debateai/crypto";
import { migrate } from "@debateai/db";
import { startTestDatabase, type TestDatabase } from "../support/testDatabase.js";
import { importHistoricalRegisterFixture, registerFixtureRow } from "../support/registerFixtures.js";
let db:TestDatabase;
const policy={kind:"BACKUP_EMAIL_VERIFICATION_POLICY",policy_version:1,proof:"AUTHENTICATED_SELF_PASSWORD_CURRENT_TOTP_AND_BOUND_EMAIL",maximum_elapsed_ms:1800000,per_source_across_accounts:20,source_window_ms:300000,proof_failures_per_attempt:5,preserve_credentials:true,ordinary_only:true};
const key=Buffer.alloc(32,8),source={ipArgon2id:`argon2id-audit:v1:${"a".repeat(64)}`,userAgentArgon2id:`argon2id-audit:v1:${"b".repeat(64)}`};
const hash=()=>`sha256:${createHash("sha256").update(randomUUID()).digest("hex")}`;
const box=(user:string)=>encrypt(key,Buffer.from("bound@example.test"),["identity","user.email_ciphertext",user,"run:none",user,`user-dek:${user}`,"1"]);
async function fixture(){const user=randomUUID(),session=randomUUID(),factor=randomUUID(),primary=randomUUID(),backup=randomUUID(),envelope=box(user),token=hash(),link=hash();await db.pool.query(`INSERT INTO identity."user"(user_id,email_blind_index,email_ciphertext,recovery_email_ciphertext,password_hash,pseudonym,state,adult_affirmed_at) VALUES($1,$2,$3,$3,'unchanged-password',$4,'active',clock_timestamp())`,[user,createEmailBlindIndex(key,`${user}@example.test`),envelope,`backup-${user}`]);await db.pool.query(`INSERT INTO identity.channel_binding(channel_binding_id,user_id,channel_type,address_ciphertext,state,verified_at) VALUES($1,$3,'email',$4,'verified',clock_timestamp()),($2,$3,'recovery_email',$4,'pending_verification',NULL)`,[primary,backup,user,envelope]);await db.pool.query(`INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,secret_ciphertext,state,verified_at) VALUES($1,$2,'totp',$3,'active',clock_timestamp())`,[factor,user,envelope]);await db.pool.query(`INSERT INTO identity.session(session_id,user_id,token_hash,csrf_token_hash,last_mfa_at,idle_expires_at,absolute_expires_at) VALUES($1,$2,$3,$3,clock_timestamp(),clock_timestamp()+interval '1 hour',clock_timestamp()+interval '1 day')`,[session,user,token]);return {user,session,factor,primary,backup,envelope,token,link};}
async function start(a:Awaited<ReturnType<typeof fixture>>){const step=Number((await db.pool.query(`SELECT floor(extract(epoch FROM clock_timestamp())/30)::bigint AS n`)).rows[0].n);return (await db.pool.query(`SELECT identity.backup_email_start($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) AS outcome`,[a.session,a.token,'unchanged-password',a.factor,a.envelope,null,step,a.link,JSON.stringify([a.primary,a.backup].map(channelId=>({channelId,envelope:box(a.user),...(channelId===a.backup?{proofEnvelope:box(a.user)}:{})}))),source,3,randomUUID()])).rows[0].outcome;}
beforeAll(async()=>{db=await startTestDatabase();await migrate(db.pool);await importHistoricalRegisterFixture(db.pool,3,[registerFixtureRow("backupEmailVerificationPolicy",policy,"approved bound backup verification")]);});afterAll(async()=>await db?.stop());
it("exposes a separate backup verification capability",async()=>{expect((await db.pool.query(`SELECT to_regprocedure('identity.backup_email_confirm(text,jsonb)') IS NOT NULL AS present`)).rows[0].present).toBe(true);});
it("verifies only the currently bound pending address and leaves password/factor/codes/sessions unchanged",async()=>{const a=await fixture();expect(await start(a)).toBe(true);expect((await db.pool.query(`SELECT state FROM identity.channel_binding WHERE channel_binding_id=$1`,[a.backup])).rows[0].state).toBe("pending_verification");expect((await db.pool.query(`SELECT identity.backup_email_confirm($1,$2) AS outcome`,[a.link,source])).rows[0].outcome).toBe("VERIFIED");expect((await db.pool.query(`SELECT identity.backup_email_confirm($1,$2) AS outcome`,[a.link,source])).rows[0].outcome).toBe("VERIFIED");expect((await db.pool.query(`SELECT password_hash FROM identity."user" WHERE user_id=$1`,[a.user])).rows[0].password_hash).toBe("unchanged-password");expect((await db.pool.query(`SELECT state,secret_ciphertext FROM identity.mfa_factor WHERE mfa_factor_id=$1`,[a.factor])).rows[0]).toEqual({state:"active",secret_ciphertext:a.envelope});expect((await db.pool.query(`SELECT revoked_at FROM identity.session WHERE session_id=$1`,[a.session])).rows[0].revoked_at).toBeNull();});
it.each(["password","backup","factor","staff","hold","erasure"])("refuses a %s change between current-MFA step-up and mail proof",async(kind)=>{const a=await fixture();expect(await start(a)).toBe(true);if(kind==="password")await db.pool.query(`UPDATE identity."user" SET password_hash='changed' WHERE user_id=$1`,[a.user]);if(kind==="backup")await db.pool.query(`UPDATE identity."user" SET recovery_email_ciphertext=$1 WHERE user_id=$2`,[box(randomUUID()),a.user]);if(kind==="factor")await db.pool.query(`UPDATE identity.mfa_factor SET secret_ciphertext=$1 WHERE mfa_factor_id=$2`,[box(randomUUID()),a.factor]);if(kind==="staff")await db.pool.query(`INSERT INTO staff.subject(user_id,state) VALUES($1,'DISABLED')`,[a.user]);if(kind==="hold")await db.pool.query(`INSERT INTO identity.account_security_hold(user_id,held) VALUES($1,true)`,[a.user]);if(kind==="erasure")await db.pool.query(`INSERT INTO identity.account_erasure_request(user_id,requested_at,execute_at) VALUES($1,clock_timestamp(),clock_timestamp())`,[a.user]);expect((await db.pool.query(`SELECT identity.backup_email_confirm($1,$2) AS outcome`,[a.link,source])).rows[0].outcome).toBe("INVALID");});
it("backup source cleanup waits for admission and keeps its refreshed window",async()=>{const a=await fixture(),refresh={...source,ipArgon2id:`argon2id-audit:v1:${"7".repeat(64)}`};await db.pool.query(`INSERT INTO identity.backup_email_source_window VALUES($1,clock_timestamp()-interval '6 minutes',20)`,[refresh.ipArgon2id]);const lock=await db.pool.connect();await lock.query("BEGIN");try{await lock.query(`SELECT pg_advisory_xact_lock(hashtextextended('backup-email:source:'||$1,0))`,[refresh.ipArgon2id]);const cleanup=db.pool.query(`SELECT identity.backup_email_expire(1000)`);await new Promise(r=>setTimeout(r,100));expect((await db.pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE '%backup_email_expire%'`)).rows[0].n).toBeGreaterThan(0);expect((await lock.query(`SELECT identity.backup_email_admit($1,$2,$3,3) AS value`,[a.session,a.token,refresh])).rows[0].value).toBe(true);await lock.query("COMMIT");await cleanup;expect((await db.pool.query(`SELECT uses FROM identity.backup_email_source_window WHERE source_digest=$1`,[refresh.ipArgon2id])).rows).toEqual([{uses:1}]);}finally{await lock.query("ROLLBACK");lock.release();}});
