import { seedInstalledAuth106 } from "../support/auth106.js";
import { randomUUID,createHash } from "node:crypto";
import { beforeAll,afterAll,expect,it } from "vitest";
import { encrypt,createEmailBlindIndex } from "@debateai/crypto";
import { migrate } from "@debateai/db";
import { RECOVERY_POLICY_REGISTER_ROW, PASSWORD_RESET_POLICY_REGISTER_ROW } from "@debateai/register";
import { startTestDatabase,type TestDatabase } from "../support/testDatabase.js";
import { importHistoricalRegisterFixture,registerFixtureRow } from "../support/registerFixtures.js";
let db:TestDatabase;
const policy={kind:"MFA_RECOVERY_POLICY",policy_version:1,proof:"CURRENT_PASSWORD_AND_ISSUED_PRIOR_VERIFIED_BOUND_EMAIL",tier_qualification:"FRESH_PROOF_PAIR_WITH_ACCOUNT_RISK_CHECKS",email_challenge_ttl_ms:1800000,replacement_ttl_ms:300000,recognized_context_required:false,recognized_context_lookback_ms:2592000000,risk_retention_ms:7776000000,maximum_risk_signals:128,adverse_kinds:["SESSION_CONTEXT_CHANGED","RECOVERY_PROOF_FAILED"],adverse_rule:"AFTER_LATEST_COMPLETED_LOGIN_OR_ANY_WITHOUT_LOGIN",per_source_across_accounts:20,source_window_ms:300000,proof_failures_per_attempt:5,cancel_cooldown_ms:86400000,failure_cooldown_ms:300000,preserve_password:true,ordinary_only:true};
const key=Buffer.alloc(32,7),source={ipArgon2id:`argon2id-audit:v1:${"c".repeat(64)}`,userAgentArgon2id:`argon2id-audit:v1:${"d".repeat(64)}`},hash=()=>`sha256:${createHash("sha256").update(randomUUID()).digest("hex")}`;
const box=(u:string)=>encrypt(key,Buffer.from("owned@example.test"),["identity","user.email_ciphertext",u,"run:none",u,`user-dek:${u}`,"1"]);
const encoded=`$argon2id$v=19$m=19456,t=2,p=1$${"A".repeat(22)}$${"B".repeat(43)}`;
async function createLegacyFixture(){const user=randomUUID(),primary=randomUUID(),backup=randomUUID(),factor=randomUUID(),envelope=box(user),index=createEmailBlindIndex(key,`${user}@example.test`);await db.pool.query(`INSERT INTO identity."user"(user_id,email_blind_index,email_ciphertext,recovery_email_ciphertext,password_hash,pseudonym,state,adult_affirmed_at) VALUES($1,$2,$3,$3,'preserved-password',$4,'active',clock_timestamp())`,[user,index,envelope,`mfa-${user}`]);await db.pool.query(`INSERT INTO identity.channel_binding(channel_binding_id,user_id,channel_type,address_ciphertext,state,verified_at) VALUES($1,$3,'email',$4,'verified',clock_timestamp()),($2,$3,'recovery_email',$4,'verified',clock_timestamp())`,[primary,backup,user,envelope]);await db.pool.query(`INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,secret_ciphertext,state,verified_at) VALUES($1,$2,'totp',$3,'active',clock_timestamp())`,[factor,user,envelope]);return{user,primary,backup,factor,envelope,index,link:hash(),cancel:hash(),session:hash(),csrf:hash(),challenge:randomUUID()};}
const legacyFixtures:Awaited<ReturnType<typeof createLegacyFixture>>[]=[];
async function fixture(){const value=legacyFixtures.shift();if(!value)throw Error("LEGACY106_FIXTURE_EXHAUSTED");return value;}
async function start(a:Awaited<ReturnType<typeof fixture>>,destination="primary"){const candidate=(await db.pool.query(`SELECT identity.mfa_recovery_prepare($1,$2) AS value`,[a.index,destination])).rows[0].value;return(await db.pool.query(`SELECT identity.mfa_recovery_start($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) AS result`,[a.index,destination,a.user,[a.primary,a.backup].sort(),a.link,a.cancel,JSON.stringify([a.primary,a.backup].sort().map(channelId=>({channelId,envelope:box(a.user),...(candidate?.channels.find((c:{channelId:string;cancelAuthorized:boolean})=>c.channelId===channelId)?.cancelAuthorized?{cancelEnvelope:box(a.user)}:{}),...(channelId===(destination==="primary"?a.primary:a.backup)?{proofEnvelope:box(a.user)}:{})}))),source,3,a.challenge])).rows[0].result;}
async function pair(a:Awaited<ReturnType<typeof fixture>>){const risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'link') AS value`,[a.link])).rows[0].value;return(await db.pool.query(`SELECT identity.mfa_recovery_exchange($1,$2,$3,$4,$5,$6,$7) AS result`,[a.link,'preserved-password',a.session,a.csrf,box(a.user),risk.fingerprint,source])).rows[0].result;}
async function ready(a:Awaited<ReturnType<typeof fixture>>){const id=randomUUID(),seed=box(a.user);await db.pool.query(`SELECT identity.mfa_recovery_stage_factor($1,$2,$3,$4)`,[a.session,id,seed,source]);const step=Number((await db.pool.query(`SELECT floor(extract(epoch FROM clock_timestamp())/30)::bigint AS n`)).rows[0].n);await db.pool.query(`SELECT identity.mfa_recovery_verify_factor($1,$2,$3,$4,$5,$6)`,[a.session,id,seed,null,step,source]);const codes=Array.from({length:10},(_,i)=>({slot:i+1,hash:encoded.slice(0,-1)+i}));await db.pool.query(`SELECT identity.mfa_recovery_stage_codes($1,$2,$3)`,[a.session,JSON.stringify(codes),source]);await db.pool.query(`SELECT identity.mfa_recovery_ack_code($1,1,$2,$3)`,[a.session,codes[0]!.hash,source]);return id;}
type Fixture=Awaited<ReturnType<typeof fixture>>;
type WaitChannel={channelId:string;cancelAuthorized:boolean};
/** READY -> WAITING (2026-10-09): the old immediate completion now only starts the 24-hour wait. */
async function waitNotices(a:Fixture){const p=(await db.pool.query(`SELECT identity.mfa_recovery_prepare_wait($1) AS value`,[a.session])).rows[0].value;if(!p)return null;return{prepared:p,notices:(p.channels as WaitChannel[]).map(c=>({channelId:c.channelId,...(c.cancelAuthorized?{cancelEnvelope:box(a.user)}:{}),...(c.channelId===p.proofChannelId?{finishEnvelope:box(a.user)}:{})}))};}
async function beginWait(a:Fixture,fingerprint?:string){const w=await waitNotices(a);const risk=fingerprint??(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value?.fingerprint??"none";const finishHash=hash(),waitCancel=hash();const value=(await db.pool.query(`SELECT identity.mfa_recovery_begin_wait($1,$2,$3,$4,$5,$6) AS value`,[a.session,risk,finishHash,waitCancel,JSON.stringify(w?.notices??[]),source])).rows[0].value;return{value,finishHash,waitCancel};}
async function finish(a:Fixture){const w=await beginWait(a);return w.value?.status==="WAITING"?"WAITING":"INVALID";}
/** The database clock decides the 24 hours; a test moves the pending row (and its scheduled finish mail) 25 hours back. */
async function age(a:Fixture){await db.pool.query(`UPDATE identity.mfa_recovery_control SET waiting_at=waiting_at-interval '25 hours',not_before=not_before-interval '25 hours' WHERE user_id=$1 AND stage='WAITING'`,[a.user]);await db.pool.query(`UPDATE identity.mfa_recovery_notice n SET available_at=n.available_at-interval '25 hours' FROM identity.mfa_recovery_control c WHERE c.challenge_id=n.challenge_id AND c.user_id=$1 AND n.event_kind='FINISH'`,[a.user]);}
async function complete(finishHash:string,password="preserved-password"){const risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'finish') AS value`,[finishHash])).rows[0].value;return(await db.pool.query(`SELECT identity.mfa_recovery_finish($1,$2,$3,$4) AS value`,[finishHash,password,risk?.fingerprint??"none",source])).rows[0].value;}
beforeAll(async()=>{db=await startTestDatabase();await seedInstalledAuth106(db.pool);for(let i=0;i<64;i++)legacyFixtures.push(await createLegacyFixture());await migrate(db.pool);await importHistoricalRegisterFixture(db.pool,3,[registerFixtureRow("mfaRecoveryPolicy",policy,"approved known-password issued bound email rule"),registerFixtureRow("recoveryPolicy",RECOVERY_POLICY_REGISTER_ROW.value,RECOVERY_POLICY_REGISTER_ROW.sourceRef),registerFixtureRow("passwordResetPolicy",PASSWORD_RESET_POLICY_REGISTER_ROW.value,PASSWORD_RESET_POLICY_REGISTER_ROW.sourceRef)]);});afterAll(async()=>await db?.stop());
it("exposes the separately sealed known-password MFA recovery capability",async()=>{expect((await db.pool.query(`SELECT to_regprocedure('identity.mfa_recovery_complete(text,text,jsonb)') IS NOT NULL AS present`)).rows[0].present).toBe(true);});
it("email challenge creates no account grant, paired proofs bind one five-minute attempt, one wait wins, and completion after 24 h preserves password",async()=>{const a=await fixture();expect(await start(a)).toBe(true);expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.account_recovery_binding WHERE user_id=$1 AND closed_at IS NULL`,[a.user])).rows[0].n).toBe(0);expect(await pair(a)).toBe("FACTOR_REQUIRED");const control=(await db.pool.query(`SELECT extract(epoch FROM(expires_at-paired_at)) AS duration FROM identity.mfa_recovery_control WHERE user_id=$1`,[a.user])).rows[0];expect(Number(control.duration)).toBe(300);const newFactor=randomUUID(),newSecret=box(a.user);expect((await db.pool.query(`SELECT identity.mfa_recovery_stage_factor($1,$2,$3,$4) AS result`,[a.session,newFactor,newSecret,source])).rows[0].result).toBe(true);const step=Number((await db.pool.query(`SELECT floor(extract(epoch FROM clock_timestamp())/30)::bigint AS n`)).rows[0].n);expect((await db.pool.query(`SELECT identity.mfa_recovery_verify_factor($1,$2,$3,$4,$5,$6) AS result`,[a.session,newFactor,newSecret,null,step,source])).rows[0].result).toBe(true);const codes=Array.from({length:10},(_,i)=>({slot:i+1,hash:encoded.slice(0,-1)+i}));await db.pool.query(`SELECT identity.mfa_recovery_stage_codes($1,$2,$3)`,[a.session,JSON.stringify(codes),source]);await db.pool.query(`SELECT identity.mfa_recovery_ack_code($1,1,$2,$3)`,[a.session,codes[0]!.hash,source]);const w=await waitNotices(a),risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value,finishes=[hash(),hash()];const outcomes=await Promise.all(finishes.map(f=>db.pool.query(`SELECT identity.mfa_recovery_begin_wait($1,$2,$3,$4,$5,$6) AS value`,[a.session,risk.fingerprint,f,hash(),JSON.stringify(w!.notices),source])));expect(outcomes.map(r=>r.rows[0].value?.status??"INVALID").sort()).toEqual(["INVALID","WAITING"]);const winner=finishes[outcomes.findIndex(r=>r.rows[0].value)]!;expect((await db.pool.query(`SELECT mfa_factor_id FROM identity.mfa_factor WHERE user_id=$1 AND state='active'`,[a.user])).rows).toEqual([{mfa_factor_id:a.factor}]);expect(await complete(winner)).toBe("TOO_EARLY");await age(a);expect(await complete(winner)).toBe("COMPLETED");expect(await complete(winner)).toBe("INVALID");expect((await db.pool.query(`SELECT password_hash FROM identity."user" WHERE user_id=$1`,[a.user])).rows[0].password_hash).toBe("preserved-password");expect((await db.pool.query(`SELECT mfa_factor_id FROM identity.mfa_factor WHERE user_id=$1 AND state='active'`,[a.user])).rows).toEqual([{mfa_factor_id:newFactor}]);expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.recovery_code WHERE user_id=$1 AND consumed_at IS NULL AND revoked_at IS NULL`,[a.user])).rows[0].n).toBe(10);});
it("refuses unverified backup proof without creating a recovery binding",async()=>{const a=await fixture();await db.pool.query(`UPDATE identity.channel_binding SET state='pending_verification',verified_at=NULL WHERE channel_binding_id=$1`,[a.backup]);expect(await start(a,"backup")).toBe(false);expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.account_recovery_binding WHERE user_id=$1`,[a.user])).rows[0].n).toBe(0);});
it.each(["staff","hold","password","factor","email","epoch","erasure"])("refuses %s transitions before paired proof authority",async(kind)=>{const a=await fixture();expect(await start(a)).toBe(true);if(kind==="staff")await db.pool.query(`INSERT INTO staff.subject(user_id,state) VALUES($1,'DISABLED')`,[a.user]);if(kind==="hold")await db.pool.query(`INSERT INTO identity.account_security_hold(user_id,held) VALUES($1,true)`,[a.user]);if(kind==="password")await db.pool.query(`UPDATE identity."user" SET password_hash='changed' WHERE user_id=$1`,[a.user]);if(kind==="factor")await db.pool.query(`UPDATE identity.mfa_factor SET secret_ciphertext=$1 WHERE mfa_factor_id=$2`,[box(randomUUID()),a.factor]);if(kind==="email")await db.pool.query(`UPDATE identity."user" SET email_ciphertext=$1 WHERE user_id=$2`,[box(randomUUID()),a.user]);if(kind==="epoch")await db.pool.query(`INSERT INTO identity.account_security_hold(user_id,held,security_epoch) VALUES($1,false,9)`,[a.user]);if(kind==="erasure")await db.pool.query(`INSERT INTO identity.account_erasure_request(user_id,requested_at,execute_at) VALUES($1,clock_timestamp(),clock_timestamp())`,[a.user]);expect(await pair(a)).toBe("INVALID");});
it("refuses inventory changes after mail proof was issued",async()=>{const a=await fixture();expect(await start(a)).toBe(true);await db.pool.query(`UPDATE identity.channel_binding SET state='revoked',revoked_at=clock_timestamp() WHERE channel_binding_id=$1`,[a.backup]);expect(await pair(a)).toBe("INVALID");});
it("refuses inventory changes after pairing before atomic replacement",async()=>{const a=await fixture();expect(await start(a)).toBe(true);expect(await pair(a)).toBe("FACTOR_REQUIRED");await ready(a);await db.pool.query(`UPDATE identity.channel_binding SET state='revoked',revoked_at=clock_timestamp() WHERE channel_binding_id=$1`,[a.backup]);expect(await finish(a)).toBe("INVALID");});
it("refuses inventory changes during the 24-hour wait and voids the pending replacement",async()=>{const a=await fixture();await start(a);await pair(a);await ready(a);const w=await beginWait(a);expect(w.value.status).toBe("WAITING");await age(a);await db.pool.query(`UPDATE identity.channel_binding SET state='revoked',revoked_at=clock_timestamp() WHERE channel_binding_id=$1`,[a.backup]);expect(await complete(w.finishHash)).toBe("INVALID");expect((await db.pool.query(`SELECT stage FROM identity.mfa_recovery_control WHERE user_id=$1`,[a.user])).rows[0].stage).toBe("EXPIRED");expect((await db.pool.query(`SELECT mfa_factor_id FROM identity.mfa_factor WHERE user_id=$1 AND state='active'`,[a.user])).rows).toEqual([{mfa_factor_id:a.factor}]);});
it("serializes two email proofs so only one recovery binding wins",async()=>{const a=await fixture(),b={...a,link:hash(),cancel:hash(),session:hash(),csrf:hash(),challenge:randomUUID()};expect(await start(a)).toBe(true);expect(await start(b,"backup")).toBe(true);expect((await Promise.all([pair(a),pair(b)])).sort()).toEqual(["FACTOR_REQUIRED","INVALID"]);});
it("rechecks the DB expiry after a real wait-start lock wait",async()=>{const a=await fixture();await start(a);await pair(a);await ready(a);const w=await waitNotices(a),risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value,lock=await db.pool.connect();await lock.query("BEGIN");try{await lock.query(`SELECT identity.lock_security_subjects($1)`,[[a.user]]);await lock.query(`UPDATE identity.mfa_recovery_control SET expires_at=clock_timestamp()+interval '300 milliseconds' WHERE user_id=$1`,[a.user]);const pending=db.pool.query(`SELECT identity.mfa_recovery_begin_wait($1,$2,$3,$4,$5,$6) AS result`,[a.session,risk.fingerprint,hash(),hash(),JSON.stringify(w!.notices),source]);await new Promise(r=>setTimeout(r,100));expect((await db.pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE '%mfa_recovery_begin_wait%'`)).rows[0].n).toBeGreaterThan(0);await new Promise(r=>setTimeout(r,250));await lock.query("COMMIT");expect((await pending).rows[0].result).toBeNull();}finally{await lock.query("ROLLBACK");lock.release();}});
it("honors global T2 cooldown and adds 24h contest protection for MFA cancel",async()=>{const a=await fixture();await db.pool.query(`INSERT INTO identity.password_recovery_retry_lock(user_id,locked_until) VALUES($1,clock_timestamp()+interval '24 hours')`,[a.user]);expect(await start(a)).toBe(false);await db.pool.query(`DELETE FROM identity.password_recovery_retry_lock WHERE user_id=$1`,[a.user]);await start(a);await pair(a);expect((await db.pool.query(`SELECT identity.mfa_recovery_cancel_session($1,$2) AS value`,[a.session,source])).rows[0].value).toBe("CANCELLED");expect((await db.pool.query(`SELECT locked_until>clock_timestamp()+interval '23 hours' AS paused FROM identity.password_recovery_retry_lock WHERE user_id=$1`,[a.user])).rows[0].paused).toBe(true);expect((await db.pool.query(`SELECT identity.mfa_recovery_read($1) AS value`,[a.session])).rows[0].value.stage).toBe("CANCELLED");expect((await db.pool.query(`SELECT identity.password_recovery_prepare($1) AS value`,[a.index])).rows[0].value).toBeNull();});
it("proof failures impose the existing temporary cross-method cooldown without changing credentials",async()=>{const a=await fixture();await start(a);for(let i=0;i<5;i++)await db.pool.query(`SELECT identity.mfa_recovery_failure($1,'link',$2)`,[a.link,source]);expect((await db.pool.query(`SELECT locked_until>clock_timestamp()+interval '4 minutes' AS paused FROM identity.password_recovery_retry_lock WHERE user_id=$1`,[a.user])).rows[0].paused).toBe(true);expect(await start({...a,challenge:randomUUID(),link:hash(),cancel:hash()})).toBe(false);expect((await db.pool.query(`SELECT password_hash FROM identity."user" WHERE user_id=$1`,[a.user])).rows[0].password_hash).toBe("preserved-password");});
it("new MFA code restart keeps the same expiry and requires independent code acknowledgement",async()=>{const a=await fixture();await start(a);await pair(a);const original=(await db.pool.query(`SELECT expires_at FROM identity.mfa_recovery_control WHERE user_id=$1`,[a.user])).rows[0].expires_at;await ready(a);expect((await db.pool.query(`SELECT expires_at FROM identity.mfa_recovery_control WHERE user_id=$1`,[a.user])).rows[0].expires_at).toEqual(original);});
it("normal password reset and MFA recovery cannot both win the shared live binding",async()=>{const a=await fixture();await start(a);const reset=db.pool.query(`SELECT identity.password_reset_start($1,$2,$3,$4,$5,$6,$7,$8,3) AS value`,[a.index,a.user,[a.primary,a.backup].sort(),box(a.user),hash(),hash(),JSON.stringify([a.primary,a.backup].sort().map(channelId=>({channelId,envelope:box(a.user),...(channelId===a.primary?{proofEnvelope:box(a.user)}:{})}))),source]);const[created,paired]=await Promise.all([reset,pair(a)]);expect(Number(created.rows[0].value)+Number(paired==="FACTOR_REQUIRED")).toBe(1);expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.account_recovery_binding WHERE user_id=$1 AND closed_at IS NULL`,[a.user])).rows[0].n).toBe(1);});
it("live risk writer shares the lock and a committed adverse event defeats a stale completion snapshot",async()=>{const a=await fixture();await start(a);await pair(a);await ready(a);const old=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value,handle=(await db.pool.query(`SELECT r.public_handle FROM identity.account_recovery_request r JOIN identity.mfa_recovery_control c USING(recovery_request_id) WHERE c.user_id=$1`,[a.user])).rows[0].public_handle,context=encrypt(key,Buffer.from(JSON.stringify({v:1,networkRef:source.ipArgon2id,clientRef:source.userAgentArgon2id})),["identity","authentication_risk_signal.context_ciphertext",a.user,"run:none",a.user,`auth-risk:${a.user}:v1`,"1"]),lock=await db.pool.connect();await lock.query("BEGIN");try{await lock.query(`SELECT identity.mfa_recovery_read($1)`,[a.session]);const pending=db.pool.query(`SELECT identity.record_authentication_risk_signal_for_recovery($1,'RECOVERY_PROOF_FAILED',$2)`,[handle,context]);await new Promise(r=>setTimeout(r,100));expect((await db.pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE '%record_authentication_risk_signal_for_recovery%'`)).rows[0].n).toBeGreaterThan(0);await lock.query("COMMIT");await pending;expect((await beginWait(a,old.fingerprint)).value).toBeNull();expect(await finish(a)).toBe("INVALID");}finally{await lock.query("ROLLBACK");lock.release();}});
it("a winning wait start blocks concurrent normal session risk insertion until its commit without deadlock",async()=>{const a=await fixture();await start(a);await pair(a);await ready(a);const session=randomUUID(),token=hash(),binding=hash();await db.pool.query(`INSERT INTO identity.session(session_id,user_id,token_hash,csrf_token_hash,binding_context,last_mfa_at,idle_expires_at,absolute_expires_at) VALUES($1,$2,$3,$3,$4,clock_timestamp(),clock_timestamp()+interval '1 hour',clock_timestamp()+interval '1 day')`,[session,a.user,token,{user_agent_hash:binding}]);const context=encrypt(key,Buffer.from(JSON.stringify({v:1,networkRef:source.ipArgon2id,clientRef:source.userAgentArgon2id})),["identity","authentication_risk_signal.context_ciphertext",a.user,"run:none",a.user,`auth-risk:${a.user}:v1`,"1"]),risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value,lock=await db.pool.connect();await lock.query("BEGIN");try{await lock.query(`SELECT identity.mfa_recovery_read($1)`,[a.session]);const pending=db.pool.query(`SELECT identity.record_authentication_risk_signal_for_session($1,$2,'SESSION_CONTEXT_CHANGED',$3)`,[token,binding,context]);await new Promise(r=>setTimeout(r,100));expect((await db.pool.query(`SELECT count(*)::int AS n FROM pg_stat_activity WHERE wait_event_type='Lock' AND query LIKE '%record_authentication_risk_signal_for_session%'`)).rows[0].n).toBeGreaterThan(0);const w=(await lock.query(`SELECT identity.mfa_recovery_prepare_wait($1) AS value`,[a.session])).rows[0].value as {proofChannelId:string;channels:WaitChannel[]};expect((await lock.query(`SELECT identity.mfa_recovery_begin_wait($1,$2,$3,$4,$5,$6) AS value`,[a.session,risk.fingerprint,hash(),hash(),JSON.stringify(w.channels.map(c=>({channelId:c.channelId,...(c.cancelAuthorized?{cancelEnvelope:box(a.user)}:{}),...(c.channelId===w.proofChannelId?{finishEnvelope:box(a.user)}:{})}))),source])).rows[0].value.status).toBe("WAITING");await lock.query("COMMIT");await pending;}finally{await lock.query("ROLLBACK");lock.release();}});
it("does not promote an originally pending notice to cancellation authority after its backup is verified",async()=>{const a=await fixture();await db.pool.query(`UPDATE identity.channel_binding SET state='pending_verification',verified_at=NULL WHERE channel_binding_id=$1`,[a.backup]);expect(await start(a)).toBe(true);expect(await pair(a)).toBe("FACTOR_REQUIRED");await db.pool.query(`UPDATE identity.channel_binding SET state='verified',verified_at=clock_timestamp() WHERE channel_binding_id=$1`,[a.backup]);let seen=false;for(let i=0;i<1000;i++){const n=(await db.pool.query(`SELECT identity.mfa_recovery_claim_notice(60000) AS value`)).rows[0].value;if(!n)break;if(n.userId===a.user&&n.channelId===a.backup&&n.event==="STARTED"){expect(n.cancelAllowed).toBe(false);seen=true;}await db.pool.query(`SELECT identity.mfa_recovery_finish_notice($1,$2,true,300000,3)`,[n.noticeId,n.leaseId]);}expect(seen).toBe(true);});
it("MFA source cleanup removes only stale quota rows so structural capacity can recover",async()=>{const stale=`argon2id-audit:v1:${"8".repeat(64)}`,fresh=`argon2id-audit:v1:${"9".repeat(64)}`;await db.pool.query(`INSERT INTO identity.mfa_recovery_source_window VALUES($1,clock_timestamp()-interval '6 minutes',21),($2,clock_timestamp(),21)`,[stale,fresh]);await db.pool.query(`SELECT identity.mfa_recovery_expire(1000)`);expect((await db.pool.query(`SELECT source_digest FROM identity.mfa_recovery_source_window WHERE source_digest=ANY($1::text[])`,[[stale,fresh]])).rows).toEqual([{source_digest:fresh}]);});

// Owner ruling 2026-10-09 (design note docs/superpowers/specs/2026-10-09-auth-db-batch-design.md, item 2):
// replacing an authenticator through email + password waits 24 hours; the database enforces it.
async function readyWaiting(){const a=await fixture();expect(await start(a)).toBe(true);expect(await pair(a)).toBe("FACTOR_REQUIRED");const newFactor=await ready(a);const w=await beginWait(a);expect(w.value?.status).toBe("WAITING");return{a,newFactor,...w};}
async function liveSession(user:string){const session=randomUUID(),token=hash();await db.pool.query(`INSERT INTO identity.session(session_id,user_id,token_hash,csrf_token_hash,binding_context,last_mfa_at,idle_expires_at,absolute_expires_at) VALUES($1,$2,$3,$4,$5,clock_timestamp(),clock_timestamp()+interval '1 hour',clock_timestamp()+interval '1 day')`,[session,user,token,hash(),{user_agent_hash:hash()}]);return{userId:user,sessionId:session,tokenHash:token};}
async function stage(user:string){return(await db.pool.query(`SELECT stage FROM identity.mfa_recovery_control WHERE user_id=$1 ORDER BY waiting_at DESC NULLS LAST LIMIT 1`,[user])).rows[0]?.stage;}
it("starting the wait replaces nothing: the old authenticator, recovery codes and sessions keep working",async()=>{const a=await fixture();await db.pool.query(`INSERT INTO identity.recovery_code(user_id,code_slot,code_hash,created_at) VALUES($1,1,$2,clock_timestamp())`,[a.user,encoded]);const s=await liveSession(a.user);expect(await start(a)).toBe(true);await pair(a);const newFactor=await ready(a);const w=await beginWait(a);
 expect(w.value.status).toBe("WAITING");const row=(await db.pool.query(`SELECT stage,extract(epoch FROM not_before-waiting_at)::int AS wait,extract(epoch FROM expires_at-not_before)::int AS window,csrf_hash FROM identity.mfa_recovery_control WHERE user_id=$1`,[a.user])).rows[0];expect(row).toEqual({stage:"WAITING",wait:86400,window:604800,csrf_hash:null});
 expect(new Date(w.value.notBefore).getTime()-Date.now()).toBeGreaterThan(86_000_000);
 expect((await db.pool.query(`SELECT mfa_factor_id,state FROM identity.mfa_factor WHERE user_id=$1 AND state<>'revoked' ORDER BY state`,[a.user])).rows).toEqual([{mfa_factor_id:a.factor,state:"active"},{mfa_factor_id:newFactor,state:"verified_pending_recovery"}]);
 expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.recovery_code WHERE user_id=$1 AND consumed_at IS NULL AND revoked_at IS NULL`,[a.user])).rows[0].n).toBe(1);
 expect((await db.pool.query(`SELECT revoked_at FROM identity.session WHERE session_id=$1`,[s.sessionId])).rows[0].revoked_at).toBeNull();
 // The five-minute recovery binding is closed, so ordinary password reset is not blocked by the wait.
 expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.account_recovery_binding WHERE user_id=$1 AND closed_at IS NULL`,[a.user])).rows[0].n).toBe(0);
 // The recovery browser session can read the waiting state but can no longer act.
 const read=(await db.pool.query(`SELECT identity.mfa_recovery_read($1) AS value`,[a.session])).rows[0].value;expect(read.stage).toBe("WAITING");expect(read.csrfHash).toBeNull();expect(new Date(read.notBefore).toISOString()).toBe(new Date(w.value.notBefore).toISOString());
 expect((await db.pool.query(`SELECT identity.mfa_recovery_prepare_wait($1) AS value`,[a.session])).rows[0].value).toBeNull();
});
it("mails every bound address a WAITING notice and schedules the finish link for the proving address at not_before",async()=>{const {a,finishHash}=await readyWaiting();
 const notices=(await db.pool.query(`SELECT n.channel_id,n.event_kind,n.available_at>clock_timestamp()+interval '23 hours' AS later FROM identity.mfa_recovery_notice n JOIN identity.mfa_recovery_control c USING(challenge_id) WHERE c.user_id=$1 AND n.event_kind IN('WAITING','FINISH') ORDER BY n.event_kind,n.channel_id`,[a.user])).rows;
 expect(notices).toEqual([{channel_id:a.primary,event_kind:"FINISH",later:true},...[a.primary,a.backup].sort().map(channel_id=>({channel_id,event_kind:"WAITING",later:false}))]);
 const claimed:Array<{userId:string;event:string;cancelAllowed:boolean;notBefore?:string;noticeId:string;leaseId:string}>=[];for(let i=0;i<1000;i++){const n=(await db.pool.query(`SELECT identity.mfa_recovery_claim_notice(60000) AS value`)).rows[0].value;if(!n)break;if(n.userId===a.user)claimed.push(n);await db.pool.query(`SELECT identity.mfa_recovery_finish_notice($1,$2,true,300000,3)`,[n.noticeId,n.leaseId]);}
 const waiting=claimed.filter(n=>n.event==="WAITING");expect(waiting).toHaveLength(2);for(const n of waiting){expect(n.cancelAllowed).toBe(true);expect(n.notBefore).toBeTruthy();}expect(claimed.some(n=>n.event==="FINISH")).toBe(false);
 await age(a);const finish=(await db.pool.query(`SELECT identity.mfa_recovery_claim_notice(60000) AS value`)).rows[0].value;expect(finish).toMatchObject({userId:a.user,channelId:a.primary,event:"FINISH"});expect(finish.notBefore).toBeTruthy();await db.pool.query(`SELECT identity.mfa_recovery_finish_notice($1,$2,true,300000,3)`,[finish.noticeId,finish.leaseId]);
 expect((await db.pool.query(`SELECT identity.mfa_recovery_prepare_finish($1) AS value`,[finishHash])).rows[0].value).toMatchObject({userId:a.user,passwordHash:"preserved-password",ready:true});
});
it("refuses to finish before 24 hours even when the API is bypassed, then finishes once and only then revokes the old factor, codes and sessions",async()=>{const a=await fixture();await db.pool.query(`INSERT INTO identity.recovery_code(user_id,code_slot,code_hash,created_at) VALUES($1,1,$2,clock_timestamp())`,[a.user,encoded]);const s=await liveSession(a.user);await start(a);await pair(a);const newFactor=await ready(a);const w=await beginWait(a);
 expect((await db.pool.query(`SELECT identity.mfa_recovery_prepare_finish($1) AS value`,[w.finishHash])).rows[0].value).toMatchObject({ready:false});
 expect(await complete(w.finishHash)).toBe("TOO_EARLY");
 // Moving only not_before (not the wait start) is refused by the table itself.
 await expect(db.pool.query(`UPDATE identity.mfa_recovery_control SET not_before=clock_timestamp() WHERE user_id=$1`,[a.user])).rejects.toMatchObject({code:"23514"});
 expect(await complete(w.finishHash)).toBe("TOO_EARLY");expect(await stage(a.user)).toBe("WAITING");
 await age(a);
 expect(await complete(w.finishHash,"wrong-password")).toBe("INVALID");
 expect(await complete(w.finishHash)).toBe("COMPLETED");
 expect((await db.pool.query(`SELECT mfa_factor_id FROM identity.mfa_factor WHERE user_id=$1 AND state='active'`,[a.user])).rows).toEqual([{mfa_factor_id:newFactor}]);
 expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.recovery_code WHERE user_id=$1 AND consumed_at IS NULL AND revoked_at IS NULL`,[a.user])).rows[0].n).toBe(10);
 expect((await db.pool.query(`SELECT revoked_at IS NOT NULL AS revoked FROM identity.session WHERE session_id=$1`,[s.sessionId])).rows[0].revoked).toBe(true);
 expect((await db.pool.query(`SELECT password_hash FROM identity."user" WHERE user_id=$1`,[a.user])).rows[0].password_hash).toBe("preserved-password");
 expect(await complete(w.finishHash)).toBe("INVALID");
});
it("the old immediate completion is inert and no longer granted to the recovery runtime",async()=>{const a=await fixture();await start(a);await pair(a);await ready(a);const risk=(await db.pool.query(`SELECT identity.mfa_recovery_risk($1,'session') AS value`,[a.session])).rows[0].value;
 expect((await db.pool.query(`SELECT identity.mfa_recovery_complete($1,$2,$3) AS value`,[a.session,risk.fingerprint,source])).rows[0].value).toBe("INVALID");expect(await stage(a.user)).toBe("READY");
 const grants=(await db.pool.query(`SELECT p.proname,has_function_privilege('debateai_mfa_recovery_runtime',p.oid,'EXECUTE') AS runtime,has_function_privilege('debateai_authorization_runtime',p.oid,'EXECUTE') AS authorization,has_function_privilege('debateai_runtime',p.oid,'EXECUTE') AS api,pg_get_userbyid(p.proowner) AS owner,p.prosecdef,p.proconfig FROM pg_proc p WHERE p.pronamespace='identity'::regnamespace AND p.proname IN('mfa_recovery_complete','mfa_recovery_waiting_current','mfa_recovery_prepare_wait','mfa_recovery_begin_wait','mfa_recovery_prepare_finish','mfa_recovery_finish','mfa_recovery_pending_read','mfa_recovery_pending_cancel') ORDER BY p.proname`)).rows;
 expect(grants.map(g=>[g.proname,g.runtime,g.authorization,g.api])).toEqual([["mfa_recovery_begin_wait",true,false,false],["mfa_recovery_complete",false,false,false],["mfa_recovery_finish",true,false,false],["mfa_recovery_pending_cancel",false,true,false],["mfa_recovery_pending_read",false,true,false],["mfa_recovery_prepare_finish",true,false,false],["mfa_recovery_prepare_wait",true,false,false],["mfa_recovery_waiting_current",false,false,false]]);
 for(const g of grants){expect(g.owner).toBe("debateai_mfa_recovery_owner");expect(g.prosecdef).toBe(true);expect(g.proconfig).toEqual(["search_path=pg_catalog"]);}
});
it("cancels a waiting replacement with the emailed wait-cancel link or the original cancel link",async()=>{for(const which of["wait","start"]as const){const {a,newFactor,finishHash,waitCancel}=await readyWaiting();
 expect((await db.pool.query(`SELECT identity.mfa_recovery_cancel($1,$2) AS value`,[which==="wait"?waitCancel:a.cancel,source])).rows[0].value).toBe("CANCELLED");
 expect(await stage(a.user)).toBe("CANCELLED");expect((await db.pool.query(`SELECT state FROM identity.mfa_factor WHERE mfa_factor_id=$1`,[newFactor])).rows[0].state).toBe("revoked");
 expect((await db.pool.query(`SELECT locked_until>clock_timestamp()+interval '23 hours' AS paused FROM identity.password_recovery_retry_lock WHERE user_id=$1`,[a.user])).rows[0].paused).toBe(true);
 await age(a);expect(await complete(finishHash)).toBe("INVALID");
 expect((await db.pool.query(`SELECT identity.mfa_recovery_cancel($1,$2) AS value`,[waitCancel,source])).rows[0].value).toBe("CANCELLED");}
});
it("a signed-in session of the same account sees the pending replacement and can cancel it; another account cannot",async()=>{const {a,finishHash}=await readyWaiting();const own=await liveSession(a.user),other=await fixture(),stranger=await liveSession(other.user);
 const pending=(await db.pool.query(`SELECT identity.mfa_recovery_pending_read($1) AS value`,[own])).rows[0].value;expect(Object.keys(pending).sort()).toEqual(["notBefore","waitingAt"]);
 expect((await db.pool.query(`SELECT identity.mfa_recovery_pending_read($1) AS value`,[stranger])).rows[0].value).toBeNull();
 await expect(db.pool.query(`SELECT identity.mfa_recovery_pending_read($1) AS value`,[{...own,tokenHash:hash()}])).rejects.toThrow("CONSUMER_SECURITY_INVALID");
 expect((await db.pool.query(`SELECT identity.mfa_recovery_pending_cancel($1,$2) AS value`,[stranger,source])).rows[0].value).toBe("INVALID");expect(await stage(a.user)).toBe("WAITING");
 expect((await db.pool.query(`SELECT identity.mfa_recovery_pending_cancel($1,$2) AS value`,[own,source])).rows[0].value).toBe("CANCELLED");expect(await stage(a.user)).toBe("CANCELLED");
 expect((await db.pool.query(`SELECT identity.mfa_recovery_pending_read($1) AS value`,[own])).rows[0].value).toBeNull();await age(a);expect(await complete(finishHash)).toBe("INVALID");
});
it("a password change during the wait voids the pending replacement",async()=>{const {a,newFactor,finishHash}=await readyWaiting();const own=await liveSession(a.user);await db.pool.query(`UPDATE identity."user" SET password_hash='changed-by-owner' WHERE user_id=$1`,[a.user]);
 expect((await db.pool.query(`SELECT identity.mfa_recovery_pending_read($1) AS value`,[own])).rows[0].value).toBeNull();expect(await stage(a.user)).toBe("EXPIRED");
 expect((await db.pool.query(`SELECT state FROM identity.mfa_factor WHERE mfa_factor_id=$1`,[newFactor])).rows[0].state).toBe("revoked");await age(a);expect(await complete(finishHash,"changed-by-owner")).toBe("INVALID");
});
it("keeps at most one waiting replacement per account",async()=>{const {a}=await readyWaiting();const b={...a,link:hash(),cancel:hash(),session:hash(),csrf:hash(),challenge:randomUUID()};expect(await start(b,"backup")).toBe(true);expect(await pair(b)).toBe("FACTOR_REQUIRED");await ready(b);expect((await beginWait(b)).value).toBeNull();expect((await db.pool.query(`SELECT count(*)::int AS n FROM identity.mfa_recovery_control WHERE user_id=$1 AND stage='WAITING'`,[a.user])).rows[0].n).toBe(1);});
