import {realpathSync} from 'node:fs';
import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { createPool, migrate, type Pool } from '@debateai/db';
import { ownerCandidate, ownerNativeReceipts } from '../support/ownerRecoveryFixtures.js';
import { startTestDatabase, type TestDatabase } from '../support/testDatabase.js';

let database: TestDatabase, jit: Pool, runtime: Pool;
const digest=(value:string)=>`sha256:${createHash('sha256').update(value).digest('hex')}`;
const firstGeneration=randomUUID(),firstVerifier=digest('task6-offline-proof');
async function candidate() {
 const userId=randomUUID(),factorId=randomUUID(),credentialIds=[`key_${randomUUID().replaceAll('-','')}`,`key_${randomUUID().replaceAll('-','')}`];
 await database.pool.query(`INSERT INTO identity."user"(user_id,email_blind_index,email_ciphertext,recovery_email_ciphertext,password_hash,pseudonym,state,adult_affirmed_at) VALUES($1,$2,'{}','{}','synthetic-password',$3,'active',now())`,[userId,createHash('sha256').update(userId).digest(),userId]);
 await database.pool.query(`INSERT INTO identity.channel_binding(user_id,channel_type,address_ciphertext,state,created_at,verified_at) VALUES($1,'email','{}','verified',now(),now())`,[userId]);
 await database.pool.query(`INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,secret_ciphertext,state,created_at,verified_at,last_accepted_step) VALUES($1,$2,'totp','{}','active',now(),now(),1)`,[factorId,userId]);
 for(const credentialId of credentialIds){const id=randomUUID();await database.pool.query(`INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,credential_id,public_key,state,created_at,verified_at,relying_party_id,credential_origin,user_verification_required,backup_eligible,backup_state,device_label_ciphertext,signature_counter) VALUES($1,$2,'passkey',$3,'{"format":"COSE_KEY_BASE64URL_V1","value":"YQ"}','active',now(),now(),'localhost','https://localhost',true,false,false,$4,0)`,[id,userId,credentialId,{v:1,keyId:`passkey-label:${id}:v1`,nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}]);}
 return {userId,credentialIds};
}
beforeAll(async()=>{
 database=await startTestDatabase();await migrate(database.pool);
 await database.pool.query(`ALTER ROLE debateai_prod_staff_recovery PASSWORD 'task6-synthetic-jit-only' VALID UNTIL '${new Date(Date.now()+240000).toISOString()}'`);
 await database.pool.query(`CREATE ROLE task6_runtime LOGIN PASSWORD 'task6-synthetic-runtime-only' IN ROLE debateai_runtime`);
 const url=new URL(database.connectionString);url.username='debateai_prod_staff_recovery';url.password='task6-synthetic-jit-only';jit=createPool(url.toString());url.username='task6_runtime';url.password='task6-synthetic-runtime-only';runtime=createPool(url.toString());
},120000);
afterAll(async()=>{await jit?.end();await runtime?.end();await database?.stop();});
describe('independent Owner authority on disposable PostgreSQL',()=>{
 it('refuses legacy JIT prepare without independent recovery generation proof',async()=>{
  const target=await candidate();await expect(jit.query('SELECT staff.prepare_owner_command($1,$2,$3,$4::text[],$5,$6)', ['BOOTSTRAP',target.userId,null,target.credentialIds,randomUUID(),digest('synthetic-command-nonce')])).rejects.toThrow('OWNER_RECOVERY_GENERATION_REQUIRED');
  expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_command')).rows[0].n).toBe(0);
 });
 it('denies material installation and protected exact receipt reads to the real runtime principal',async()=>{
  await expect(runtime.query('SELECT staff.install_owner_recovery_generation($1,$2,$3)',[randomUUID(),digest('synthetic-proof'),randomUUID()])).rejects.toMatchObject({code:'42501'});
  await expect(runtime.query('SELECT staff.read_owner_command($1)',[randomUUID()])).rejects.toMatchObject({code:'42501'});
  await expect(runtime.query('SELECT staff.read_owner_receipts($1,$2::uuid[])',[randomUUID(),[randomUUID(),randomUUID()]])).rejects.toMatchObject({code:'42501'});
 });
 it('requires current generation proof, two native stored receipts, and atomically admits only one first Owner',async()=>{
  await jit.query('SELECT staff.install_owner_recovery_generation($1,$2,$3)',[firstGeneration,firstVerifier,randomUUID()]);
  const targets=[await ownerCandidate(database.pool),await ownerCandidate(database.pool)];
  const commands:Array<{target:Awaited<ReturnType<typeof ownerCandidate>>;commandId:string;operationId:string;receiptIds:readonly [string,string];nextGeneration:string;nextVerifier:string;nextLineage:string;alert:object}>=[];
  for(const target of targets){
   const nonce=Buffer.alloc(32,7).toString('base64url'),operationId=randomUUID(),commandId=randomUUID();
   await expect(jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[commandId,'BOOTSTRAP',target.userId,null,null,false,target.credentialIds,operationId,digest(nonce),firstGeneration,digest('wrong-proof')])).rejects.toThrow('OWNER_RECOVERY_PROOF_INVALID');
   await jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[commandId,'BOOTSTRAP',target.userId,null,null,false,target.credentialIds,operationId,digest(nonce),firstGeneration,firstVerifier]);
   expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_designation WHERE active')).rows[0].n).toBe(0);
   await expect(jit.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[commandId,[randomUUID(),randomUUID()],operationId,'BOOTSTRAP',firstGeneration,firstVerifier,randomUUID(),digest('next'),randomUUID(),{}])).rejects.toThrow('STAFF_OWNER_RECEIPTS_INVALID');
   const receiptIds=await ownerNativeReceipts(runtime,target,commandId,nonce),nextGeneration=randomUUID(),nextVerifier=digest('next'+nextGeneration),nextLineage=randomUUID();
   await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['f'.repeat(64),randomUUID(),'fixture-only',randomUUID(),new Date(Date.now()+60000)]);
   const ready=(await database.pool.query('SELECT generation FROM staff.independent_alert_readiness')).rows[0].generation as string;
   await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[commandId,operationId,'f'.repeat(64),ready]);
   commands.push({target,commandId,operationId,receiptIds,nextGeneration,nextVerifier,nextLineage,alert:{schema:'staff-alert-v1',event:'BOOTSTRAP',operationId,envelope:{v:1,keyId:'fixture',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}}});
  }
  // Each command receives its own current lease against the same publication.
  const ready=(await database.pool.query('SELECT generation FROM staff.independent_alert_readiness')).rows[0].generation as string;
  for(const c of commands)await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[c.commandId,c.operationId,'f'.repeat(64),ready]);
  const commit=(c:typeof commands[number])=>jit.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb) AS value',[c.commandId,c.receiptIds,c.operationId,'BOOTSTRAP',firstGeneration,firstVerifier,c.nextGeneration,c.nextVerifier,c.nextLineage,c.alert]);
  const outcomes=await Promise.allSettled(commands.map(commit));expect(outcomes.filter(x=>x.status==='fulfilled')).toHaveLength(1);
  const winner=commands[outcomes.findIndex(x=>x.status==='fulfilled')]!;
  expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_designation WHERE active')).rows[0].n).toBe(1);
  expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.bootstrap_marker')).rows[0].n).toBe(1);
  expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_possession_receipt WHERE command_id=$1 AND consumed_at IS NOT NULL',[winner.commandId])).rows[0].n).toBe(2);
  expect((await commit(winner)).rows[0].value).toEqual((outcomes.find(x=>x.status==='fulfilled') as PromiseFulfilledResult<Awaited<ReturnType<typeof commit>>>).value.rows[0].value);
  expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.audit_event WHERE operation_id=$1',[winner.operationId])).rows[0].n).toBe(1);
  await expect(jit.query('SELECT staff.install_owner_recovery_generation($1,$2,$3)',[firstGeneration,firstVerifier,randomUUID()])).rejects.toThrow('OWNER_RECOVERY_GENERATION_ALREADY_INSTALLED');
  const {encrypt,decrypt}=await import('@debateai/crypto'),{mkdtemp,readFile,writeFile,rm}=await import('node:fs/promises'),{join}=await import('node:path'),{tmpdir}=await import('node:os');
  const privateRunId=randomUUID(),privateDek=randomBytes(32),privateAad=['core','run.content_ciphertext',privateRunId,privateRunId,winner.target.ownerRef,'task6-private-run:v1','1'] as const,privateEnvelope=encrypt(privateDek,Buffer.from('synthetic-held-private-question'),privateAad);
  const provision=(await database.pool.query('SELECT core.prepare_run_key_provision($1,$2,$3,$4) AS value',[privateRunId,winner.target.userId,winner.target.ownerRef,winner.target.ordinarySessionId])).rows[0].value as string,attestationSecret=randomBytes(32);
  const attestation=(await database.pool.query(`SELECT audit_crypto_internal.hmac(core.content_envelope_attestation_bytes($1::uuid,'core.run',($1::uuid)::text,'content_ciphertext',$2::jsonb),$3,'sha256') AS value`,[privateRunId,privateEnvelope,attestationSecret])).rows[0].value as Buffer;
  const document={runId:privateRunId,questionLine:'⟦DEBATEAI:CIPHERTEXT:V1⟧',askerId:'owner:'+winner.target.ownerRef,executionRef:provision,callerScope:'ASKER',asOf:new Date().toISOString(),askerRiskTier:'casual',riskTier:'casual',tierSource:'ASKER',tierProvenanceRef:'task6-synthetic',compositionBudgetTier:'low',depthParams:{depth:1},discoveredPanel:[{agentId:'task6-synthetic'}],strangerSampleRate:1,envelopeBasis:{source:'task6-synthetic'},registerVersion:1,batteryVersion:'task6-synthetic',askContract:{ciphertext:true,v:1},contentCiphertext:privateEnvelope,contentAttestation:attestation.toString('base64'),contentAttestationSecret:attestationSecret.toString('base64')};
  expect((await database.pool.query('SELECT core.create_encrypted_run($1::jsonb,$2,$3,$4::jsonb) AS value',[document,winner.target.userId,winner.target.ownerRef,JSON.stringify([])])).rows[0].value).toBe(true);attestationSecret.fill(0);
  const privateRoot=await mkdtemp(join(tmpdir(),'task6-private-content-')),privateKeyFile=join(privateRoot,'run-key');await writeFile(privateKeyFile,privateDek,{mode:0o600});const privateKeyHash=createHash('sha256').update(privateDek).digest('hex');
  const replacement=await ownerCandidate(database.pool),op=randomUUID(),command=randomUUID(),nonce=Buffer.alloc(32,8).toString('base64url');
  await expect(jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[command,'RECOVER_OWNER',replacement.userId,randomUUID(),winner.target.userId,false,replacement.credentialIds,op,digest(nonce),winner.nextGeneration,winner.nextVerifier])).rejects.toThrow('STAFF_OWNER_PREDECESSOR_INVALID');
  await jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[command,'RECOVER_OWNER',replacement.userId,winner.nextLineage,winner.target.userId,false,replacement.credentialIds,op,digest(nonce),winner.nextGeneration,winner.nextVerifier]);
  const receipts=await ownerNativeReceipts(runtime,replacement,command,nonce),next=randomUUID(),verifier=digest('third'+next),lineage=randomUUID();
  const ready2=randomUUID();await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['f'.repeat(64),ready2,'fixture-only',randomUUID(),new Date(Date.now()+60000)]);await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[command,op,'f'.repeat(64),ready2]);
  await jit.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[command,receipts,op,'RECOVER_OWNER',winner.nextGeneration,winner.nextVerifier,next,verifier,lineage,{schema:'staff-alert-v1',event:'RECOVER_OWNER',operationId:op,envelope:{v:1,keyId:'fixture',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}}]);
  expect((await database.pool.query('SELECT held FROM identity.account_security_hold WHERE user_id=$1',[winner.target.userId])).rows[0].held).toBe(true);
  expect((await database.pool.query('SELECT owner_ref FROM identity."user" WHERE user_id=$1',[winner.target.userId])).rows[0].owner_ref).toBe(winner.target.ownerRef);
  expect((await database.pool.query('SELECT owner_ref FROM core.run_ownership_event WHERE run_id=$1 ORDER BY at_seq DESC LIMIT 1',[privateRunId])).rows[0].owner_ref).toBe(winner.target.ownerRef);expect((await database.pool.query('SELECT content_ciphertext FROM core.run WHERE run_id=$1',[privateRunId])).rows[0].content_ciphertext).toEqual(privateEnvelope);expect(createHash('sha256').update(await readFile(privateKeyFile)).digest('hex')).toBe(privateKeyHash);expect(decrypt(privateDek,privateEnvelope,privateAad).toString()).toBe('synthetic-held-private-question');const replacementDek=randomBytes(32);expect(()=>decrypt(replacementDek,privateEnvelope,privateAad)).toThrow();replacementDek.fill(0);privateDek.fill(0);await rm(privateRoot,{recursive:true,force:true});

  await database.pool.query('DELETE FROM identity."user" WHERE user_id=$1',[replacement.userId]);
  const erased=(await database.pool.query('SELECT l.lineage_id,s.user_id,s.state FROM staff.owner_lineage l JOIN staff.subject s USING(staff_id)')).rows[0];expect(erased).toEqual({lineage_id:lineage,user_id:null,state:'ERASED'});
  const final=await ownerCandidate(database.pool),finalOp=randomUUID(),finalCommand=randomUUID(),finalNonce=Buffer.alloc(32,9).toString('base64url');
  await expect(jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[finalCommand,'RECOVER_OWNER',final.userId,winner.nextLineage,null,true,final.credentialIds,finalOp,digest(finalNonce),next,verifier])).rejects.toThrow('STAFF_OWNER_PREDECESSOR_INVALID');
  await jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[finalCommand,'RECOVER_OWNER',final.userId,lineage,null,true,final.credentialIds,finalOp,digest(finalNonce),next,verifier]);
  const finalReceipts=await ownerNativeReceipts(runtime,final,finalCommand,finalNonce),finalReady=randomUUID();await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['f'.repeat(64),finalReady,'fixture-only',randomUUID(),new Date(Date.now()+60000)]);await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[finalCommand,finalOp,'f'.repeat(64),finalReady]);
  await jit.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[finalCommand,finalReceipts,finalOp,'RECOVER_OWNER',next,verifier,randomUUID(),digest('final'),randomUUID(),{schema:'staff-alert-v1',event:'RECOVER_OWNER',operationId:finalOp,envelope:{v:1,keyId:'fixture',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}}]);
  expect((await database.pool.query('SELECT s.user_id FROM staff.owner_designation d JOIN staff.subject s USING(staff_id) WHERE d.active')).rows[0].user_id).toBe(final.userId);
  expect((await database.pool.query('SELECT count(*)::int AS n FROM identity."user" WHERE user_id=$1',[replacement.userId])).rows[0].n).toBe(0);
 });

 it('rechecks legitimate clipped command/receipt expiry after the final blocking COMMIT readiness lock',async()=>{
  const current=(await database.pool.query('SELECT l.lineage_id,s.user_id,g.generation,g.verifier FROM staff.owner_lineage l JOIN staff.subject s USING(staff_id) CROSS JOIN staff.owner_recovery_generation g')).rows[0],target=await ownerCandidate(database.pool),commandId=randomUUID(),operationId=randomUUID(),nonce=Buffer.alloc(32,11).toString('base64url');
  await jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[commandId,'RECOVER_OWNER',target.userId,current.lineage_id,current.user_id,false,target.credentialIds,operationId,digest(nonce),current.generation,current.verifier]);
  const receipts=await ownerNativeReceipts(runtime,target,commandId,nonce),ready=randomUUID();await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['f'.repeat(64),ready,'fixture-only',randomUUID(),new Date(Date.now()+60000)]);await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[commandId,operationId,'f'.repeat(64),ready]);
  const expiry=(await database.pool.query("SELECT clock_timestamp()+interval '1200 milliseconds' AS expiry")).rows[0].expiry;await database.pool.query('UPDATE staff.owner_command SET expires_at=$2 WHERE command_id=$1',[commandId,expiry]);await database.pool.query('UPDATE staff.owner_possession_receipt SET expires_at=$2 WHERE command_id=$1',[commandId,expiry]);
  const committing=await jit.connect(),barrier=await database.pool.connect();
  try{
   await committing.query('BEGIN');await committing.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[commandId,receipts,operationId,'RECOVER_OWNER',current.generation,current.verifier,randomUUID(),digest('late-next'),randomUUID(),{schema:'staff-alert-v1',event:'RECOVER_OWNER',operationId,envelope:{v:1,keyId:'fixture',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}}]);
   await barrier.query('BEGIN');await barrier.query('SELECT 1 FROM staff.independent_alert_readiness WHERE singleton FOR UPDATE');const pid=(await committing.query('SELECT pg_backend_pid() AS pid')).rows[0].pid as number;
   const commit=committing.query('COMMIT'),denial=expect(commit).rejects.toThrow('STAFF_OWNER_COMMIT_EXPIRED');let blocked=false;for(let i=0;i<100;i++){const row=(await database.pool.query('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1',[pid])).rows[0];if(row?.wait_event_type==='Lock'){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}expect(blocked).toBe(true);await new Promise(r=>setTimeout(r,1300));await barrier.query('COMMIT');await denial;
   expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.audit_event WHERE operation_id=$1',[operationId])).rows[0].n).toBe(0);expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_possession_receipt WHERE command_id=$1 AND consumed_at IS NOT NULL',[commandId])).rows[0].n).toBe(0);expect((await database.pool.query('SELECT generation FROM staff.owner_recovery_generation')).rows[0].generation).toBe(current.generation);expect((await database.pool.query('SELECT user_id FROM staff.subject s JOIN staff.owner_designation d USING(staff_id) WHERE d.active')).rows[0].user_id).toBe(current.user_id);
  }finally{await committing.query('ROLLBACK');await barrier.query('ROLLBACK');committing.release();barrier.release();}
 });
 it('orders concurrent recovery after predecessor erasure and cancels the stale live command without consuming generation or receipts',async()=>{
  const current=(await database.pool.query('SELECT l.lineage_id,s.user_id,g.generation,g.verifier FROM staff.owner_lineage l JOIN staff.subject s USING(staff_id) CROSS JOIN staff.owner_recovery_generation g')).rows[0],target=await ownerCandidate(database.pool),commandId=randomUUID(),operationId=randomUUID(),nonce=Buffer.alloc(32,12).toString('base64url');
  await jit.query('SELECT staff.prepare_owner_command_v2($1,$2,$3,$4,$5,$6,$7::text[],$8,$9,$10,$11)',[commandId,'RECOVER_OWNER',target.userId,current.lineage_id,current.user_id,false,target.credentialIds,operationId,digest(nonce),current.generation,current.verifier]);const receipts=await ownerNativeReceipts(runtime,target,commandId,nonce),ready=randomUUID();await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['f'.repeat(64),ready,'fixture-only',randomUUID(),new Date(Date.now()+60000)]);await jit.query('SELECT staff.authorize_owner_alert_operation($1,$2,$3,$4)',[commandId,operationId,'f'.repeat(64),ready]);
  const erasing=await database.pool.connect(),committing=await jit.connect();try{
   await erasing.query('BEGIN');await erasing.query('SELECT identity.lock_security_subjects($1::uuid[])',[[current.user_id]]);const pid=(await committing.query('SELECT pg_backend_pid() AS pid')).rows[0].pid as number;
   const commit=committing.query('SELECT staff.commit_owner_command($1,$2::uuid[],$3,$4,$5,$6,$7,$8,$9,$10::jsonb)',[commandId,receipts,operationId,'RECOVER_OWNER',current.generation,current.verifier,randomUUID(),digest('erasure-next'),randomUUID(),{schema:'staff-alert-v1',event:'RECOVER_OWNER',operationId,envelope:{v:1,keyId:'fixture',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='}}]),refusal=expect(commit).rejects.toThrow('STAFF_OWNER_COMMAND_INVALID');let blocked=false;for(let i=0;i<100;i++){if((await database.pool.query('SELECT wait_event_type FROM pg_stat_activity WHERE pid=$1',[pid])).rows[0]?.wait_event_type==='Lock'){blocked=true;break;}await new Promise(r=>setTimeout(r,10));}expect(blocked).toBe(true);
   await erasing.query('DELETE FROM identity."user" WHERE user_id=$1',[current.user_id]);await erasing.query('COMMIT');await refusal;
   expect((await database.pool.query('SELECT previous_user_id,previous_erased,state FROM staff.owner_command WHERE command_id=$1',[commandId])).rows[0]).toEqual({previous_user_id:null,previous_erased:true,state:'CANCELLED'});expect((await database.pool.query('SELECT generation FROM staff.owner_recovery_generation')).rows[0].generation).toBe(current.generation);expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.owner_possession_receipt WHERE command_id=$1 AND consumed_at IS NOT NULL',[commandId])).rows[0].n).toBe(0);expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.bootstrap_marker')).rows[0].n).toBe(1);expect((await database.pool.query('SELECT l.lineage_id,s.user_id,s.state FROM staff.owner_lineage l JOIN staff.subject s USING(staff_id)')).rows[0]).toEqual({lineage_id:current.lineage_id,user_id:null,state:'ERASED'});
  }finally{await erasing.query('ROLLBACK');erasing.release();committing.release();}
 });
 it('captures exact recovery ACLs, denies raw material/table reads and rechecks already-connected expired JIT readers',async()=>{
  const names=['require_owner_recovery_jit','owner_recovery_commit_guard','owner_command_prepare_commit_guard','prepare_owner_command','install_owner_recovery_generation','owner_command_json','require_owner_predecessor','prepare_owner_command_v2','read_owner_command','read_owner_receipts','read_owner_alert_metadata','authorize_owner_alert_operation','owner_recovery_request','read_committed_owner_operation','commit_owner_command','recheck_owner_commit','erase_subject_mapping'];
  const allowed=['prepare_owner_command','install_owner_recovery_generation','prepare_owner_command_v2','read_owner_command','read_owner_receipts','read_owner_alert_metadata','authorize_owner_alert_operation','read_committed_owner_operation','commit_owner_command'];
  const functions=(await database.pool.query(`SELECT p.oid::regprocedure::text AS signature,p.proname,pg_get_userbyid(p.proowner) AS owner,p.prosecdef,p.proconfig,p.proacl::text AS acl,EXISTS(SELECT 1 FROM aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) a WHERE a.grantee=0 AND a.privilege_type='EXECUTE') AS public,has_function_privilege('debateai_runtime',p.oid,'EXECUTE') AS runtime,has_function_privilege('debateai_staff_recovery',p.oid,'EXECUTE') AS recovery FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='staff' AND p.proname=ANY($1) ORDER BY signature`,[names])).rows;
  expect(functions).toHaveLength(17);for(const f of functions){expect(f.owner).toBe('debateai_staff_security_owner');expect(f.proconfig).toEqual(['search_path=pg_catalog']);expect(f.public).toBe(false);expect(f.runtime).toBe(false);expect(f.recovery).toBe(allowed.includes(f.proname));expect(f.prosecdef).toBe(f.proname!=='owner_recovery_request');}
  for(const pool of [runtime,jit])for(const table of ['owner_lineage','owner_recovery_generation','owner_recovery_operation'])await expect(pool.query('SELECT * FROM staff.'+table)).rejects.toMatchObject({code:'42501'});
  const connected=await jit.connect();try{await database.pool.query("ALTER ROLE debateai_prod_staff_recovery VALID UNTIL '-infinity'");for(const [sql,values] of [['SELECT staff.read_owner_command($1)',[randomUUID()]],['SELECT staff.read_owner_receipts($1,$2::uuid[])',[randomUUID(),[randomUUID(),randomUUID()]]],['SELECT staff.read_owner_alert_metadata($1,$2)',[randomUUID(),randomUUID()]]] as const)await expect(connected.query(sql,[...values])).rejects.toThrow('STAFF_RECOVERY_JIT_REQUIRED');}finally{connected.release();await database.pool.query(`ALTER ROLE debateai_prod_staff_recovery VALID UNTIL '${new Date(Date.now()+240000).toISOString()}'`);}
  const relations=(await database.pool.query(`SELECT c.oid::regclass::text AS relation,pg_get_userbyid(c.relowner) AS owner,c.relacl::text AS acl FROM pg_class c WHERE c.oid IN('staff.owner_lineage'::regclass,'staff.owner_recovery_generation'::regclass,'staff.owner_recovery_operation'::regclass) ORDER BY relation`)).rows;
  const {writeFile}=await import('node:fs/promises');await writeFile('/Users/stefannour/DebateAIRO/docs/operations/admin-implementation-2026-10-02/logs/task6-catalog-acl.json',JSON.stringify({functions,relations},null,2)+'\n');
 });

});

describe('root-private file/SQL interruption protocol with actual native receipts',()=>{
 it('recovers each durable crash window only for the exact operation and refuses completed replay',async()=>{
  const {mkdtemp,realpath,readFile,rm,writeFile}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join,resolve}=await import('node:path');
  const {syntheticOwnerCustody,syntheticAlertFiles}=await import('../support/ownerRecoveryCustody.js');
  const {PosixOwnerRecoveryLock,ownerDigest}=await import('../../apps/runner/src/owner-recovery-custody.js');
  const {createOwnerRecoveryMaterial}=await import('../../apps/runner/src/owner-recovery-material.js');
  const {prepareOwnerCommand,bootstrapOwner,recoverOwner,validateOwnerReceipts}=await import('../../apps/runner/src/owner-command.js');
  const {PostgresOwnerCommandRepository,PostgresStaffIndependentReadinessPublisher}=await import('@debateai/db');
  const {RootStaffAlertConfiguration}=await import('../../apps/api/src/staff/alerts.js');
  const db=await startTestDatabase(),root=await realpath(await mkdtemp(join(tmpdir(),'task6-crash-')));let closed:Pool|undefined,web:Pool|undefined;
  try{
   await migrate(db.pool);await db.pool.query(`ALTER ROLE debateai_prod_staff_recovery PASSWORD 'task6-private-crash-only' VALID UNTIL '${new Date(Date.now()+240000).toISOString()}'`);await db.pool.query(`CREATE ROLE task6_crash_runtime LOGIN PASSWORD 'task6-private-runtime-only' IN ROLE debateai_runtime`);
   const url=new URL(db.connectionString);url.username='debateai_prod_staff_recovery';url.password='task6-private-crash-only';closed=createPool(url.toString());url.username='task6_crash_runtime';url.password='task6-private-runtime-only';web=createPool(url.toString());
   const custody=syntheticOwnerCustody(root),lock=new PosixOwnerRecoveryLock(custody,{pythonPath:'/usr/bin/python3',helperPath:realpathSync(resolve('apps/runner/src/owner-recovery-lock.py'))}),materialFile=join(root,'material'),verifierFile=join(root,'verifier'),lockFile=join(root,'lock');
   const initial=await createOwnerRecoveryMaterial({materialFile,verifierFile,lockFile,custody,lock}),initialBundle=JSON.parse(await readFile(materialFile,'utf8')),base=new PostgresOwnerCommandRepository(closed),publisher=new PostgresStaffIndependentReadinessPublisher(closed);await base.install({generation:initialBundle.generation,verifier:initial.verifier,operationId:initial.receiptId});
   const alertConfigPath=join(root,'alert-config'),configGeneration=randomUUID();await writeFile(alertConfigPath,JSON.stringify({schema:'staff-independent-alert-config-v1',generation:configGeneration,executable:'/usr/bin/true',from:'root@example.invalid',recipient:'independent@example.invalid',ackAdapterId:'synthetic-only'}),{mode:0o600});
   const configHash=ownerDigest(await readFile(alertConfigPath)),configuration=new RootStaffAlertConfiguration({path:alertConfigPath,files:syntheticAlertFiles(root),acknowledgements:new Map([['synthetic-only',{evidence:async()=>({configSha256:configHash,generation:configGeneration,rehearsalId:randomUUID(),expiresAt:new Date(Date.now()+60000)}),acknowledge:async()=> 'ACK' as const}]])});
   let prior:{userId:string;lineageId:string}|undefined;
   const windows=['next-material','next-verifier','journal','sql-before','sql-after','sql-kill','material-published','verifier-published','receipt','nonce-removed'] as const;
   for(const stage of windows){
    const target=await ownerCandidate(db.pool),commandId=randomUUID(),operationId=randomUUID(),purpose=prior===undefined?'BOOTSTRAP' as const:'RECOVER_OWNER' as const;
    const paths={materialFile,verifierFile,lockFile,nonceFile:join(root,stage+'-nonce'),journalFile:join(root,stage+'-journal'),nextMaterialFile:join(root,stage+'-next-material'),nextVerifierFile:join(root,stage+'-next-verifier')},receiptFile=join(root,stage+'-receipt');
    const current=JSON.parse(await readFile(materialFile,'utf8')),proof=Buffer.from(current.proof,'base64url'),privateInput={repository:base,publisher,custody,lock,paths,proof,configuration,keys:{load:async()=>Buffer.alloc(32,17)}};
    const command=prior===undefined?{purpose:'BOOTSTRAP' as const,commandId,operationId,targetUserId:target.userId,credentialIds:target.credentialIds}:{purpose:'RECOVER_OWNER' as const,commandId,operationId,targetUserId:target.userId,credentialIds:target.credentialIds,predecessor:{kind:'LIVE' as const,lineageId:prior.lineageId,userId:prior.userId}};
    await prepareOwnerCommand(command,privateInput);const nonce=JSON.parse(await readFile(paths.nonceFile,'utf8')).nonce as string,receiptIds=await ownerNativeReceipts(web,target,commandId,nonce),selection={commandId,receiptIds,receiptFile},run=purpose==='BOOTSTRAP'?bootstrapOwner:recoverOwner;
    if(stage==='next-material'){
     const storedCommand=(await base.read(commandId))!,storedReceipts=await base.readReceipts(commandId,receiptIds),bound={commandId,receiptIds,operationId,purpose};
     for(const patch of [{receiptId:randomUUID()},{commandId:randomUUID()},{purpose:'RECOVER_OWNER'},{targetUserId:randomUUID()},{ordinarySessionId:randomUUID()},{targetAccountSecurityEpoch:storedCommand.targetAccountSecurityEpoch+1},{credentialId:'unselected-key'},{nonceSha256:digest('forged-nonce')},{verifiedAt:new Date(NaN)},{verifiedAt:new Date(Date.now()+60000)},{expiresAt:new Date(0)},{consumedAt:new Date()}]){
      expect(()=>validateOwnerReceipts(storedCommand,bound,nonce,[{...storedReceipts[0]!,...patch} as typeof storedReceipts[number],storedReceipts[1]!],new Date())).toThrow('OWNER_POSSESSION_RECEIPTS_INVALID');
     }
     await expect(bootstrapOwner({...selection,receipts:storedReceipts} as typeof selection,privateInput)).rejects.toThrow('OWNER_COMMAND_INPUT_INVALID');
     await expect(bootstrapOwner(selection,{...privateInput,proof:Buffer.alloc(32,99)})).rejects.toThrow('OWNER_RECOVERY_PROOF_INVALID');
    }
    let armed=true;const crashCustody=syntheticOwnerCustody(root,(operation,path)=>{
     if(!armed)return;const hit=stage==='next-material'&&operation==='synced'&&path===paths.nextMaterialFile||stage==='next-verifier'&&operation==='synced'&&path===paths.nextVerifierFile||stage==='journal'&&operation==='synced'&&path===paths.journalFile||stage==='material-published'&&operation==='renamed'&&path===materialFile||stage==='verifier-published'&&operation==='renamed'&&path===verifierFile||stage==='receipt'&&operation==='synced'&&path===receiptFile||stage==='nonce-removed'&&operation==='unlinked'&&path===paths.nonceFile;
     if(hit){armed=false;throw new Error('SYNTHETIC_INTERRUPTION');}
    });
    const crashRepo=Object.create(base) as typeof base;crashRepo.commit=async(...args)=>{if(stage==='sql-before'&&armed){armed=false;throw new Error('SYNTHETIC_INTERRUPTION');}const receipt=await base.commit(...args);if(stage==='sql-after'&&armed){armed=false;throw new Error('SYNTHETIC_INTERRUPTION');}return receipt;};
    const crashLock=new PosixOwnerRecoveryLock(crashCustody,{pythonPath:'/usr/bin/python3',helperPath:realpathSync(resolve('apps/runner/src/owner-recovery-lock.py'))});
    if(stage==='sql-kill'){
     const {spawn}=await import('node:child_process'),{openSync,closeSync,constants}=await import('node:fs');
     const privateDescriptor=join(root,'kill-private-input');const connection=new URL(db.connectionString);connection.username='debateai_prod_staff_recovery';connection.password='task6-private-crash-only';
     await writeFile(privateDescriptor,JSON.stringify({databaseUrl:connection.toString(),root,paths,selection,proof:current.proof,configHash,configGeneration,alertConfigPath,purpose}),{mode:0o600});const fd=openSync(privateDescriptor,constants.O_RDONLY|constants.O_NOFOLLOW);
     const code=`import fs,{realpathSync} from 'node:fs';import {createPool,PostgresOwnerCommandRepository,PostgresStaffIndependentReadinessPublisher} from '@debateai/db';import {syntheticOwnerCustody,syntheticAlertFiles} from './tests/support/ownerRecoveryCustody.ts';import {PosixOwnerRecoveryLock} from './apps/runner/src/owner-recovery-custody.ts';import {RootStaffAlertConfiguration} from './apps/api/src/staff/alerts.ts';import {bootstrapOwner,recoverOwner} from './apps/runner/src/owner-command.ts';import {resolve} from 'node:path';import {randomUUID} from 'node:crypto';const x=JSON.parse(fs.readFileSync(3,'utf8')),pool=createPool(x.databaseUrl),repository=new PostgresOwnerCommandRepository(pool),custody=syntheticOwnerCustody(x.root),lock=new PosixOwnerRecoveryLock(custody,{pythonPath:'/usr/bin/python3',helperPath:realpathSync(resolve('apps/runner/src/owner-recovery-lock.py'))}),original=repository.commit.bind(repository);repository.commit=async(...args)=>{await original(...args);process.stdout.write('COMMITTED\\n');await new Promise(()=>{setInterval(()=>{},1000);});throw Error('UNREACHABLE');};const configuration=new RootStaffAlertConfiguration({path:x.alertConfigPath,files:syntheticAlertFiles(x.root),acknowledgements:new Map([['synthetic-only',{evidence:async()=>({configSha256:x.configHash,generation:x.configGeneration,rehearsalId:randomUUID(),expiresAt:new Date(Date.now()+60000)}),acknowledge:async()=> 'ACK'}]])});await (x.purpose==='BOOTSTRAP'?bootstrapOwner:recoverOwner)(x.selection,{repository,publisher:new PostgresStaffIndependentReadinessPublisher(pool),custody,lock,paths:x.paths,proof:Buffer.from(x.proof,'base64url'),configuration,keys:{load:async()=>Buffer.alloc(32,17)}});`;
     const child=spawn(process.execPath,['--import','tsx','--input-type=module','-e',code],{cwd:process.cwd(),stdio:['ignore','pipe','ignore',fd],env:{PATH:process.env.PATH!,HOME:process.env.HOME!,TMPDIR:process.env.TMPDIR!}});closeSync(fd);
     try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{child.kill('SIGKILL');reject(new Error('KILL_CEREMONY_NOT_COMMITTED'));},5000);child.stdout!.once('data',bytes=>{clearTimeout(timer);if(String(bytes).trim()==='COMMITTED')resolve();else reject(new Error('KILL_CEREMONY_OUTPUT_INVALID'));});child.once('exit',()=>{clearTimeout(timer);reject(new Error('KILL_CEREMONY_EARLY_EXIT'));});});const stopped=new Promise<void>(resolve=>child.once('close',()=>resolve()));child.kill('SIGKILL');await stopped;
      expect((await db.pool.query('SELECT count(*)::int AS n FROM staff.owner_recovery_operation WHERE operation_id=$1',[operationId])).rows[0].n).toBe(1);expect(JSON.parse(await readFile(materialFile,'utf8')).generation).toBe(current.generation);
     }finally{child.kill('SIGKILL');await rm(privateDescriptor,{force:true});}
    }else await expect(run(selection,{...privateInput,repository:crashRepo,custody:crashCustody,lock:crashLock})).rejects.toThrow('SYNTHETIC_INTERRUPTION');
    if(await custody.exists(paths.journalFile))await expect(run({...selection,receiptIds:[receiptIds[1],receiptIds[0]]},privateInput)).rejects.toThrow('OWNER_JOURNAL_MISMATCH');
    const receipt=await run(selection,privateInput);expect(receipt.operationId).toBe(operationId);expect(JSON.parse(await readFile(receiptFile,'utf8'))).toEqual({operationId,outcome:'COMPLETED',recordedAt:receipt.recordedAt.toISOString()});expect((await db.pool.query('SELECT count(*)::int AS n FROM staff.audit_event WHERE operation_id=$1',[operationId])).rows[0].n).toBe(1);
    await expect(run(selection,privateInput)).rejects.toThrow('OWNER_RECEIPT_OUTPUT_CONFLICT');expect(await custody.exists(paths.nonceFile)).toBe(false);expect(await custody.exists(paths.journalFile)).toBe(false);
    const next=JSON.parse(await readFile(materialFile,'utf8'));expect(next.generation).not.toBe(current.generation);expect(next.proof).not.toBe(current.proof);expect((await db.pool.query('SELECT generation FROM staff.owner_recovery_generation')).rows[0].generation).toBe(next.generation);
    const currentOwner=(await db.pool.query('SELECT l.lineage_id,s.user_id FROM staff.owner_lineage l JOIN staff.subject s USING(staff_id)')).rows[0];prior={userId:currentOwner.user_id,lineageId:currentOwner.lineage_id};proof.fill(0);
   }
  }finally{await closed?.end();await web?.end();await db.stop();await rm(root,{recursive:true,force:true});}
 });
});
