import { createHash, randomUUID } from 'node:crypto';
import { mkdtemp, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { FileUserDekStore, generateDek, loadKek, destroyKek } from '@debateai/crypto';
import { createPool, migrate, type Pool, PostgresStaffRepository } from '@debateai/db';
import { afterAll, beforeAll, expect, it } from 'vitest';
import type { StaffTargetInvitationMessage } from '../../apps/api/src/staff/alerts.js';
import { startTestDatabase, type TestDatabase } from '../support/testDatabase.js';
let alerts:typeof import('../../apps/api/src/staff/alerts.js');let database:TestDatabase,runtime:Pool,jit:Pool;
const hash=(s:string)=>'sha256:'+createHash('sha256').update(s).digest('hex');
const envelope={v:1,keyId:'fixture-key',nonce:'AAAAAAAAAAAAAAAA',tag:'AAAAAAAAAAAAAAAAAAAAAA==',ct:'YQ=='};
const intent=(operationId:string,event:string)=>({schema:'staff-alert-v1',operationId,event,envelope});
beforeAll(async()=>{alerts=await import('../../apps/api/src/staff/alerts.js').catch(()=>({})) as typeof alerts;database=await startTestDatabase();await migrate(database.pool);await database.pool.query("CREATE ROLE task5_runtime LOGIN PASSWORD 'private-task5-fixture' IN ROLE debateai_runtime");const u=new URL(database.connectionString);u.username='task5_runtime';u.password='private-task5-fixture';runtime=createPool(u.toString());await database.pool.query("ALTER ROLE debateai_prod_staff_recovery LOGIN PASSWORD 'task5-jit-private' VALID UNTIL '"+new Date(Date.now()+240000).toISOString()+"'");const j=new URL(database.connectionString);j.username='debateai_prod_staff_recovery';j.password='task5-jit-private';jit=createPool(j.toString());});
afterAll(async()=>{await runtime?.end();await jit?.end();await database?.stop();});
const generation=randomUUID();async function ready(){await jit.query("SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)",['a'.repeat(64),generation,'capture-v1',randomUUID(),new Date(Date.now()+60000)]);}
async function authorize(operationId:string){return runtime.query('SELECT staff.authorize_alert_operation($1,$2,$3)',[operationId,'a'.repeat(64),generation]);}
async function account(){const userId=randomUUID(),sessionId=randomUUID(),factorId=randomUUID();await database.pool.query(`INSERT INTO identity."user"(user_id,email_blind_index,email_ciphertext,recovery_email_ciphertext,password_hash,pseudonym,state,adult_affirmed_at) VALUES($1,$2,'{}','{}','fixture-password',$3,'active',now());`,[userId,createHash('sha256').update(userId).digest(),userId]);await database.pool.query("INSERT INTO identity.session(session_id,user_id,token_hash,csrf_token_hash,binding_context,idle_expires_at,absolute_expires_at,last_mfa_at) VALUES($1,$2,$3,$4,'{}',now()+interval '1 hour',now()+interval '2 hours',now())",[sessionId,userId,hash(sessionId),hash('csrf'+sessionId)]);await database.pool.query("INSERT INTO identity.channel_binding(user_id,channel_type,address_ciphertext,state,created_at,verified_at) VALUES($1,'email','{}','verified',now(),now())",[userId]);await database.pool.query("INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,secret_ciphertext,state,created_at,verified_at,last_accepted_step) VALUES($1,$2,'totp','{}','active',now(),now(),1)",[factorId,userId]);return {userId,sessionId};}
async function subject(owner=false){const a=await account(),staffId=randomUUID(),privilegeSessionId=randomUUID();const capabilities=owner?['TEAM_READ','TEAM_INVITE','TEAM_GRANT','TEAM_DISABLE','AUDIT_READ','EMERGENCY_DISABLE']:['TEAM_READ'];await database.pool.query("INSERT INTO staff.subject(staff_id,user_id,capabilities) VALUES($1,$2,$3)",[staffId,a.userId,capabilities]);if(owner){await database.pool.query('UPDATE staff.owner_designation SET active=false WHERE active');await database.pool.query('INSERT INTO staff.owner_designation(staff_id) VALUES($1)',[staffId]);}await database.pool.query("INSERT INTO staff.privilege_session(privilege_session_id,staff_id,user_id,ordinary_session_id,token_hash,security_epoch,account_security_epoch,grant_revision,idle_expires_at,absolute_expires_at) VALUES($1,$2,$3,$4,$5,0,0,0,now()+interval '15 minutes',now()+interval '8 hours')",[privilegeSessionId,staffId,a.userId,a.sessionId,hash(privilegeSessionId)]);return {...a,staffId,context:{staffId,userId:a.userId,ordinarySessionId:a.sessionId,privilegeSessionId,designation:owner?'OWNER':'DELEGATED',securityEpoch:0,accountSecurityEpoch:0,grantRevision:0,capabilities}};}
async function proof(actor:Awaited<ReturnType<typeof subject>>,target:Readonly<{staffId:string}>,action='TEAM_GRANT'){const operationId=randomUUID(),proofId=randomUUID(),binding={action,targetId:target.staffId,operationId,expectedRevision:0,bodySha256:'b'.repeat(64)};await database.pool.query("INSERT INTO staff.action_proof(proof_id,staff_id,user_id,ordinary_session_id,privilege_session_id,security_epoch,account_security_epoch,grant_revision,binding,credential_id,expires_at) VALUES($1,$2,$3,$4,$5,0,0,0,$6,'verified-fixture-key',now()+interval '5 minutes')",[proofId,actor.staffId,actor.userId,actor.sessionId,actor.context.privilegeSessionId,binding]);return {operationId,proofId,binding};}
async function grant(actor:Awaited<ReturnType<typeof subject>>,target:Awaited<ReturnType<typeof subject>>,p:Awaited<ReturnType<typeof proof>>,alert=intent(p.operationId,'GRANT')){await authorize(p.operationId);return runtime.query('SELECT staff.grant($1::jsonb,$2,$3::jsonb,$4,$5::text[],$6,$7::jsonb,$8::jsonb) AS value',[actor.context,p.proofId,p.binding,target.staffId,['AUDIT_READ'],p.operationId,{code:'GRANT_CHANGE'},alert]);}
it('denies absent readiness, gates enabling atomically, allows COMPROMISE during outage and never succeeds on audit failure',async()=>{
 const owner=await subject(true),target=await subject(),p=await proof(owner,target);
 await expect(runtime.query('SELECT staff.read_independent_alert_readiness() AS value')).resolves.toMatchObject({rows:[{value:'UNAVAILABLE'}]});
 await expect(grant(owner,target,p)).rejects.toThrow('STAFF_ALERT_UNAVAILABLE');
 expect((await database.pool.query('SELECT grant_revision FROM staff.subject WHERE staff_id=$1',[target.staffId])).rows[0].grant_revision).toBe('0');
 const emergency=await proof(owner,target,'EMERGENCY_DISABLE');
 await database.pool.query(`CREATE FUNCTION public.task5_fail_audit() RETURNS trigger LANGUAGE plpgsql AS $$BEGIN RAISE EXCEPTION 'TASK5_AUDIT_FAILURE';END$$;CREATE TRIGGER task5_fail_audit BEFORE INSERT ON staff.audit_event FOR EACH ROW EXECUTE FUNCTION public.task5_fail_audit()`);
 const disable=()=>runtime.query('SELECT staff.disable($1::jsonb,$2,$3::jsonb,$4,$5,$6,$7::jsonb,$8::jsonb) AS value',[owner.context,emergency.proofId,emergency.binding,target.staffId,'COMPROMISE',emergency.operationId,{code:'SECURITY_RESPONSE'},intent(emergency.operationId,'DISABLE')]);
 try{await expect(disable()).rejects.toThrow('TASK5_AUDIT_FAILURE');expect((await database.pool.query('SELECT state FROM staff.subject WHERE staff_id=$1',[target.staffId])).rows[0].state).toBe('ACTIVE');}finally{await database.pool.query('DROP TRIGGER task5_fail_audit ON staff.audit_event;DROP FUNCTION public.task5_fail_audit()');}
 expect((await disable()).rows[0].value.outcome).toBe('COMPLETED');expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.alert_outbox o JOIN staff.audit_event a USING(event_id) WHERE operation_id=$1',[emergency.operationId])).rows[0].n).toBe(1);
});
it('keeps audit/outbox/receipt immutable and runtime readiness/mapping/dispatch strictly enumerated',async()=>{
 await ready();const owner=await subject(true),target=await subject(),p=await proof(owner,target);await grant(owner,target,p);await grant(owner,target,p);
 expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.audit_event WHERE operation_id=$1',[p.operationId])).rows[0].n).toBe(1);
 for(const table of ['audit_event','alert_outbox','alert_delivery_receipt','alert_dispatch_state','independent_alert_readiness'])for(const sql of [`SELECT * FROM staff.${table}`,`UPDATE staff.${table} SET ${table==='audit_event'?'ticket_ref=NULL':table==='alert_outbox'?'key_ref=gen_random_uuid()':table==='alert_delivery_receipt'?"outcome='FAILED'":table==='alert_dispatch_state'?'attempts=0':'config_sha256=NULL'}`,`DELETE FROM staff.${table}`,`TRUNCATE staff.${table} CASCADE`])await expect(runtime.query(sql)).rejects.toMatchObject({code:'42501'});
 for(const table of ['audit_event','alert_outbox','alert_delivery_receipt'])for(const sql of [`DELETE FROM staff.${table}`,`TRUNCATE staff.${table} CASCADE`])await expect(database.pool.query(sql)).rejects.toMatchObject({code:'55000'});
 await expect(runtime.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['a'.repeat(64),generation,'capture-v1',randomUUID(),new Date(Date.now()+60000)])).rejects.toMatchObject({code:'42501'});
 const acl=(await database.pool.query(`SELECT p.oid::regprocedure::text AS signature,pg_get_userbyid(p.proowner) AS owner,p.proacl::text AS acl,p.proconfig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='staff' AND p.proname IN ('claim_alert_delivery','settle_alert_delivery','read_alert_delivery_status','read_alert_key_mapping','read_alert_user_mapping','publish_independent_alert_readiness','read_independent_alert_readiness') ORDER BY signature`)).rows;
 expect(acl).toHaveLength(7);for(const row of acl){expect(row.owner).toBe('debateai_staff_security_owner');expect(row.proconfig,row.signature).toEqual(['claim_alert_delivery(','publish_independent_alert_readiness('].some(n=>row.signature.startsWith('staff.'+n))?['search_path=pg_catalog, pg_temp']:['search_path=pg_catalog']);expect(row.acl).not.toMatch(/[,{]=X/);}console.info('[TASK5_EXACT_FUNCTION_ACL]',JSON.stringify(acl));
});
it('claims concurrently without collapse of event purposes and rejects fabricated/stale acknowledgement',async()=>{
 await ready();await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,terminal) SELECT outbox_id,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');const target=await account(),keyRef=(await database.pool.query('SELECT audit_token FROM identity."user" WHERE user_id=$1',[target.userId])).rows[0].audit_token;const eventId=randomUUID(),operationId=randomUUID();await authorize(operationId);await database.pool.query("INSERT INTO staff.audit_event(event_id,operation_id,request_sha256,event_type,reason_code) VALUES($1,$2,$3,'INVITE','TEAM_ONBOARDING')",[eventId,operationId,'c'.repeat(64)]);await database.pool.query("INSERT INTO staff.alert_outbox(event_id,purpose,key_ref,encrypted_payload) SELECT $1,p,$2,$3 FROM unnest(ARRAY['INDEPENDENT_METADATA_ALERT','TARGET_INVITATION']) p",[eventId,keyRef,envelope]);
 const [a,b]=await Promise.all([runtime.query('SELECT staff.claim_alert_delivery(1) AS value'),runtime.query('SELECT staff.claim_alert_delivery(1) AS value')]);const claims=[...a.rows[0].value,...b.rows[0].value];expect(claims).toHaveLength(2);expect(claims.map((c:{purpose:string})=>c.purpose).sort()).toEqual(['INDEPENDENT_METADATA_ALERT','TARGET_INVITATION']);expect(new Set(claims.map((c:{outboxId:string})=>c.outboxId)).size).toBe(2);
 const c=claims.find((c:{eventId:string})=>c.eventId===eventId);expect(c).toBeDefined();if(c){expect(await runtime.query("SELECT staff.settle_alert_delivery($1,$2,'DELIVERED',NULL) AS value",[c.outboxId,randomUUID()])).toMatchObject({rows:[{value:false}]});expect(await runtime.query("SELECT staff.settle_alert_delivery($1,$2,'DELIVERED',NULL) AS value",[c.outboxId,c.claimToken])).toMatchObject({rows:[{value:true}]});expect(await runtime.query("SELECT staff.settle_alert_delivery($1,$2,'DELIVERED',NULL) AS value",[c.outboxId,c.claimToken])).toMatchObject({rows:[{value:false}]});}
 await expect(runtime.query('SELECT staff.claim_alert_delivery(101)')).rejects.toThrow('STAFF_ALERT_LIMIT_INVALID');
});
it('dispatches only stored bounded encrypted events, persists retries, severs erased key mappings and guards overlap/crash ambiguity',async()=>{
 expect(alerts.StaffAlertDispatcher).toBeTypeOf('function');await ready();
 // Do not let earlier deliberately invalid fixture envelopes enter this behavior test.
 await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,attempts,terminal) SELECT outbox_id,0,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');
 const owner=await subject(true),target=await subject(),p=await proof(owner,target),root=await mkdtemp(join(tmpdir(),'task5-key-')),kek=loadKek(generateDek()),users=new FileUserDekStore(root,kek);const key=generateDek();await users.store(target.userId,key);key.fill(0);
 try {
  const repository=new alerts.PostgresStaffAlertRepository(runtime),producer=new alerts.StaffAlertIntentProducer({keys:users,mappings:repository,readiness:{require:async(operationId:string)=>{expect((await authorize(operationId)).rows[0].authorize_alert_operation).toBe(true);}}});const encrypted=await producer.mutation({event:'GRANT',operationId:p.operationId,keyUserId:target.userId,actorStaffId:owner.staffId,subjectStaffId:target.staffId,reason:{code:'GRANT_CHANGE'}});await grant(owner,target,p,encrypted);
  const delivered:string[]=[];let failures=1;const log:string[]=[];
  const dispatcher=new alerts.StaffAlertDispatcher({repository,keys:users,independentTransport:{send:async(id:string,message:unknown)=>{expect(message).toEqual({schema:'staff-security-metadata-v1',event:'GRANT',operationId:p.operationId,actorStaffId:owner.staffId,subjectStaffId:target.staffId,reason:{code:'GRANT_CHANGE'}});expect(JSON.stringify(message)).not.toContain(target.userId);expect(JSON.stringify(message)).not.toContain(encrypted.envelope.keyId);if(failures-->0)throw new Error('secret@example.invalid private-sentinel');delivered.push(id);return 'ACK' as const;}},readiness:async()=> 'READY' as const,log:(code:string)=>log.push(code)});
  expect(await dispatcher.drain({limit:10})).toEqual({acked:0,pending:1});expect(log).toEqual(['TRANSPORT_UNAVAILABLE']);
  await database.pool.query("UPDATE staff.alert_dispatch_state SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE NOT terminal");expect(await dispatcher.drain({limit:10})).toEqual({acked:1,pending:0});expect(delivered).toHaveLength(1);expect(await dispatcher.drain({limit:10})).toEqual({acked:0,pending:0});
  const other=await subject(),q=await proof(owner,other),otherKey=generateDek();await users.store(other.userId,otherKey);otherKey.fill(0);await grant(owner,other,q,await producer.mutation({event:'GRANT',operationId:q.operationId,keyUserId:other.userId,actorStaffId:owner.staffId,subjectStaffId:other.staffId,reason:{code:'GRANT_CHANGE'}}));await users.destroy(other.userId);await database.pool.query('DELETE FROM identity."user" WHERE user_id=$1',[other.userId]);expect(await dispatcher.drain({limit:10})).toEqual({acked:0,pending:0});expect((await database.pool.query("SELECT r.outcome FROM staff.alert_delivery_receipt r JOIN staff.alert_outbox o USING(outbox_id) JOIN staff.audit_event a USING(event_id) WHERE a.operation_id=$1",[q.operationId])).rows[0].outcome).toBe('SEVERED');
  const blocked={...dispatcher};await expect(dispatcher.drain({limit:0})).rejects.toThrow('STAFF_ALERT_LIMIT_INVALID');void blocked;
 } finally {destroyKek(kek);await rm(root,{recursive:true,force:true});}
});
it('rechecks the readiness operation lease at delayed COMMIT and rolls all mutation state back',async()=>{
 await ready();const owner=await subject(true),target=await subject(),p=await proof(owner,target);await authorize(p.operationId);const client=await runtime.connect();
 try {
  await client.query('BEGIN');await client.query('SELECT staff.grant($1::jsonb,$2,$3::jsonb,$4,$5::text[],$6,$7::jsonb,$8::jsonb)',[owner.context,p.proofId,p.binding,target.staffId,['AUDIT_READ'],p.operationId,{code:'GRANT_CHANGE'},intent(p.operationId,'GRANT')]);
  await database.pool.query("UPDATE staff.alert_operation_readiness SET expires_at=clock_timestamp()+interval '100 milliseconds' WHERE operation_id=$1",[p.operationId]);await new Promise(r=>setTimeout(r,150));
  await expect(client.query('COMMIT')).rejects.toThrow('STAFF_ALERT_UNAVAILABLE');
  expect((await database.pool.query('SELECT grant_revision FROM staff.subject WHERE staff_id=$1',[target.staffId])).rows[0].grant_revision).toBe('0');expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.audit_event WHERE operation_id=$1',[p.operationId])).rows[0].n).toBe(0);
 }finally{await client.query('ROLLBACK');client.release();}
});
it('serializes final enabling commit against root revocation and rejects mismatched/stale generations',async()=>{
 await ready();expect((await runtime.query('SELECT staff.authorize_alert_operation($1,$2,$3) AS value',[randomUUID(),'a'.repeat(64),randomUUID()])).rows[0].value).toBe(false);
 const owner=await subject(true),target=await subject(),p=await proof(owner,target);await authorize(p.operationId);const client=await runtime.connect();
 try{await client.query('BEGIN');await client.query('SELECT staff.grant($1::jsonb,$2,$3::jsonb,$4,$5::text[],$6,$7::jsonb,$8::jsonb)',[owner.context,p.proofId,p.binding,target.staffId,['AUDIT_READ'],p.operationId,{code:'GRANT_CHANGE'},intent(p.operationId,'GRANT')]);await client.query('SET CONSTRAINTS ALL IMMEDIATE');let revoked=false;const revoke=jit.query('SELECT staff.revoke_independent_alert_readiness($1)',[generation]).then(result=>{revoked=true;return result;});await new Promise(r=>setTimeout(r,30));expect(revoked).toBe(false);await client.query('COMMIT');await revoke;expect((await runtime.query('SELECT staff.read_independent_alert_readiness($1,$2) AS value',['a'.repeat(64),generation])).rows[0].value).toBe('UNAVAILABLE');}finally{await client.query('ROLLBACK');client.release();}
 await ready();const second=await subject(),q=await proof(owner,second);await authorize(q.operationId);await jit.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['d'.repeat(64),randomUUID(),'capture-v1',randomUUID(),new Date(Date.now()+60000)]);await expect(runtime.query('SELECT staff.grant($1::jsonb,$2,$3::jsonb,$4,$5::text[],$6,$7::jsonb,$8::jsonb)',[owner.context,q.proofId,q.binding,second.staffId,['AUDIT_READ'],q.operationId,{code:'GRANT_CHANGE'},intent(q.operationId,'GRANT')])).rejects.toThrow('STAFF_ALERT_UNAVAILABLE');
});
it('uses finite persisted retries, timeout/overlap guards and truthful delivery-before-receipt recovery identity',async()=>{
 await ready();await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,terminal) SELECT outbox_id,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');
 const owner=await subject(true),target=await subject(),p=await proof(owner,target),root=await mkdtemp(join(tmpdir(),'task5-retry-')),kek=loadKek(generateDek()),users=new FileUserDekStore(root,kek),key=generateDek();await users.store(target.userId,key);key.fill(0);
 const repository=new alerts.PostgresStaffAlertRepository(runtime),producer=new alerts.StaffAlertIntentProducer({keys:users,mappings:repository,readiness:{require:async(operationId:string)=>{await authorize(operationId);}}});
 try{
  await grant(owner,target,p,await producer.mutation({event:'GRANT',operationId:p.operationId,keyUserId:target.userId,actorStaffId:owner.staffId,subjectStaffId:target.staffId,reason:{code:'GRANT_CHANGE'}}));
  const logs:string[]=[],timeout=new alerts.StaffAlertDispatcher({repository,keys:users,independentTransport:{send:async()=>new Promise<'ACK'>(()=>{})},readiness:async()=> 'READY',timeoutMs:10,log:c=>logs.push(c)});
  for(let attempt=0;attempt<3;attempt++){expect(await timeout.drain({limit:1})).toEqual({acked:0,pending:attempt<2?1:0});await database.pool.query("UPDATE staff.alert_dispatch_state SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE NOT terminal");}expect(logs).toEqual(['TIMEOUT','TIMEOUT','TIMEOUT']);expect((await repository.status()).exhausted).toBeGreaterThan(0);
  const other=await subject(),q=await proof(owner,other),key2=generateDek();await users.store(other.userId,key2);key2.fill(0);await grant(owner,other,q,await producer.mutation({event:'GRANT',operationId:q.operationId,keyUserId:other.userId,actorStaffId:owner.staffId,subjectStaffId:other.staffId,reason:{code:'GRANT_CHANGE'}}));
  const sent:string[]=[];let failReceipt=true;const crashRepo=Object.create(repository) as typeof repository;crashRepo.settle=async(claim,outcome,code)=>{if(outcome==='DELIVERED'&&failReceipt){failReceipt=false;throw new Error('FIXTURE_RECEIPT_CRASH');}return repository.settle(claim,outcome,code);};
  const crash=new alerts.StaffAlertDispatcher({repository:crashRepo,keys:users,independentTransport:{send:async(id)=>{sent.push(id);return 'ACK';}},readiness:async()=> 'READY'});
  await expect(crash.drain({limit:1})).rejects.toThrow('FIXTURE_RECEIPT_CRASH');expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.alert_delivery_receipt r JOIN staff.alert_outbox o USING(outbox_id) JOIN staff.audit_event a USING(event_id) WHERE operation_id=$1',[q.operationId])).rows[0].n).toBe(0);
  await database.pool.query("UPDATE staff.alert_dispatch_state SET claimed_until=clock_timestamp()-interval '1 second' WHERE NOT terminal");expect(await crash.drain({limit:1})).toEqual({acked:1,pending:0});expect(sent).toHaveLength(2);expect(sent[0]).toBe(sent[1]);expect((await database.pool.query("SELECT r.failure_code FROM staff.alert_delivery_receipt r JOIN staff.alert_outbox o USING(outbox_id) JOIN staff.audit_event a USING(event_id) WHERE operation_id=$1 ORDER BY r.recorded_at",[q.operationId])).rows.map(r=>r.failure_code)).toEqual(['ACK_UNCERTAIN',null]);
  const third=await subject(),t=await proof(owner,third),key3=generateDek();await users.store(third.userId,key3);key3.fill(0);await grant(owner,third,t,await producer.mutation({event:'GRANT',operationId:t.operationId,keyUserId:third.userId,actorStaffId:owner.staffId,subjectStaffId:third.staffId,reason:{code:'GRANT_CHANGE'}}));let release:()=>void=()=>{},entered:()=>void=()=>{};const started=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);const overlapping=new alerts.StaffAlertDispatcher({repository,keys:users,independentTransport:{send:async()=>{entered();await wait;return 'ACK';}},readiness:async()=> 'READY'});const draining=overlapping.drain({limit:1});await started;await expect(overlapping.drain({limit:1})).rejects.toThrow('STAFF_ALERT_DRAIN_IN_PROGRESS');release();expect(await draining).toEqual({acked:1,pending:0});
 }finally{destroyKek(kek);await rm(root,{recursive:true,force:true});}
});
it('retries a transient key failure and never sends after the whole claim pipeline times out',async()=>{
 await ready();await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,terminal) SELECT outbox_id,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');
 const owner=await subject(true),target=await subject(),p=await proof(owner,target),root=await mkdtemp(join(tmpdir(),'task5-stall-')),kek=loadKek(generateDek()),users=new FileUserDekStore(root,kek),key=generateDek();await users.store(target.userId,key);key.fill(0);const repository=new alerts.PostgresStaffAlertRepository(runtime),producer=new alerts.StaffAlertIntentProducer({keys:users,mappings:repository,readiness:{require:async(operationId:string)=>{await authorize(operationId);}}});
 try{
  await grant(owner,target,p,await producer.mutation({event:'GRANT',operationId:p.operationId,keyUserId:target.userId,actorStaffId:owner.staffId,subjectStaffId:target.staffId,reason:{code:'GRANT_CHANGE'}}));
  const transient=new alerts.StaffAlertDispatcher({repository,keys:{load:async()=>{throw new Error('FIXTURE_TRANSIENT_KEY_CUSTODY');}},independentTransport:{send:async()=> 'ACK'},readiness:async()=> 'READY'});expect(await transient.drain({limit:1})).toEqual({acked:0,pending:1});
  expect((await database.pool.query('SELECT r.outcome,r.failure_code FROM staff.alert_delivery_receipt r JOIN staff.alert_outbox o USING(outbox_id) JOIN staff.audit_event a USING(event_id) WHERE operation_id=$1',[p.operationId])).rows).toEqual([{outcome:'FAILED',failure_code:'KEY_UNAVAILABLE'}]);
  await database.pool.query("UPDATE staff.alert_dispatch_state SET next_attempt_at=clock_timestamp()-interval '1 second' WHERE NOT terminal");let release:()=>void=()=>{},entered:()=>void=()=>{};const started=new Promise<void>(r=>entered=r),wait=new Promise<void>(r=>release=r);let sent=0;
  const stalled=new alerts.StaffAlertDispatcher({repository,keys:users,independentTransport:{send:async()=>{sent++;return 'ACK';}},readiness:async()=>{entered();await wait;return 'READY';},timeoutMs:25});const draining=stalled.drain({limit:1});await started;
  const result=await Promise.race([draining,new Promise(r=>setTimeout(()=>r('STALLED'),100))]);release();expect(result).toEqual({acked:0,pending:1});await new Promise(r=>setTimeout(r,30));expect(sent).toBe(0);
 }finally{destroyKek(kek);await rm(root,{recursive:true,force:true});}
});

it('requires the actual closed JIT identity and rechecks an expired connected publisher',async()=>{
 const connected=await jit.connect();try{await database.pool.query("ALTER ROLE debateai_prod_staff_recovery VALID UNTIL '-infinity'");await expect(connected.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['a'.repeat(64),generation,'capture-v1',randomUUID(),new Date(Date.now()+60000)])).rejects.toThrow('STAFF_RECOVERY_JIT_REQUIRED');}finally{connected.release();await database.pool.query("ALTER ROLE debateai_prod_staff_recovery VALID UNTIL '"+new Date(Date.now()+240000).toISOString()+"'");}
});
it('keeps target invitation handle/recipient scope separate and refuses ciphertext purpose substitution',async()=>{
 await ready();await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,terminal) SELECT outbox_id,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');
 const owner=await subject(true),root=await mkdtemp(join(tmpdir(),'task5-purpose-')),kek=loadKek(generateDek()),users=new FileUserDekStore(root,kek),repository=new alerts.PostgresStaffAlertRepository(runtime),producer=new alerts.StaffAlertIntentProducer({keys:users,mappings:repository,readiness:{require:async(operationId:string)=>{await authorize(operationId);}}});
 const handles:string[]=[],independent:string[]=[],targets:StaffTargetInvitationMessage[]=[];
 try{
  const dispatcher=new alerts.StaffAlertDispatcher({repository,keys:users,independentTransport:{send:async(id,message)=>{independent.push(JSON.stringify({id,message}));return 'ACK';}},targetInvitationTransport:{send:async(_id,message)=>{targets.push(message);return 'ACK';}},readiness:async()=> 'READY'});
  for(const substitute of [false,true]){
   const target=await account(),key=generateDek();await users.store(target.userId,key);key.fill(0);const p=await proof(owner,{staffId:target.userId},'TEAM_INVITE'),handle=(substitute?'p':'q').repeat(43);handles.push(handle);
   const alert=await producer.mutation({event:'INVITE',operationId:p.operationId,keyUserId:target.userId,actorStaffId:owner.staffId,subjectStaffId:null,reason:{code:'TEAM_ONBOARDING'}}),delivery=await producer.invitation({operationId:p.operationId,targetUserId:target.userId,invitationHandle:handle});
   await runtime.query('SELECT staff.invite($1::jsonb,$2,$3::jsonb,$4,$5::text[],$6,$7::jsonb,$8,$9::jsonb,$10::jsonb)',[owner.context,p.proofId,p.binding,target.userId,['TEAM_READ'],p.operationId,{code:'TEAM_ONBOARDING'},hash(handle),alert,substitute?{...delivery,envelope:alert.envelope}:delivery]);
   expect(await dispatcher.drain({limit:2})).toEqual({acked:substitute?1:2,pending:substitute?1:0});
   if(!substitute){expect(targets).toEqual([{targetUserId:target.userId,operationId:p.operationId,invitationHandle:handle}]);}
   else{expect(targets).toHaveLength(1);expect((await database.pool.query("SELECT r.failure_code FROM staff.alert_delivery_receipt r JOIN staff.alert_outbox o USING(outbox_id) JOIN staff.audit_event a USING(event_id) WHERE operation_id=$1 AND purpose='TARGET_INVITATION'",[p.operationId])).rows).toEqual([{failure_code:'PAYLOAD_INVALID'}]);}
  }
  for(const handle of handles)expect(independent.join('')).not.toContain(handle);expect(independent.join('')).not.toContain('example.invalid');expect(independent.join('')).toContain('TEAM_ONBOARDING');expect(independent.join('')).toContain('staff-security-metadata-v1');expect(independent.join('')).not.toContain('keyId');
 }finally{destroyKek(kek);await rm(root,{recursive:true,force:true});}
});
it('captures exact new function/table/column/role ACLs and denies every non-enumerated seam',async()=>{
 const names=['require_alert_readiness_jit','publish_independent_alert_readiness','revoke_independent_alert_readiness','read_independent_alert_readiness','authorize_alert_operation','require_alert_operation','guard_alert_audit_insert','guard_alert_outbox_insert','guard_alert_commit','read_alert_user_mapping','read_alert_key_mapping','claim_alert_delivery','settle_alert_delivery','read_alert_delivery_status','release_alert_delivery'];
 const functions=(await database.pool.query(`SELECT p.oid::regprocedure::text AS signature,p.proname,pg_get_userbyid(p.proowner) AS owner,p.prosecdef,p.proconfig,p.proacl::text AS acl,EXISTS(SELECT 1 FROM aclexplode(COALESCE(p.proacl,acldefault('f',p.proowner))) a WHERE a.grantee=0 AND a.privilege_type='EXECUTE') AS public,has_function_privilege('debateai_runtime',p.oid,'EXECUTE') AS runtime,has_function_privilege('debateai_staff_recovery',p.oid,'EXECUTE') AS recovery FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='staff' AND p.proname=ANY($1) ORDER BY signature`,[names])).rows;
 expect(functions).toHaveLength(15);// Auth DB batch review: these five also search pg_temp last, so a temp object cannot shadow a type they use.
 const tempLast=['require_alert_readiness_jit','publish_independent_alert_readiness','revoke_independent_alert_readiness','claim_alert_delivery','release_alert_delivery'];const runtimeNames=['read_independent_alert_readiness','authorize_alert_operation','read_alert_user_mapping','read_alert_key_mapping','claim_alert_delivery','settle_alert_delivery','read_alert_delivery_status','release_alert_delivery'];for(const f of functions){expect(f.owner).toBe('debateai_staff_security_owner');expect(f.prosecdef).toBe(true);expect(f.proconfig,f.proname).toEqual(tempLast.includes(f.proname)?['search_path=pg_catalog, pg_temp']:['search_path=pg_catalog']);expect(f.public).toBe(false);expect(f.runtime).toBe(runtimeNames.includes(f.proname));expect(f.recovery).toBe(['publish_independent_alert_readiness','revoke_independent_alert_readiness'].includes(f.proname));}
 const tables=(await database.pool.query(`SELECT c.oid::regclass::text AS relation,pg_get_userbyid(c.relowner) AS owner,c.relacl::text AS acl FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='staff' AND c.relkind='r' ORDER BY relation`)).rows;
 const columns=(await database.pool.query(`SELECT c.oid::regclass::text AS relation,a.attname,a.attacl::text AS acl FROM pg_attribute a JOIN pg_class c ON c.oid=a.attrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN('staff','identity') AND a.attnum>0 AND NOT a.attisdropped AND a.attacl IS NOT NULL ORDER BY relation,a.attnum`)).rows;
 const roles=(await database.pool.query(`SELECT r.rolname,r.rolcanlogin,r.rolinherit,r.rolsuper,r.rolcreatedb,r.rolcreaterole,r.rolreplication,r.rolbypassrls,ARRAY(SELECT p.rolname FROM pg_auth_members m JOIN pg_roles p ON p.oid=m.roleid WHERE m.member=r.oid ORDER BY p.rolname) AS memberships FROM pg_roles r WHERE r.rolname IN('debateai_runtime','debateai_staff_security_owner','debateai_staff_recovery','debateai_prod_staff_recovery') ORDER BY r.rolname`)).rows;
 const witness={functions,tables,columns,roles};console.info('[TASK5_EXACT_CATALOG_ACL]',JSON.stringify(witness));
});

// Design note 2026-10-09 item 4: a password-less, peer-authenticated readiness writer replaces the minted JIT password.
async function asWriter<T>(role:string,use:(c:import('pg').PoolClient)=>Promise<T>):Promise<T>{const c=await database.pool.connect();try{await c.query(`SET SESSION AUTHORIZATION ${role}`);return await use(c);}finally{await c.query('RESET SESSION AUTHORIZATION').catch(()=>undefined);c.release();}}
it('the readiness writer is a password-less login that can only publish and revoke readiness',async()=>{
 const role=(await database.pool.query(`SELECT rolcanlogin,rolsuper,rolcreatedb,rolcreaterole,rolreplication,rolbypassrls,rolconnlimit,(SELECT count(*)::int FROM pg_auth_members m WHERE m.member=r.oid OR m.roleid=r.oid) AS memberships FROM pg_roles r WHERE rolname='debateai_staff_readiness_writer'`)).rows;
 expect(role).toEqual([{rolcanlogin:true,rolsuper:false,rolcreatedb:false,rolcreaterole:false,rolreplication:false,rolbypassrls:false,rolconnlimit:2,memberships:0}]);
 expect((await database.pool.query(`SELECT rolpassword IS NULL AS none FROM pg_authid WHERE rolname='debateai_staff_readiness_writer'`)).rows[0].none).toBe(true);
 const callable=(await database.pool.query(`SELECT p.oid::regprocedure::text AS signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname NOT IN('pg_catalog','information_schema','public') AND has_schema_privilege('debateai_staff_readiness_writer',n.oid,'USAGE') AND has_function_privilege('debateai_staff_readiness_writer',p.oid,'EXECUTE') ORDER BY 1`)).rows.map(r=>r.signature);
 expect(callable).toEqual(['staff.publish_independent_alert_readiness(text,uuid,text,uuid,timestamp with time zone)','staff.revoke_independent_alert_readiness(uuid)']);
 expect((await database.pool.query(`SELECT count(*)::int AS n FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname NOT IN('pg_catalog','information_schema') AND (has_table_privilege('debateai_staff_readiness_writer',c.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER') OR has_any_column_privilege('debateai_staff_readiness_writer',c.oid,'SELECT,INSERT,UPDATE,REFERENCES'))`)).rows[0].n).toBe(0);
 // The API runtime gains nothing.
 for(const runtimeRole of ['debateai_runtime','debateai_billing_runtime','debateai_authorization_runtime'])expect((await database.pool.query(`SELECT has_function_privilege($1,'staff.publish_independent_alert_readiness(text,uuid,text,uuid,timestamptz)','EXECUTE') OR has_function_privilege($1,'staff.revoke_independent_alert_readiness(uuid)','EXECUTE') OR pg_has_role($1,'debateai_staff_readiness_writer','MEMBER') AS any`,[runtimeRole])).rows[0].any).toBe(false);
 const fresh=randomUUID();
 await asWriter('debateai_staff_readiness_writer',async c=>{
  expect((await c.query('SELECT session_user::text AS who')).rows[0].who).toBe('debateai_staff_readiness_writer');
  expect((await c.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5) AS value',['a'.repeat(64),fresh,'capture-v1',randomUUID(),new Date(Date.now()+60000)])).rows[0].value).toBe(true);
  expect((await c.query("SELECT staff.read_independent_alert_readiness($1,$2) AS value",['a'.repeat(64),fresh]).catch(e=>({rows:[{value:e.code}]}))).rows[0].value).toBe('42501');
 });
 expect((await database.pool.query("SELECT staff.read_independent_alert_readiness($1,$2) AS value",['a'.repeat(64),fresh])).rows[0].value).toBe('READY');
 await asWriter('debateai_staff_readiness_writer',async c=>{expect((await c.query('SELECT staff.revoke_independent_alert_readiness($1) AS value',[fresh])).rows[0].value).toBe(true);await expect(c.query('SELECT * FROM staff.independent_alert_readiness')).rejects.toMatchObject({code:'42501'});});
 expect((await database.pool.query("SELECT staff.read_independent_alert_readiness($1,$2) AS value",['a'.repeat(64),fresh])).rows[0].value).toBe('UNAVAILABLE');
 // Any other login holding the capability is still refused by the guard, exactly as before.
 await database.pool.query("DO $$BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='task5_impostor') THEN CREATE ROLE task5_impostor LOGIN IN ROLE debateai_staff_recovery;END IF;END$$");
 await asWriter('task5_impostor',async c=>{await expect(c.query('SELECT staff.publish_independent_alert_readiness($1,$2,$3,$4,$5)',['a'.repeat(64),randomUUID(),'capture-v1',randomUUID(),new Date(Date.now()+60000)])).rejects.toThrow('STAFF_RECOVERY_JIT_REQUIRED');});
 await ready();
});
// Design note 2026-10-09 item 5: a claim given back before any send keeps the row's attempts.
it('releases a live claim without spending an attempt and refuses a stale or foreign release',async()=>{
 await ready();await database.pool.query('INSERT INTO staff.alert_dispatch_state(outbox_id,terminal) SELECT outbox_id,true FROM staff.alert_outbox ON CONFLICT(outbox_id) DO UPDATE SET terminal=true');
 const target=await account(),keyRef=(await database.pool.query('SELECT audit_token FROM identity."user" WHERE user_id=$1',[target.userId])).rows[0].audit_token,eventId=randomUUID(),operationId=randomUUID();await authorize(operationId);
 await database.pool.query("INSERT INTO staff.audit_event(event_id,operation_id,request_sha256,event_type,reason_code) VALUES($1,$2,$3,'INVITE','TEAM_ONBOARDING')",[eventId,operationId,'d'.repeat(64)]);
 await database.pool.query("INSERT INTO staff.alert_outbox(event_id,purpose,key_ref,encrypted_payload) VALUES($1,'INDEPENDENT_METADATA_ALERT',$2,$3)",[eventId,keyRef,envelope]);
 const state=async(outboxId:string)=>(await database.pool.query('SELECT attempts,claim_token,terminal FROM staff.alert_dispatch_state WHERE outbox_id=$1',[outboxId])).rows[0];
 const [first]=(await runtime.query('SELECT staff.claim_alert_delivery(1) AS value')).rows[0].value;expect(first.eventId).toBe(eventId);expect(first.attempt).toBe(1);
 expect((await runtime.query('SELECT staff.release_alert_delivery($1,$2) AS value',[first.outboxId,randomUUID()])).rows[0].value).toBe(false);
 expect((await runtime.query('SELECT staff.release_alert_delivery($1,$2) AS value',[first.outboxId,first.claimToken])).rows[0].value).toBe(true);
 expect(await state(first.outboxId)).toEqual({attempts:0,claim_token:null,terminal:false});
 expect((await runtime.query('SELECT staff.release_alert_delivery($1,$2) AS value',[first.outboxId,first.claimToken])).rows[0].value).toBe(false);
 const [again]=(await runtime.query('SELECT staff.claim_alert_delivery(1) AS value')).rows[0].value;expect(again.outboxId).toBe(first.outboxId);expect(again.attempt).toBe(1);
 expect((await database.pool.query('SELECT count(*)::int AS n FROM staff.alert_delivery_receipt WHERE outbox_id=$1',[first.outboxId])).rows[0].n).toBe(0);
 await database.pool.query("UPDATE staff.alert_dispatch_state SET claimed_until=clock_timestamp()-interval '1 second' WHERE outbox_id=$1",[again.outboxId]);
 expect((await runtime.query('SELECT staff.release_alert_delivery($1,$2) AS value',[again.outboxId,again.claimToken])).rows[0].value).toBe(false);
 expect((await database.pool.query("SELECT has_function_privilege('debateai_staff_readiness_writer','staff.release_alert_delivery(uuid,uuid)','EXECUTE') AS writer")).rows[0].writer).toBe(false);
});
// Auth DB batch review 2026-10-09: no role but the owner may create temporary objects, so nothing can shadow a type
// or relation a definer function resolves; the readiness writer is adopted only when it carries nothing extra.
it('no runtime role or the readiness writer can create a temporary object',async()=>{
 const roles=['debateai_runtime','debateai_billing_runtime','debateai_authorization_runtime','debateai_mfa_recovery_runtime','debateai_staff_recovery','debateai_staff_readiness_writer','task5_runtime'];
 for(const role of roles)expect((await database.pool.query("SELECT has_database_privilege($1,current_database(),'TEMPORARY') AS temp",[role])).rows[0].temp,role).toBe(false);
 await asWriter('debateai_staff_readiness_writer',async c=>{await expect(c.query('CREATE TEMP TABLE shadow_probe(x int)')).rejects.toMatchObject({code:'42501'});await expect(c.query('CREATE TYPE pg_temp.timestamptz AS (x int)')).rejects.toMatchObject({code:'42501'});});
 await expect(runtime.query('CREATE TEMP TABLE shadow_probe(x int)')).rejects.toMatchObject({code:'42501'});
 // How many other definer functions still search pg_temp implicitly first (mitigated by the revoke above).
 const left=(await database.pool.query(`SELECT count(*)::int AS n FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE p.prosecdef AND n.nspname NOT IN('pg_catalog','information_schema') AND NOT EXISTS(SELECT 1 FROM unnest(coalesce(p.proconfig,'{}')) s WHERE s LIKE 'search_path=%pg_temp')`)).rows[0].n;
 console.info('[DEFINER_SEARCH_PATH_WITHOUT_PG_TEMP]',left);
});
async function batchSql(){const { readFile }=await import('node:fs/promises');const { AUTH_DB_BATCH_MIGRATION }=await import('../../packages/db/src/migration-forward-auth-db-batch.js');return readFile(new URL(`../../migrations/${AUTH_DB_BATCH_MIGRATION}`,import.meta.url),'utf8');}
async function writerGuard(){const sql=await batchSql();const begin=sql.indexOf('-- readiness-writer-guard:begin'),end=sql.indexOf('-- readiness-writer-guard:end');expect(begin).toBeGreaterThan(-1);expect(end).toBeGreaterThan(begin);return sql.slice(begin,end);}
it('adopts an existing readiness writer only when it has no settings, password, expiry, ownership or extra privilege',async()=>{
 const guard=await writerGuard();await database.pool.query(guard);
 const refused=async(tamper:string,undo:string,code:string)=>{await database.pool.query(tamper);try{await expect(database.pool.query(guard)).rejects.toThrow(code);}finally{await database.pool.query(undo);}await database.pool.query(guard);};
 await refused("ALTER ROLE debateai_staff_readiness_writer SET work_mem='1MB'","ALTER ROLE debateai_staff_readiness_writer RESET ALL",'STAFF_READINESS_WRITER_SETTINGS');
 await refused("ALTER ROLE debateai_staff_readiness_writer IN DATABASE debateai_s00 SET statement_timeout='1s'","ALTER ROLE debateai_staff_readiness_writer IN DATABASE debateai_s00 RESET ALL",'STAFF_READINESS_WRITER_SETTINGS');
 await refused("ALTER ROLE debateai_staff_readiness_writer PASSWORD 'tamper-only'","ALTER ROLE debateai_staff_readiness_writer PASSWORD NULL",'STAFF_READINESS_WRITER_ATTRIBUTES');
 await refused("ALTER ROLE debateai_staff_readiness_writer VALID UNTIL 'infinity'","UPDATE pg_authid SET rolvaliduntil=NULL WHERE rolname='debateai_staff_readiness_writer'",'STAFF_READINESS_WRITER_ATTRIBUTES');
 await refused('GRANT SELECT ON staff.alert_outbox TO debateai_staff_readiness_writer','REVOKE SELECT ON staff.alert_outbox FROM debateai_staff_readiness_writer','STAFF_READINESS_WRITER_PRIVILEGES');
 await refused('GRANT CREATE ON SCHEMA staff TO debateai_staff_readiness_writer','REVOKE CREATE ON SCHEMA staff FROM debateai_staff_readiness_writer','STAFF_READINESS_WRITER_PRIVILEGES');
 await refused('GRANT EXECUTE ON FUNCTION staff.read_independent_alert_readiness(text,uuid) TO debateai_staff_readiness_writer','REVOKE EXECUTE ON FUNCTION staff.read_independent_alert_readiness(text,uuid) FROM debateai_staff_readiness_writer','STAFF_READINESS_WRITER_PRIVILEGES');
 await refused('GRANT TEMPORARY ON DATABASE debateai_s00 TO debateai_staff_readiness_writer','REVOKE TEMPORARY ON DATABASE debateai_s00 FROM debateai_staff_readiness_writer','STAFF_READINESS_WRITER_PRIVILEGES');
 await refused('CREATE TABLE public.writer_owned(x int);ALTER TABLE public.writer_owned OWNER TO debateai_staff_readiness_writer','DROP TABLE public.writer_owned','STAFF_READINESS_WRITER_OWNS_OBJECTS');
});
it("the batch's verifier refuses a readiness writer with a password or an expiry",async()=>{
 const { readFile }=await import('node:fs/promises');const verifier=await readFile(new URL('../../migrations/lineage/verify-auth-db-batch.sql',import.meta.url),'utf8');await database.pool.query(verifier);
 for(const [tamper,undo] of [["ALTER ROLE debateai_staff_readiness_writer PASSWORD 'tamper-only'","ALTER ROLE debateai_staff_readiness_writer PASSWORD NULL"],["ALTER ROLE debateai_staff_readiness_writer VALID UNTIL 'infinity'","UPDATE pg_authid SET rolvaliduntil=NULL WHERE rolname='debateai_staff_readiness_writer'"],["ALTER ROLE debateai_staff_readiness_writer SET work_mem='1MB'","ALTER ROLE debateai_staff_readiness_writer RESET ALL"]] as const){
  await database.pool.query(tamper);try{await expect(database.pool.query(verifier)).rejects.toThrow('MIGRATION_FORWARD_AUTH_DB_BATCH_WRITER_DRIFT');}finally{await database.pool.query(undo);}
 }
 await database.pool.query(verifier);
});
