import { createHash } from "node:crypto";
import { readFile,writeFile } from "node:fs/promises";
const R="/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/support-conversation-20260914",E=`${R}/evidence`,P=`${R}/probes`;
const sha=b=>createHash("sha256").update(b).digest("hex"),readJson=async p=>JSON.parse(await readFile(p,"utf8")),writeJson=async(p,v)=>writeFile(p,`${JSON.stringify(v,null,2)}\n`,{flag:"wx",mode:0o600});
const gate=await readJson(`${E}/GUIDE_PREVIEW_RECOVER34-gate-template.json`),gatePath=`${E}/GUIDE_RUNTIME_BIND36-gate-template.json`;await writeJson(gatePath,gate);const gateBytes=await readFile(gatePath);
const command=await readJson(`${E}/GUIDE_PREVIEW_RECOVER34-command-contract.json`),commandPath=`${E}/GUIDE_RUNTIME_BIND36-command-contract.json`;
command.node="GUIDE_RUNTIME_BIND36";command.gateTemplatePath=gatePath;command.gateTemplateSha256=sha(gateBytes);command.browserProfile=`${P}/GUIDE_RUNTIME_BIND36/browser-profile`;
for(const [name,phase] of Object.entries(command.phases)){
  phase.argv[2]=commandPath;phase.output=phase.output.replaceAll("GUIDE_LIVE29","GUIDE_LIVE30");phase.log=phase.log.replaceAll("GUIDE_LIVE29","GUIDE_LIVE30");
  if(name==="preflight"){phase.ui.output=phase.ui.output.replaceAll("LIVE29","LIVE30");phase.ui.log=phase.ui.log.replaceAll("LIVE29","LIVE30");phase.ui.argv[3]=phase.ui.output}
}
command.phases.readiness.argv[1]=`${P}/GUIDE_RUNTIME_BIND36/phase-readiness.mjs`;
command.phases.rowProof.childArgv[4]=command.phases.gate.output;command.phases.rowProof.childArgv[6]=`${E}/GUIDE_ROW_PROOF-run-LIVE30.json`;command.phases.rowProof.result=command.phases.rowProof.childArgv[6];
command.phases.capture.childArgv[4]=command.phases.gate.output;
await writeJson(commandPath,command);const commandBytes=await readFile(commandPath),commandHash=sha(commandBytes);
const oldScript=await readFile(`${P}/GUIDE_OPERATOR_FIX35/run-operator.mjs`,"utf8");let script=oldScript.replaceAll("GUIDE_PREVIEW_RECOVER34","GUIDE_RUNTIME_BIND36").replaceAll("GUIDE_LIVE29","GUIDE_LIVE30");script=script.replace("f8a5df033841912013df6eda0f13d5811f9e709712e8311f692d7926d9d52030",commandHash);const scriptPath=`${P}/GUIDE_RUNTIME_BIND36/run-operator.mjs`;await writeFile(scriptPath,script,{flag:"wx",mode:0o600});const scriptBytes=await readFile(scriptPath);
const operator=await readJson(`${E}/GUIDE_OPERATOR_FIX35-operator-contract.json`);operator.node="GUIDE_RUNTIME_BIND36";operator.ticket="t_b048e75f";operator.argv[3]=scriptPath;operator.script={path:scriptPath,sha256:sha(scriptBytes),bytes:scriptBytes.byteLength};operator.commandContract={path:commandPath,sha256:commandHash,bytes:commandBytes.byteLength};operator.operatorOwned.outputs.prerequisite=operator.operatorOwned.outputs.prerequisite.replaceAll("GUIDE_LIVE29","GUIDE_LIVE30");operator.operatorOwned.outputs.stop=operator.operatorOwned.outputs.stop.replaceAll("GUIDE_LIVE29","GUIDE_LIVE30");for(const name of Object.keys(operator.operatorOwned.logs))operator.operatorOwned.logs[name]=operator.operatorOwned.logs[name].replaceAll("GUIDE_PREVIEW_RECOVER34","GUIDE_RUNTIME_BIND36");operator.futureAbsence.paths=operator.futureAbsence.paths.map(path=>path.replaceAll("GUIDE_LIVE29","GUIDE_LIVE30").replaceAll("LIVE29","LIVE30").replaceAll("GUIDE_PREVIEW_RECOVER34-operator","GUIDE_RUNTIME_BIND36-operator").replaceAll(`${P}/GUIDE_CAPTURE_FIX29/browser-profile`,command.browserProfile));operator.delta={kind:"RUNTIME_SCHEMA_AND_FRESH_LIVE30_BINDING",retainedRuntime9:true,retainedActualGuide22:true,retainedOwnerContract:true};
const operatorPath=`${E}/GUIDE_RUNTIME_BIND36-operator-contract.json`;await writeJson(operatorPath,operator);console.log(JSON.stringify({commandHash,scriptHash:operator.script.sha256,operatorHash:sha(await readFile(operatorPath)),futurePaths:operator.futureAbsence.paths.length}));
