// @vitest-environment jsdom
import {act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {ContractHttpError} from '@debateai/contract';
import {SecuritySettings} from '../../apps/ui/components/SecuritySettings';
import {retainSocialStepUp} from '../../apps/ui/lib/socialStepUpHandoff';
import publicCatalog from '../../apps/ui/messages/en/public.json';
import NewDebatePage from '../../apps/ui/app/new/NewDebatePageClient';
import catalog from '../../apps/ui/messages/en/newDebate.json';import homeCatalog from '../../apps/ui/messages/en/home.json';import chromeCatalog from '../../apps/ui/messages/en/chrome.json';import settingsCatalog from '../../apps/ui/messages/en/settings.json';import authCatalog from '../../apps/ui/messages/en/auth.json';
const state=vi.hoisted(()=>({create:vi.fn(),update:vi.fn(),step:vi.fn(),push:vi.fn(),begin:vi.fn(),redirect:vi.fn(),read:vi.fn(),provider:false,search:'',owner:'fixture'}));
vi.mock('next/navigation',()=>({useRouter:()=>({push:state.push}),useSearchParams:()=>new URLSearchParams(state.search),usePathname:()=>'/new'}));
vi.mock('@/components/AuthGate',()=>({AuthGate:({children}:any)=>children('session-marker')}));
vi.mock('@/components/support/SupportWidget',()=>({SupportWidget:()=>null}));
vi.mock('@/components/SensitiveDataConsent',()=>({useSensitiveDataConsent:()=>({ensureConsent:async()=>true,modal:null}),isSensitiveDataConsentRefusal:()=>false}));
vi.mock('@/components/CrisisSupport',()=>({useCrisisSupport:()=>({offerIfCrisis:()=>false,flags:()=>false,offer(){},modal:null}),isCrisisSupportRefusal:()=>false}));
vi.mock('@/lib/billing/room',()=>({useAskRoom:()=>[null,()=>{},async()=>null],readAskRoom:async()=>null,waitingRoomOf:()=>null}));
vi.mock('@/lib/api',async(original)=>({...await original<typeof import('../../apps/ui/lib/api')>(),createDebate:state.create,contractClient:{
 readSession:state.read,
 getBillingUsage:async()=>({plan_id:null,windows:[]}),phoneProfile:async()=>({phone_present:false,phone_masked:null,phone_verified:false,updated_at:null}),
 authMethods:async()=>({methods:[],available_step_up_methods:state.provider?['provider']:['password_totp'],step_up_providers:state.provider?['google']:[],recovery_codes_remaining:0}),stepUp:state.step,updatePhoneProfile:state.update,beginSocialStepUp:state.begin,authProviders:async()=>({providers:[]}),linkedSocialProviders:async()=>({providers:[]}),recoveryEmail:async()=>({state:'absent',email:null,pending:null}),listSessions:async()=>({sessions:[]}),
}}));
let root:Root;
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);sessionStorage.clear();state.provider=false;state.search='topic=My%20original%20question';state.owner='fixture';state.read.mockReset().mockImplementation(async()=>({asker_id:state.owner,session_id:'11111111-1111-4111-8111-111111111111',caller_scope:'ASKER',ownership_provenance:'server_session',provisional_identity_model:false}));state.begin.mockReset().mockResolvedValue({authorization_url:'https://accounts.example.invalid/authorize?state=synthetic'});state.redirect.mockReset();const native=window;const location={get href(){return native.location.href},get origin(){return native.location.origin},get pathname(){return native.location.pathname},get search(){return native.location.search},get hash(){return native.location.hash},assign:state.redirect};vi.stubGlobal('window',new Proxy(native,{get(target,key){if(key==='location')return location;const value=Reflect.get(target,key,target);return ['addEventListener','removeEventListener','dispatchEvent','getComputedStyle'].includes(String(key))?value.bind(target):value}}));native.history.replaceState(null,'','/new?topic=My%20original%20question&lang=ro&room=kept');state.create.mockReset();state.update.mockReset();state.step.mockReset();state.push.mockReset();state.create.mockRejectedValueOnce(new ContractHttpError('UNPROCESSABLE',422,'safe','ACCOUNT_PHONE_REQUIRED')).mockResolvedValue({id:'fixture-debate'});state.step.mockResolvedValue({status:'step_up_complete',csrf_token:'c'.repeat(43),step_up_grant:{action:'CHANGE_PHONE_PROFILE',token:'g'.repeat(43),expires_at:new Date(Date.now()+300000).toISOString()}});state.update.mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null});});
afterEach(async()=>{await act(async()=>root.unmount());vi.unstubAllGlobals();});
async function mount(tune?:()=>Promise<void>){await act(async()=>root.render(<NewDebatePage catalog={catalog} homeCatalog={homeCatalog} chromeCatalog={chromeCatalog} settingsCatalog={settingsCatalog} authCatalog={authCatalog}/>));if(tune)await tune();await act(async()=>document.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));}
async function input(selector:string,value:string){await act(async()=>{const field=document.querySelector<HTMLInputElement>(selector)!;Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(field,value);field.dispatchEvent(new Event('input',{bubbles:true}));});}
async function click(text:string){const button=[...document.querySelectorAll('button')].find(x=>x.textContent?.trim()===text)!;expect(button).toBeDefined();await act(async()=>button.click());}
async function update(){await input('input[type=tel]','+40 712 345 678');await click('Password · 6-digit authentication code');await input('input[type=password]','long password');await input('input[autocomplete=one-time-code]','123456');}
it('cancel preserves the complete mounted draft without another debate request',async()=>{await mount();expect(document.body.textContent).toContain('Add your phone');expect(state.create).toHaveBeenCalledTimes(1);expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('My original question');await click('Cancel');expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('My original question');expect(state.create).toHaveBeenCalledTimes(1);expect(state.update).not.toHaveBeenCalled();});
it('successful encrypted update retries the real original question/config and navigates only on success',async()=>{await mount();const original=state.create.mock.calls[0];await update();expect(state.update).toHaveBeenCalledWith({phone:'+40712345678',grantToken:'g'.repeat(43)});expect(state.create).toHaveBeenCalledTimes(2);expect(state.create.mock.calls[1]).toEqual(original);expect(state.push).toHaveBeenCalledWith('/debate/fixture-debate?starting=1');});
it('failed encrypted update keeps draft/options and makes no retry request',async()=>{state.update.mockRejectedValueOnce(new Error('PRIVATE FAILURE'));await mount();await update();expect(state.update).toHaveBeenCalledTimes(1);expect(state.create).toHaveBeenCalledTimes(1);expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('My original question');expect(document.body.textContent).not.toContain('PRIVATE FAILURE');expect(state.push).not.toHaveBeenCalled();});
it.each(['Control','Meta'])('actual %s+Enter cannot submit again while phone completion is pending',async modifier=>{await mount();expect(document.querySelector<HTMLButtonElement>('.ndStart')!.disabled).toBe(true);const field=document.querySelector<HTMLTextAreaElement>('textarea')!;await act(async()=>field.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true,cancelable:true,ctrlKey:modifier==='Control',metaKey:modifier==='Meta'})));expect(state.create).toHaveBeenCalledTimes(1);expect(state.update).not.toHaveBeenCalled();expect(field.value).toBe('My original question');});

const draftKey='debateai.phone-completion-draft.v1';
async function providerBoundary(){state.provider=true;await mount(async()=>{
 const premium=document.querySelector<HTMLButtonElement>('[data-field="planTier"][data-value="premium"]')!;expect(premium).toBeDefined();await act(async()=>premium.click());await act(async()=>document.querySelector<HTMLButtonElement>('.ndOptionsToggle')!.click());
 for(const [id,value] of [['depthMode','manual'],['scrutinyDepth','exhaustive']]) await act(async()=>{const field=document.getElementById(id) as HTMLSelectElement;expect(field.disabled).toBe(false);field.value=value;field.dispatchEvent(new Event('change',{bubbles:true}));});
 await input('#branchingWidth','3');await input('#concurrency','4');await input('#maxTokens','1216');
 });await input('input[type=tel]','+40 712 345 678');await click('Continue with Google');}
async function remountNew(){await act(async()=>root.unmount());document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);state.search='';await act(async()=>root.render(<NewDebatePage catalog={catalog} homeCatalog={homeCatalog} chromeCatalog={chromeCatalog} settingsCatalog={settingsCatalog} authCatalog={authCatalog}/>));}
it('actual provider redirect saves only the owned question/options/request and scrubs only topic from the URL',async()=>{await providerBoundary();const raw=sessionStorage.getItem(draftKey);expect(raw).not.toBeNull();const saved=JSON.parse(raw!);expect(saved.owner).toBe('fixture');expect(saved.form.topic).toBe('My original question');expect(saved.form.optionsOpen).toBe(true);expect(saved.form.depthMode).toBe('manual');expect(saved.form.scrutiny).toBe('exhaustive');expect(saved.form.branching).toBe(3);expect(saved.form.concurrency).toBe(4);expect(saved.form.maxTokens).toBe(1216);expect(saved.submitted.config).toEqual(state.create.mock.calls[0][1]);expect(Object.keys(saved.form).sort()).toEqual(['asOf','branching','budgetTier','concurrency','decisionScope','depth','depthMode','maxTokens','optionsOpen','planTier','riskTier','riskTierWasEdited','scrutiny','topic'].sort());expect(raw).not.toContain('+40 712');expect(raw).not.toContain('step_up_grant');expect(raw).not.toContain('csrf_token');expect(state.begin).toHaveBeenCalledWith('google',{action:'CHANGE_PHONE_PROFILE'});expect(state.redirect).toHaveBeenCalledTimes(1);expect(window.location.search).toBe('?lang=ro&room=kept');});
it.each(['cancel','refusal'])('provider %s restores all draft fields without retry or phone update',async outcome=>{if(outcome==='refusal')state.begin.mockRejectedValueOnce(new Error('PRIVATE_PROVIDER_FAILURE'));await providerBoundary();const raw=sessionStorage.getItem(draftKey);expect(raw).not.toBeNull();await remountNew();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('My original question');expect(document.querySelector<HTMLInputElement>('input[type=tel]')!.value).toBe('');expect(document.querySelector<HTMLSelectElement>('#depthMode')!.value).toBe('manual');expect(document.querySelector<HTMLSelectElement>('#scrutinyDepth')!.value).toBe('exhaustive');expect(document.querySelector<HTMLInputElement>('#branchingWidth')!.value).toBe('3');expect(document.querySelector<HTMLInputElement>('#concurrency')!.value).toBe('4');expect(document.querySelector<HTMLInputElement>('#maxTokens')!.value).toBe('1216');expect(state.create).toHaveBeenCalledTimes(1);expect(state.update).not.toHaveBeenCalled();expect(document.querySelector<HTMLButtonElement>('.ndStart')!.disabled).toBe(true);});
it('provider success re-enters phone in Security then retries exactly once with the original request on /new',async()=>{await providerBoundary();const original=state.create.mock.calls[0];await act(async()=>root.unmount());document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);retainSocialStepUp(await state.step());await act(async()=>root.render(<SecuritySettings catalog={settingsCatalog} authCatalog={authCatalog} publicCatalog={publicCatalog} locale="en"/>));await click('Confirm action');expect(document.querySelector<HTMLInputElement>('input[type=tel]')!.value).toBe('');expect(state.update).not.toHaveBeenCalled();await input('input[type=tel]','+40 712 345 678');await click('Confirm action');expect(state.update).toHaveBeenCalledTimes(1);expect(state.push).toHaveBeenCalledWith('/new');expect(state.create).toHaveBeenCalledTimes(1);await remountNew();expect(state.create).toHaveBeenCalledTimes(2);expect(state.create.mock.calls[1]).toEqual(original);expect(sessionStorage.getItem(draftKey)).toBeNull();await remountNew();expect(state.create).toHaveBeenCalledTimes(2);});
it('owner mismatch does not show a stored draft and clears it',async()=>{await providerBoundary();expect(sessionStorage.getItem(draftKey)).not.toBeNull();state.owner='other';await remountNew();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('');expect(sessionStorage.getItem(draftKey)).toBeNull();expect(state.create).toHaveBeenCalledTimes(1);});
it('storage failure keeps the mounted draft and genuine provider choice without redirect',async()=>{const write=vi.spyOn(Storage.prototype,'setItem').mockImplementation(()=>{throw new DOMException('quota','QuotaExceededError')});try{await providerBoundary();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('My original question');expect(state.begin).not.toHaveBeenCalled();expect(state.redirect).not.toHaveBeenCalled();expect(document.querySelector('[role=alert]')).not.toBeNull();expect([...document.querySelectorAll('button')].some(b=>b.textContent==='Continue with Google')).toBe(true);}finally{write.mockRestore();}});
it('cancellation while fresh owner lookup is pending cannot write or redirect',async()=>{state.provider=true;await mount();await input('input[type=tel]','+40 712 345 678');let resolve!:(v:any)=>void;state.read.mockReturnValueOnce(new Promise(r=>resolve=r));await click('Continue with Google');await click('Cancel');await act(async()=>resolve({asker_id:'fixture'}));expect(sessionStorage.getItem(draftKey)).toBeNull();expect(state.begin).not.toHaveBeenCalled();expect(state.redirect).not.toHaveBeenCalled();});
it.each(['version','unknown-key','opaque-provenance'])('rejects %s carrier data before showing stored topic or retrying',async kind=>{await providerBoundary();const value=JSON.parse(sessionStorage.getItem(draftKey)!);if(kind==='version')value.version=2;else if(kind==='unknown-key')value.flow_token='forbidden';else value.submitted.config.tier_provenance_ref='opaque:forbidden';sessionStorage.setItem(draftKey,JSON.stringify(value));await remountNew();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('');expect(sessionStorage.getItem(draftKey)).toBeNull();expect(state.create).toHaveBeenCalledTimes(1);});
it('expiry denies draft restoration and update acknowledgement without renewing the original deadline',async()=>{await providerBoundary();const value=JSON.parse(sessionStorage.getItem(draftKey)!);expect(value.expires_at-value.created_at).toBe(15*60000);const time=vi.spyOn(Date,'now').mockReturnValue(value.expires_at+1);try{await remountNew();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('');expect(sessionStorage.getItem(draftKey)).toBeNull();expect(state.create).toHaveBeenCalledTimes(1);}finally{time.mockRestore();}});
it('unauthenticated owner lookup clears the old draft without exposing it',async()=>{await providerBoundary();state.read.mockRejectedValueOnce(new ContractHttpError('UNAUTHENTICATED',401,'safe'));await remountNew();expect(document.querySelector<HTMLTextAreaElement>('textarea')!.value).toBe('');expect(sessionStorage.getItem(draftKey)).toBeNull();expect(state.create).toHaveBeenCalledTimes(1);});
it('provider refusal and return do not renew the original draft validity window',async()=>{state.begin.mockRejectedValueOnce(new Error('provider refused'));await providerBoundary();const first=JSON.parse(sessionStorage.getItem(draftKey)!);await remountNew();const time=vi.spyOn(Date,'now').mockReturnValue(first.created_at+60000);try{await input('input[type=tel]','+40 712 345 678');await click('Continue with Google');const next=JSON.parse(sessionStorage.getItem(draftKey)!);expect(next.id).toBe(first.id);expect(next.created_at).toBe(first.created_at);expect(next.expires_at).toBe(first.expires_at);}finally{time.mockRestore();}});
