// @vitest-environment jsdom
import {act} from 'react';import {createRoot,type Root} from 'react-dom/client';import {afterEach,beforeEach,it,expect,vi} from 'vitest';import {existsSync,readFileSync} from 'node:fs';
import settings from '../../apps/ui/messages/en/settings.json';import auth from '../../apps/ui/messages/en/auth.json';
let root:Root;const proof=(action:string)=>({status:'step_up_complete',csrf_token:'c'.repeat(43),step_up_grant:{token:'g'.repeat(43),action,expires_at:new Date(Date.now()+300000).toISOString()}});
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);});afterEach(async()=>{await act(async()=>root.unmount());vi.unstubAllGlobals();});
async function mount(client:any,resume:any,onUpdated=vi.fn()){expect(existsSync('apps/ui/components/PhoneProfileCard.tsx')).toBe(true);const {PhoneProfileCard}=await import(/* @vite-ignore */ '../../apps/ui/components/' + 'PhoneProfileCard.tsx');await act(async()=>root.render(<PhoneProfileCard client={client} catalog={settings} authCatalog={auth} resume={resume} onUpdated={onUpdated}/>));}
it('reveal stays masked until explicit exact confirmation and clears on lifecycle event',async()=>{const c={phoneProfile:vi.fn().mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null}),revealPhoneProfile:vi.fn().mockResolvedValue({phone:'+40712345678',phone_verified:false})};await mount(c,{authorization:{action:'READ_PHONE_PROFILE'},initialProof:proof('READ_PHONE_PROFILE')});expect(document.body.textContent).not.toContain('+40712345678');expect(c.revealPhoneProfile).not.toHaveBeenCalled();await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());expect(document.body.textContent).toContain('+40712345678');await act(async()=>window.dispatchEvent(new Event('debateai:staff-session-ended')));expect(document.body.textContent).not.toContain('+40712345678');});
it('validates the real shared international phone normalizer and invokes retry only after encrypted update success',async()=>{const done=vi.fn();const c={phoneProfile:vi.fn().mockResolvedValue({phone_present:false,phone_masked:null,phone_verified:false,updated_at:null}),updatePhoneProfile:vi.fn().mockRejectedValueOnce(new Error('SECRET')).mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null})};await mount(c,{authorization:{action:'CHANGE_PHONE_PROFILE'},initialProof:proof('CHANGE_PHONE_PROFILE')},done);const input=document.querySelector<HTMLInputElement>('input[type="tel"]')!;const set=async(value:string)=>act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);input.dispatchEvent(new Event('input',{bubbles:true}));});await set('0712345678');await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());expect(c.updatePhoneProfile).not.toHaveBeenCalled();await set('+40 712 345 678');await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());expect(c.updatePhoneProfile).toHaveBeenCalledWith({phone:'+40712345678',grantToken:'g'.repeat(43)});expect(done).not.toHaveBeenCalled();expect(document.body.textContent).not.toContain('SECRET');});
it('/new intercepts the server phone refusal before generic banner handling; Library directs topic to the complete /new flow',()=>{const n=readFileSync('apps/ui/app/new/NewDebatePageClient.tsx','utf8');expect(n).toContain('ACCOUNT_PHONE_REQUIRED');expect(n).toContain('<PhoneProfileCard');const l=readFileSync('apps/ui/components/LibraryComposer.tsx','utf8');expect(l).not.toContain('max_depth: 3, branching: 2, max_tokens: 800');});
it('temporary reveal expires at the original grant deadline, without extending freshness',async()=>{vi.useFakeTimers();try{const c={phoneProfile:vi.fn().mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null}),revealPhoneProfile:vi.fn().mockResolvedValue({phone:'+40712345678',phone_verified:false})};const initialProof=proof('READ_PHONE_PROFILE');initialProof.step_up_grant.expires_at=new Date(Date.now()+1000).toISOString();await mount(c,{authorization:{action:'READ_PHONE_PROFILE'},initialProof});await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());expect(document.body.textContent).toContain('+40712345678');await act(async()=>vi.advanceTimersByTime(1001));expect(document.body.textContent).not.toContain('+40712345678');}finally{vi.useRealTimers();}});
it('canceling phone confirmation keeps a pending masked metadata read usable',async()=>{const data={phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null};let resolve!:(value:typeof data)=>void;const c={phoneProfile:vi.fn(()=>new Promise<typeof data>(r=>resolve=r)),authMethods:vi.fn().mockResolvedValue({methods:[],available_step_up_methods:[],step_up_providers:[],recovery_codes_remaining:0})};await mount(c,null);const change=[...document.querySelectorAll('button')].find(x=>x.textContent==='Change phone')!;await act(async()=>change.click());const cancel=[...document.querySelectorAll('button')].find(x=>x.textContent==='Cancel')!;await act(async()=>cancel.click());await act(async()=>resolve(data));expect(document.body.textContent).toContain('+40 ••• 678');});
