// @vitest-environment jsdom
import {expect,it,vi} from 'vitest';
import {mount,unmount} from './task11-harness.js';
const mocks=vi.hoisted(()=>({confirm:vi.fn()}));
vi.mock('@/lib/api',()=>({contractClient:{confirmRecoveryEmail:mocks.confirm}}));
import Page from '../../apps/ui/app/verify-recovery-email/page.js';
it('scrubs before purpose-specific confirmation and confirmed output never starts enrollment',async()=>{mocks.confirm.mockReset().mockImplementation(async input=>{expect(window.location.hash).toBe('');expect(input).toEqual({token:'a'.repeat(43)});return {status:'CONFIRMED'};});window.history.replaceState(null,'','/verify-recovery-email#token='+ 'a'.repeat(43));const {host,root}=await mount(<Page/>);try{expect(mocks.confirm).toHaveBeenCalledOnce();expect(host.textContent).toContain('Recovery email confirmed.');expect(host.querySelector('input')).toBeNull();expect(host.querySelector('a')?.getAttribute('href')).toBe('/login');}finally{await unmount(root,host);window.history.replaceState(null,'','/');}});
it.each(['?token='+ 'a'.repeat(43),'#token='+ 'a'.repeat(43)+'&token='+ 'b'.repeat(43),'#token=malformed'])('invalid recovery purpose input %s is fully scrubbed and cannot fall back into enrollment',async residue=>{mocks.confirm.mockReset();window.history.replaceState(null,'','/verify-recovery-email'+residue);const {host,root}=await mount(<Page/>);try{expect(mocks.confirm).not.toHaveBeenCalled();expect(window.location.href).not.toContain('token');expect(host.textContent).toContain('invalid or expired');}finally{await unmount(root,host);window.history.replaceState(null,'','/');}});
it('replayed/lost-response confirmation remains a safe invalid-link state',async()=>{mocks.confirm.mockReset().mockRejectedValue(new Error('PRIVATE_ACCOUNT_DETAIL'));window.history.replaceState(null,'','/verify-recovery-email#token='+ 'a'.repeat(43));const {host,root}=await mount(<Page/>);try{expect(host.textContent).not.toContain('PRIVATE_ACCOUNT_DETAIL');expect(host.textContent).not.toContain('Recovery email confirmed.');expect(host.textContent).toContain('invalid or expired');}finally{await unmount(root,host);window.history.replaceState(null,'','/');}});
