// @vitest-environment jsdom
import {act} from 'react';
import {expect,it,vi} from 'vitest';
import {RecoveryFlow} from '../../apps/ui/components/auth/RecoveryFlow.js';
import {OnboardingEvidence} from '../../apps/ui/components/auth/OnboardingEvidence.js';
import {SecurityEnrollment} from '../../apps/ui/components/auth/SecurityEnrollment.js';
import {mount,unmount,input,click} from './task11-harness.js';
import auth from '../../apps/ui/messages/en/auth.json';
import {TERMS_OF_SERVICE} from '../../apps/ui/lib/termsOfService.js';
import {PRIVACY_POLICY} from '../../apps/ui/lib/privacyPolicy.js';
const token='a'.repeat(43),cap='b'.repeat(43);
const requirements={status:'RECOVERY_ENROLL_ONLY',country:'RO',age_confirmation_required:false,legal_acceptance_required:false,terms:{locale:'en',version:TERMS_OF_SERVICE.version,sha256:TERMS_OF_SERVICE.sha256,url:'/terms?lang=en'},privacy:{locale:'en',version:PRIVACY_POLICY.version,sha256:PRIVACY_POLICY.sha256,url:'/privacy?lang=en'}};
it('RECOVERY_ENROLL_ONLY and status evidence never authenticate; PASSWORD_UNAVAILABLE retains independent passkey and optional restart code',async()=>{window.history.replaceState(null,'','/recover#token='+token);const done=vi.fn(),store=vi.spyOn(Storage.prototype,'setItem'),client={recoveryProve:vi.fn(async input=>{expect(window.location.hash).toBe('');expect(input).toEqual({token,recovery_code:'SAVED-CODE',method:'passkey'});return {status:'RECOVERY_ENROLL_ONLY',recovery_capability:cap,replacement_recovery_code:'RESTART-CODE',expires_at:new Date(Date.now()+300000).toISOString(),available_methods:['passkey'],totp_unavailable_reason:'PASSWORD_UNAVAILABLE'};}),recoveryEnrollmentStatus:vi.fn().mockResolvedValue(requirements),authMethods:vi.fn()};const {host,root}=await mount(<RecoveryFlow catalog={auth} locale="en" client={client as any} onAuthenticated={done}/>);try{await input(host,'[name=code]','SAVED-CODE');await act(async()=>host.querySelector('form')!.requestSubmit());expect(done).not.toHaveBeenCalled();expect(client.authMethods).not.toHaveBeenCalled();expect(host.textContent).toContain('RESTART-CODE');expect(host.textContent).toContain('This account has no usable password');expect(host.textContent).toContain('Create a passkey');expect(host.textContent).not.toContain('Use an authenticator app instead');expect(host.querySelector('input')).toBeNull();expect(store).not.toHaveBeenCalled();}finally{store.mockRestore();await unmount(root,host);window.history.replaceState(null,'','/');}});
it('original recovery expiry clears cap/seed while the one-time restart code remains optional and ephemeral',async()=>{vi.useFakeTimers();window.history.replaceState(null,'','/recover#token='+token);const client={recoveryProve:vi.fn().mockResolvedValue({status:'RECOVERY_ENROLL_ONLY',recovery_capability:cap,replacement_recovery_code:'RESTART-CODE',expires_at:new Date(Date.now()+1000).toISOString(),available_methods:['passkey'],totp_unavailable_reason:'PASSWORD_UNAVAILABLE'}),recoveryEnrollmentStatus:vi.fn().mockResolvedValue(requirements)};const {host,root}=await mount(<RecoveryFlow catalog={auth} locale="en" client={client as any}/>);try{await input(host,'[name=code]','SAVED-CODE');await act(async()=>host.querySelector('form')!.requestSubmit());await act(async()=>vi.advanceTimersByTime(1001));expect(host.textContent).toContain('This recovery attempt expired');expect(host.textContent).toContain('RESTART-CODE');expect(host.textContent).not.toContain('Create a passkey');}finally{await unmount(root,host);vi.useRealTimers();window.history.replaceState(null,'','/');}});
it('pending and recovery evidence use disjoint authority, exact displayed pairs and only server-required DOB; 204 only advances evidence',async()=>{const ready=vi.fn(),client={recoveryEnrollmentStatus:vi.fn().mockResolvedValue({...requirements,age_confirmation_required:true}),completeRecoveryEvidence:vi.fn().mockResolvedValue(undefined),pendingOnboardingStatus:vi.fn(),completePendingOnboarding:vi.fn()};const {host,root}=await mount(<OnboardingEvidence authority={{kind:'recovery',token:cap}} locale="en" catalog={auth} client={client as any} onReady={ready}/>);try{await input(host,'[name=dob-d]','01');await input(host,'[name=dob-m]','01');await input(host,'[name=dob-y]','1990');await act(async()=>host.querySelector('form')!.requestSubmit());expect(client.completeRecoveryEvidence).toHaveBeenCalledWith({recovery_capability:cap,locale:'en',terms:{version:TERMS_OF_SERVICE.version,sha256:TERMS_OF_SERVICE.sha256},privacy:{version:PRIVACY_POLICY.version,sha256:PRIVACY_POLICY.sha256},date_of_birth:'1990-01-01',terms_accepted:true,privacy_acknowledged:true,adult_affirmed:true});expect(client.completePendingOnboarding).not.toHaveBeenCalled();expect(ready).toHaveBeenCalledOnce();}finally{await unmount(root,host);}});
it('mismatched returned legal hash cannot be accepted or copied unseen into completion',async()=>{const client={pendingOnboardingStatus:vi.fn().mockResolvedValue({...requirements,status:'pending_mfa',legal_acceptance_required:true,terms:{...requirements.terms,sha256:'f'.repeat(64)}}),completePendingOnboarding:vi.fn()},ready=vi.fn();const {host,root}=await mount(<OnboardingEvidence authority={{kind:'pending',token}} locale="en" catalog={auth} client={client as any} onReady={ready}/>);try{expect(host.querySelector('[role=alert]')).not.toBeNull();expect(host.querySelector('form')).toBeNull();expect(client.completePendingOnboarding).not.toHaveBeenCalled();expect(ready).not.toHaveBeenCalled();}finally{await unmount(root,host);}});
it('switching recovery methods clears obsolete TOTP and rejects late passkey resolve at original deadline',async()=>{let resolve:(value:any)=>void=()=>{};const browser={register:vi.fn().mockReturnValue(new Promise(r=>resolve=r)),cancel:vi.fn()},client={beginRecoveryEnrollment:vi.fn(async request=>request.method==='passkey'?{method:'passkey',challenge_handle:'c'.repeat(43),expires_at:new Date(Date.now()+300000).toISOString(),options:{}}:{method:'totp',challenge_handle:'d'.repeat(43),secret:'A'.repeat(32),otpauthUri:'otpauth://totp/test?secret='+ 'A'.repeat(32),expires_at:new Date(Date.now()+300000).toISOString()}),completeRecoveryEnrollment:vi.fn()},done=vi.fn();const {host,root}=await mount(<SecurityEnrollment catalog={auth} authority={{kind:'recovery',token:cap,expiresAt:new Date(Date.now()+300000).toISOString(),availableMethods:['passkey','totp']}} client={client as any} browser={browser as any} onAuthenticated={done}/>);try{await click(host,'Create a passkey');await click(host,'Use an authenticator app instead');await act(async()=>resolve({}));expect(client.completeRecoveryEnrollment).not.toHaveBeenCalled();expect(done).not.toHaveBeenCalled();expect(host.querySelector('[name=code]')).not.toBeNull();expect(browser.cancel).toHaveBeenCalled();}finally{await unmount(root,host);}});
