// @vitest-environment jsdom
import {expect,it,vi} from 'vitest';
import {signup,fillSignup,submitSignup} from './task11-signup.js';
import {unmount} from './task11-harness.js';
it.each(['','not-an-email','a@b','a@b..test'])('one-email form rejects malformed FormData %j inline before any request',async value=>{const client={register:vi.fn(),checkAge:vi.fn()};const {host,root}=await signup(client);try{await fillSignup(host);host.querySelector<HTMLInputElement>('[name=email]')!.value=value;await submitSignup(host);expect(host.querySelector('[name=confirm-email]')).toBeNull();expect(document.activeElement).toBe(host.querySelector('[name=email]'));expect(client.register).not.toHaveBeenCalled();expect(client.checkAge).not.toHaveBeenCalled();}finally{await unmount(root,host);}});
it.each(['0712345678','+40 12','+40 712 345 678 ext. 1'])('raw telephone %j uses the shared international normalizer and fails inline',async value=>{const client={register:vi.fn(),checkAge:vi.fn()};const {host,root}=await signup(client);try{await fillSignup(host);host.querySelector<HTMLInputElement>('[name=phone]')!.value=value;await submitSignup(host);expect(host.querySelector('[name=phone]')?.getAttribute('aria-invalid')).toBe('true');expect(client.register).not.toHaveBeenCalled();}finally{await unmount(root,host);}});
// Owner ruling 2026-10-09: the phone is optional. Left empty, sign-up goes through and sends no phone.
it.each(['','   '])('an empty phone %j is allowed and the registration carries no phone',async value=>{const client={register:vi.fn().mockResolvedValue({retry_after_seconds:60}),checkAge:vi.fn().mockResolvedValue({outcome:'allowed'})};const {host,root}=await signup(client);try{await fillSignup(host);host.querySelector<HTMLInputElement>('[name=phone]')!.value=value;await submitSignup(host);expect(host.querySelector('[name=phone]')?.getAttribute('aria-invalid')).not.toBe('true');expect(client.register).toHaveBeenCalledTimes(1);expect(client.register.mock.calls[0]![0]).not.toHaveProperty('phone');}finally{await unmount(root,host);}});
it('the phone field is marked optional, is not required, and says what the number is for',async()=>{const client={register:vi.fn(),checkAge:vi.fn()};const {host,root}=await signup(client);try{const field=host.querySelector<HTMLInputElement>('[name=phone]')!;expect(field.required).toBe(false);expect(host.querySelector(`label[for="${field.id}"]`)?.textContent).toBe('Phone (optional)');const hint=host.querySelector(`#${field.id}-hint`)!.textContent!;expect(hint).toContain('Optional. Later, we may text you a code to help you get back into your account, and if you ask us for help we can call or text you. Stored encrypted; never shared or used for marketing.');expect(hint).toContain('Include the international prefix, for example +40 712 345 678. This number is unverified.');expect(hint).not.toMatch(/duplicate/i);}finally{await unmount(root,host);}});
