// @vitest-environment jsdom
import { act, StrictMode } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { existsSync } from 'node:fs';
import settings from '../../apps/ui/messages/en/settings.json';
import auth from '../../apps/ui/messages/en/auth.json';
import publicCatalog from '../../apps/ui/messages/en/public.json';
let root:Root;
const factor='11111111-1111-4111-8111-111111111111';
const proof=(action:any,target:any={})=>({status:'step_up_complete',csrf_token:'c'.repeat(43),step_up_grant:{token:'g'.repeat(43),action,...target,expires_at:new Date(Date.now()+300000).toISOString()}});
const client=()=>({ authMethods:vi.fn().mockResolvedValue({methods:[{factor_id:factor,type:'passkey',label:'My key',created_at:'2026-10-01T10:00:00Z',last_used_at:null,removable:false}],recovery_codes_remaining:10,available_step_up_methods:['passkey'],step_up_providers:[]}), phoneProfile:vi.fn().mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null}), recoveryEmail:vi.fn().mockResolvedValue({state:'absent',email:null,pending:null}), authProviders:vi.fn().mockResolvedValue({providers:[]}),linkedSocialProviders:vi.fn().mockResolvedValue({providers:[]}),removeAuthMethod:vi.fn().mockResolvedValue(undefined),listSessions:vi.fn().mockResolvedValue({sessions:[]}),logout:vi.fn(),revokeAllSessions:vi.fn(),revokeSession:vi.fn()});
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);});
afterEach(async()=>{await act(async()=>root.unmount());vi.unstubAllGlobals();});
async function mount(c:any,resume?:any){expect(existsSync('apps/ui/components/SecuritySettings.tsx')).toBe(true);const {SecuritySettings}=await import(/* @vite-ignore */ '../../apps/ui/components/' + 'SecuritySettings.tsx');await act(async()=>root.render(<StrictMode><SecuritySettings client={c} catalog={settings} authCatalog={auth} publicCatalog={publicCatalog} locale="en" resume={resume}/></StrictMode>));}
it('keeps active sessions and prevents removing the advertised last method',async()=>{const c=client();await mount(c);expect(document.body.textContent).toContain('Active sessions');expect(document.querySelector<HTMLButtonElement>('[data-remove-factor]')?.disabled).toBe(true);expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('a resumed exact factor proof waits for explicit operation confirmation and consumes the exact target once',async()=>{const c=client(); c.authMethods.mockResolvedValue({...await c.authMethods(),methods:[{factor_id:factor,type:'passkey',label:'My key',created_at:'2026-10-01T10:00:00Z',last_used_at:null,removable:true}]}); await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof:proof('REMOVE_AUTH_METHOD',{target_factor_id:factor})}); expect(c.removeAuthMethod).not.toHaveBeenCalled(); const button=document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!;expect(button).not.toBeNull();await act(async()=>{button.click();button.click();});expect(c.removeAuthMethod).toHaveBeenCalledTimes(1);expect(c.removeAuthMethod).toHaveBeenCalledWith(factor,'g'.repeat(43));});
it('expired and wrong-target resume proofs never remove a method',async()=>{const c=client(); await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof:proof('REMOVE_AUTH_METHOD',{target_factor_id:'22222222-2222-4222-8222-222222222222'})});expect(document.querySelector('[data-resumed-confirm]')).toBeNull();expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('an ADD_PASSKEY proof exposes only its authorized ceremony and never borrows it for TOTP',async()=>{const c={...client(),beginPasskeyEnrollment:vi.fn(),beginTotpEnrollment:vi.fn()};await mount(c,{authorization:{action:'ADD_PASSKEY'},initialProof:proof('ADD_PASSKEY')});await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());const panel=document.querySelector('section[aria-label="Protect your account"]');expect(panel?.textContent).toContain('Create a passkey');expect(panel?.textContent).not.toContain('Use an authenticator app instead');expect(c.beginTotpEnrollment).not.toHaveBeenCalled();});
it('an actually expired original proof cannot expose a resumed operation',async()=>{const c=client();const initialProof=proof('REMOVE_AUTH_METHOD',{target_factor_id:factor});initialProof.step_up_grant.expires_at=new Date(Date.now()-1).toISOString();await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof});expect(document.querySelector('[data-resumed-confirm]')).toBeNull();expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('canceling confirmation does not lose a pending safe metadata read',async()=>{const c=client();const data=await c.authMethods();let resolve!: (value:typeof data)=>void;const pending=new Promise<typeof data>(r=>resolve=r);c.authMethods.mockReturnValue(pending);await mount(c);const add=[...document.querySelectorAll('button')].find(x=>x.textContent==='Create a passkey')!;await act(async()=>add.click());const cancel=[...document.querySelectorAll('button')].find(x=>x.textContent==='Cancel')!;await act(async()=>cancel.click());await act(async()=>resolve(data));expect(document.body.textContent).toContain('My key');expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('does not fabricate a recovery-code count while safe metadata is pending',async()=>{const c=client();const data=await c.authMethods();let resolve!:(value:typeof data)=>void;c.authMethods.mockReturnValue(new Promise<typeof data>(r=>resolve=r));await mount(c);expect(document.body.textContent).not.toContain('Recovery codes: 0');const button=[...document.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent==='Generate new recovery codes')!;expect(button.disabled).toBe(true);await act(async()=>resolve(data));expect(document.body.textContent).toContain('Recovery codes: 10');});
