// @vitest-environment jsdom
import { act, StrictMode } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { existsSync } from 'node:fs';
import settings from '../../apps/ui/messages/en/settings.json';
import auth from '../../apps/ui/messages/en/auth.json';
import publicCatalog from '../../apps/ui/messages/en/public.json';
const enrollmentBrowser=vi.hoisted(()=>({register:vi.fn().mockResolvedValue({}),cancel:vi.fn()}));
vi.mock('@/lib/consumerWebAuthn',()=>({createConsumerWebAuthnBrowser:()=>enrollmentBrowser}));
let root:Root;
const factor='11111111-1111-4111-8111-111111111111';
const proof=(action:any,target:any={})=>({status:'step_up_complete',csrf_token:'c'.repeat(43),step_up_grant:{token:'g'.repeat(43),action,...target,expires_at:new Date(Date.now()+300000).toISOString()}});
const client=()=>({ authMethods:vi.fn().mockResolvedValue({methods:[{factor_id:factor,type:'passkey',label:'My key',created_at:'2026-10-01T10:00:00Z',last_used_at:null,removable:false}],recovery_codes_remaining:10,available_step_up_methods:['passkey'],step_up_providers:[]}), phoneProfile:vi.fn().mockResolvedValue({phone_present:true,phone_masked:'+40 ••• 678',phone_verified:false,updated_at:null}), recoveryEmail:vi.fn().mockResolvedValue({state:'absent',email:null,pending:null}), authProviders:vi.fn().mockResolvedValue({providers:[]}),linkedSocialProviders:vi.fn().mockResolvedValue({providers:[]}),removeAuthMethod:vi.fn().mockResolvedValue(undefined),listSessions:vi.fn().mockResolvedValue({sessions:[]}),logout:vi.fn(),revokeAllSessions:vi.fn(),revokeSession:vi.fn(),pendingMfaRecovery:vi.fn().mockResolvedValue({pending:null}),cancelPendingMfaRecovery:vi.fn().mockResolvedValue({status:'cancelled'})});
beforeEach(()=>{vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);document.body.innerHTML='<div id="root"></div>';root=createRoot(document.getElementById('root')!);});
afterEach(async()=>{await act(async()=>root.unmount());vi.unstubAllGlobals();});
async function mount(c:any,resume?:any){expect(existsSync('apps/ui/components/SecuritySettings.tsx')).toBe(true);const {SecuritySettings}=await import(/* @vite-ignore */ '../../apps/ui/components/' + 'SecuritySettings.tsx');await act(async()=>root.render(<StrictMode><SecuritySettings client={c} catalog={settings} authCatalog={auth} publicCatalog={publicCatalog} locale="en" resume={resume}/></StrictMode>));}
it('keeps active sessions and prevents removing the advertised last method',async()=>{const c=client();await mount(c);expect(document.body.textContent).toContain('Active sessions');expect(document.querySelector<HTMLButtonElement>('[data-remove-factor]')?.disabled).toBe(true);expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('a resumed exact factor proof waits for explicit operation confirmation and consumes the exact target once',async()=>{const c=client(); c.authMethods.mockResolvedValue({...await c.authMethods(),methods:[{factor_id:factor,type:'passkey',label:'My key',created_at:'2026-10-01T10:00:00Z',last_used_at:null,removable:true}]}); await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof:proof('REMOVE_AUTH_METHOD',{target_factor_id:factor})}); expect(c.removeAuthMethod).not.toHaveBeenCalled(); const button=document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!;expect(button).not.toBeNull();await act(async()=>{button.click();button.click();});expect(c.removeAuthMethod).toHaveBeenCalledTimes(1);expect(c.removeAuthMethod).toHaveBeenCalledWith(factor,'g'.repeat(43));});
it('expired and wrong-target resume proofs never remove a method',async()=>{const c=client(); await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof:proof('REMOVE_AUTH_METHOD',{target_factor_id:'22222222-2222-4222-8222-222222222222'})});expect(document.querySelector('[data-resumed-confirm]')).toBeNull();expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('an ADD_PASSKEY proof exposes only its authorized ceremony and never borrows it for TOTP',async()=>{const c={...client(),beginPasskeyEnrollment:vi.fn(),beginTotpEnrollment:vi.fn()};await mount(c,{authorization:{action:'ADD_PASSKEY'},initialProof:proof('ADD_PASSKEY')});await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());const panel=document.querySelector('section[aria-label="Protect your account"]');expect(panel?.textContent).toContain('Create a passkey');expect(panel?.textContent).not.toContain('Use an authenticator app instead');expect(c.beginTotpEnrollment).not.toHaveBeenCalled();});
it('an actually expired original proof cannot expose a resumed operation',async()=>{const c=client();const initialProof=proof('REMOVE_AUTH_METHOD',{target_factor_id:factor});initialProof.step_up_grant.expires_at=new Date(Date.now()-1).toISOString();await mount(c,{authorization:{action:'REMOVE_AUTH_METHOD',target_factor_id:factor},initialProof});expect(document.querySelector('[data-resumed-confirm]')).toBeNull();expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('canceling confirmation does not lose a pending safe metadata read',async()=>{const c=client();const data=await c.authMethods();let resolve!: (value:typeof data)=>void;const pending=new Promise<typeof data>(r=>resolve=r);c.authMethods.mockReturnValue(pending);await mount(c);const add=[...document.querySelectorAll('button')].find(x=>x.textContent==='Create a passkey')!;await act(async()=>add.click());const cancel=[...document.querySelectorAll('button')].find(x=>x.textContent==='Cancel')!;await act(async()=>cancel.click());await act(async()=>resolve(data));expect(document.body.textContent).toContain('My key');expect(c.removeAuthMethod).not.toHaveBeenCalled();});
it('does not fabricate a recovery-code count while safe metadata is pending',async()=>{const c=client();const data=await c.authMethods();let resolve!:(value:typeof data)=>void;c.authMethods.mockReturnValue(new Promise<typeof data>(r=>resolve=r));await mount(c);expect(document.body.textContent).not.toContain('Recovery codes: 0');const button=[...document.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent==='Generate new recovery codes')!;expect(button.disabled).toBe(true);await act(async()=>resolve(data));expect(document.body.textContent).toContain('Recovery codes: 10');});

it('successful enrollment remains successful when metadata refresh rejects with localized feedback',async()=>{const c={...client(),beginPasskeyEnrollment:vi.fn().mockResolvedValue({challenge_handle:'p'.repeat(43),options:{}}),completePasskeyEnrollment:vi.fn().mockResolvedValue({status:'enrolled'})};await mount(c,{authorization:{action:'ADD_PASSKEY'},initialProof:proof('ADD_PASSKEY')});await act(async()=>document.querySelector<HTMLButtonElement>('[data-resumed-confirm]')!.click());c.authMethods.mockRejectedValueOnce(new Error('PRIVATE_REFRESH_FAILURE'));const panel=document.querySelector('section[aria-label="Protect your account"]')!;await act(async()=>[...panel.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent==='Create a passkey')!.click());expect(c.completePasskeyEnrollment).toHaveBeenCalledTimes(1);expect(document.querySelector('[role=status]')?.textContent).toContain('Account protected');expect(document.querySelector('[role=alert]')?.textContent).toContain('Security details');expect(document.body.textContent).not.toContain('PRIVATE_REFRESH_FAILURE');expect(document.body.textContent).not.toContain('The enrolment service is temporarily unavailable');});

// Owner ruling 2026-10-09: Settings says what the phone is for, beside the format help. Sign-up still
// asks for a phone on this branch, so the line never calls it optional (the DB batch makes it so).
const PHONE_PURPOSE='Later, we may text you a code to help you get back into your account, and if you ask us for help we can call or text you. Stored encrypted; never shared or used for marketing.';
it('the phone card says what the phone is for, beside the format help, without calling it optional',async()=>{await mount(client());expect(document.body.textContent).toContain(PHONE_PURPOSE);expect(document.body.textContent).not.toMatch(/optional/i);expect(document.body.textContent).toContain('Include the international prefix');expect(document.body.textContent).not.toContain('Add your phone to continue');});
// Owner ruling 2026-10-09 ("don't get locked out"): a reminder while the account has neither recovery codes nor a passkey.
const LOCKOUT_REMINDER='You have no recovery codes or passkey yet. If you lose your phone, they let you back in straight away.';
const totpOnly=(codes:number)=>({methods:[{factor_id:factor,type:'totp',label:null,created_at:'2026-10-01T10:00:00Z',last_used_at:null,removable:false}],recovery_codes_remaining:codes,available_step_up_methods:['password_totp'],step_up_providers:[]});
it('Security reminds a person who has neither recovery codes nor a passkey',async()=>{const c=client();c.authMethods.mockResolvedValue(totpOnly(0));await mount(c);expect(document.body.textContent).toContain(LOCKOUT_REMINDER);});
it('Security shows no reminder once recovery codes exist',async()=>{const c=client();c.authMethods.mockResolvedValue(totpOnly(10));await mount(c);expect(document.body.textContent).toContain('Recovery codes');expect(document.body.textContent).not.toContain(LOCKOUT_REMINDER);});
it('Security shows no reminder once a passkey exists, even without codes',async()=>{const c=client();c.authMethods.mockResolvedValue({...await c.authMethods(),recovery_codes_remaining:0});await mount(c);expect(document.body.textContent).not.toContain(LOCKOUT_REMINDER);});
it('Security shows no reminder while the methods are still loading',async()=>{const c=client();c.authMethods.mockReturnValue(new Promise(()=>{}));await mount(c);expect(document.body.textContent).not.toContain(LOCKOUT_REMINDER);});

// Owner ruling 2026-10-09: an authenticator recovery waiting its 24 hours shows here, and any signed-in session can cancel it.
// Review M2 2026-10-09: the banner says from when it can be finished (it never finishes by itself), so the time is relative to now.
const NOT_BEFORE=new Date(Date.now()+6*3600000).toISOString();
const pendingClient=()=>{const c=client();c.pendingMfaRecovery.mockResolvedValue({pending:{not_before:NOT_BEFORE,started_at:'2026-10-09T12:00:00.000Z'}});return c;};
const banner=()=>document.querySelector<HTMLElement>('[data-pending-recovery]');
it('Security shows a waiting authenticator recovery in plain words, with when it can be finished',async()=>{await mount(pendingClient());expect(banner()).not.toBeNull();expect(banner()!.textContent).toContain(settings['settings.security.pendingRecovery.title']);expect(banner()!.textContent).toContain('You can finish it from ');expect(banner()!.textContent).not.toContain('It finishes at');expect(banner()!.textContent).not.toContain('You can finish it now');expect(banner()!.textContent).toContain('Until it is finished, your current authenticator');expect(banner()!.textContent).toContain(new Intl.DateTimeFormat('en',{dateStyle:'medium',timeStyle:'short'}).format(new Date(NOT_BEFORE)));expect(banner()!.textContent).toContain("If this wasn't you, cancel it.");expect(banner()!.querySelector('time')?.getAttribute('datetime')).toBe(NOT_BEFORE);});
it('once the 24 hours are over, the banner says it can be finished now from the emailed link, with no time',async()=>{const c=client();c.pendingMfaRecovery.mockResolvedValue({pending:{not_before:new Date(Date.now()-60000).toISOString(),started_at:new Date(Date.now()-86460000).toISOString()}});await mount(c);expect(banner()!.textContent).toContain('You can finish it now — use the link in your email.');expect(banner()!.textContent).not.toContain('You can finish it from');expect(banner()!.querySelector('time')).toBeNull();expect(banner()!.textContent).toContain("If this wasn't you, cancel it.");});
it('Security shows no recovery banner when nothing is waiting',async()=>{const c=client();await mount(c);expect(c.pendingMfaRecovery).toHaveBeenCalled();expect(banner()).toBeNull();});
it('Cancel stops the waiting recovery once and says so',async()=>{const c=pendingClient();await mount(c);const button=[...banner()!.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent===settings['settings.security.pendingRecovery.cancel'])!;expect(button).toBeDefined();await act(async()=>{button.click();button.click();});expect(c.cancelPendingMfaRecovery).toHaveBeenCalledTimes(1);expect(banner()).toBeNull();expect(document.body.textContent).toContain('Recovery cancelled.');});
it('a failed cancel keeps the banner and says what to do',async()=>{const c=pendingClient();c.cancelPendingMfaRecovery.mockRejectedValue(new Error('PRIVATE_FAILURE'));await mount(c);await act(async()=>[...banner()!.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent===settings['settings.security.pendingRecovery.cancel'])!.click());expect(banner()).not.toBeNull();expect(document.body.textContent).toContain(settings['settings.security.pendingRecovery.failed']);expect(document.body.textContent).not.toContain('PRIVATE_FAILURE');});
it('a recovery that already ended by the time of Cancel just disappears',async()=>{const c=pendingClient();const {ContractHttpError}=await import('../../packages/contract/src/http-error.js');c.cancelPendingMfaRecovery.mockRejectedValue(new ContractHttpError('UNPROCESSABLE',409,'gone','MFA_ENROLLMENT_STATE_INVALID'));await mount(c);c.pendingMfaRecovery.mockResolvedValue({pending:null});await act(async()=>[...banner()!.querySelectorAll<HTMLButtonElement>('button')].find(x=>x.textContent===settings['settings.security.pendingRecovery.cancel'])!.click());expect(banner()).toBeNull();expect(document.body.textContent).not.toContain(settings['settings.security.pendingRecovery.failed']);});
