// @vitest-environment jsdom
import {expect,it,vi} from "vitest";
import {SecurityEnrollment} from "../../apps/ui/components/auth/SecurityEnrollment.js";
import {mount,unmount,click} from "./task11-harness.js";
it("prefers passkey, cancellation keeps authenticator fallback and enrollment needs no TOTP",async()=>{const client={beginPasskeyEnrollment:vi.fn().mockResolvedValue({challenge_handle:"a".repeat(43),options:{}}),completePasskeyEnrollment:vi.fn().mockResolvedValue({status:"authenticated"}),beginTotpEnrollment:vi.fn()};const browser={register:vi.fn().mockRejectedValue(new DOMException("cancel","NotAllowedError")),cancel:vi.fn()};const authenticated=vi.fn();const {host,root}=await mount(<SecurityEnrollment authority={{kind:"pending",token:"b".repeat(43)}} client={client as any} browser={browser as any} onAuthenticated={authenticated}/>);try{await click(host,"Create a passkey");expect(authenticated).not.toHaveBeenCalled();expect(host.textContent).toContain("Use an authenticator app instead");browser.register.mockResolvedValue({});await click(host,"Create a passkey");expect(authenticated).toHaveBeenCalledOnce();expect(client.beginTotpEnrollment).not.toHaveBeenCalled();}finally{await unmount(root,host);}});
import {act} from 'react';
it('clears obsolete seed and code when enrollment authority changes and enrolled output does not authenticate',async()=>{const client={beginTotpEnrollment:vi.fn().mockResolvedValue({enrollment_token:'c'.repeat(43),secret:'A'.repeat(32),otpauthUri:'otpauth://totp/test?secret='+ 'A'.repeat(32),expires_at:new Date(Date.now()+300000).toISOString()}),completeTotpEnrollment:vi.fn().mockResolvedValue({status:'enrolled'})};const authenticated=vi.fn(),added=vi.fn();const {host,root}=await mount(<SecurityEnrollment authority={{kind:'pending',token:'a'.repeat(43)}} client={client as any} onAuthenticated={authenticated} onEnrolled={added}/>);try{await click(host,'Use an authenticator app instead');expect(host.querySelector('input[name=code]')).not.toBeNull();await act(async()=>root.render(<SecurityEnrollment authority={{kind:'pending',token:'b'.repeat(43)}} client={client as any} onAuthenticated={authenticated} onEnrolled={added}/>));expect(host.querySelector('input[name=code]')).toBeNull();await click(host,'Use an authenticator app instead');const field=host.querySelector<HTMLInputElement>('input[name=code]')!;await act(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(field,'123456');field.dispatchEvent(new Event('input',{bubbles:true}));});expect(added).toHaveBeenCalledOnce();expect(authenticated).not.toHaveBeenCalled();}finally{await unmount(root,host);}});
it('initial authenticated activation returns directly without a completion-card click',async()=>{const client={beginPasskeyEnrollment:vi.fn().mockResolvedValue({challenge_handle:'a'.repeat(43),options:{}}),completePasskeyEnrollment:vi.fn().mockResolvedValue({status:'authenticated'})},browser={register:vi.fn().mockResolvedValue({}),cancel:vi.fn()},done=vi.fn();const {host,root}=await mount(<SecurityEnrollment authority={{kind:'pending',token:'b'.repeat(43)}} client={client as any} browser={browser as any} onAuthenticated={done}/>);try{await click(host,'Create a passkey');expect(done).toHaveBeenCalledOnce();expect(host.textContent).not.toContain('Continue');}finally{await unmount(root,host);}});

it('initial passkey activation keeps a dispatched success when another method is clicked',async()=>{
 let release!:(v:any)=>void;const pending=new Promise(r=>release=r),done=vi.fn();const client={beginPasskeyEnrollment:async()=>({challenge_handle:'a'.repeat(43),options:{}}),completePasskeyEnrollment:()=>pending,beginTotpEnrollment:vi.fn()},browser={register:async()=>({}),cancel:vi.fn()};
 const {host,root}=await mount(<SecurityEnrollment authority={{kind:'pending',token:'b'.repeat(43)}} client={client as any} browser={browser as any} onAuthenticated={done}/>);
 try{await click(host,'Create a passkey');expect([...host.querySelectorAll('button')].find(b=>b.textContent==='Use an authenticator app instead')?.disabled).toBe(true);await click(host,'Use an authenticator app instead');await act(async()=>release({status:'authenticated'}));expect(done).toHaveBeenCalledOnce();expect(client.beginTotpEnrollment).not.toHaveBeenCalled();}finally{await unmount(root,host);}
});
