// @vitest-environment jsdom
import {StrictMode,act} from 'react';
import {expect,it,vi} from 'vitest';
import {SecurityConfirmation} from '../../apps/ui/components/auth/SecurityConfirmation.js';
import {SecurityActionResume} from '../../apps/ui/components/auth/SecurityActionResume.js';
import auth from '../../apps/ui/messages/en/auth.json';
import settings from '../../apps/ui/messages/en/settings.json';
import pub from '../../apps/ui/messages/en/public.json';
import {mount,unmount,click} from './task11-harness.js';
const run='11111111-1111-4111-8111-111111111111';
const grant=(target=run)=>({status:'step_up_complete',csrf_token:'c'.repeat(43),step_up_grant:{action:'PUBLISH',target_run_id:target,token:'g'.repeat(43),expires_at:new Date(Date.now()+300000).toISOString()}});
it('passkey-only confirmation supplies exact action-target and rotation result without password or TOTP',async()=>{const done=vi.fn(),client={authMethods:vi.fn().mockResolvedValue({methods:[],recovery_codes_remaining:0,available_step_up_methods:['passkey'],step_up_providers:[]}),beginPasskeyStepUp:vi.fn().mockResolvedValue({options:{},challenge_handle:'a'.repeat(43)}),completePasskeyStepUp:vi.fn().mockResolvedValue(grant())},browser={authenticate:vi.fn().mockResolvedValue({}),cancel:vi.fn()};const {host,root}=await mount(<SecurityConfirmation catalog={auth} authorization={{action:'PUBLISH',target_run_id:run}} client={client as any} browser={browser as any} onConfirmed={done}/>);try{expect(host.querySelector('input')).toBeNull();await click(host,'Use a passkey');expect(client.beginPasskeyStepUp).toHaveBeenCalledWith({action:'PUBLISH',target_run_id:run});expect(done).toHaveBeenCalledOnce();expect(done.mock.calls[0]![0].step_up_grant.target_run_id).toBe(run);}finally{await unmount(root,host);}});
it('rejects wrong-target, missing and expired proof before the operation',async()=>{for(const result of [grant('22222222-2222-4222-8222-222222222222'),{...grant(),step_up_grant:undefined},{...grant(),step_up_grant:{...grant().step_up_grant,expires_at:new Date(Date.now()-1).toISOString()}}]){const done=vi.fn();const {host,root}=await mount(<SecurityConfirmation catalog={auth} authorization={{action:'PUBLISH',target_run_id:run}} initialProof={result as any} client={{authMethods:vi.fn().mockResolvedValue({methods:[],available_step_up_methods:[],step_up_providers:[],recovery_codes_remaining:0})}} onConfirmed={done}/>);try{await click(host,'Confirm action');expect(done).not.toHaveBeenCalled();}finally{await unmount(root,host);}}});
it('provider resume takes once under StrictMode, never auto-executes and cannot replay the same action',async()=>{const take=vi.fn().mockReturnValue(grant()),publish=vi.fn().mockResolvedValue({state:'PUBLISHED',public_ref:'ref'}),client={authMethods:vi.fn().mockResolvedValue({methods:[],available_step_up_methods:[],step_up_providers:[],recovery_codes_remaining:0}),publishRun:publish};const {host,root}=await mount(<StrictMode><SecurityActionResume catalog={auth} settingsCatalog={settings} publicCatalog={pub} locale="en" takeProof={take as any} client={client as any}/></StrictMode>);try{expect(take).toHaveBeenCalledOnce();expect(publish).not.toHaveBeenCalled();await act(async()=>host.querySelector<HTMLInputElement>('input[type=checkbox]')!.click());await act(async()=>{const button=[...host.querySelectorAll<HTMLButtonElement>('button')].find(b=>b.textContent==='Confirm action')!;button.click();button.click();});expect(publish).toHaveBeenCalledOnce();expect(publish).toHaveBeenCalledWith(run,'g'.repeat(43));}finally{await unmount(root,host);}});
it('exposes the exact typed Task12 onResume handoff and discards expired original deadlines',async()=>{const result={...grant(),step_up_grant:{...grant().step_up_grant,action:'ADD_PASSKEY',target_run_id:undefined}},handler=vi.fn();delete result.step_up_grant.target_run_id;const {host,root}=await mount(<SecurityActionResume catalog={auth} settingsCatalog={settings} publicCatalog={pub} locale="en" takeProof={()=>result as any} client={{authMethods:vi.fn().mockResolvedValue({methods:[],available_step_up_methods:[],step_up_providers:[],recovery_codes_remaining:0})} as any} onResume={handler}/>);try{expect(handler).not.toHaveBeenCalled();await click(host,'Confirm action');expect(handler).toHaveBeenCalledWith({action:'ADD_PASSKEY'},expect.objectContaining({step_up_grant:expect.objectContaining({token:'g'.repeat(43),action:'ADD_PASSKEY'})}));}finally{await unmount(root,host);}});
it('original provider grant expiry removes confirmation without executing and retains optional replacement code',async()=>{vi.useFakeTimers();const value={...grant(),replacement_recovery_code:'OPTIONAL-RESTART',step_up_grant:{...grant().step_up_grant,expires_at:new Date(Date.now()+1000).toISOString()}},publish=vi.fn(),client={authMethods:vi.fn().mockResolvedValue({methods:[],available_step_up_methods:[],step_up_providers:[],recovery_codes_remaining:0}),publishRun:publish};const {host,root}=await mount(<SecurityActionResume catalog={auth} settingsCatalog={settings} publicCatalog={pub} locale="en" takeProof={()=>value as any} client={client as any}/>);try{await act(async()=>vi.advanceTimersByTime(1001));expect([...host.querySelectorAll('button')].find(b=>b.textContent==='Confirm action')).toBeUndefined();expect(host.textContent).toContain('OPTIONAL-RESTART');expect(publish).not.toHaveBeenCalled();}finally{await unmount(root,host);vi.useRealTimers();}});
it('cancels an explicit browser proof on unmount and ignores its late resolve',async()=>{let resolve:(value:any)=>void=()=>{};const browser={authenticate:vi.fn().mockReturnValue(new Promise(r=>resolve=r)),cancel:vi.fn()},client={authMethods:vi.fn().mockResolvedValue({methods:[],recovery_codes_remaining:0,available_step_up_methods:['passkey'],step_up_providers:[]}),beginPasskeyStepUp:vi.fn().mockResolvedValue({options:{},challenge_handle:'a'.repeat(43)}),completePasskeyStepUp:vi.fn()},done=vi.fn();const {host,root}=await mount(<SecurityConfirmation catalog={auth} authorization={{action:'PUBLISH',target_run_id:run}} client={client as any} browser={browser as any} onConfirmed={done}/>);await click(host,'Use a passkey');await act(async()=>root.unmount());await act(async()=>resolve({}));expect(browser.cancel).toHaveBeenCalled();expect(client.completePasskeyStepUp).not.toHaveBeenCalled();expect(done).not.toHaveBeenCalled();host.remove();vi.unstubAllGlobals();});
