import { z } from 'zod';
import { RegisterRequestSchema, RegistrationVerificationAckSchema } from './consumer-auth.js';
export const SocialProviderSchema = z.enum(['google', 'apple', 'facebook', 'x']);
const Handle = z.string().regex(/^[A-Za-z0-9_-]{43}$/);
export const AuthProvidersResponseSchema = z.object({ providers: z.array(z.object({ id: SocialProviderSchema, name: z.enum(['Google', 'Apple', 'Facebook', 'X']) }).strict()).max(4) }).strict();
export const BeginSocialLoginRequestSchema = z.object({ next: z.enum(['/', '/new', '/settings', '/settings/security', '/account']).optional() }).strict();
export const BeginSocialLinkRequestSchema = BeginSocialLoginRequestSchema.extend({ step_up_grant: Handle }).strict();
export const BeginSocialLoginResponseSchema = z.object({ authorization_url: z.url().max(4096) }).strict();
export const SocialSignupStatusRequestSchema = z.object({ continuation_token: Handle }).strict();
export const SocialSignupStatusResponseSchema = z.object({ provider: SocialProviderSchema, email: z.email().max(254).nullable(), name: z.string().max(256).nullable(), expires_at: z.iso.datetime() }).strict();
export const CompleteSocialSignupRequestSchema = RegisterRequestSchema.omit({ password: true }).extend({ continuation_token: Handle }).strict();
export const CompleteSocialSignupResponseSchema = z.union([RegistrationVerificationAckSchema, z.object({ status: z.literal('mfa_required'), enrollment_token: Handle, expires_at: z.iso.datetime() }).strict()]);
export const UnlinkSocialProviderRequestSchema = z.object({ provider: SocialProviderSchema, step_up_grant: Handle }).strict();
export const SocialLinksResponseSchema = z.object({ providers: z.array(z.object({ provider: SocialProviderSchema, linked_at: z.iso.datetime(), removable: z.boolean() }).strict()).max(4) }).strict();
export type CompleteSocialSignupRequest = z.infer<typeof CompleteSocialSignupRequestSchema>;
export type CompleteSocialSignupResponse = z.infer<typeof CompleteSocialSignupResponseSchema>;
export type AuthProvidersResponse = z.infer<typeof AuthProvidersResponseSchema>;
export type SocialSignupStatusResponse = z.infer<typeof SocialSignupStatusResponseSchema>;
export type SocialLinksResponse = z.infer<typeof SocialLinksResponseSchema>;
export const socialAuthContractSchemas = { AuthProvidersResponse: AuthProvidersResponseSchema, BeginSocialLoginRequest: BeginSocialLoginRequestSchema, BeginSocialLinkRequest: BeginSocialLinkRequestSchema, BeginSocialLoginResponse: BeginSocialLoginResponseSchema, SocialSignupStatusRequest: SocialSignupStatusRequestSchema, SocialSignupStatusResponse: SocialSignupStatusResponseSchema, CompleteSocialSignupRequest: CompleteSocialSignupRequestSchema, CompleteSocialSignupResponse: CompleteSocialSignupResponseSchema, UnlinkSocialProviderRequest: UnlinkSocialProviderRequestSchema, SocialLinksResponse: SocialLinksResponseSchema };
