import type { SupportCapability } from "./catalog.js";
import type { SupportLanguage } from "./locale.js";
import { SUPPORT_CAPABILITY_KEY_NAMES } from "./ui-labels.js";

/**
 * cookie-compliance S05 (SPEC-v5 R13, V-22): the 10 capability ids no screen element names (TRANSLATE rows). Paid plans
 * (P24, merge with #62) add the four paid-plan pages no screen link names: the checkout (reached only by the pricing
 * cards' per-plan "Choose {plan}"), its return page (reached from the bank) and the two archived texts (reached by the
 * versions lists' generic "Read").
 */
export const SUPPORT_TRANSLATED_CAPABILITY_IDS = Object.freeze([
  "product-identity", "home-library", "new-debate", "owner-debate", "public-debate",
  "help-desk", "sign-in", "verify-email", "enroll-mfa", "operator-workers",
  "billing-checkout", "billing-checkout-return", "legal-terms-version-text", "legal-privacy-version-text",
] as const);
export type SupportTranslatedCapabilityId = (typeof SUPPORT_TRANSLATED_CAPABILITY_IDS)[number];
type OtherLanguage = Exclude<SupportLanguage, "en" | "ro">;

/**
 * The name of each TRANSLATE-row product area in each of the 33 locales without their own help texts, written by hand
 * (V-22: never a mechanical swap of control labels; not in catalog.ts, S02's signed bytes; not in apps/ui/messages, the
 * oracle). One entry per locale, each with all 14 ids; checked by S05's checker (CAPABILITY ENGLISH / MECHANICAL /
 * SCRIPT, FOREIGN) and by tests/unit/support-capability-names.test.ts. The four paid-plan names (P24) use the words the
 * locale's own billing and legal screens use for subscription, card, terms and privacy policy.
 */
export const SUPPORT_CAPABILITY_TRANSLATIONS: Readonly<Partial<Record<OtherLanguage, Readonly<Record<SupportTranslatedCapabilityId, string>>>>> = Object.freeze({
  ar: Object.freeze({
    "product-identity": "حول Dialectical Engine",
    "home-library": "الصفحة الرئيسية ومكتبة المناظرات",
    "new-debate": "إنشاء مناظرة بخيارات الخطة",
    "owner-debate": "مساحة عمل المناظرة الخاصة بالمالك",
    "public-debate": "مناظرة منشورة",
    "help-desk": "محادثات الدعم والحالات التي يتولاها موظف",
    "sign-in": "تسجيل الدخول واسترداد MFA المحفوظ",
    "verify-email": "حالة التحقق من البريد الإلكتروني",
    "enroll-mfa": "حالة التسجيل في MFA",
    "operator-workers": "عرض العمليات للمشغّلين فقط",
    "billing-checkout": "نموذج البطاقة للاشتراك",
    "billing-checkout-return": "تأكيد الاشتراك",
    "legal-terms-version-text": "نسخة سابقة من الشروط",
    "legal-privacy-version-text": "نسخة سابقة من سياسة الخصوصية",
  }),
  bg: Object.freeze({
    "product-identity": "За Dialectical Engine",
    "home-library": "Начална страница и библиотека с дебати",
    "new-debate": "Създаване на дебат с настройките на плана",
    "owner-debate": "Работно пространство на собственика на дебата",
    "public-debate": "Публикуван дебат",
    "help-desk": "Разговори с поддръжката и случаи с човек",
    "sign-in": "Вход и запазено възстановяване на MFA",
    "verify-email": "Състояние на потвърждението на имейла",
    "enroll-mfa": "Състояние на регистрацията за MFA",
    "operator-workers": "Изглед на процесите само за оператори",
    "billing-checkout": "Формуляр на картата за абонамента",
    "billing-checkout-return": "Потвърждение на абонамента",
    "legal-terms-version-text": "Предишна версия на условията",
    "legal-privacy-version-text": "Предишна версия на политиката за поверителност",
  }),
  cs: Object.freeze({
    "product-identity": "O Dialectical Engine",
    "home-library": "Domovská stránka a knihovna debat",
    "new-debate": "Vytvoření debaty s možnostmi plánu",
    "owner-debate": "Pracovní prostor vlastníka debaty",
    "public-debate": "Zveřejněná debata",
    "help-desk": "Konverzace s podporou a případy řešené člověkem",
    "sign-in": "Přihlášení a uložené obnovení MFA",
    "verify-email": "Stav ověření e-mailu",
    "enroll-mfa": "Stav registrace MFA",
    "operator-workers": "Přehled procesů pouze pro operátory",
    "billing-checkout": "Formulář karty pro předplatné",
    "billing-checkout-return": "Potvrzení předplatného",
    "legal-terms-version-text": "Dřívější verze podmínek",
    "legal-privacy-version-text": "Dřívější verze zásad ochrany osobních údajů",
  }),
  da: Object.freeze({
    "product-identity": "Om Dialectical Engine",
    "home-library": "Forside og debatbibliotek",
    "new-debate": "Opret en debat med planens indstillinger",
    "owner-debate": "Debatejerens arbejdsområde",
    "public-debate": "Offentliggjort debat",
    "help-desk": "Supportsamtaler og sager til en medarbejder",
    "sign-in": "Indlogning og gemt MFA-gendannelse",
    "verify-email": "Status for e-mailbekræftelse",
    "enroll-mfa": "Status for MFA-tilmelding",
    "operator-workers": "Visning af baggrundsprocesser kun for operatører",
    "billing-checkout": "Kortformular til abonnementet",
    "billing-checkout-return": "Bekræftelse af abonnementet",
    "legal-terms-version-text": "En tidligere version af vilkårene",
    "legal-privacy-version-text": "En tidligere version af privatlivspolitikken",
  }),
  de: Object.freeze({
    "product-identity": "Über Dialectical Engine",
    "home-library": "Startseite und Debattenbibliothek",
    "new-debate": "Debatte mit Tarifoptionen erstellen",
    "owner-debate": "Arbeitsbereich des Debatteneigentümers",
    "public-debate": "Veröffentlichte Debatte",
    "help-desk": "Support-Gespräche und Fälle mit menschlicher Betreuung",
    "sign-in": "Anmeldung und gespeicherte MFA-Wiederherstellung",
    "verify-email": "Status der E-Mail-Bestätigung",
    "enroll-mfa": "Status der MFA-Einrichtung",
    "operator-workers": "Prozessansicht nur für Betreiber",
    "billing-checkout": "Kartenformular für das Abonnement",
    "billing-checkout-return": "Bestätigung des Abonnements",
    "legal-terms-version-text": "Eine frühere Fassung der Nutzungsbedingungen",
    "legal-privacy-version-text": "Eine frühere Fassung der Datenschutzerklärung",
  }),
  el: Object.freeze({
    "product-identity": "Σχετικά με το Dialectical Engine",
    "home-library": "Αρχική σελίδα και βιβλιοθήκη αντιπαραθέσεων",
    "new-debate": "Δημιουργία αντιπαράθεσης με τις επιλογές του προγράμματος",
    "owner-debate": "Χώρος εργασίας του κατόχου της αντιπαράθεσης",
    "public-debate": "Δημοσιευμένη αντιπαράθεση",
    "help-desk": "Συνομιλίες υποστήριξης και υποθέσεις με άνθρωπο",
    "sign-in": "Σύνδεση και αποθηκευμένη ανάκτηση MFA",
    "verify-email": "Κατάσταση επαλήθευσης ηλεκτρονικού ταχυδρομείου",
    "enroll-mfa": "Κατάσταση εγγραφής MFA",
    "operator-workers": "Προβολή διεργασιών μόνο για διαχειριστές",
    "billing-checkout": "Φόρμα κάρτας για τη συνδρομή",
    "billing-checkout-return": "Επιβεβαίωση της συνδρομής",
    "legal-terms-version-text": "Μια παλαιότερη έκδοση των όρων",
    "legal-privacy-version-text": "Μια παλαιότερη έκδοση της πολιτικής απορρήτου",
  }),
  es: Object.freeze({
    "product-identity": "Acerca de Dialectical Engine",
    "home-library": "Inicio y biblioteca de debates",
    "new-debate": "Crear un debate con las opciones del plan",
    "owner-debate": "Espacio de trabajo del propietario del debate",
    "public-debate": "Debate publicado",
    "help-desk": "Conversaciones de soporte y casos atendidos por personas",
    "sign-in": "Inicio de sesión y recuperación MFA guardada",
    "verify-email": "Estado de verificación del correo electrónico",
    "enroll-mfa": "Estado de inscripción en MFA",
    "operator-workers": "Vista de procesos solo para operadores",
    "billing-checkout": "Formulario de tarjeta para la suscripción",
    "billing-checkout-return": "Confirmación de la suscripción",
    "legal-terms-version-text": "Una versión anterior de los términos",
    "legal-privacy-version-text": "Una versión anterior de la política de privacidad",
  }),
  et: Object.freeze({
    "product-identity": "Teave Dialectical Engine'i kohta",
    "home-library": "Avaleht ja väitluste raamatukogu",
    "new-debate": "Väitluse loomine paketi valikutega",
    "owner-debate": "Väitluse omaniku tööruum",
    "public-debate": "Avaldatud väitlus",
    "help-desk": "Tugivestlused ja inimese käsitletavad juhtumid",
    "sign-in": "Sisselogimine ja salvestatud MFA taastamine",
    "verify-email": "E-posti kinnitamise olek",
    "enroll-mfa": "MFA registreerimise olek",
    "operator-workers": "Ainult operaatoritele mõeldud protsesside vaade",
    "billing-checkout": "Tellimuse kaardivorm",
    "billing-checkout-return": "Tellimuse kinnitus",
    "legal-terms-version-text": "Tingimuste varasem versioon",
    "legal-privacy-version-text": "Privaatsuspoliitika varasem versioon",
  }),
  fi: Object.freeze({
    "product-identity": "Tietoa Dialectical Enginestä",
    "home-library": "Etusivu ja väittelykirjasto",
    "new-debate": "Väittelyn luominen tilauksen asetuksilla",
    "owner-debate": "Väittelyn omistajan työtila",
    "public-debate": "Julkaistu väittely",
    "help-desk": "Tukikeskustelut ja henkilön käsittelemät tapaukset",
    "sign-in": "Kirjautuminen ja tallennettu MFA-palautus",
    "verify-email": "Sähköpostin vahvistuksen tila",
    "enroll-mfa": "MFA-käyttöönoton tila",
    "operator-workers": "Vain ylläpitäjille tarkoitettu prosessinäkymä",
    "billing-checkout": "Tilauksen korttilomake",
    "billing-checkout-return": "Tilauksen vahvistus",
    "legal-terms-version-text": "Käyttöehtojen aiempi versio",
    "legal-privacy-version-text": "Tietosuojakäytännön aiempi versio",
  }),
  fr: Object.freeze({
    "product-identity": "À propos de Dialectical Engine",
    "home-library": "Accueil et bibliothèque de débats",
    "new-debate": "Créer un débat avec les options de la formule",
    "owner-debate": "Espace de travail du propriétaire du débat",
    "public-debate": "Débat publié",
    "help-desk": "Conversations d’assistance et dossiers traités par une personne",
    "sign-in": "Connexion et récupération MFA enregistrée",
    "verify-email": "État de la vérification de l’e-mail",
    "enroll-mfa": "État de l’inscription MFA",
    "operator-workers": "Vue des processus réservée aux opérateurs",
    "billing-checkout": "Formulaire de carte pour l’abonnement",
    "billing-checkout-return": "Confirmation de l’abonnement",
    "legal-terms-version-text": "Une version antérieure des conditions d’utilisation",
    "legal-privacy-version-text": "Une version antérieure de la politique de confidentialité",
  }),
  ga: Object.freeze({
    "product-identity": "Faoi Dialectical Engine",
    "home-library": "Baile agus leabharlann díospóireachtaí",
    "new-debate": "Díospóireacht a chruthú le roghanna an phlean",
    "owner-debate": "Spás oibre úinéir na díospóireachta",
    "public-debate": "Díospóireacht foilsithe",
    "help-desk": "Comhráite tacaíochta agus cásanna le duine",
    "sign-in": "Síniú isteach agus aisghabháil MFA sábháilte",
    "verify-email": "Staid fhíorú an ríomhphoist",
    "enroll-mfa": "Staid chlárú MFA",
    "operator-workers": "Amharc próiseas d’oibreoirí amháin",
    "billing-checkout": "Foirm an chárta chun liostáil le plean",
    "billing-checkout-return": "Deimhniú an tsíntiúis",
    "legal-terms-version-text": "Leagan níos luaithe de na téarmaí",
    "legal-privacy-version-text": "Leagan níos luaithe den bheartas príobháideachais",
  }),
  he: Object.freeze({
    "product-identity": "אודות Dialectical Engine",
    "home-library": "דף הבית וספריית הדיונים",
    "new-debate": "יצירת דיון עם אפשרויות התוכנית",
    "owner-debate": "סביבת העבודה של בעל הדיון",
    "public-debate": "דיון שפורסם",
    "help-desk": "שיחות תמיכה ופניות לנציג אנושי",
    "sign-in": "התחברות ושחזור MFA שמור",
    "verify-email": "מצב אימות הדוא״ל",
    "enroll-mfa": "מצב ההרשמה ל-MFA",
    "operator-workers": "תצוגת תהליכים למפעילים בלבד",
    "billing-checkout": "טופס הכרטיס למינוי",
    "billing-checkout-return": "אישור המינוי",
    "legal-terms-version-text": "גרסה קודמת של התנאים",
    "legal-privacy-version-text": "גרסה קודמת של מדיניות הפרטיות",
  }),
  hi: Object.freeze({
    "product-identity": "Dialectical Engine के बारे में",
    "home-library": "मुख्य पृष्ठ और वाद-विवाद संग्रह",
    "new-debate": "योजना विकल्पों के साथ वाद-विवाद बनाना",
    "owner-debate": "वाद-विवाद स्वामी का कार्यक्षेत्र",
    "public-debate": "प्रकाशित वाद-विवाद",
    "help-desk": "सहायता बातचीत और व्यक्ति द्वारा देखे जाने वाले मामले",
    "sign-in": "लॉग इन और सहेजी गई MFA पुनर्प्राप्ति",
    "verify-email": "ईमेल सत्यापन की स्थिति",
    "enroll-mfa": "MFA नामांकन की स्थिति",
    "operator-workers": "केवल ऑपरेटरों के लिए प्रक्रिया दृश्य",
    "billing-checkout": "सदस्यता के लिए कार्ड फ़ॉर्म",
    "billing-checkout-return": "सदस्यता की पुष्टि",
    "legal-terms-version-text": "शर्तों का एक पिछला संस्करण",
    "legal-privacy-version-text": "गोपनीयता नीति का एक पिछला संस्करण",
  }),
  hr: Object.freeze({
    "product-identity": "O proizvodu Dialectical Engine",
    "home-library": "Početna stranica i knjižnica rasprava",
    "new-debate": "Izrada rasprave s opcijama plana",
    "owner-debate": "Radni prostor vlasnika rasprave",
    "public-debate": "Objavljena rasprava",
    "help-desk": "Razgovori s podrškom i slučajevi koje rješava osoba",
    "sign-in": "Prijava i spremljeni oporavak MFA",
    "verify-email": "Stanje potvrde e-pošte",
    "enroll-mfa": "Stanje upisa u MFA",
    "operator-workers": "Prikaz procesa samo za operatere",
    "billing-checkout": "Obrazac kartice za pretplatu",
    "billing-checkout-return": "Potvrda pretplate",
    "legal-terms-version-text": "Ranija verzija uvjeta",
    "legal-privacy-version-text": "Ranija verzija pravila o privatnosti",
  }),
  hu: Object.freeze({
    "product-identity": "A Dialectical Engine névjegye",
    "home-library": "Kezdőlap és vitakönyvtár",
    "new-debate": "Vita létrehozása az előfizetési szint beállításaival",
    "owner-debate": "A vita tulajdonosának munkaterülete",
    "public-debate": "Közzétett vita",
    "help-desk": "Ügyfélszolgálati beszélgetések és munkatárs által kezelt ügyek",
    "sign-in": "Bejelentkezés és mentett MFA-helyreállítás",
    "verify-email": "E-mail-cím megerősítésének állapota",
    "enroll-mfa": "MFA-regisztráció állapota",
    "operator-workers": "Csak üzemeltetőknek szóló folyamatnézet",
    "billing-checkout": "Kártyaűrlap az előfizetéshez",
    "billing-checkout-return": "Az előfizetés visszaigazolása",
    "legal-terms-version-text": "A feltételek egy korábbi változata",
    "legal-privacy-version-text": "Az adatvédelmi szabályzat egy korábbi változata",
  }),
  id: Object.freeze({
    "product-identity": "Tentang Dialectical Engine",
    "home-library": "Beranda dan pustaka debat",
    "new-debate": "Membuat debat dengan opsi paket",
    "owner-debate": "Ruang kerja pemilik debat",
    "public-debate": "Debat yang diterbitkan",
    "help-desk": "Percakapan dukungan dan kasus yang ditangani petugas",
    "sign-in": "Proses masuk dan pemulihan MFA tersimpan",
    "verify-email": "Status verifikasi email",
    "enroll-mfa": "Status pendaftaran MFA",
    "operator-workers": "Tampilan proses khusus operator",
    "billing-checkout": "Formulir kartu untuk langganan",
    "billing-checkout-return": "Konfirmasi langganan",
    "legal-terms-version-text": "Versi terdahulu ketentuan layanan",
    "legal-privacy-version-text": "Versi terdahulu kebijakan privasi",
  }),
  it: Object.freeze({
    "product-identity": "Informazioni su Dialectical Engine",
    "home-library": "Pagina iniziale e raccolta di dibattiti",
    "new-debate": "Creare un dibattito con le opzioni del piano",
    "owner-debate": "Area di lavoro del proprietario del dibattito",
    "public-debate": "Dibattito pubblicato",
    "help-desk": "Conversazioni di assistenza e casi gestiti da una persona",
    "sign-in": "Accesso e recupero MFA salvato",
    "verify-email": "Stato della verifica dell’email",
    "enroll-mfa": "Stato della registrazione MFA",
    "operator-workers": "Vista dei processi riservata agli operatori",
    "billing-checkout": "Modulo della carta per l’abbonamento",
    "billing-checkout-return": "Conferma dell’abbonamento",
    "legal-terms-version-text": "Una versione precedente delle condizioni di servizio",
    "legal-privacy-version-text": "Una versione precedente dell’informativa sulla privacy",
  }),
  ja: Object.freeze({
    "product-identity": "Dialectical Engine について",
    "home-library": "ホームとディベートライブラリ",
    "new-debate": "プランのオプションを使ったディベートの作成",
    "owner-debate": "ディベート所有者のワークスペース",
    "public-debate": "公開済みのディベート",
    "help-desk": "サポートの会話と担当者対応のケース",
    "sign-in": "ログインと保存済みの MFA 復旧",
    "verify-email": "メール確認の状態",
    "enroll-mfa": "MFA 登録の状態",
    "operator-workers": "オペレーター専用の処理状況ビュー",
    "billing-checkout": "サブスクリプションのカード入力フォーム",
    "billing-checkout-return": "サブスクリプションの登録確認",
    "legal-terms-version-text": "利用規約の過去の版",
    "legal-privacy-version-text": "プライバシーポリシーの過去の版",
  }),
  ko: Object.freeze({
    "product-identity": "Dialectical Engine 소개",
    "home-library": "홈 및 토론 라이브러리",
    "new-debate": "요금제 옵션으로 토론 만들기",
    "owner-debate": "토론 소유자 작업 공간",
    "public-debate": "게시된 토론",
    "help-desk": "지원 대화 및 상담원 처리 사례",
    "sign-in": "로그인 및 저장된 MFA 복구",
    "verify-email": "이메일 인증 상태",
    "enroll-mfa": "MFA 등록 상태",
    "operator-workers": "운영자 전용 처리 현황 보기",
    "billing-checkout": "구독 카드 입력 양식",
    "billing-checkout-return": "구독 확인",
    "legal-terms-version-text": "이용약관의 이전 버전",
    "legal-privacy-version-text": "개인정보 처리방침의 이전 버전",
  }),
  lt: Object.freeze({
    "product-identity": "Apie Dialectical Engine",
    "home-library": "Pradžios puslapis ir debatų biblioteka",
    "new-debate": "Debatų kūrimas su plano parinktimis",
    "owner-debate": "Debatų savininko darbo sritis",
    "public-debate": "Paskelbti debatai",
    "help-desk": "Pagalbos pokalbiai ir žmogaus nagrinėjami atvejai",
    "sign-in": "Prisijungimas ir išsaugotas MFA atkūrimas",
    "verify-email": "El. pašto patvirtinimo būsena",
    "enroll-mfa": "MFA registracijos būsena",
    "operator-workers": "Tik operatoriams skirtas procesų rodinys",
    "billing-checkout": "Prenumeratos kortelės forma",
    "billing-checkout-return": "Prenumeratos patvirtinimas",
    "legal-terms-version-text": "Ankstesnė sąlygų versija",
    "legal-privacy-version-text": "Ankstesnė privatumo politikos versija",
  }),
  lv: Object.freeze({
    "product-identity": "Par Dialectical Engine",
    "home-library": "Sākumlapa un debašu bibliotēka",
    "new-debate": "Debašu izveide ar plāna iespējām",
    "owner-debate": "Debašu īpašnieka darbvieta",
    "public-debate": "Publicētās debates",
    "help-desk": "Atbalsta sarunas un cilvēka izskatāmi gadījumi",
    "sign-in": "Pierakstīšanās un saglabātā MFA atkopšana",
    "verify-email": "E-pasta verifikācijas statuss",
    "enroll-mfa": "MFA reģistrācijas statuss",
    "operator-workers": "Procesu skats tikai operatoriem",
    "billing-checkout": "Abonementa kartes veidlapa",
    "billing-checkout-return": "Abonementa apstiprinājums",
    "legal-terms-version-text": "Agrāka noteikumu versija",
    "legal-privacy-version-text": "Agrāka privātuma politikas versija",
  }),
  mt: Object.freeze({
    "product-identity": "Dwar Dialectical Engine",
    "home-library": "Paġna ewlenija u librerija tad-dibattiti",
    "new-debate": "Oħloq dibattitu bl-għażliet tal-pjan",
    "owner-debate": "Spazju tax-xogħol tas-sid tad-dibattitu",
    "public-debate": "Dibattitu ppubblikat",
    "help-desk": "Konversazzjonijiet ta’ appoġġ u każijiet immaniġġjati minn persuna",
    "sign-in": "Dħul fil-kont u rkupru MFA salvat",
    "verify-email": "Stat tal-verifika tal-email",
    "enroll-mfa": "Stat tar-reġistrazzjoni MFA",
    "operator-workers": "Veduta tal-proċessi għall-operaturi biss",
    "billing-checkout": "Formola tal-karta għall-abbonament",
    "billing-checkout-return": "Konferma tal-abbonament",
    "legal-terms-version-text": "Verżjoni preċedenti tat-termini",
    "legal-privacy-version-text": "Verżjoni preċedenti tal-politika dwar il-privatezza",
  }),
  nl: Object.freeze({
    "product-identity": "Over Dialectical Engine",
    "home-library": "Startpagina en debatbibliotheek",
    "new-debate": "Een debat maken met de opties van het abonnement",
    "owner-debate": "Werkruimte van de debateigenaar",
    "public-debate": "Gepubliceerd debat",
    "help-desk": "Supportgesprekken en zaken voor een medewerker",
    "sign-in": "Aanmelding en opgeslagen MFA-herstel",
    "verify-email": "Status van de e-mailverificatie",
    "enroll-mfa": "Status van de MFA-registratie",
    "operator-workers": "Procesweergave alleen voor beheerders",
    "billing-checkout": "Kaartformulier voor het abonnement",
    "billing-checkout-return": "Bevestiging van het abonnement",
    "legal-terms-version-text": "Een eerdere versie van de voorwaarden",
    "legal-privacy-version-text": "Een eerdere versie van het privacybeleid",
  }),
  pl: Object.freeze({
    "product-identity": "Informacje o Dialectical Engine",
    "home-library": "Strona główna i biblioteka debat",
    "new-debate": "Tworzenie debaty z opcjami planu",
    "owner-debate": "Obszar roboczy właściciela debaty",
    "public-debate": "Opublikowana debata",
    "help-desk": "Rozmowy z pomocą techniczną i sprawy prowadzone przez człowieka",
    "sign-in": "Logowanie i zapisane odzyskiwanie MFA",
    "verify-email": "Stan weryfikacji adresu e-mail",
    "enroll-mfa": "Stan rejestracji MFA",
    "operator-workers": "Widok procesów tylko dla operatorów",
    "billing-checkout": "Formularz karty do subskrypcji",
    "billing-checkout-return": "Potwierdzenie subskrypcji",
    "legal-terms-version-text": "Wcześniejsza wersja warunków",
    "legal-privacy-version-text": "Wcześniejsza wersja polityki prywatności",
  }),
  pt: Object.freeze({
    "product-identity": "Sobre o Dialectical Engine",
    "home-library": "Início e biblioteca de debates",
    "new-debate": "Criar um debate com as opções do plano",
    "owner-debate": "Área de trabalho do proprietário do debate",
    "public-debate": "Debate publicado",
    "help-desk": "Conversas de apoio e casos tratados por uma pessoa",
    "sign-in": "Início de sessão e recuperação MFA guardada",
    "verify-email": "Estado da verificação do e-mail",
    "enroll-mfa": "Estado da inscrição MFA",
    "operator-workers": "Vista de processos apenas para operadores",
    "billing-checkout": "Formulário do cartão para a subscrição",
    "billing-checkout-return": "Confirmação da subscrição",
    "legal-terms-version-text": "Uma versão anterior dos Termos de Serviço",
    "legal-privacy-version-text": "Uma versão anterior da Política de Privacidade",
  }),
  ru: Object.freeze({
    "product-identity": "О Dialectical Engine",
    "home-library": "Главная страница и библиотека дебатов",
    "new-debate": "Создание дебатов с параметрами тарифа",
    "owner-debate": "Рабочая область владельца дебатов",
    "public-debate": "Опубликованные дебаты",
    "help-desk": "Разговоры с поддержкой и обращения к сотруднику",
    "sign-in": "Вход и сохранённое восстановление MFA",
    "verify-email": "Статус подтверждения электронной почты",
    "enroll-mfa": "Статус подключения MFA",
    "operator-workers": "Просмотр процессов только для операторов",
    "billing-checkout": "Форма карты для подписки",
    "billing-checkout-return": "Подтверждение подписки",
    "legal-terms-version-text": "Одна из прежних версий условий",
    "legal-privacy-version-text": "Одна из прежних версий политики конфиденциальности",
  }),
  sk: Object.freeze({
    "product-identity": "O Dialectical Engine",
    "home-library": "Domovská stránka a knižnica debát",
    "new-debate": "Vytvorenie debaty s možnosťami programu",
    "owner-debate": "Pracovný priestor vlastníka debaty",
    "public-debate": "Zverejnená debata",
    "help-desk": "Konverzácie s podporou a prípady riešené človekom",
    "sign-in": "Prihlásenie a uložené obnovenie MFA",
    "verify-email": "Stav overenia e-mailu",
    "enroll-mfa": "Stav registrácie MFA",
    "operator-workers": "Prehľad procesov len pre operátorov",
    "billing-checkout": "Formulár karty pre predplatné",
    "billing-checkout-return": "Potvrdenie predplatného",
    "legal-terms-version-text": "Staršia verzia podmienok",
    "legal-privacy-version-text": "Staršia verzia zásad ochrany osobných údajov",
  }),
  sl: Object.freeze({
    "product-identity": "O Dialectical Engine",
    "home-library": "Domača stran in knjižnica razprav",
    "new-debate": "Ustvarjanje razprave z možnostmi paketa",
    "owner-debate": "Delovni prostor lastnika razprave",
    "public-debate": "Objavljena razprava",
    "help-desk": "Pogovori s podporo in primeri, ki jih obravnava oseba",
    "sign-in": "Prijava in shranjena obnovitev MFA",
    "verify-email": "Stanje potrditve e-pošte",
    "enroll-mfa": "Stanje včlanitve v MFA",
    "operator-workers": "Pogled procesov samo za operaterje",
    "billing-checkout": "Obrazec kartice za naročnino",
    "billing-checkout-return": "Potrditev naročnine",
    "legal-terms-version-text": "Starejša različica pogojev",
    "legal-privacy-version-text": "Starejša različica pravilnika o zasebnosti",
  }),
  sv: Object.freeze({
    "product-identity": "Om Dialectical Engine",
    "home-library": "Startsida och debattbibliotek",
    "new-debate": "Skapa en debatt med abonnemangets alternativ",
    "owner-debate": "Debattägarens arbetsyta",
    "public-debate": "Publicerad debatt",
    "help-desk": "Supportsamtal och ärenden som hanteras av en person",
    "sign-in": "Inloggning och sparad MFA-återställning",
    "verify-email": "Status för e-postverifiering",
    "enroll-mfa": "Status för MFA-registrering",
    "operator-workers": "Processvy endast för operatörer",
    "billing-checkout": "Kortformulär för abonnemanget",
    "billing-checkout-return": "Bekräftelse av abonnemanget",
    "legal-terms-version-text": "En tidigare version av villkoren",
    "legal-privacy-version-text": "En tidigare version av integritetspolicyn",
  }),
  tr: Object.freeze({
    "product-identity": "Dialectical Engine hakkında",
    "home-library": "Ana sayfa ve tartışma kütüphanesi",
    "new-debate": "Plan seçenekleriyle tartışma oluşturma",
    "owner-debate": "Tartışma sahibinin çalışma alanı",
    "public-debate": "Yayımlanmış tartışma",
    "help-desk": "Destek konuşmaları ve yetkili tarafından ele alınan vakalar",
    "sign-in": "Oturum açma ve kayıtlı MFA kurtarma",
    "verify-email": "E-posta doğrulama durumu",
    "enroll-mfa": "MFA kayıt durumu",
    "operator-workers": "Yalnızca operatörlere özel işlem görünümü",
    "billing-checkout": "Abonelik için kart formu",
    "billing-checkout-return": "Abonelik onayı",
    "legal-terms-version-text": "Koşulların önceki bir sürümü",
    "legal-privacy-version-text": "Gizlilik politikasının önceki bir sürümü",
  }),
  uk: Object.freeze({
    "product-identity": "Про Dialectical Engine",
    "home-library": "Головна сторінка та бібліотека дебатів",
    "new-debate": "Створення дебатів із параметрами плану",
    "owner-debate": "Робоча область власника дебатів",
    "public-debate": "Опубліковані дебати",
    "help-desk": "Розмови з підтримкою та звернення до співробітника",
    "sign-in": "Вхід і збережене відновлення MFA",
    "verify-email": "Стан підтвердження електронної пошти",
    "enroll-mfa": "Стан підключення MFA",
    "operator-workers": "Перегляд процесів лише для операторів",
    "billing-checkout": "Форма картки для підписки",
    "billing-checkout-return": "Підтвердження підписки",
    "legal-terms-version-text": "Одна з попередніх версій умов",
    "legal-privacy-version-text": "Одна з попередніх версій політики конфіденційності",
  }),
  vi: Object.freeze({
    "product-identity": "Giới thiệu về Dialectical Engine",
    "home-library": "Trang chủ và thư viện tranh luận",
    "new-debate": "Tạo cuộc tranh luận với các tùy chọn gói",
    "owner-debate": "Không gian làm việc của chủ sở hữu cuộc tranh luận",
    "public-debate": "Cuộc tranh luận đã xuất bản",
    "help-desk": "Trò chuyện hỗ trợ và các trường hợp do nhân viên xử lý",
    "sign-in": "Đăng nhập và khôi phục MFA đã lưu",
    "verify-email": "Trạng thái xác minh email",
    "enroll-mfa": "Trạng thái đăng ký MFA",
    "operator-workers": "Chế độ xem tiến trình chỉ dành cho người vận hành",
    "billing-checkout": "Biểu mẫu thẻ cho gói đăng ký",
    "billing-checkout-return": "Xác nhận gói đăng ký",
    "legal-terms-version-text": "Một phiên bản trước của điều khoản",
    "legal-privacy-version-text": "Một phiên bản trước của chính sách quyền riêng tư",
  }),
  zh: Object.freeze({
    "product-identity": "关于 Dialectical Engine",
    "home-library": "首页和辩论资料库",
    "new-debate": "使用方案选项创建辩论",
    "owner-debate": "辩论所有者工作区",
    "public-debate": "已发布的辩论",
    "help-desk": "支持对话和人工处理的案例",
    "sign-in": "登录和已保存的 MFA 恢复",
    "verify-email": "电子邮件验证状态",
    "enroll-mfa": "MFA 注册状态",
    "operator-workers": "仅限运营人员的处理进程视图",
    "billing-checkout": "订阅的银行卡填写表单",
    "billing-checkout-return": "订阅确认",
    "legal-terms-version-text": "服务条款的一个旧版本",
    "legal-privacy-version-text": "隐私政策的一个旧版本",
  }),
});

/**
 * The capability name the model reads in its capability line (context.ts `baseSection`). en and ro: catalog.ts's own
 * name. The other 33: the KEY-row page link (generated from apps/ui/messages into ui-labels.ts) or the TRANSLATE-row
 * label above; an id in neither falls back to the en name, which the checker reports as CAPABILITY ENGLISH / UNMAPPED.
 * Matching and routing never call this: they keep reading item.labels[corpusLocale] (R10).
 */
export function supportCapabilityName(capability: Pick<SupportCapability, "id" | "labels">, language: SupportLanguage): string {
  if (language === "en" || language === "ro") return capability.labels[language];
  const keyed: Readonly<Record<string, string>> = SUPPORT_CAPABILITY_KEY_NAMES[language];
  const translated: Readonly<Record<string, string>> = SUPPORT_CAPABILITY_TRANSLATIONS[language] ?? {};
  return keyed[capability.id] ?? translated[capability.id] ?? capability.labels.en;
}
