// Generated by scripts/generate-ui-labels.mjs. Do not edit by hand.
import type { SupportActionId } from "./catalog.js";
import type { SupportLanguage } from "./locale.js";

export const SUPPORT_UI_LABELS = {
  "ar": {
    "home": "Dialectical Engine — الصفحة الرئيسية",
    "start-debate": "بدء مناظرة",
    "sign-in": "الحساب",
    "sign-up": "إنشاء حساب",
    "help": "المساعدة",
    "support-status": "حالة الخدمة",
    "method": "آلية العمل",
    "sample-transcript": "السجلات",
    "settings": "الإعدادات",
    "active-sessions": "نشط الجلسات",
    "privacy-preferences": "الخصوصية",
    "claim-legacy": "الادعاء قديم المناظرات",
    "delete-account": "حذف الحساب",
    "public-catalog": "المناظرات العامة",
    "your-debates": "مناظراتك",
    "owner-debate": "فتح مناظرتك",
    "public-debate": "فتح المناظرة العامة"
  },
  "bg": {
    "home": "Dialectical Engine — дом",
    "start-debate": "Започнете дебат",
    "sign-in": "Профил",
    "sign-up": "Създаване на профил",
    "help": "Помощ",
    "support-status": "Състояние на услугата",
    "method": "Как работи",
    "sample-transcript": "Преписи",
    "settings": "Настройки",
    "active-sessions": "Активни сесии",
    "privacy-preferences": "Поверителност",
    "claim-legacy": "Заявяване на наследени дебати",
    "delete-account": "Изтриване на профила",
    "public-catalog": "Публични дебати",
    "your-debates": "Вашите дебати",
    "owner-debate": "Отворете Вашия дебат",
    "public-debate": "Отворете публичен дебат"
  },
  "cs": {
    "home": "Dialectical Engine — domů",
    "start-debate": "Začněte debatu",
    "sign-in": "Účet",
    "sign-up": "Vytvořit účet",
    "help": "Pomoc",
    "support-status": "Stav služby",
    "method": "Jak to funguje",
    "sample-transcript": "Přepisy",
    "settings": "Nastavení",
    "active-sessions": "Aktivní relace",
    "privacy-preferences": "Soukromí",
    "claim-legacy": "Převzít starší debaty",
    "delete-account": "Smazat účet",
    "public-catalog": "Veřejné debaty",
    "your-debates": "Vaše debaty",
    "owner-debate": "Otevřít vaši debatu",
    "public-debate": "Otevřít veřejnou debatu"
  },
  "da": {
    "home": "Dialectical Engine — hjem",
    "start-debate": "Start en debat",
    "sign-in": "Konto",
    "sign-up": "Opret en",
    "help": "Hjælp",
    "support-status": "Tjenestestatus",
    "method": "Hvordan det virker",
    "sample-transcript": "Afskrifter",
    "settings": "Indstillinger",
    "active-sessions": "Aktive sessioner",
    "privacy-preferences": "Privatliv",
    "claim-legacy": "Gør krav på ældre debatter",
    "delete-account": "Slet konto",
    "public-catalog": "Offentlige debatter",
    "your-debates": "Dine debatter",
    "owner-debate": "Åbn din debat",
    "public-debate": "Åbn offentlig debat"
  },
  "de": {
    "home": "Dialectical Engine — Startseite",
    "start-debate": "Debatte beginnen",
    "sign-in": "Konto",
    "sign-up": "erstellen ein",
    "help": "Hilfe",
    "support-status": "Dienststatus",
    "method": "Funktionsweise",
    "sample-transcript": "Transkripte",
    "settings": "Einstellungen",
    "active-sessions": "aktiv Sitzungen",
    "privacy-preferences": "Datenschutz",
    "claim-legacy": "Behauptung Legacy Debatten",
    "delete-account": "löschen Konto",
    "public-catalog": "Öffentliche Debatten",
    "your-debates": "Ihre Debatten",
    "owner-debate": "Ihre Debatte öffnen",
    "public-debate": "Öffentliche Debatte öffnen"
  },
  "el": {
    "home": "Dialectical Engine — αρχική σελίδα",
    "start-debate": "Έναρξη αντιπαράθεσης",
    "sign-in": "Λογαριασμός",
    "sign-up": "δημιουργία ένα",
    "help": "Βοήθεια",
    "support-status": "Κατάσταση υπηρεσίας",
    "method": "Πώς λειτουργεί",
    "sample-transcript": "Απομαγνητοφωνήσεις",
    "settings": "Ρυθμίσεις",
    "active-sessions": "ενεργό περίοδοι σύνδεσης",
    "privacy-preferences": "απόρρητο",
    "claim-legacy": "ισχυρισμός παλαιό αντιπαραθέσεις",
    "delete-account": "διαγραφή λογαριασμός",
    "public-catalog": "Δημόσιες αντιπαραθέσεις",
    "your-debates": "Οι αντιπαραθέσεις σας",
    "owner-debate": "Άνοιγμα της αντιπαράθεσής σας",
    "public-debate": "Άνοιγμα δημόσιας αντιπαράθεσης"
  },
  "en": {
    "home": "Dialectical Engine — home",
    "start-debate": "Start a debate",
    "sign-in": "Account",
    "sign-up": "Create one",
    "help": "Help",
    "support-status": "Service status",
    "method": "How it works",
    "sample-transcript": "Transcripts",
    "settings": "Settings",
    "active-sessions": "Active sessions",
    "privacy-preferences": "Privacy",
    "claim-legacy": "Claim legacy debates",
    "delete-account": "Delete account",
    "public-catalog": "Public debates",
    "your-debates": "Your debates",
    "owner-debate": "Open your debate",
    "public-debate": "Open public debate"
  },
  "es": {
    "home": "Dialectical Engine — inicio",
    "start-debate": "Iniciar un debate",
    "sign-in": "Cuenta",
    "sign-up": "Cree una",
    "help": "Ayuda",
    "support-status": "Estado del servicio",
    "method": "Cómo funciona",
    "sample-transcript": "Transcripciones",
    "settings": "Configuración",
    "active-sessions": "Ativo sessões",
    "privacy-preferences": "PRIVACIDAD",
    "claim-legacy": "AFIRMACIÓN legado debates",
    "delete-account": "ELIMINAR cuenta",
    "public-catalog": "Debates públicos",
    "your-debates": "Sus debates",
    "owner-debate": "Abrir su debate",
    "public-debate": "Abrir el debate público"
  },
  "et": {
    "home": "Dialectical Engine — kodu",
    "start-debate": "Alustage arutelu",
    "sign-in": "konto",
    "sign-up": "loo üks",
    "help": "Abi",
    "support-status": "Teenuse olek",
    "method": "Kuidas see toimib",
    "sample-transcript": "Ärakirjad",
    "settings": "Seaded",
    "active-sessions": "aktiivne seansid",
    "privacy-preferences": "privaatsus",
    "claim-legacy": "väide pärand väitlused",
    "delete-account": "kustuta konto",
    "public-catalog": "Avalikud arutelud",
    "your-debates": "Teie arutelud",
    "owner-debate": "Avage oma väitlus",
    "public-debate": "Avage avalik väitlus"
  },
  "fi": {
    "home": "Dialectical Engine — etusivu",
    "start-debate": "Aloita väittely",
    "sign-in": "Tili",
    "sign-up": "luo yksi",
    "help": "Ohje",
    "support-status": "Palvelun tila",
    "method": "Näin se toimii",
    "sample-transcript": "Litteroinnit",
    "settings": "Asetukset",
    "active-sessions": "aktiivinen istunnot",
    "privacy-preferences": "tietosuoja",
    "claim-legacy": "väite vanha väittelyt",
    "delete-account": "poista tili",
    "public-catalog": "Julkiset väittelyt",
    "your-debates": "Omat väittelysi",
    "owner-debate": "Avaa väittelysi",
    "public-debate": "Avaa julkinen väittely"
  },
  "fr": {
    "home": "Dialectical Engine — accueil",
    "start-debate": "Lancer un débat",
    "sign-in": "Compte",
    "sign-up": "créer un",
    "help": "Aide",
    "support-status": "État du service",
    "method": "Fonctionnement",
    "sample-transcript": "Transcriptions",
    "settings": "Paramètres",
    "active-sessions": "actif sessions",
    "privacy-preferences": "confidentialité",
    "claim-legacy": "affirmation hérité débats",
    "delete-account": "supprimer compte",
    "public-catalog": "Débats publics",
    "your-debates": "Vos débats",
    "owner-debate": "Ouvrir votre débat",
    "public-debate": "Ouvrir le débat public"
  },
  "ga": {
    "home": "Dialectical Engine — baile",
    "start-debate": "Tosaigh díospóireacht",
    "sign-in": "Cuntas",
    "sign-up": "Cruthaigh aon",
    "help": "Cabhair",
    "support-status": "Stádas seirbhíse",
    "method": "Conas a oibríonn sé",
    "sample-transcript": "Tras-scríbhinní",
    "settings": "Socruithe",
    "active-sessions": "Gníomhach seisiúin",
    "privacy-preferences": "Príobháideachas",
    "claim-legacy": "Maíomh oidhreachta díospóireachtaí",
    "delete-account": "Scrios cuntas",
    "public-catalog": "Díospóireachtaí poiblí",
    "your-debates": "Do chuid díospóireachtaí",
    "owner-debate": "Oscail do dhíospóireacht",
    "public-debate": "Oscail díospóireacht phoiblí"
  },
  "he": {
    "home": "Dialectical Engine — דף הבית",
    "start-debate": "התחלת דיון",
    "sign-in": "חשבון",
    "sign-up": "יצירת חשבון",
    "help": "עזרה",
    "support-status": "מצב השירות",
    "method": "איך זה עובד",
    "sample-transcript": "תמלילים",
    "settings": "הגדרות",
    "active-sessions": "פעיל הפעלות",
    "privacy-preferences": "פרטיות",
    "claim-legacy": "טענה מורשת דיונים",
    "delete-account": "מחיקה החשבון",
    "public-catalog": "דיונים ציבוריים",
    "your-debates": "הדיונים שלך",
    "owner-debate": "פתיחת הדיון שלך",
    "public-debate": "פתיחת דיון ציבורי"
  },
  "hi": {
    "home": "Dialectical Engine — मुख्य पृष्ठ",
    "start-debate": "बहस शुरू करें",
    "sign-in": "खाता",
    "sign-up": "एक बनाएँ",
    "help": "सहायता",
    "support-status": "सेवा की स्थिति",
    "method": "यह कैसे काम करता है",
    "sample-transcript": "प्रतिलिपियाँ",
    "settings": "सेटिंग",
    "active-sessions": "सक्रिय sessions",
    "privacy-preferences": "गोपनीयता",
    "claim-legacy": "दावा legacy बहसें",
    "delete-account": "हटाएँ खाता",
    "public-catalog": "सार्वजनिक बहसें",
    "your-debates": "आपकी बहसें",
    "owner-debate": "अपनी बहस खोलें",
    "public-debate": "सार्वजनिक बहस खोलें"
  },
  "hr": {
    "home": "Dialectical Engine — dom",
    "start-debate": "Započnite raspravu",
    "sign-in": "Račun",
    "sign-up": "Izradite ga",
    "help": "Pomoć",
    "support-status": "Stanje usluge",
    "method": "Kako radi",
    "sample-transcript": "Prijepisi",
    "settings": "Postavke",
    "active-sessions": "Aktivne sesije",
    "privacy-preferences": "Privatnost",
    "claim-legacy": "Preuzmi naslijeđene rasprave",
    "delete-account": "Izbriši račun",
    "public-catalog": "Javne rasprave",
    "your-debates": "Vaše rasprave",
    "owner-debate": "Otvorite svoju raspravu",
    "public-debate": "Otvorite javnu raspravu"
  },
  "hu": {
    "home": "Dialectical Engine — kezdőlap",
    "start-debate": "Vita indítása",
    "sign-in": "Fiók",
    "sign-up": "Létrehozás egy",
    "help": "Súgó",
    "support-status": "Szolgáltatás állapota",
    "method": "Hogyan működik?",
    "sample-transcript": "Átiratok",
    "settings": "Beállítások",
    "active-sessions": "Aktív munkamenetek",
    "privacy-preferences": "Adatvédelem",
    "claim-legacy": "Állítás örökölt viták",
    "delete-account": "Törlés fiók",
    "public-catalog": "Nyilvános viták",
    "your-debates": "Saját viták",
    "owner-debate": "Vita megnyitása",
    "public-debate": "Nyilvános vita megnyitása"
  },
  "id": {
    "home": "Dialectical Engine — beranda",
    "start-debate": "Mulai debat",
    "sign-in": "Akun",
    "sign-up": "Buat akun",
    "help": "Bantuan",
    "support-status": "Status layanan",
    "method": "Cara kerjanya",
    "sample-transcript": "Transkrip",
    "settings": "Pengaturan",
    "active-sessions": "aktif sessions",
    "privacy-preferences": "privasi",
    "claim-legacy": "klaim legacy debat",
    "delete-account": "hapus akun",
    "public-catalog": "Debat publik",
    "your-debates": "Debat Anda",
    "owner-debate": "Buka debat Anda",
    "public-debate": "Buka debat publik"
  },
  "it": {
    "home": "Dialectical Engine — pagina iniziale",
    "start-debate": "Avvia un dibattito",
    "sign-in": "Account",
    "sign-up": "Crea uno",
    "help": "Aiuto",
    "support-status": "Stato del servizio",
    "method": "Come funziona",
    "sample-transcript": "Trascrizioni",
    "settings": "Impostazioni",
    "active-sessions": "Attivo sessioni",
    "privacy-preferences": "Privacy",
    "claim-legacy": "Affermazione precedente dibattiti",
    "delete-account": "Elimina account",
    "public-catalog": "Dibattiti pubblici",
    "your-debates": "I tuoi dibattiti",
    "owner-debate": "Apri il tuo dibattito",
    "public-debate": "Apri dibattito pubblico"
  },
  "ja": {
    "home": "Dialectical Engine — ホーム",
    "start-debate": "ディベートを開始",
    "sign-in": "アカウント",
    "sign-up": "作成する",
    "help": "ヘルプ",
    "support-status": "サービス状況",
    "method": "仕組み",
    "sample-transcript": "記録",
    "settings": "設定",
    "active-sessions": "有効 sessions",
    "privacy-preferences": "プライバシー",
    "claim-legacy": "主張 legacy 討論",
    "delete-account": "削除 アカウント",
    "public-catalog": "公開ディベート",
    "your-debates": "自分のディベート",
    "owner-debate": "自分のディベートを開く",
    "public-debate": "公開ディベートを開く"
  },
  "ko": {
    "home": "Dialectical Engine — 홈",
    "start-debate": "토론 시작",
    "sign-in": "계정",
    "sign-up": "계정 만들기",
    "help": "도움말",
    "support-status": "서비스 상태",
    "method": "작동 방식",
    "sample-transcript": "기록",
    "settings": "설정",
    "active-sessions": "활성 sessions",
    "privacy-preferences": "개인정보",
    "claim-legacy": "주장 legacy 토론",
    "delete-account": "삭제 계정",
    "public-catalog": "공개 토론",
    "your-debates": "내 토론",
    "owner-debate": "내 토론 열기",
    "public-debate": "공개 토론 열기"
  },
  "lt": {
    "home": "Dialectical Engine — pradžia",
    "start-debate": "Pradėti debatus",
    "sign-in": "Paskyra",
    "sign-up": "Sukurti vienas",
    "help": "Pagalba",
    "support-status": "Paslaugos būsena",
    "method": "Kaip tai veikia",
    "sample-transcript": "Stenogramos",
    "settings": "Nuostatos",
    "active-sessions": "Aktyvus sesijos",
    "privacy-preferences": "Privatumas",
    "claim-legacy": "Teiginys senasis debatai",
    "delete-account": "Ištrinti paskyra",
    "public-catalog": "Vieši debatai",
    "your-debates": "Jūsų debatai",
    "owner-debate": "Atverti savo debatus",
    "public-debate": "Atverti viešus debatus"
  },
  "lv": {
    "home": "Dialectical Engine — sākums",
    "start-debate": "Sākt debates",
    "sign-in": "Konts",
    "sign-up": "Izveidot viens",
    "help": "Palīdzība",
    "support-status": "Pakalpojuma statuss",
    "method": "Kā tas darbojas",
    "sample-transcript": "Transkripti",
    "settings": "Iestatījumi",
    "active-sessions": "Aktīvs sesijas",
    "privacy-preferences": "Privātums",
    "claim-legacy": "Apgalvojums mantots debates",
    "delete-account": "Dzēst konts",
    "public-catalog": "Publiskās debates",
    "your-debates": "Jūsu debates",
    "owner-debate": "Atvērt savas debates",
    "public-debate": "Atvērt publiskās debates"
  },
  "mt": {
    "home": "Dialectical Engine — paġna ewlenija",
    "start-debate": "Ibda dibattitu",
    "sign-in": "Kont",
    "sign-up": "Oħloq wieħed",
    "help": "Għajnuna",
    "support-status": "Status tas-servizz",
    "method": "Kif jaħdem",
    "sample-transcript": "Traskrizzjonijiet",
    "settings": "Issettjar",
    "active-sessions": "Attiv sessjonijiet",
    "privacy-preferences": "Privatezza",
    "claim-legacy": "Pretensjoni storiku dibattiti",
    "delete-account": "Ħassar kont",
    "public-catalog": "Dibattiti pubbliċi",
    "your-debates": "Id-dibattiti tiegħek",
    "owner-debate": "Iftaħ id-dibattitu tiegħek",
    "public-debate": "Iftaħ dibattitu pubbliku"
  },
  "nl": {
    "home": "Dialectical Engine — thuis",
    "start-debate": "Begin een debat",
    "sign-in": "Account",
    "sign-up": "Maak er een aan",
    "help": "Hulp",
    "support-status": "Servicestatus",
    "method": "Hoe het werkt",
    "sample-transcript": "Transcripties",
    "settings": "Instellingen",
    "active-sessions": "Actieve sessies",
    "privacy-preferences": "Privacy",
    "claim-legacy": "Eerdere debatten koppelen",
    "delete-account": "Account verwijderen",
    "public-catalog": "Publieke debatten",
    "your-debates": "Jouw debatten",
    "owner-debate": "Uw debat openen",
    "public-debate": "Openbaar debat openen"
  },
  "pl": {
    "home": "Dialectical Engine — strona główna",
    "start-debate": "Rozpocznij debatę",
    "sign-in": "Konto",
    "sign-up": "Utwórz jeden",
    "help": "Pomoc",
    "support-status": "Stan usługi",
    "method": "Jak to działa",
    "sample-transcript": "Transkrypcje",
    "settings": "Ustawienia",
    "active-sessions": "Aktywny sesje",
    "privacy-preferences": "Prywatność",
    "claim-legacy": "Teza starszy debaty",
    "delete-account": "Usuń konto",
    "public-catalog": "Debaty publiczne",
    "your-debates": "Twoje debaty",
    "owner-debate": "Otwórz swoją debatę",
    "public-debate": "Otwórz debatę publiczną"
  },
  "pt": {
    "home": "Dialectical Engine — início",
    "start-debate": "Iniciar um debate",
    "sign-in": "Conta",
    "sign-up": "Criar um",
    "help": "Ajuda",
    "support-status": "Estado do serviço",
    "method": "Como funciona",
    "sample-transcript": "Transcrições",
    "settings": "Definições",
    "active-sessions": "Ativo sessões",
    "privacy-preferences": "Privacidade",
    "claim-legacy": "Afirmação legado debates",
    "delete-account": "Eliminar conta",
    "public-catalog": "Debates públicos",
    "your-debates": "Os seus debates",
    "owner-debate": "Abrir o seu debate",
    "public-debate": "Abrir debate público"
  },
  "ro": {
    "home": "Dialectical Engine — pagina principală",
    "start-debate": "Începeți o dezbatere",
    "sign-in": "Cont",
    "sign-up": "Creați un",
    "help": "Ajutor",
    "support-status": "Starea serviciului",
    "method": "Cum funcționează",
    "sample-transcript": "Transcrieri",
    "settings": "Setări",
    "active-sessions": "Activ sesiuni",
    "privacy-preferences": "Confidențialitate",
    "claim-legacy": "Afirmație moștenit dezbateri",
    "delete-account": "Ștergeți cont",
    "public-catalog": "Dezbateri publice",
    "your-debates": "Dezbaterile dvs.",
    "owner-debate": "Deschideți dezbaterea dumneavoastră",
    "public-debate": "Deschideți dezbaterea publică"
  },
  "ru": {
    "home": "Dialectical Engine — главная",
    "start-debate": "Начать дискуссию",
    "sign-in": "Учётная запись",
    "sign-up": "Создать один",
    "help": "Помощь",
    "support-status": "Состояние сервиса",
    "method": "Как это работает",
    "sample-transcript": "Стенограммы",
    "settings": "Настройки",
    "active-sessions": "Активный сеансы",
    "privacy-preferences": "Конфиденциальность",
    "claim-legacy": "Тезис устаревший дискуссии",
    "delete-account": "Удалить учётная запись",
    "public-catalog": "Публичные дискуссии",
    "your-debates": "Ваши дискуссии",
    "owner-debate": "Открыть ваши дебаты",
    "public-debate": "Открыть общедоступные дебаты"
  },
  "sk": {
    "home": "Dialectical Engine — domovská stránka",
    "start-debate": "Začať diskusiu",
    "sign-in": "Účet",
    "sign-up": "Vytvoriť účet",
    "help": "Pomoc",
    "support-status": "Stav služby",
    "method": "Ako to funguje",
    "sample-transcript": "Prepisy",
    "settings": "Nastavenia",
    "active-sessions": "Aktivní relácia",
    "privacy-preferences": "SÚKROMIE",
    "claim-legacy": "Prevzít starší diskusie",
    "delete-account": "Smazat účet",
    "public-catalog": "Verejné diskusie",
    "your-debates": "Vaše diskusie",
    "owner-debate": "Otvoriť vašu diskusiu",
    "public-debate": "Otvoriť verejnú diskusiu"
  },
  "sl": {
    "home": "Dialectical Engine — domača stran",
    "start-debate": "Začni razpravo",
    "sign-in": "Račun",
    "sign-up": "Ustvarite ga",
    "help": "Pomoč",
    "support-status": "Stanje storitve",
    "method": "Kako deluje",
    "sample-transcript": "Prepisi",
    "settings": "Nastavitve",
    "active-sessions": "Aktivne sesije",
    "privacy-preferences": "ZASEBNOST",
    "claim-legacy": "Preuzmi naslijedene razprave",
    "delete-account": "IZBRIŠI račun",
    "public-catalog": "Javne razprave",
    "your-debates": "Vaše razprave",
    "owner-debate": "Odpri svojo razpravo",
    "public-debate": "Odpri javno razpravo"
  },
  "sv": {
    "home": "Dialectical Engine — startsida",
    "start-debate": "Starta en debatt",
    "sign-in": "Konto",
    "sign-up": "Skapa ett",
    "help": "Hjälp",
    "support-status": "Tjänstestatus",
    "method": "Så fungerar det",
    "sample-transcript": "Transkriptioner",
    "settings": "Inställningar",
    "active-sessions": "Aktive sessioner",
    "privacy-preferences": "INTEGRITET",
    "claim-legacy": "Gör krav på äldre debatter",
    "delete-account": "RADERA konto",
    "public-catalog": "Offentliga debatter",
    "your-debates": "Dina debatter",
    "owner-debate": "Öppna din debatt",
    "public-debate": "Öppna offentlig debatt"
  },
  "tr": {
    "home": "Dialectical Engine — ana sayfa",
    "start-debate": "Tartışma başlat",
    "sign-in": "Hesap",
    "sign-up": "Hesap oluştur",
    "help": "Yardım",
    "support-status": "Hizmet durumu",
    "method": "Nasıl çalışır",
    "sample-transcript": "Tutanaklar",
    "settings": "Ayarlar",
    "active-sessions": "Etkin oturumlar",
    "privacy-preferences": "Gizlilik",
    "claim-legacy": "İddia eski tartışmalar",
    "delete-account": "Sil hesap",
    "public-catalog": "Herkese açık tartışmalar",
    "your-debates": "Tartışmalarınız",
    "owner-debate": "Tartışmanızı aç",
    "public-debate": "Herkese açık tartışmayı aç"
  },
  "uk": {
    "home": "Dialectical Engine — головна",
    "start-debate": "Почати дебати",
    "sign-in": "Обліковий запис",
    "sign-up": "Створити",
    "help": "Довідка",
    "support-status": "Стан сервісу",
    "method": "Як це працює",
    "sample-transcript": "Стенограми",
    "settings": "Налаштування",
    "active-sessions": "Активний сеанси",
    "privacy-preferences": "КОНФІДЕНЦІЙНІСТЬ",
    "claim-legacy": "ТЕЗА устаревший дискуссии",
    "delete-account": "ВИДАЛИТИ обліковий запис",
    "public-catalog": "Публічні дебати",
    "your-debates": "Ваші дебати",
    "owner-debate": "Відкрити ваші дебати",
    "public-debate": "Відкрити загальнодоступні дебати"
  },
  "vi": {
    "home": "Dialectical Engine — trang chủ",
    "start-debate": "Bắt đầu một cuộc tranh luận",
    "sign-in": "Tài khoản",
    "sign-up": "Tạo tài khoản",
    "help": "Trợ giúp",
    "support-status": "Trạng thái dịch vụ",
    "method": "Cách hoạt động",
    "sample-transcript": "Bản ghi",
    "settings": "Cài đặt",
    "active-sessions": "Đang hoạt động các phiên",
    "privacy-preferences": "Quyền riêng tư",
    "claim-legacy": "Mệnh đề cũ các cuộc tranh luận",
    "delete-account": "Xóa tài khoản",
    "public-catalog": "Các cuộc tranh luận công khai",
    "your-debates": "Các cuộc tranh luận của bạn",
    "owner-debate": "Mở cuộc tranh luận của bạn",
    "public-debate": "Mở cuộc tranh luận công khai"
  },
  "zh": {
    "home": "Dialectical Engine — 首页",
    "start-debate": "开始辩论",
    "sign-in": "账户",
    "sign-up": "创建账户",
    "help": "帮助",
    "support-status": "服务状态",
    "method": "运作方式",
    "sample-transcript": "文字记录",
    "settings": "设置",
    "active-sessions": "已启用 sessions",
    "privacy-preferences": "隐私",
    "claim-legacy": "主张 legacy 辩论",
    "delete-account": "删除 账户",
    "public-catalog": "公开辩论",
    "your-debates": "您的辩论",
    "owner-debate": "打开您的辩论",
    "public-debate": "打开公开辩论"
  }
} as const satisfies Readonly<Record<SupportLanguage, Readonly<Record<Exclude<SupportActionId, "forgot-password">, string>>>>;

export const SUPPORT_UI_LABEL_ALIASES = {
  "ar": {
    "home": [
      "Dialectical Engine — الصفحة الرئيسية"
    ],
    "start-debate": [
      "بدء مناظرة",
      "مناظرة جديدة",
      "بدء جولة"
    ],
    "sign-in": [
      "الحساب"
    ],
    "sign-up": [
      "إنشاء حساب"
    ],
    "help": [
      "المساعدة"
    ],
    "support-status": [
      "حالة الخدمة"
    ],
    "method": [
      "آلية العمل",
      "المنهج"
    ],
    "sample-transcript": [
      "السجلات"
    ],
    "settings": [
      "الإعدادات"
    ],
    "active-sessions": [
      "نشط الجلسات"
    ],
    "privacy-preferences": [
      "الخصوصية"
    ],
    "claim-legacy": [
      "الادعاء قديم المناظرات"
    ],
    "delete-account": [
      "حذف الحساب"
    ],
    "public-catalog": [
      "المناظرات العامة"
    ],
    "your-debates": [
      "مناظراتك"
    ],
    "owner-debate": [
      "فتح مناظرتك"
    ],
    "public-debate": [
      "فتح المناظرة العامة"
    ]
  },
  "bg": {
    "home": [
      "Dialectical Engine — дом"
    ],
    "start-debate": [
      "Започнете дебат",
      "Нов дебат",
      "Започнете кръг"
    ],
    "sign-in": [
      "Профил"
    ],
    "sign-up": [
      "Създаване на профил"
    ],
    "help": [
      "Помощ"
    ],
    "support-status": [
      "Състояние на услугата"
    ],
    "method": [
      "Как работи",
      "Метод"
    ],
    "sample-transcript": [
      "Преписи"
    ],
    "settings": [
      "Настройки"
    ],
    "active-sessions": [
      "Активни сесии"
    ],
    "privacy-preferences": [
      "Поверителност"
    ],
    "claim-legacy": [
      "Заявяване на наследени дебати"
    ],
    "delete-account": [
      "Изтриване на профила"
    ],
    "public-catalog": [
      "Публични дебати"
    ],
    "your-debates": [
      "Вашите дебати"
    ],
    "owner-debate": [
      "Отворете Вашия дебат"
    ],
    "public-debate": [
      "Отворете публичен дебат"
    ]
  },
  "cs": {
    "home": [
      "Dialectical Engine — domů"
    ],
    "start-debate": [
      "Začněte debatu",
      "Nová debata",
      "Začněte kolo"
    ],
    "sign-in": [
      "Účet"
    ],
    "sign-up": [
      "Vytvořit účet"
    ],
    "help": [
      "Pomoc"
    ],
    "support-status": [
      "Stav služby"
    ],
    "method": [
      "Jak to funguje",
      "Metoda"
    ],
    "sample-transcript": [
      "Přepisy"
    ],
    "settings": [
      "Nastavení"
    ],
    "active-sessions": [
      "Aktivní relace"
    ],
    "privacy-preferences": [
      "Soukromí"
    ],
    "claim-legacy": [
      "Převzít starší debaty"
    ],
    "delete-account": [
      "Smazat účet"
    ],
    "public-catalog": [
      "Veřejné debaty"
    ],
    "your-debates": [
      "Vaše debaty"
    ],
    "owner-debate": [
      "Otevřít vaši debatu"
    ],
    "public-debate": [
      "Otevřít veřejnou debatu"
    ]
  },
  "da": {
    "home": [
      "Dialectical Engine — hjem"
    ],
    "start-debate": [
      "Start en debat",
      "Ny debat",
      "Start en runde"
    ],
    "sign-in": [
      "Konto"
    ],
    "sign-up": [
      "Opret en"
    ],
    "help": [
      "Hjælp"
    ],
    "support-status": [
      "Tjenestestatus"
    ],
    "method": [
      "Hvordan det virker",
      "Metode"
    ],
    "sample-transcript": [
      "Afskrifter"
    ],
    "settings": [
      "Indstillinger"
    ],
    "active-sessions": [
      "Aktive sessioner"
    ],
    "privacy-preferences": [
      "Privatliv"
    ],
    "claim-legacy": [
      "Gør krav på ældre debatter"
    ],
    "delete-account": [
      "Slet konto"
    ],
    "public-catalog": [
      "Offentlige debatter"
    ],
    "your-debates": [
      "Dine debatter"
    ],
    "owner-debate": [
      "Åbn din debat"
    ],
    "public-debate": [
      "Åbn offentlig debat"
    ]
  },
  "de": {
    "home": [
      "Dialectical Engine — Startseite"
    ],
    "start-debate": [
      "Debatte beginnen",
      "Neue Debatte",
      "Runde beginnen"
    ],
    "sign-in": [
      "Konto"
    ],
    "sign-up": [
      "erstellen ein"
    ],
    "help": [
      "Hilfe"
    ],
    "support-status": [
      "Dienststatus"
    ],
    "method": [
      "Funktionsweise",
      "Methode"
    ],
    "sample-transcript": [
      "Transkripte"
    ],
    "settings": [
      "Einstellungen"
    ],
    "active-sessions": [
      "aktiv Sitzungen"
    ],
    "privacy-preferences": [
      "Datenschutz"
    ],
    "claim-legacy": [
      "Behauptung Legacy Debatten"
    ],
    "delete-account": [
      "löschen Konto"
    ],
    "public-catalog": [
      "Öffentliche Debatten"
    ],
    "your-debates": [
      "Ihre Debatten"
    ],
    "owner-debate": [
      "Ihre Debatte öffnen"
    ],
    "public-debate": [
      "Öffentliche Debatte öffnen"
    ]
  },
  "el": {
    "home": [
      "Dialectical Engine — αρχική σελίδα"
    ],
    "start-debate": [
      "Έναρξη αντιπαράθεσης",
      "Νέα αντιπαράθεση",
      "Έναρξη γύρου"
    ],
    "sign-in": [
      "Λογαριασμός"
    ],
    "sign-up": [
      "δημιουργία ένα"
    ],
    "help": [
      "Βοήθεια"
    ],
    "support-status": [
      "Κατάσταση υπηρεσίας"
    ],
    "method": [
      "Πώς λειτουργεί",
      "Μέθοδος"
    ],
    "sample-transcript": [
      "Απομαγνητοφωνήσεις"
    ],
    "settings": [
      "Ρυθμίσεις"
    ],
    "active-sessions": [
      "ενεργό περίοδοι σύνδεσης"
    ],
    "privacy-preferences": [
      "απόρρητο"
    ],
    "claim-legacy": [
      "ισχυρισμός παλαιό αντιπαραθέσεις"
    ],
    "delete-account": [
      "διαγραφή λογαριασμός"
    ],
    "public-catalog": [
      "Δημόσιες αντιπαραθέσεις"
    ],
    "your-debates": [
      "Οι αντιπαραθέσεις σας"
    ],
    "owner-debate": [
      "Άνοιγμα της αντιπαράθεσής σας"
    ],
    "public-debate": [
      "Άνοιγμα δημόσιας αντιπαράθεσης"
    ]
  },
  "en": {
    "home": [
      "Dialectical Engine — home"
    ],
    "start-debate": [
      "Start a debate",
      "New debate",
      "Start a round"
    ],
    "sign-in": [
      "Account"
    ],
    "sign-up": [
      "Create one"
    ],
    "help": [
      "Help"
    ],
    "support-status": [
      "Service status"
    ],
    "method": [
      "How it works",
      "Method"
    ],
    "sample-transcript": [
      "Transcripts"
    ],
    "settings": [
      "Settings"
    ],
    "active-sessions": [
      "Active sessions"
    ],
    "privacy-preferences": [
      "Privacy"
    ],
    "claim-legacy": [
      "Claim legacy debates"
    ],
    "delete-account": [
      "Delete account"
    ],
    "public-catalog": [
      "Public debates"
    ],
    "your-debates": [
      "Your debates"
    ],
    "owner-debate": [
      "Open your debate"
    ],
    "public-debate": [
      "Open public debate"
    ]
  },
  "es": {
    "home": [
      "Dialectical Engine — inicio"
    ],
    "start-debate": [
      "Iniciar un debate",
      "Nuevo debate",
      "Iniciar una ronda"
    ],
    "sign-in": [
      "Cuenta"
    ],
    "sign-up": [
      "Cree una"
    ],
    "help": [
      "Ayuda"
    ],
    "support-status": [
      "Estado del servicio"
    ],
    "method": [
      "Cómo funciona",
      "Método"
    ],
    "sample-transcript": [
      "Transcripciones"
    ],
    "settings": [
      "Configuración"
    ],
    "active-sessions": [
      "Ativo sessões"
    ],
    "privacy-preferences": [
      "PRIVACIDAD"
    ],
    "claim-legacy": [
      "AFIRMACIÓN legado debates"
    ],
    "delete-account": [
      "ELIMINAR cuenta"
    ],
    "public-catalog": [
      "Debates públicos"
    ],
    "your-debates": [
      "Sus debates"
    ],
    "owner-debate": [
      "Abrir su debate"
    ],
    "public-debate": [
      "Abrir el debate público"
    ]
  },
  "et": {
    "home": [
      "Dialectical Engine — kodu"
    ],
    "start-debate": [
      "Alustage arutelu",
      "Uus arutelu",
      "Alusta ringi"
    ],
    "sign-in": [
      "konto"
    ],
    "sign-up": [
      "loo üks"
    ],
    "help": [
      "Abi"
    ],
    "support-status": [
      "Teenuse olek"
    ],
    "method": [
      "Kuidas see toimib",
      "meetod"
    ],
    "sample-transcript": [
      "Ärakirjad"
    ],
    "settings": [
      "Seaded"
    ],
    "active-sessions": [
      "aktiivne seansid"
    ],
    "privacy-preferences": [
      "privaatsus"
    ],
    "claim-legacy": [
      "väide pärand väitlused"
    ],
    "delete-account": [
      "kustuta konto"
    ],
    "public-catalog": [
      "Avalikud arutelud"
    ],
    "your-debates": [
      "Teie arutelud"
    ],
    "owner-debate": [
      "Avage oma väitlus"
    ],
    "public-debate": [
      "Avage avalik väitlus"
    ]
  },
  "fi": {
    "home": [
      "Dialectical Engine — etusivu"
    ],
    "start-debate": [
      "Aloita väittely",
      "Uusi väittely",
      "Aloita kierros"
    ],
    "sign-in": [
      "Tili"
    ],
    "sign-up": [
      "luo yksi"
    ],
    "help": [
      "Ohje"
    ],
    "support-status": [
      "Palvelun tila"
    ],
    "method": [
      "Näin se toimii",
      "Menetelmä"
    ],
    "sample-transcript": [
      "Litteroinnit"
    ],
    "settings": [
      "Asetukset"
    ],
    "active-sessions": [
      "aktiivinen istunnot"
    ],
    "privacy-preferences": [
      "tietosuoja"
    ],
    "claim-legacy": [
      "väite vanha väittelyt"
    ],
    "delete-account": [
      "poista tili"
    ],
    "public-catalog": [
      "Julkiset väittelyt"
    ],
    "your-debates": [
      "Omat väittelysi"
    ],
    "owner-debate": [
      "Avaa väittelysi"
    ],
    "public-debate": [
      "Avaa julkinen väittely"
    ]
  },
  "fr": {
    "home": [
      "Dialectical Engine — accueil"
    ],
    "start-debate": [
      "Lancer un débat",
      "Nouveau débat",
      "Commencer une manche"
    ],
    "sign-in": [
      "Compte"
    ],
    "sign-up": [
      "créer un"
    ],
    "help": [
      "Aide"
    ],
    "support-status": [
      "État du service"
    ],
    "method": [
      "Fonctionnement",
      "Méthode"
    ],
    "sample-transcript": [
      "Transcriptions"
    ],
    "settings": [
      "Paramètres"
    ],
    "active-sessions": [
      "actif sessions"
    ],
    "privacy-preferences": [
      "confidentialité"
    ],
    "claim-legacy": [
      "affirmation hérité débats"
    ],
    "delete-account": [
      "supprimer compte"
    ],
    "public-catalog": [
      "Débats publics"
    ],
    "your-debates": [
      "Vos débats"
    ],
    "owner-debate": [
      "Ouvrir votre débat"
    ],
    "public-debate": [
      "Ouvrir le débat public"
    ]
  },
  "ga": {
    "home": [
      "Dialectical Engine — baile"
    ],
    "start-debate": [
      "Tosaigh díospóireacht",
      "Díospóireacht nua",
      "Tosaigh babhta"
    ],
    "sign-in": [
      "Cuntas"
    ],
    "sign-up": [
      "Cruthaigh aon"
    ],
    "help": [
      "Cabhair"
    ],
    "support-status": [
      "Stádas seirbhíse"
    ],
    "method": [
      "Conas a oibríonn sé",
      "Modh"
    ],
    "sample-transcript": [
      "Tras-scríbhinní"
    ],
    "settings": [
      "Socruithe"
    ],
    "active-sessions": [
      "Gníomhach seisiúin"
    ],
    "privacy-preferences": [
      "Príobháideachas"
    ],
    "claim-legacy": [
      "Maíomh oidhreachta díospóireachtaí"
    ],
    "delete-account": [
      "Scrios cuntas"
    ],
    "public-catalog": [
      "Díospóireachtaí poiblí"
    ],
    "your-debates": [
      "Do chuid díospóireachtaí"
    ],
    "owner-debate": [
      "Oscail do dhíospóireacht"
    ],
    "public-debate": [
      "Oscail díospóireacht phoiblí"
    ]
  },
  "he": {
    "home": [
      "Dialectical Engine — דף הבית"
    ],
    "start-debate": [
      "התחלת דיון",
      "דיון חדש",
      "התחלת סבב"
    ],
    "sign-in": [
      "חשבון"
    ],
    "sign-up": [
      "יצירת חשבון"
    ],
    "help": [
      "עזרה"
    ],
    "support-status": [
      "מצב השירות"
    ],
    "method": [
      "איך זה עובד",
      "שיטה"
    ],
    "sample-transcript": [
      "תמלילים"
    ],
    "settings": [
      "הגדרות"
    ],
    "active-sessions": [
      "פעיל הפעלות"
    ],
    "privacy-preferences": [
      "פרטיות"
    ],
    "claim-legacy": [
      "טענה מורשת דיונים"
    ],
    "delete-account": [
      "מחיקה החשבון"
    ],
    "public-catalog": [
      "דיונים ציבוריים"
    ],
    "your-debates": [
      "הדיונים שלך"
    ],
    "owner-debate": [
      "פתיחת הדיון שלך"
    ],
    "public-debate": [
      "פתיחת דיון ציבורי"
    ]
  },
  "hi": {
    "home": [
      "Dialectical Engine — मुख्य पृष्ठ"
    ],
    "start-debate": [
      "बहस शुरू करें",
      "नई बहस",
      "दौर शुरू करें"
    ],
    "sign-in": [
      "खाता"
    ],
    "sign-up": [
      "एक बनाएँ"
    ],
    "help": [
      "सहायता"
    ],
    "support-status": [
      "सेवा की स्थिति"
    ],
    "method": [
      "यह कैसे काम करता है",
      "विधि"
    ],
    "sample-transcript": [
      "प्रतिलिपियाँ"
    ],
    "settings": [
      "सेटिंग"
    ],
    "active-sessions": [
      "सक्रिय sessions"
    ],
    "privacy-preferences": [
      "गोपनीयता"
    ],
    "claim-legacy": [
      "दावा legacy बहसें"
    ],
    "delete-account": [
      "हटाएँ खाता"
    ],
    "public-catalog": [
      "सार्वजनिक बहसें"
    ],
    "your-debates": [
      "आपकी बहसें"
    ],
    "owner-debate": [
      "अपनी बहस खोलें"
    ],
    "public-debate": [
      "सार्वजनिक बहस खोलें"
    ]
  },
  "hr": {
    "home": [
      "Dialectical Engine — dom"
    ],
    "start-debate": [
      "Započnite raspravu",
      "Nova rasprava",
      "Započni rundu"
    ],
    "sign-in": [
      "Račun"
    ],
    "sign-up": [
      "Izradite ga"
    ],
    "help": [
      "Pomoć"
    ],
    "support-status": [
      "Stanje usluge"
    ],
    "method": [
      "Kako radi",
      "Metoda"
    ],
    "sample-transcript": [
      "Prijepisi"
    ],
    "settings": [
      "Postavke"
    ],
    "active-sessions": [
      "Aktivne sesije"
    ],
    "privacy-preferences": [
      "Privatnost"
    ],
    "claim-legacy": [
      "Preuzmi naslijeđene rasprave"
    ],
    "delete-account": [
      "Izbriši račun"
    ],
    "public-catalog": [
      "Javne rasprave"
    ],
    "your-debates": [
      "Vaše rasprave"
    ],
    "owner-debate": [
      "Otvorite svoju raspravu"
    ],
    "public-debate": [
      "Otvorite javnu raspravu"
    ]
  },
  "hu": {
    "home": [
      "Dialectical Engine — kezdőlap"
    ],
    "start-debate": [
      "Vita indítása",
      "Új vita",
      "Forduló indítása"
    ],
    "sign-in": [
      "Fiók"
    ],
    "sign-up": [
      "Létrehozás egy"
    ],
    "help": [
      "Súgó"
    ],
    "support-status": [
      "Szolgáltatás állapota"
    ],
    "method": [
      "Hogyan működik?",
      "Módszer"
    ],
    "sample-transcript": [
      "Átiratok"
    ],
    "settings": [
      "Beállítások"
    ],
    "active-sessions": [
      "Aktív munkamenetek"
    ],
    "privacy-preferences": [
      "Adatvédelem"
    ],
    "claim-legacy": [
      "Állítás örökölt viták"
    ],
    "delete-account": [
      "Törlés fiók"
    ],
    "public-catalog": [
      "Nyilvános viták"
    ],
    "your-debates": [
      "Saját viták"
    ],
    "owner-debate": [
      "Vita megnyitása"
    ],
    "public-debate": [
      "Nyilvános vita megnyitása"
    ]
  },
  "id": {
    "home": [
      "Dialectical Engine — beranda"
    ],
    "start-debate": [
      "Mulai debat",
      "Debat baru",
      "Mulai ronde"
    ],
    "sign-in": [
      "Akun"
    ],
    "sign-up": [
      "Buat akun"
    ],
    "help": [
      "Bantuan"
    ],
    "support-status": [
      "Status layanan"
    ],
    "method": [
      "Cara kerjanya",
      "Metode"
    ],
    "sample-transcript": [
      "Transkrip"
    ],
    "settings": [
      "Pengaturan"
    ],
    "active-sessions": [
      "aktif sessions"
    ],
    "privacy-preferences": [
      "privasi"
    ],
    "claim-legacy": [
      "klaim legacy debat"
    ],
    "delete-account": [
      "hapus akun"
    ],
    "public-catalog": [
      "Debat publik"
    ],
    "your-debates": [
      "Debat Anda"
    ],
    "owner-debate": [
      "Buka debat Anda"
    ],
    "public-debate": [
      "Buka debat publik"
    ]
  },
  "it": {
    "home": [
      "Dialectical Engine — pagina iniziale"
    ],
    "start-debate": [
      "Avvia un dibattito",
      "Nuovo dibattito",
      "Inizia un round"
    ],
    "sign-in": [
      "Account"
    ],
    "sign-up": [
      "Crea uno"
    ],
    "help": [
      "Aiuto"
    ],
    "support-status": [
      "Stato del servizio"
    ],
    "method": [
      "Come funziona",
      "Metodo"
    ],
    "sample-transcript": [
      "Trascrizioni"
    ],
    "settings": [
      "Impostazioni"
    ],
    "active-sessions": [
      "Attivo sessioni"
    ],
    "privacy-preferences": [
      "Privacy"
    ],
    "claim-legacy": [
      "Affermazione precedente dibattiti"
    ],
    "delete-account": [
      "Elimina account"
    ],
    "public-catalog": [
      "Dibattiti pubblici"
    ],
    "your-debates": [
      "I tuoi dibattiti"
    ],
    "owner-debate": [
      "Apri il tuo dibattito"
    ],
    "public-debate": [
      "Apri dibattito pubblico"
    ]
  },
  "ja": {
    "home": [
      "Dialectical Engine — ホーム"
    ],
    "start-debate": [
      "ディベートを開始",
      "新しいディベート",
      "ラウンドを開始"
    ],
    "sign-in": [
      "アカウント"
    ],
    "sign-up": [
      "作成する"
    ],
    "help": [
      "ヘルプ"
    ],
    "support-status": [
      "サービス状況"
    ],
    "method": [
      "仕組み",
      "方式"
    ],
    "sample-transcript": [
      "記録"
    ],
    "settings": [
      "設定"
    ],
    "active-sessions": [
      "有効 sessions"
    ],
    "privacy-preferences": [
      "プライバシー"
    ],
    "claim-legacy": [
      "主張 legacy 討論"
    ],
    "delete-account": [
      "削除 アカウント"
    ],
    "public-catalog": [
      "公開ディベート"
    ],
    "your-debates": [
      "自分のディベート"
    ],
    "owner-debate": [
      "自分のディベートを開く"
    ],
    "public-debate": [
      "公開ディベートを開く"
    ]
  },
  "ko": {
    "home": [
      "Dialectical Engine — 홈"
    ],
    "start-debate": [
      "토론 시작",
      "새 토론",
      "라운드 시작"
    ],
    "sign-in": [
      "계정"
    ],
    "sign-up": [
      "계정 만들기"
    ],
    "help": [
      "도움말"
    ],
    "support-status": [
      "서비스 상태"
    ],
    "method": [
      "작동 방식",
      "방식"
    ],
    "sample-transcript": [
      "기록"
    ],
    "settings": [
      "설정"
    ],
    "active-sessions": [
      "활성 sessions"
    ],
    "privacy-preferences": [
      "개인정보"
    ],
    "claim-legacy": [
      "주장 legacy 토론"
    ],
    "delete-account": [
      "삭제 계정"
    ],
    "public-catalog": [
      "공개 토론"
    ],
    "your-debates": [
      "내 토론"
    ],
    "owner-debate": [
      "내 토론 열기"
    ],
    "public-debate": [
      "공개 토론 열기"
    ]
  },
  "lt": {
    "home": [
      "Dialectical Engine — pradžia"
    ],
    "start-debate": [
      "Pradėti debatus",
      "Nauji debatai",
      "Pradėti raundą"
    ],
    "sign-in": [
      "Paskyra"
    ],
    "sign-up": [
      "Sukurti vienas"
    ],
    "help": [
      "Pagalba"
    ],
    "support-status": [
      "Paslaugos būsena"
    ],
    "method": [
      "Kaip tai veikia",
      "Metodas"
    ],
    "sample-transcript": [
      "Stenogramos"
    ],
    "settings": [
      "Nuostatos"
    ],
    "active-sessions": [
      "Aktyvus sesijos"
    ],
    "privacy-preferences": [
      "Privatumas"
    ],
    "claim-legacy": [
      "Teiginys senasis debatai"
    ],
    "delete-account": [
      "Ištrinti paskyra"
    ],
    "public-catalog": [
      "Vieši debatai"
    ],
    "your-debates": [
      "Jūsų debatai"
    ],
    "owner-debate": [
      "Atverti savo debatus"
    ],
    "public-debate": [
      "Atverti viešus debatus"
    ]
  },
  "lv": {
    "home": [
      "Dialectical Engine — sākums"
    ],
    "start-debate": [
      "Sākt debates",
      "Jaunas debates",
      "Sākt raundu"
    ],
    "sign-in": [
      "Konts"
    ],
    "sign-up": [
      "Izveidot viens"
    ],
    "help": [
      "Palīdzība"
    ],
    "support-status": [
      "Pakalpojuma statuss"
    ],
    "method": [
      "Kā tas darbojas",
      "Metode"
    ],
    "sample-transcript": [
      "Transkripti"
    ],
    "settings": [
      "Iestatījumi"
    ],
    "active-sessions": [
      "Aktīvs sesijas"
    ],
    "privacy-preferences": [
      "Privātums"
    ],
    "claim-legacy": [
      "Apgalvojums mantots debates"
    ],
    "delete-account": [
      "Dzēst konts"
    ],
    "public-catalog": [
      "Publiskās debates"
    ],
    "your-debates": [
      "Jūsu debates"
    ],
    "owner-debate": [
      "Atvērt savas debates"
    ],
    "public-debate": [
      "Atvērt publiskās debates"
    ]
  },
  "mt": {
    "home": [
      "Dialectical Engine — paġna ewlenija"
    ],
    "start-debate": [
      "Ibda dibattitu",
      "Dibattitu ġdid",
      "Ibda rawnd"
    ],
    "sign-in": [
      "Kont"
    ],
    "sign-up": [
      "Oħloq wieħed"
    ],
    "help": [
      "Għajnuna"
    ],
    "support-status": [
      "Status tas-servizz"
    ],
    "method": [
      "Kif jaħdem",
      "Metodu"
    ],
    "sample-transcript": [
      "Traskrizzjonijiet"
    ],
    "settings": [
      "Issettjar"
    ],
    "active-sessions": [
      "Attiv sessjonijiet"
    ],
    "privacy-preferences": [
      "Privatezza"
    ],
    "claim-legacy": [
      "Pretensjoni storiku dibattiti"
    ],
    "delete-account": [
      "Ħassar kont"
    ],
    "public-catalog": [
      "Dibattiti pubbliċi"
    ],
    "your-debates": [
      "Id-dibattiti tiegħek"
    ],
    "owner-debate": [
      "Iftaħ id-dibattitu tiegħek"
    ],
    "public-debate": [
      "Iftaħ dibattitu pubbliku"
    ]
  },
  "nl": {
    "home": [
      "Dialectical Engine — thuis"
    ],
    "start-debate": [
      "Begin een debat",
      "Nieuw debat",
      "Begin een ronde"
    ],
    "sign-in": [
      "Account"
    ],
    "sign-up": [
      "Maak er een aan"
    ],
    "help": [
      "Hulp"
    ],
    "support-status": [
      "Servicestatus"
    ],
    "method": [
      "Hoe het werkt",
      "Methode"
    ],
    "sample-transcript": [
      "Transcripties"
    ],
    "settings": [
      "Instellingen"
    ],
    "active-sessions": [
      "Actieve sessies"
    ],
    "privacy-preferences": [
      "Privacy"
    ],
    "claim-legacy": [
      "Eerdere debatten koppelen"
    ],
    "delete-account": [
      "Account verwijderen"
    ],
    "public-catalog": [
      "Publieke debatten"
    ],
    "your-debates": [
      "Jouw debatten"
    ],
    "owner-debate": [
      "Uw debat openen"
    ],
    "public-debate": [
      "Openbaar debat openen"
    ]
  },
  "pl": {
    "home": [
      "Dialectical Engine — strona główna"
    ],
    "start-debate": [
      "Rozpocznij debatę",
      "Nowa debata",
      "Rozpocznij rundę"
    ],
    "sign-in": [
      "Konto"
    ],
    "sign-up": [
      "Utwórz jeden"
    ],
    "help": [
      "Pomoc"
    ],
    "support-status": [
      "Stan usługi"
    ],
    "method": [
      "Jak to działa",
      "Metoda"
    ],
    "sample-transcript": [
      "Transkrypcje"
    ],
    "settings": [
      "Ustawienia"
    ],
    "active-sessions": [
      "Aktywny sesje"
    ],
    "privacy-preferences": [
      "Prywatność"
    ],
    "claim-legacy": [
      "Teza starszy debaty"
    ],
    "delete-account": [
      "Usuń konto"
    ],
    "public-catalog": [
      "Debaty publiczne"
    ],
    "your-debates": [
      "Twoje debaty"
    ],
    "owner-debate": [
      "Otwórz swoją debatę"
    ],
    "public-debate": [
      "Otwórz debatę publiczną"
    ]
  },
  "pt": {
    "home": [
      "Dialectical Engine — início"
    ],
    "start-debate": [
      "Iniciar um debate",
      "Novo debate",
      "Iniciar uma ronda"
    ],
    "sign-in": [
      "Conta"
    ],
    "sign-up": [
      "Criar um"
    ],
    "help": [
      "Ajuda"
    ],
    "support-status": [
      "Estado do serviço"
    ],
    "method": [
      "Como funciona",
      "Método"
    ],
    "sample-transcript": [
      "Transcrições"
    ],
    "settings": [
      "Definições"
    ],
    "active-sessions": [
      "Ativo sessões"
    ],
    "privacy-preferences": [
      "Privacidade"
    ],
    "claim-legacy": [
      "Afirmação legado debates"
    ],
    "delete-account": [
      "Eliminar conta"
    ],
    "public-catalog": [
      "Debates públicos"
    ],
    "your-debates": [
      "Os seus debates"
    ],
    "owner-debate": [
      "Abrir o seu debate"
    ],
    "public-debate": [
      "Abrir debate público"
    ]
  },
  "ro": {
    "home": [
      "Dialectical Engine — pagina principală"
    ],
    "start-debate": [
      "Începeți o dezbatere",
      "Dezbatere nouă",
      "Începeți o rundă"
    ],
    "sign-in": [
      "Cont"
    ],
    "sign-up": [
      "Creați un"
    ],
    "help": [
      "Ajutor"
    ],
    "support-status": [
      "Starea serviciului"
    ],
    "method": [
      "Cum funcționează",
      "Metodă"
    ],
    "sample-transcript": [
      "Transcrieri"
    ],
    "settings": [
      "Setări"
    ],
    "active-sessions": [
      "Activ sesiuni"
    ],
    "privacy-preferences": [
      "Confidențialitate"
    ],
    "claim-legacy": [
      "Afirmație moștenit dezbateri"
    ],
    "delete-account": [
      "Ștergeți cont"
    ],
    "public-catalog": [
      "Dezbateri publice"
    ],
    "your-debates": [
      "Dezbaterile dvs."
    ],
    "owner-debate": [
      "Deschideți dezbaterea dumneavoastră"
    ],
    "public-debate": [
      "Deschideți dezbaterea publică"
    ]
  },
  "ru": {
    "home": [
      "Dialectical Engine — главная"
    ],
    "start-debate": [
      "Начать дискуссию",
      "Новая дискуссия",
      "Начать раунд"
    ],
    "sign-in": [
      "Учётная запись"
    ],
    "sign-up": [
      "Создать один"
    ],
    "help": [
      "Помощь"
    ],
    "support-status": [
      "Состояние сервиса"
    ],
    "method": [
      "Как это работает",
      "Метод"
    ],
    "sample-transcript": [
      "Стенограммы"
    ],
    "settings": [
      "Настройки"
    ],
    "active-sessions": [
      "Активный сеансы"
    ],
    "privacy-preferences": [
      "Конфиденциальность"
    ],
    "claim-legacy": [
      "Тезис устаревший дискуссии"
    ],
    "delete-account": [
      "Удалить учётная запись"
    ],
    "public-catalog": [
      "Публичные дискуссии"
    ],
    "your-debates": [
      "Ваши дискуссии"
    ],
    "owner-debate": [
      "Открыть ваши дебаты"
    ],
    "public-debate": [
      "Открыть общедоступные дебаты"
    ]
  },
  "sk": {
    "home": [
      "Dialectical Engine — domovská stránka"
    ],
    "start-debate": [
      "Začať diskusiu",
      "Nová diskusia",
      "Začať kolo"
    ],
    "sign-in": [
      "Účet"
    ],
    "sign-up": [
      "Vytvoriť účet"
    ],
    "help": [
      "Pomoc"
    ],
    "support-status": [
      "Stav služby"
    ],
    "method": [
      "Ako to funguje",
      "Metóda"
    ],
    "sample-transcript": [
      "Prepisy"
    ],
    "settings": [
      "Nastavenia"
    ],
    "active-sessions": [
      "Aktivní relácia"
    ],
    "privacy-preferences": [
      "SÚKROMIE"
    ],
    "claim-legacy": [
      "Prevzít starší diskusie"
    ],
    "delete-account": [
      "Smazat účet"
    ],
    "public-catalog": [
      "Verejné diskusie"
    ],
    "your-debates": [
      "Vaše diskusie"
    ],
    "owner-debate": [
      "Otvoriť vašu diskusiu"
    ],
    "public-debate": [
      "Otvoriť verejnú diskusiu"
    ]
  },
  "sl": {
    "home": [
      "Dialectical Engine — domača stran"
    ],
    "start-debate": [
      "Začni razpravo",
      "Nova razprava",
      "Začni krog"
    ],
    "sign-in": [
      "Račun"
    ],
    "sign-up": [
      "Ustvarite ga"
    ],
    "help": [
      "Pomoč"
    ],
    "support-status": [
      "Stanje storitve"
    ],
    "method": [
      "Kako deluje",
      "Metoda"
    ],
    "sample-transcript": [
      "Prepisi"
    ],
    "settings": [
      "Nastavitve"
    ],
    "active-sessions": [
      "Aktivne sesije"
    ],
    "privacy-preferences": [
      "ZASEBNOST"
    ],
    "claim-legacy": [
      "Preuzmi naslijedene razprave"
    ],
    "delete-account": [
      "IZBRIŠI račun"
    ],
    "public-catalog": [
      "Javne razprave"
    ],
    "your-debates": [
      "Vaše razprave"
    ],
    "owner-debate": [
      "Odpri svojo razpravo"
    ],
    "public-debate": [
      "Odpri javno razpravo"
    ]
  },
  "sv": {
    "home": [
      "Dialectical Engine — startsida"
    ],
    "start-debate": [
      "Starta en debatt",
      "Ny debatt",
      "Starta en omgång"
    ],
    "sign-in": [
      "Konto"
    ],
    "sign-up": [
      "Skapa ett"
    ],
    "help": [
      "Hjälp"
    ],
    "support-status": [
      "Tjänstestatus"
    ],
    "method": [
      "Så fungerar det",
      "Metod"
    ],
    "sample-transcript": [
      "Transkriptioner"
    ],
    "settings": [
      "Inställningar"
    ],
    "active-sessions": [
      "Aktive sessioner"
    ],
    "privacy-preferences": [
      "INTEGRITET"
    ],
    "claim-legacy": [
      "Gör krav på äldre debatter"
    ],
    "delete-account": [
      "RADERA konto"
    ],
    "public-catalog": [
      "Offentliga debatter"
    ],
    "your-debates": [
      "Dina debatter"
    ],
    "owner-debate": [
      "Öppna din debatt"
    ],
    "public-debate": [
      "Öppna offentlig debatt"
    ]
  },
  "tr": {
    "home": [
      "Dialectical Engine — ana sayfa"
    ],
    "start-debate": [
      "Tartışma başlat",
      "Yeni tartışma",
      "Tur başlat"
    ],
    "sign-in": [
      "Hesap"
    ],
    "sign-up": [
      "Hesap oluştur"
    ],
    "help": [
      "Yardım"
    ],
    "support-status": [
      "Hizmet durumu"
    ],
    "method": [
      "Nasıl çalışır",
      "Yöntem"
    ],
    "sample-transcript": [
      "Tutanaklar"
    ],
    "settings": [
      "Ayarlar"
    ],
    "active-sessions": [
      "Etkin oturumlar"
    ],
    "privacy-preferences": [
      "Gizlilik"
    ],
    "claim-legacy": [
      "İddia eski tartışmalar"
    ],
    "delete-account": [
      "Sil hesap"
    ],
    "public-catalog": [
      "Herkese açık tartışmalar"
    ],
    "your-debates": [
      "Tartışmalarınız"
    ],
    "owner-debate": [
      "Tartışmanızı aç"
    ],
    "public-debate": [
      "Herkese açık tartışmayı aç"
    ]
  },
  "uk": {
    "home": [
      "Dialectical Engine — головна"
    ],
    "start-debate": [
      "Почати дебати",
      "Нові дебати",
      "Почати раунд"
    ],
    "sign-in": [
      "Обліковий запис"
    ],
    "sign-up": [
      "Створити"
    ],
    "help": [
      "Довідка"
    ],
    "support-status": [
      "Стан сервісу"
    ],
    "method": [
      "Як це працює",
      "Метод"
    ],
    "sample-transcript": [
      "Стенограми"
    ],
    "settings": [
      "Налаштування"
    ],
    "active-sessions": [
      "Активний сеанси"
    ],
    "privacy-preferences": [
      "КОНФІДЕНЦІЙНІСТЬ"
    ],
    "claim-legacy": [
      "ТЕЗА устаревший дискуссии"
    ],
    "delete-account": [
      "ВИДАЛИТИ обліковий запис"
    ],
    "public-catalog": [
      "Публічні дебати"
    ],
    "your-debates": [
      "Ваші дебати"
    ],
    "owner-debate": [
      "Відкрити ваші дебати"
    ],
    "public-debate": [
      "Відкрити загальнодоступні дебати"
    ]
  },
  "vi": {
    "home": [
      "Dialectical Engine — trang chủ"
    ],
    "start-debate": [
      "Bắt đầu một cuộc tranh luận",
      "Cuộc tranh luận mới",
      "Bắt đầu một vòng"
    ],
    "sign-in": [
      "Tài khoản"
    ],
    "sign-up": [
      "Tạo tài khoản"
    ],
    "help": [
      "Trợ giúp"
    ],
    "support-status": [
      "Trạng thái dịch vụ"
    ],
    "method": [
      "Cách hoạt động",
      "Phương pháp"
    ],
    "sample-transcript": [
      "Bản ghi"
    ],
    "settings": [
      "Cài đặt"
    ],
    "active-sessions": [
      "Đang hoạt động các phiên"
    ],
    "privacy-preferences": [
      "Quyền riêng tư"
    ],
    "claim-legacy": [
      "Mệnh đề cũ các cuộc tranh luận"
    ],
    "delete-account": [
      "Xóa tài khoản"
    ],
    "public-catalog": [
      "Các cuộc tranh luận công khai"
    ],
    "your-debates": [
      "Các cuộc tranh luận của bạn"
    ],
    "owner-debate": [
      "Mở cuộc tranh luận của bạn"
    ],
    "public-debate": [
      "Mở cuộc tranh luận công khai"
    ]
  },
  "zh": {
    "home": [
      "Dialectical Engine — 首页"
    ],
    "start-debate": [
      "开始辩论",
      "新辩论",
      "开始一轮"
    ],
    "sign-in": [
      "账户"
    ],
    "sign-up": [
      "创建账户"
    ],
    "help": [
      "帮助"
    ],
    "support-status": [
      "服务状态"
    ],
    "method": [
      "运作方式",
      "方法"
    ],
    "sample-transcript": [
      "文字记录"
    ],
    "settings": [
      "设置"
    ],
    "active-sessions": [
      "已启用 sessions"
    ],
    "privacy-preferences": [
      "隐私"
    ],
    "claim-legacy": [
      "主张 legacy 辩论"
    ],
    "delete-account": [
      "删除 账户"
    ],
    "public-catalog": [
      "公开辩论"
    ],
    "your-debates": [
      "您的辩论"
    ],
    "owner-debate": [
      "打开您的辩论"
    ],
    "public-debate": [
      "打开公开辩论"
    ]
  }
} as const satisfies Readonly<Record<SupportLanguage, Readonly<Record<Exclude<SupportActionId, "forgot-password">, readonly string[]>>>>;

export const SUPPORT_TOPIC_PROMPTS = {
  "ar": [
    {
      "prompt": "كيف أبدأ مناظرتي الأولى؟",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "ما دلالة علامة الشرط؟",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "كيف أقرأ الدرجات والمراجعات والأحكام؟",
      "sourceIds": []
    },
    {
      "prompt": "هل يمكنني إلغاء نشر مناظرة؟",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "كيف أدير MFA والجلسات النشطة؟",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "كيف تتم حماية محادثة الدعم الخاصة بي؟",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "bg": [
    {
      "prompt": "Как да започна първия си дебат?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Какво означава знакът за условие?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Как да разчитам оценките, прегледите и решенията?",
      "sourceIds": []
    },
    {
      "prompt": "Мога ли да отменя публикуването на дебат?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Как да управлявам MFA и активните сесии?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Как е защитен разговорът ми с поддръжката?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "cs": [
    {
      "prompt": "Jak zahájím svou první debatu?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Co znamená značka podmínky?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Jak mám číst skóre, hodnocení a verdikty?",
      "sourceIds": []
    },
    {
      "prompt": "Mohu zrušit publikování debaty?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Jak mohu spravovat MFA a aktivní relace?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Jak je chráněna moje konverzace s podporou?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "da": [
    {
      "prompt": "Hvordan starter jeg min første debat?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Hvad betyder en betingelsesmarkering?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Hvordan skal jeg læse point, vurderinger og afgørelser?",
      "sourceIds": []
    },
    {
      "prompt": "Kan jeg afpublicere en debat?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Hvordan administrerer jeg MFA og aktive sessioner?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Hvordan beskyttes min supportsamtale?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "de": [
    {
      "prompt": "Wie starte ich meine erste Debatte?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Was bedeutet eine Bedingungsmarkierung?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Wie sind Punktzahlen, Bewertungen und Urteile zu lesen?",
      "sourceIds": []
    },
    {
      "prompt": "Kann ich die Veröffentlichung einer Debatte zurücknehmen?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Wie verwalte ich MFA und aktive Sitzungen?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Wie wird mein Supportgespräch geschützt?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "el": [
    {
      "prompt": "Πώς μπορώ να ξεκινήσω την πρώτη μου αντιπαράθεση;",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Τι σημαίνει μια ένδειξη συνθήκης;",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Πώς πρέπει να διαβάζω τις βαθμολογίες, τις αξιολογήσεις και τις ετυμηγορίες;",
      "sourceIds": []
    },
    {
      "prompt": "Μπορώ να αναιρέσω τη δημοσίευση μιας αντιπαράθεσης;",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Πώς διαχειρίζομαι το MFA και τις ενεργές συνεδρίες;",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Πώς προστατεύεται η συνομιλία μου με την υποστήριξη;",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "en": [
    {
      "prompt": "How do I start my first debate?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "What does a condition mark mean?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "How should I read scores, reviews, and verdicts?",
      "sourceIds": []
    },
    {
      "prompt": "Can I unpublish a debate?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "How do I manage MFA and active sessions?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "How is my support conversation protected?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "es": [
    {
      "prompt": "¿Cómo inicio mi primer debate?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "¿Qué significa una marca de condición?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "¿Cómo debo interpretar las puntuaciones, las revisiones y los veredictos?",
      "sourceIds": []
    },
    {
      "prompt": "¿Puedo retirar la publicación de un debate?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "¿Cómo gestiono MFA y las sesiones activas?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "¿Cómo se protege mi conversación con soporte?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "et": [
    {
      "prompt": "Kuidas alustada oma esimest väitlust?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Mida tähendab tingimusmärge?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kuidas lugeda punkte, hinnanguid ja otsuseid?",
      "sourceIds": []
    },
    {
      "prompt": "Kas ma saan väitluse avaldamise tühistada?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kuidas hallata MFA-d ja aktiivseid seansse?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kuidas on minu vestlus kasutajatoega kaitstud?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "fi": [
    {
      "prompt": "Miten aloitan ensimmäisen väittelyni?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Mitä ehtomerkintä tarkoittaa?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kuinka pisteitä, arvioita ja ratkaisuja tulisi tulkita?",
      "sourceIds": []
    },
    {
      "prompt": "Voinko perua väittelyn julkaisun?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Miten hallitsen MFA:ta ja aktiivisia istuntoja?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Miten tukikeskusteluni suojataan?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "fr": [
    {
      "prompt": "Comment lancer mon premier débat ?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Que signifie un marqueur de condition ?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Comment interpréter les scores, les évaluations et les verdicts ?",
      "sourceIds": []
    },
    {
      "prompt": "Puis-je dépublier un débat ?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Comment gérer le MFA et les sessions actives ?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Comment ma conversation avec l’assistance est-elle protégée ?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "ga": [
    {
      "prompt": "Conas a chuirim tús le mo chéad díospóireacht?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Cad is brí le marc coinníll?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Conas ba cheart dom scóir, léirmheasanna agus breithiúnais a léamh?",
      "sourceIds": []
    },
    {
      "prompt": "An féidir liom díospóireacht a dhífhoilsiú?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Conas a bhainistím MFA agus seisiúin ghníomhacha?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Conas a chosnaítear mo chomhrá tacaíochta?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "he": [
    {
      "prompt": "כיצד מתחילים דיון ראשון?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "מה המשמעות של סימון תנאי?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "כיצד יש לקרוא ציונים, ביקורות והכרעות?",
      "sourceIds": []
    },
    {
      "prompt": "האם ניתן לבטל פרסום של דיון?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "כיצד מנהלים MFA והפעלות פעילות?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "כיצד מוגנת שיחת התמיכה שלי?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "hi": [
    {
      "prompt": "अपनी पहली बहस कैसे शुरू करूँ?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "शर्त चिह्न का क्या अर्थ है?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "अंकों, समीक्षाओं और निर्णयों को कैसे समझूँ?",
      "sourceIds": []
    },
    {
      "prompt": "क्या बहस का प्रकाशन रद्द किया जा सकता है?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "MFA और सक्रिय सत्र कैसे प्रबंधित किए जाते हैं?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "मेरी सहायता बातचीत को कैसे सुरक्षित रखा जाता है?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "hr": [
    {
      "prompt": "Kako započeti prvu raspravu?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Što znači oznaka uvjeta?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kako tumačiti ocjene, osvrte i odluke?",
      "sourceIds": []
    },
    {
      "prompt": "Mogu li povući objavu rasprave?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kako upravljati MFA-om i aktivnim sesijama?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kako je zaštićen moj razgovor s podrškom?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "hu": [
    {
      "prompt": "Hogyan indíthatom el az első vitámat?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Mit jelent a feltételjelölés?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Hogyan értelmezzem a pontszámokat, értékeléseket és döntéseket?",
      "sourceIds": []
    },
    {
      "prompt": "Visszavonhatom egy vita közzétételét?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Hogyan kezelhetem az MFA-t és az aktív munkameneteket?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Hogyan védjük az ügyfélszolgálati beszélgetésemet?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "id": [
    {
      "prompt": "Bagaimana cara memulai debat pertama saya?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Apa arti tanda kondisi?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Bagaimana cara membaca skor, ulasan, dan putusan?",
      "sourceIds": []
    },
    {
      "prompt": "Dapatkah saya membatalkan penerbitan debat?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Bagaimana cara mengelola MFA dan sesi aktif?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Bagaimana percakapan dukungan saya dilindungi?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "it": [
    {
      "prompt": "Come posso avviare il mio primo dibattito?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Che cosa significa un indicatore di condizione?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Come si interpretano punteggi, revisioni e verdetti?",
      "sourceIds": []
    },
    {
      "prompt": "Posso annullare la pubblicazione di un dibattito?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Come gestisco l'MFA e le sessioni attive?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Come viene protetta la mia conversazione con il supporto?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "ja": [
    {
      "prompt": "最初のディベートを始めるにはどうすればよいですか？",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "条件マークとは何ですか？",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "スコア、レビュー、判定はどう読めばよいですか？",
      "sourceIds": []
    },
    {
      "prompt": "ディベートの公開を取り消せますか？",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "MFAとアクティブなセッションを管理するには？",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "サポートでの会話はどのように保護されますか？",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "ko": [
    {
      "prompt": "첫 토론을 어떻게 시작하나요?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "조건 표시의 의미는 무엇인가요?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "점수, 검토 및 판정은 어떻게 해석하나요?",
      "sourceIds": []
    },
    {
      "prompt": "토론 게시를 취소할 수 있나요?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "MFA와 활성 세션을 어떻게 관리하나요?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "지원 대화는 어떻게 보호되나요?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "lt": [
    {
      "prompt": "Kaip pradėti pirmuosius debatus?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Ką reiškia sąlygos žyma?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kaip vertinti balus, apžvalgas ir verdiktus?",
      "sourceIds": []
    },
    {
      "prompt": "Ar galiu atšaukti debatų paskelbimą?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kaip valdyti MFA ir aktyvius seansus?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kaip saugomas mano pokalbis su pagalbos tarnyba?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "lv": [
    {
      "prompt": "Kā sākt pirmās debates?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Ko nozīmē nosacījuma atzīme?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kā interpretēt vērtējumus, pārskatus un spriedumus?",
      "sourceIds": []
    },
    {
      "prompt": "Vai varu atcelt debašu publicēšanu?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kā pārvaldīt MFA un aktīvās sesijas?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kā tiek aizsargāta mana saruna ar atbalsta dienestu?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "mt": [
    {
      "prompt": "Kif nibda l-ewwel dibattitu tiegħi?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Xi tfisser marka ta' kundizzjoni?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kif għandi naqra l-punteġġi, ir-rieżamijiet u l-verdetti?",
      "sourceIds": []
    },
    {
      "prompt": "Nista' nneħħi dibattitu mill-pubblikazzjoni?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kif nimmaniġġja l-MFA u s-sessjonijiet attivi?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kif tiġi protetta l-konverżazzjoni tiegħi mal-appoġġ?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "nl": [
    {
      "prompt": "Hoe start ik mijn eerste debat?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Wat betekent een voorwaardemarkering?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Hoe moet ik scores, beoordelingen en oordelen lezen?",
      "sourceIds": []
    },
    {
      "prompt": "Kan ik de publicatie van een debat intrekken?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Hoe beheer ik MFA en actieve sessies?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Hoe wordt mijn gesprek met ondersteuning beschermd?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "pl": [
    {
      "prompt": "Jak rozpocząć pierwszą debatę?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Co oznacza znacznik warunku?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Jak interpretować punkty, recenzje i werdykty?",
      "sourceIds": []
    },
    {
      "prompt": "Czy mogę cofnąć publikację debaty?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Jak zarządzać MFA i aktywnymi sesjami?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Jak chroniona jest moja rozmowa z pomocą techniczną?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "pt": [
    {
      "prompt": "Como inicio o meu primeiro debate?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "O que significa um marcador de condição?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Como devo interpretar pontuações, análises e veredictos?",
      "sourceIds": []
    },
    {
      "prompt": "Posso retirar a publicação de um debate?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Como posso gerir a MFA e as sessões ativas?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Como é protegida a minha conversa com o apoio?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "ro": [
    {
      "prompt": "Cum încep prima mea dezbatere?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Ce înseamnă un marcaj de condiție?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Cum ar trebui să interpretez punctajele, evaluările și verdictele?",
      "sourceIds": []
    },
    {
      "prompt": "Pot anula publicarea unei dezbateri?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Cum gestionez MFA și sesiunile active?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Cum este protejată conversația mea cu serviciul de asistență?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "ru": [
    {
      "prompt": "Как начать свои первые дебаты?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Что означает метка условия?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Как читать оценки, рецензии и вердикты?",
      "sourceIds": []
    },
    {
      "prompt": "Можно ли отменить публикацию дебатов?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Как управлять MFA и активными сеансами?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Как защищена моя переписка со службой поддержки?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "sk": [
    {
      "prompt": "Ako začnem svoju prvú diskusiu?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Čo znamená značka podmienky?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Ako mám čítať skóre, posudky a verdikty?",
      "sourceIds": []
    },
    {
      "prompt": "Môžem zrušiť zverejnenie diskusie?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Ako spravujem MFA a aktívne relácie?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Ako je chránená moja konverzácia s podporou?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "sl": [
    {
      "prompt": "Kako začnem svojo prvo razpravo?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Kaj pomeni oznaka pogoja?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Kako naj berem ocene, preglede in razsodbe?",
      "sourceIds": []
    },
    {
      "prompt": "Ali lahko prekličem objavo razprave?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Kako upravljam MFA in aktivne seje?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Kako je zaščiten moj pogovor s podporo?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "sv": [
    {
      "prompt": "Hur startar jag min första debatt?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Vad betyder en villkorsmarkering?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Hur ska jag tolka poäng, granskningar och utslag?",
      "sourceIds": []
    },
    {
      "prompt": "Kan jag avpublicera en debatt?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Hur hanterar jag MFA och aktiva sessioner?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Hur skyddas mitt supportsamtal?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "tr": [
    {
      "prompt": "İlk tartışmamı nasıl başlatırım?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Koşul işareti ne anlama gelir?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Puanları, değerlendirmeleri ve hükümleri nasıl okumalıyım?",
      "sourceIds": []
    },
    {
      "prompt": "Bir tartışmayı yayından kaldırabilir miyim?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "MFA'yı ve etkin oturumları nasıl yönetirim?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Destek görüşmem nasıl korunuyor?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "uk": [
    {
      "prompt": "Як розпочати свої перші дебати?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Що означає позначка умови?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Як читати оцінки, рецензії та вердикти?",
      "sourceIds": []
    },
    {
      "prompt": "Чи можна скасувати публікацію дебатів?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Як керувати MFA та активними сеансами?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Як захищено мою розмову зі службою підтримки?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "vi": [
    {
      "prompt": "Làm thế nào để bắt đầu cuộc tranh luận đầu tiên?",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "Dấu điều kiện có ý nghĩa gì?",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "Tôi nên đọc điểm số, đánh giá và phán quyết như thế nào?",
      "sourceIds": []
    },
    {
      "prompt": "Tôi có thể hủy xuất bản một cuộc tranh luận không?",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "Tôi quản lý MFA và các phiên đang hoạt động như thế nào?",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "Cuộc trò chuyện hỗ trợ của tôi được bảo vệ như thế nào?",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ],
  "zh": [
    {
      "prompt": "如何开始我的第一次辩论？",
      "sourceIds": [
        "getting-started-debate",
        "risk-tier-choice",
        "budget-tier-choice"
      ]
    },
    {
      "prompt": "条件标记是什么意思？",
      "sourceIds": [
        "guide-how-it-works"
      ]
    },
    {
      "prompt": "如何理解分数、评审和裁决？",
      "sourceIds": []
    },
    {
      "prompt": "可以取消发布辩论吗？",
      "sourceIds": [
        "unpublish-a-debate",
        "delete-a-private-debate",
        "public-answer-disclosure"
      ]
    },
    {
      "prompt": "如何管理 MFA 和活动会话？",
      "sourceIds": [
        "settings-help-menus",
        "account-settings"
      ]
    },
    {
      "prompt": "我的支持对话如何得到保护？",
      "sourceIds": [
        "app-navigation",
        "settings-help-menus",
        "support-cases"
      ]
    }
  ]
} as const satisfies Readonly<Record<SupportLanguage, readonly Readonly<{ prompt: string; sourceIds: readonly string[] }>[]>>;
