import { createHash } from "node:crypto";
import { cp, readFile, writeFile } from "node:fs/promises";
const root="/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine";
const R=`${root}/.hermes/reports/support-conversation-20260914`,E=`${R}/evidence`,P=`${R}/probes`;
const sha=b=>createHash("sha256").update(b).digest("hex");
const readJson=async p=>JSON.parse(await readFile(p,"utf8"));
const writeJson=async(p,v)=>writeFile(p,`${JSON.stringify(v,null,2)}\n`,{flag:"wx",mode:0o600});
for(const name of ["capture-public-guide.mjs","run-operator.mjs","screenshot-evidence-successor.mjs"]){const source=`${P}/GUIDE_PREVIEW_BIND32/${name}`,target=`${P}/GUIDE_PREVIEW_RECOVER34/${name}`;let bytes=await readFile(source);if(name==="run-operator.mjs")bytes=Buffer.from(bytes.toString("utf8").replaceAll("GUIDE_PREVIEW_BIND32","GUIDE_PREVIEW_RECOVER34"));await writeFile(target,bytes,{flag:"wx",mode:0o600})}
const gate=await readJson(`${E}/GUIDE_PREVIEW_BIND32-gate-template.json`);gate.runtimeLogPath=`${R}/logs/GUIDE_RUNTIME9-stack.log`;const gatePath=`${E}/GUIDE_PREVIEW_RECOVER34-gate-template.json`;await writeJson(gatePath,gate);const gateBytes=await readFile(gatePath);
const custodyContractPath=`${E}/GUIDE_PREVIEW_RECOVER34-runtime-custody-contract.json`,custodyContractBytes=await readFile(custodyContractPath);
const owner=await readJson(`${E}/GUIDE_PREVIEW_BIND32-owner-capacity-contract.json`);owner.node="GUIDE_PREVIEW_RECOVER34";const ownerPath=`${E}/GUIDE_PREVIEW_RECOVER34-owner-capacity-contract.json`;await writeJson(ownerPath,owner);const ownerBytes=await readFile(ownerPath);
const command=await readJson(`${E}/GUIDE_PREVIEW_BIND32-command-contract.json`);command.node="GUIDE_PREVIEW_RECOVER34";command.runtimeCustodyPath=`${E}/GUIDE_PREVIEW_RECOVER34-runtime-custody.json`;command.runtimeCustodyContractPath=custodyContractPath;command.runtimeCustodyContractSha256=sha(custodyContractBytes);command.runtimeLogPath=`${R}/logs/GUIDE_RUNTIME9-stack.log`;command.gateTemplatePath=gatePath;command.gateTemplateSha256=sha(gateBytes);command.ownerCapacity.contractPath=ownerPath;command.ownerCapacity.contractSha256=sha(ownerBytes);for(const phase of Object.values(command.phases))phase.argv[2]=`${E}/GUIDE_PREVIEW_RECOVER34-command-contract.json`;command.phases.capture.childArgv[3]=`${P}/GUIDE_PREVIEW_RECOVER34/capture-public-guide.mjs`;const commandPath=`${E}/GUIDE_PREVIEW_RECOVER34-command-contract.json`;await writeJson(commandPath,command);const commandBytes=await readFile(commandPath);
const operator=await readJson(`${E}/GUIDE_PREVIEW_BIND32-operator-contract.json`);operator.node="GUIDE_PREVIEW_RECOVER34";operator.ticket="t_31c5023f";operator.argv[3]=`${P}/GUIDE_PREVIEW_RECOVER34/run-operator.mjs`;operator.script.path=operator.argv[3];const operatorScriptBytes=await readFile(operator.script.path);operator.script.sha256=sha(operatorScriptBytes);operator.script.bytes=operatorScriptBytes.byteLength;operator.commandContract.path=commandPath;operator.commandContract.sha256=sha(commandBytes);operator.commandContract.bytes=commandBytes.byteLength;for(const [name,path] of Object.entries(operator.operatorOwned.logs)){const next=path.replaceAll("GUIDE_PREVIEW_BIND32","GUIDE_PREVIEW_RECOVER34");operator.operatorOwned.logs[name]=next;const index=operator.futureAbsence.paths.indexOf(path);if(index>=0)operator.futureAbsence.paths[index]=next}const operatorPath=`${E}/GUIDE_PREVIEW_RECOVER34-operator-contract.json`;await writeJson(operatorPath,operator);
console.log(JSON.stringify({commandSha256:sha(commandBytes),operatorSha256:sha(await readFile(operatorPath)),ownerSha256:sha(ownerBytes),gateSha256:sha(gateBytes)}));
