# PACKET CODE-REV-S01-C1C2 — blind per-cluster code review (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on your ticket with `comments read through: <n>` NOW; then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` / `PLAN.md` / `DECISIONS.md` · `docs/missions/consent-ui/BASELINE.md` · the design extracts (visual truth).
Skills (Skill tool): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-reviewer` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (when judging a failure) · `superpowers:receiving-code-review` (if contested).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_c7a758f6` · **seat:** CODE-REV-S01-C1C2 · **role:** reviewer · **model:** claude-opus-5, fresh blind session · **round:** 1 of max 3
- **the work under review:** seat CODE-S01-C1C2, ticket `t_8d084df2`, commit(s) `91a090ea (C1) and 87b50e1e (C2); HEAD 87b50e1e` on branch `slice/consent-s01`; its dispatching packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S01-C1C2.md` (review it FIRST — constants, `allowed` vs deliverables, base commit); the review package (commit list + stat + full diff) at `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/review-packages/S01-C1C2-r1.diff (1049 lines: commits, stat, full diff -U10 — ONE Read)`.
- **your worktree (separate, detached at `91a090ea (C1) and 87b50e1e (C2); HEAD 87b50e1e`; cwd for every command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s01-c1c2/dialectical-engine` — never the author's lane, never the main tree. node_modules are already cloned there; run `pnpm run generate:contract` first.
- **allowed (exhaustive):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S01-C1C2-r1.md` (verdict) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-REV-S01-C1C2.md` (self-report) · scratch under `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s01-c1c2/dialectical-engine/.review-scratch/` (delete before handoff; prove with `git status --porcelain` = empty) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append) · comments on `t_c7a758f6` and ONE verdict comment on `t_8d084df2` (`--author CODE-REV-S01-C1C2`) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/` (files named `<seat>-r<round>-*` only — COMMON §10.26; copy your probe kit there BEFORE the verdict comment) · scratch is `<seat>-r<round>/` per §10.11
- **forbidden:** editing the work under review · git writes other than in-scratch probes you fully revert (`git checkout HEAD -- <path>`, then `git status --porcelain` must be empty) · the other slice · the main tree · subagents producing the verdict.

## 2. Probes (`heartbeat-reviewer` §2) — build your own from the CLAIM, never from the author's test
Run every owned cluster command yourself ×3 · re-run the author's mutants AND add mutants of your own derived from the SPEC property (e.g. flip a default, skip the scroll-end check, store the wrong key, check the box on close) · render the component in jsdom yourself with a throwaway test in `.review-scratch/` and assert the SPEC's verbatim copy and both-mode token usage · typecheck delta against BASELINE.md · colour-literal gate hit list · `git diff --stat` vs the cluster's `allowed` surface (any file outside it is blocking) · the `globals.css` block discipline (only the slice's delimited block at the end changed) · registration request shape unchanged (grep the diff for `register(`/`adult_affirmed`) · the author's `SKILLS LOADED` vs the worker floor · constants transcribed match the design extracts · self-report bar · a11y claims (roles, focus, Esc) probed, not read.

## 3. Verdict — `reviews/CODE-REV-S01-C1C2-r1.md`
`SKILLS LOADED` · `Verdict: PASS | REWORK | BLOCKED` · packet findings · B1… · N1… (each: file:line, concrete inputs → wrong outcome, evidence) · what I verified and how (verbatim outputs) · what I did NOT verify · predictions · `comments read through`. Post it as ONE comment on `t_8d084df2` (`--max-len 80000`); one-line pointer on `t_c7a758f6`. Round 3 REWORK → V DECISIONS PACKET row instead. Self-report first. Stop.

**Remedies (COMMON §10.22):** every B/N finding names its CLASS (binding) and marks its remedy `BINDING (measured: <what you ran>)` or `ADVISORY`. An advisory remedy the author refutes with output is not a NOT ADDRESSED.

## 4. Seat-specific charges (orchestrator, from the author's own handoff — verify, do not trust)
- The author's handoff (newest `READY FOR PEER REVIEW` comment by `CODE-S01-C1C2` on `t_8d084df2`) claims: C1 three runs verdict 0 (`Tests 2 failed | 7 passed (9)`, hit list 1), C2 three runs verdict 0 (`Tests 6 passed (6)`), typecheck 8 diagnostics all in the pin, `auth-flow-integration` 17/17, 9 mutants caught / 4 neighbours not caught. Re-run `CMD-C1` and `CMD-C2` yourself ×3 in YOUR worktree, from a `.sh` under `/bin/bash` and inline (COMMON §10.16).
- **Author concern 1 (verify the class):** the cluster typecheck arm cannot see `apps/ui/lib/consent.ts` or the `.tsx` test (root `tsconfig.json` excludes `apps/ui`, takes `tests/**/*.ts` only) — the author ran `cd apps/ui && npx tsc --noEmit -p tsconfig.json` as a compensating check (exit 0). Confirm with `tsc --listFiles`; if true, say so — the orchestrator adds that arm to every later cluster packet.
- **Author concern 2 (a ruling was needed):** a stored record with all five members but `essential: false` — R03 (missing member → re-ask) vs R01 (declared type). The author implemented "re-ask, no decision". ORCHESTRATOR RULING: the conservative reading stands (a record contradicting R01's declared type is not a decision) — judge the implementation and the test against that ruling, and say whether the SPEC text needs a V row.
- **Design fidelity of the tokens:** the ten values must reproduce from `docs/missions/consent-ui/design/design-data.js` per the PLAN's derivation table (S01-S02) and SPEC R24 — re-derive at least the four mode-bearing ones yourself.
- **Storage shape (R01/R04/R28):** `debateai.consent`, `{v:1, essential, quality, analytics, decidedAt}`; `COOKIE_CATEGORIES` strings byte-exact to the SPEC §Copy — diff them yourself against `design-data.js:88-90` decoded.
- The ADR is `docs/architecture/01-decisions/ADR-0021-consent-storage-contract.md` (status Proposed — V ratifies): check it transcribes the contract, invents nothing, and matches the code.
