# PACKET CODE-CROSS-03-REWORK-R1 — Opus 5 coding seat, rework round 1 of max 3 (mission `consent-ui`) — the containment tiebreak is STRICT

**STEP 0 — CLAIM before you read anything else (COMMON §10.29, §10.56):** `k show t_ed4c5e73`, then post `CLAIM` on `t_ed4c5e73` with the cursor you just read; then read the packet.

## 0. MEASURED TRUTH (COMMON §10.48)
- **TOOLING-TRAPS at dispatch: 2814 lines — read the WHOLE file at CLAIM (§10.67); re-read everything past :2814 at handoff.** Entries under `[CODE-CROSS-03, 4ef2f7d3]` and `[CODE-REV-CROSS-03, 4ef2f7d3]` are the previous round's seats'; read them like any other entry.
- **The finding you discharge — CODE-REV-CROSS-03 r1 B1** (`/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-CROSS-03-r1.md`, verdict REWORK; the packet that dispatched the previous round is charged, NOT its author): the previous round's packet prescribed `incumbent.contains(lower)` for a rule whose word is DESCENDANT. `Node.contains` is REFLEXIVE, so at `4ef2f7d3` `topmostSurface()`'s second pass (`apps/ui/components/consent/modalSemantics.ts:189-196`) matches an entry that SHARES the incumbent's container node, reassigns `topContainer` to the same node, and walks on — two surfaces sharing one container hand `Escape` to the FIRST-opened; three sharers to the EARLIEST. Measured ×3 by the reviewer's probe (`/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/code-rev-cross-03-r1-reflexive-contains.probe.test.tsx`, cases P3/P4 ASSERT it — `:184-185`, `:215`; P1/P2/P5/P6 are controls): `2 failed | 4 passed (6)` at 4ef2f7d3.
- **THE REMEDY (BINDING, measured by the reviewer):** in the second pass, `if (container === topContainer || !topContainer.contains(container)) continue;` — the probe goes `6 passed (6)`; the consent SET stays `17 files / 195 tests`; semantics + cross-slice `33/33`. No consumer shares a container today; the helper's contract ("one entry per OPEN surface"; open order everywhere but strict containment) makes the case specified, not undefined.
- **The CLASS (fix all members, not the instance):** every artifact that states the relation must say STRICT descendant: the helper's doc comment (`modalSemantics.ts:148-156`, whose termination argument "each replacement is strictly deeper" is FALSE for the reflexive predicate and TRUE after the fix — say so), the second-pass comment, ADR-0022's (b′) addendum (`docs/architecture/01-decisions/ADR-0022-shared-modal-semantics.md:165`, `:186`, and it claims "Pinned by four cases" at `:191` — CODE-REV-CROSS-03 r1 N1: exactly THREE pin the tiebreak (the nested pair in one commit, the three-deep chain, the Tab trap); the later-commit case is green with the tiebreak removed because its inner surface is already last-registered — write a dated CORRECTION addendum, never edit the earlier text), and the `CookieConsent.tsx` sentence about containment (grep `contain` in that file; measured at 4ef2f7d3 it exists once).
- **N2 (advisory, discharge it while you are in the function):** `modalSemantics.ts:191`'s `!container.isConnected` disjunct is unreachable — pass 1 selected a connected `topContainer`, and every node a connected element `contains()` is connected (reviewer mutant M6 survives 33/33). Drop the term, or write the proof into the comment; either is accepted — say which.
- **Source-text guards that scan the files you touch (P4 lesson):** `tests/render/consent-card.test.tsx:489-492` bans `addEventListener`, `.focus(`, `/\bdocument\b/`, `/["']Escape["']/` in `CookiePreferencesCard.tsx` (comments included); `tests/render/consent-policy-link.test.tsx:384-391` bans a BARE `Escape` across that file and `CookieConsent.tsx`; `tests/render/consent-guards.test.tsx` (S01-S44/S45) scans the whole `components/consent/` directory for the shared-helper tokens. Run all three after every comment edit.
- **Known-false doc constants, ticketed, not yours:** `run_c9`'s merge arms (`t_4f97ca86`); `CMD-C6`'s S02 arms vacuous in this lane (`t_38c6bbf2`); the cross-slice suite in no PLAN command (`t_4f97ca86`).

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` (§10.16–10.69) · the verdict named above (all of it — B1, N1, N2, P1–P6) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-CROSS-03.md` (the previous round's packet, for the ruling's wording it got wrong) · `docs/missions/consent-ui/slices/S02/DECISIONS.md` (the CROSS-03 rows) · `docs/missions/consent-ui/BASELINE.md` (the SET's command) · `docs/missions/consent-ui/V-DECISIONS-PACKET.md` row V-20 · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (whole file).
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:receiving-code-review` (this is a rework: verify B1 before implementing) · `superpowers:test-driven-development` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (the moment anything fails unexpectedly).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_ed4c5e73` (the CROSS-03 work ticket; your markers go there) · **seat:** CODE-CROSS-03-REWORK-R1 · **role:** worker · **model:** claude-opus-5, fresh session · **rework round 1 of max 3** (round 4 does not exist)
- **lane (cwd for EVERY command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s02/dialectical-engine` · **branch** `slice/consent-s02` · **BASE** `4ef2f7d3` (verify at CLAIM: HEAD = `4ef2f7d3`, porcelain 0). The `rev-cross-03` worktree (detached, the r1 reviewer's) and the three `rev-grok-*` worktrees exist beside the lane — never touch them.
- **review route:** CODE-REV-CROSS-03 r2 `t_956e450f` (Opus 5, blind — not yours to dispatch)
- **allowed (exhaustive — files AND tickets):** `apps/ui/components/consent/modalSemantics.ts` (the one guard term in the second pass; the doc comment `:148-156` and the pass-2 comment; N2's disjunct — no exported-shape change, proved by declaration emit) · `apps/ui/components/consent/CookieConsent.tsx` (the one containment sentence) · `docs/architecture/01-decisions/ADR-0022-shared-modal-semantics.md` (ONE dated correction addendum: strict descendant; three pinning cases named; the later-commit case green either way) · `tests/render/consent-modal-semantics.test.tsx` (ONE or TWO new cases: two surfaces sharing one container node → the last-opened answers `Escape` and traps Tab; optionally three sharers → the last-opened; RED at 4ef2f7d3 with the frames verbatim) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/slices/S02/DECISIONS.md` (append-only: one row for the strict predicate, citing the probe cases by name) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-CROSS-03-REWORK-R1.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (main tree, append-only, under `[CODE-CROSS-03-REWORK-R1, <commit>]`) · tickets: `t_ed4c5e73` only.
- **forbidden:** every other file (incl. `CookiePreferencesCard.tsx`, `consent-cross-slice.test.tsx`, `BASELINE.md`, `PROGRESS.md`, `PLAN.md`), the probes directory, the review and Grok worktrees, any dev-stack process, any git write beyond ONE commit on `slice/consent-s02`.

## 2. The work — RED first
1. Copy the reviewer's probe byte-untouched into your scratchpad and run it through your own vitest `--config` (COMMON §10.46; the lane's `@` alias; `LANE` from argv): expect `2 failed | 4 passed (6)` at 4ef2f7d3 — paste it. Write your own case(s) in the semantics suite: RED at 4ef2f7d3, frame verbatim.
2. The guard term; the comments; the ADR correction; the CookieConsent sentence; N2. GREEN: your case(s), the probe `6 passed (6)`, the semantics + cross-slice pair `35/35` or `34/34` (state which and why), the SET by BASELINE's command (`17 files`, tests = 195 + your new cases — measure, do not predict), the three source-text guard suites, `CMD-C6`/`CMD-C7`/`run_c9` (vitest half + PROPERTY), root typecheck (8 in `s14-ui`, 0 outside), the apps/ui arm, t9 (`2 failed | 7 passed (9)`, one hit `globals.css:6116`). ×3 `.sh` under `/bin/bash` AND inline, worst wins, commit column.
3. Mutants (cp + diff -q): M1 the identity term removed (the reflexive predicate back) → your case RED + probe P3/P4 RED; M2 the tiebreak removed entirely → the three nested pins RED; M3 `!topContainer.contains(container)` inverted → name what reds. Name the neighbouring mutant your pins must NOT catch.

## 3. Handoff — `REWORK READY FOR REVIEW` on `t_ed4c5e73` (body as a FILE, `"$(cat f)"`, §10.47; cursor re-read first, §10.56)
Opens with `SKILLS LOADED: …`; the commit hash — message `fix(consent-ui CROSS-03 rework 1): the containment tiebreak is STRICT — a surface sharing its container with the incumbent keeps open order (CODE-REV-CROSS-03 r1 B1; ADR three pinning cases, N1; N2)` + the Co-Authored-By line (COMMON §10.63) — `git show --stat --name-only`, the RED frames verbatim (probe + your case), the mutant table, B1/N1/N2 dispositions one line each, the gate deltas, packet defects with file:line (a wrong constant here is a finding against the orchestrator), unexpected findings, the self-report path.
