# PACKET CODE-CROSS-03 — Opus 5 coding seat (mission `consent-ui`) — the containment tiebreak (V-20 (b′)) and every non-blocking residue on the S02 lane

**STEP 0 — CLAIM before you read anything else (COMMON §10.29, §10.56):** `k show t_ed4c5e73`, then post `CLAIM` on `t_ed4c5e73` with the cursor you just read; then read the packet.

## 0. MEASURED TRUTH (COMMON §10.48 — overrides the documents listed below)
- **TOOLING-TRAPS at dispatch: 2651 lines** (COMMON §10.66). Read everything past that line at CLAIM and again at handoff; a guard refuted by a newer entry is reported, not obeyed. Your own TRAPS entries go under a heading `[CODE-CROSS-03, <commit>]` (§10.65).
- **The lane at BASE `c334136d`:** `topmostSurface()` (`apps/ui/components/consent/modalSemantics.ts:143-150`) walks the registry from the END and returns the first entry whose container is `null` or connected (`:147`). Consequence, pinned by the previous seat at `tests/render/consent-modal-semantics.test.tsx:154`, `:216-…`, `:421`: a pair mounted in ONE commit registers child-first (React runs effects child before parent), so the OUTER surface answers `Escape` — B1's harm in the nested shape. No product surface nests today (`SignUpFlow.tsx:339-347` and `CookieConsent.tsx:221` mount their policy conditionally), so nothing reachable changes either way.
- **THE RULING (orchestrator, V-20 (b′) — V can undo):** open order stays; a LOWER entry wins over the incumbent ONLY when the lower entry's container is a DESCENDANT of the incumbent's container (`incumbent.contains(lower)` — `Node.contains`, not `compareDocumentPosition`, no FOLLOWING arm anywhere). Walk: take the last connected-or-null entry as the incumbent; then, scanning downwards, replace it by any connected entry whose container the incumbent's container `contains`; repeat until nothing deeper. CODE-REV-CROSS-02 r1 (`docs/missions/consent-ui/reviews/CODE-REV-CROSS-02-r1.md`, §N2) MEASURED this rival: the full consent SET `3 failed | 190 passed (193)`, the three failures being exactly the three inversion pins, every cross-slice case green (B1 stays discharged). That measurement is this packet's §10.55 dry-run: the three cases at `:154`, `:216`, `:421` FLIP by design (rewrite them to pin (b′): the nested INNER surface answers `Escape`, and Tab traps in it); every other case in the SET stays green — name any other flip as a regression and stop.
- **Known-false doc constants, ticketed, not yours:** `S02/PLAN.md:1413-1416` (`run_c9` merge arms, `t_4f97ca86`); `S02/PLAN.md:1279-1280` (PROGRESS.md write order); the new cross-slice suite is in no PLAN cluster command (`t_4f97ca86`, N3) — it IS in the BASELINE SET by its command.
- **`CookieConsent.tsx:192-198`** states "DOM ORDER IS LOAD-BEARING … topmost by DOCUMENT POSITION — CONTAINED_BY || FOLLOWING — and not by the order they opened in". False since c334136d; the ARRANGEMENT it describes (policy after the card) still holds as V-20's recorded constraint and stays.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` (§10.16–10.66) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/INSTRUCTIONS.md` · the three verdicts whose residue you discharge: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S02-C9-r1.md` (§N1–N4), `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-CROSS-01-r1.md` (§N1, §N3, §P7), `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-CROSS-02-r1.md` (§N1, §N2, §N4, §N5) · the tickets `t_9f2dea04`, `t_51101c72` (their bodies and addenda are the residue list) · `docs/missions/consent-ui/slices/S02/SPEC.md` / `PLAN.md` (the `run_c9` and `CMD-C7` fenced blocks) / `DECISIONS.md` · `docs/missions/consent-ui/slices/S01/PLAN.md` (`CMD-C6`) · `docs/missions/consent-ui/BASELINE.md` · `docs/missions/consent-ui/V-DECISIONS-PACKET.md` rows V-20 and V-22 · `docs/architecture/01-decisions/ADR-0022-shared-modal-semantics.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (main tree; the lane's copy is stale).
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:receiving-code-review` (you discharge three verdicts' findings — verify each before implementing) · `superpowers:test-driven-development` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (the moment anything fails unexpectedly).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_ed4c5e73` · **slice tickets (V's):** `t_26efb70d` (S01), `t_9ccf3598` (S02) · **seat:** CODE-CROSS-03 · **role:** worker · **model:** claude-opus-5, fresh session · **rework rounds: max 3**
- **lane (cwd for EVERY command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s02/dialectical-engine` · **branch** `slice/consent-s02` · **BASE** `c334136d` (verify at CLAIM: HEAD = `c334136d`, porcelain 0). No review worktree exists beside the lane right now; three Grok worktrees `rev-grok-10a/10b/10c` exist detached at c334136d — never touch them.
- **comment cursor at dispatch:** read all · **review route:** CODE-REV-CROSS-03 `t_5d7078fe` (Opus 5, blind — not yours to dispatch)
- **allowed (exhaustive — files AND tickets, COMMON §10.41/§10.64):** `apps/ui/components/consent/modalSemantics.ts` (`topmostSurface()` + its doc comment + the stack comment `:51-…` + the `returnFocusRef` member JSDoc — no exported-shape change, proved by `tsc --declaration --emitDeclarationOnly` diff, NOT by an export grep) · `apps/ui/components/consent/CookieConsent.tsx` (the `:192-198` comment rewritten; the local `manageRef` renamed `chooseRef`, CROSS-01 r1 P7 — nothing else) · `apps/ui/components/consent/CookiePreferencesCard.tsx` (the `returnFocusRef` prop's doc comment only: it serves when the captured opener is not a connected element AT CLOSE, never "the opening commit") · `tests/render/consent-modal-semantics.test.tsx` (the three inversion pins rewritten to (b′); ONE new case pinning the `null`-container branch — CODE-REV-CROSS-02 r1 N1, mutant `M5 NONULL` reds it) · `tests/render/consent-policy-link.test.tsx` (the case `stays silent on Escape from the Settings entry when a valid decision is stored`, `:253`, gains a `document.activeElement` assertion that focus returned to `Cookie preferences` — CODE-REV-CROSS-01 r1 N1) · `tests/render/consent-bar.test.tsx` (the case at `:229` renamed to describe its assertion — "ships R09's geometry inside ONE delimited S01 block, followed only by whitespace or S02's delimited block"; the S02 marker literals at `:254-…` replaced by imports; one sentence naming the S02 contract suite as the co-owner of the nested-block property — C9 r1 N1/N3/N4) · NEW `tests/support/consentMarkers.ts` (exports the four marker strings `/* === consent-ui S01 === */`, `/* === end consent-ui S01 === */`, `/* === consent-ui S02 === */`, `/* === end consent-ui S02 === */`) · `tests/unit/consent-s02-style-contract.test.ts` (the duplicate-comment assertion at `:223` moves into its own `it()`; markers imported — C9 r1 N2/N3) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/BASELINE.md` (ONLY the line naming the renamed consent-bar case, if one exists — grep first; report if none) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/slices/S02/DECISIONS.md` (append-only: one dated correction line for the `:207` warrant — the export grep is blind, the declaration-emit diff is the evidence, CODE-REV-CROSS-02 r1 N4 — and one row for (b′)) · `docs/architecture/01-decisions/ADR-0022-shared-modal-semantics.md` (one addendum for (b′)) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-CROSS-03.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (main tree, append-only, under your heading) · tickets: `t_ed4c5e73` (your markers and handoff) — nothing else.
- **forbidden:** `CookieBar.tsx`, `PrivacyPolicyModal.tsx`, `SignUpFlow.tsx`, `layout.tsx`, `globals.css`, `consent-cross-slice.test.tsx`, every other test, `PROGRESS.md`, `PLAN.md`, `SPEC.md`, the probes directory, the Grok worktrees, any dev-stack process, any git write beyond ONE commit on `slice/consent-s02`.

## 2. The work — RED first, per finding
1. **(b′)**: rewrite the three inversion pins to their (b′) outcome FIRST (`:154` the nested inner answers `Escape`; the three-at-once case: the deepest answers; `:421` Tab traps in the same surface) — RED at c334136d, frames verbatim; then the helper; GREEN. Mutants (cp + diff -q): M1 the tiebreak removed → the three RED; M2 a FOLLOWING arm added back → `consent-cross-slice.test.tsx` RED; M3 `isConnected` skip removed → the detached case RED.
2. **N1 (null container)**: new case → RED under mutant `M5 NONULL` (`container !== null && container.isConnected`), GREEN at HEAD. Base-GREEN is expected; say so (the RED is the mutant's).
3. **CROSS-01 r1 N1**: the `activeElement` assertion — base-GREEN expected; mutant: skip the capture → RED.
4. **C9 r1 N1–N4**: rename, markers module, co-owner sentence, own `it()` — every assertion's operands unchanged; `git diff` shows only titles, imports and structure. The renamed title must still be found by whatever gates on it: grep `BASELINE.md`, the PLANs and the review verdicts for the old title and report every hit (edit only BASELINE's line).
5. **Comments/docs**: the four wording members of the false-mechanism class (`modalSemantics.ts` member JSDoc, `CookieConsent.tsx:192-198`, the card prop doc, ADR-0022's earlier "opening commit" sentence gets a correcting addendum, not an edit) — state per member what it says now.
6. **Verification (COMMON §10.16/§10.30/§10.49; ×3 `.sh` under `/bin/bash` AND ×3 inline, worst wins, commit column):** `CMD-C6`, `CMD-C7`, `run_c9` (vitest half + PROPERTY), the consent SET by `BASELINE.md`'s command (report files and tests by the command — seventeen files at BASE), root typecheck (8 in `s14-ui`, 0 outside), the apps/ui arm, t9 (`2 failed | 7 passed (9)`, hit list one element at `globals.css:6116`). Deltas against these pins; no count predictions bind you (§10.42).

## 3. Handoff — `READY FOR PEER REVIEW` on `t_ed4c5e73` (body as a FILE, `"$(cat f)"`, §10.47; cursor re-read first, §10.56)
Opens with `SKILLS LOADED: …`; the commit hash — message `fix(consent-ui CROSS-03): a nested surface answers Escape before the surface that contains it (V-20 (b′)) + the non-blocking residue of the C9, CROSS-01 and CROSS-02 reviews` + the Co-Authored-By line (COMMON §10.63) — `git show --stat --name-only`, the RED frames verbatim, the mutant table, the flip list (exactly the three pins, or say what else moved and stop), per-finding one-line dispositions (C9 r1 N1–N4, CROSS-01 r1 N1/N3/P7, CROSS-02 r1 N1/N2/N4/N5), the gate deltas, packet defects with file:line, unexpected findings, the self-report path.
