# PACKET CODE-S01-C3C4 — Opus 5 coding seat (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on your ticket with `comments read through: <n>` NOW; then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` (never edit) · `PLAN.md` (the steps you own: S01-S12 … S01-S18 (cluster S01-C3, the bar) then S01-S19 … S01-S24 (cluster S01-C4, the preferences card) — the PLAN cluster table rows `S01-C3`/`S01-C4` and the fenced `CMD-C3`/`CMD-C4` blocks are the source of truth; the cluster rows C3C4) · `DECISIONS.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/BASELINE.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` · your ticket's comments through the cursor. The design extracts (COMMON header) are the visual truth; the SPEC's verbatim copy and token map are binding.
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:test-driven-development` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (the moment anything is broken) · `superpowers:receiving-code-review` (on rework). List them in `SKILLS LOADED`.

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_14e117ec` · **slice ticket (V's):** `t_26efb70d` · **seat:** CODE-S01-C3C4 · **role:** worker · **model:** claude-opus-5 · **rework rounds: max 3**
- **lane (your cwd for EVERY command; never leave it, never touch the main tree):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s01/dialectical-engine` · **branch:** `slice/consent-s01` · **base commit:** `87b50e1e (C1+C2 head — verify with `git rev-parse --short HEAD` at CLAIM; if it differs, STOP and say so)` (verify with `git rev-parse HEAD` first; a mismatch is a packet defect — report and stop)
- **comment cursor at dispatch:** read all · **review route:** CODE-REV-S01-C3C4 (Opus 5, blind, separate detached worktree — not yours to dispatch)
- **clusters you own:** C3C4 — their verification commands and file surfaces are in `PLAN.md § Clusters`; run each THREE times, worst run is the verdict.
- **allowed (exhaustive, inside the lane):** **C3:** `apps/ui/components/consent/CookieBar.tsx` (create) · `apps/ui/app/globals.css` — ONE delimited S01 block appended at the END of the file (`=== consent-ui S01 ===` markers per S01-S16; not one character above the opening marker; the two token blocks are C1's and are CLOSED) · `tests/render/consent-bar.test.tsx` (create). **C4:** `apps/ui/components/consent/CookiePreferencesCard.tsx` (create) · `apps/ui/app/globals.css` (the SAME S01 block — rules appended inside it) · `tests/render/consent-card.test.tsx` (create) · plus (main-tree paths) `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-S01-C3C4.md` (self-report) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append only) · comments on `t_14e117ec` (`--author CODE-S01-C3C4`)
- **forbidden:** every other file — in particular `apps/ui/lib/consent.ts` (C2, read-only: import `COOKIE_CATEGORIES`, `writeConsent`, `decisionFor` unchanged; a needed change is a finding, not an edit), `tests/unit/t9-mode-tokens.test.ts`, both token blocks, `apps/ui/app/layout.tsx`, `apps/ui/app/settings/page.tsx`, `CookieConsent.tsx` (C5), every S02 file (`modalSemantics.ts`, `PrivacyPolicyModal.tsx` are not in this lane yet) · every other cluster's surface · the other slice's files · COMMON §3's no-touch surface · protocol docs and skills · `globals.css` above your slice's delimited block · any push, merge, Done, ticket split, branch, worktree or rebase operation · **subagents of any kind** (no helpers, no reviewers — review arrives from the orchestrator after your handoff).

## 2. The work
Implement exactly the PLAN steps named above, RED first (`heartbeat-worker` §2 refutation duty: property → mutant → RED → revert → GREEN → neighbouring mutant not caught; print `git status --porcelain` after every restore). Constants you TRANSCRIBE, never compute: the bar copy byte-exact from SPEC R11 / §Copy (`design/turn-10-cookie-consent.html`, `design-data.js` decoded) · R09 bar geometry (22px inset, 720px stack rule with its derivation — S01-S17) and R15 card geometry (`min(520px, calc(100vw - 32px))`) · the three bar buttons in the design's DOM order; NO close control, NO Esc dismissal, NO focus trap on the bar (S01-S14/S15) · the twelve category strings read from `COOKIE_CATEGORIES`, never inlined (S01-S19/S20) · the Essential switch locked (not operable by click/Space/Enter), the other two answer click AND Space (S01-S21) · footer exactly `Privacy notice` · `Essential only` · `Save choices`, no `×` (V-11) · `Save choices` writes per R04 via `decisionFor` (S01-S23) · tokens only — a `#hex`/`rgb(`/`oklch(` literal in the S01 block or a component is a defect; the OFF-toggle border stays the design's value (V-17 default (a)). Colours only via `var(--token)`; new tokens go inside the two existing token blocks AND into `tests/unit/t9-mode-tokens.test.ts`'s maps (comma-tight). Gates before handoff, in order: (1) `pnpm run generate:contract` — say you ran it and that the tree stayed clean; (2) `pnpm typecheck` — report the DELTA against BASELINE.md (no diagnostic outside the 8 pinned in `tests/unit/s14-ui.test.ts`); (3) `pnpm exec vitest run tests/unit/t9-mode-tokens.test.ts` — the colour-literal hit list is exactly the one pinned line and the other six tests are green; (4) `pnpm exec vitest run tests/render/auth-flow-integration.test.tsx` — 17+ passed, or the SPEC-named updates with their reason; (5) your cluster commands ×3 (table: run 1/2/3, worst). Commit on `slice/consent-s01` ONLY when all owned clusters are GREEN on the worst run, message ``feat(consent-ui S01-C3): cookie bar` then `feat(consent-ui S01-C4): cookie preferences card` (one commit per cluster, C3 first)`; one commit per cluster is fine; never amend a reviewed commit. Write as you go (COMMON §4b).

## 3. Handoff
`READY FOR PEER REVIEW` on `t_14e117ec`, OPENING with `SKILLS LOADED`, then: every RED frame (verbatim) · suites as `passed/total` (failures named, pre-existing dated) · the three-run cluster table · gates (1)-(4) results verbatim · constants disclosed · refutation evidence · packet defects · unexpected findings (file:line) · the commit sha(s) · `comments read through`. Self-report first (COMMON §5). Stop.


## Orchestrator additions (binding, reported beside the cluster command)
- **apps/ui project typecheck (COMMON §10.30):** `cd <lane>/apps/ui && npx tsc --noEmit -p tsconfig.json` — exit 0 required after each cluster; paste the exit code and the diagnostic count (the root `pnpm typecheck` cannot see files under `apps/ui/` or `.tsx` tests).
- **Guard satisfiability (COMMON §10.16):** run the cluster command from a `.sh` under `/bin/bash` AND inline; paste both verdicts; three runs, worst wins.

## Orchestrator addition — C2 FOLLOW-UP COMMIT FIRST (ticket `t_117e7f43`, from `reviews/CODE-REV-S01-C1C2-r1.md` N1/N2 — read those two sections, lines 225–325)
Before C3, one commit `fix(consent-ui S01-C2): strict decision predicate + typed save-choices` touching ONLY `apps/ui/lib/consent.ts`, `tests/render/consent-storage.test.tsx` and `docs/architecture/01-decisions/ADR-0021-consent-storage-contract.md` (these three are added to your allowed list for THIS commit only):
- **N1 (BINDING, measured by the reviewer's probe `probes/code-rev-s01-c1c2-r1-spec-properties.test.tsx` — run it RED first, then GREEN):** `isDecision` requires exactly five own keys and `decidedAt` matching `^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$` (the test file's own `ISO_UTC_MS`); two RED-first cases added to the R03 table; ADR-0021 Decision 3 restates the predicate ONCE, matching the code (V-19 default (a)).
- **N2 (orchestrator ruling on an ADVISORY remedy):** overloads `decisionFor(c: "accept-all" | "essential-only"): ConsentDecision` and `decisionFor(c: "save-choices", toggles: ConsentToggles): ConsentDecision`, so `decisionFor("save-choices")` no longer compiles; `CMD-C2` re-run ×3 (still verdict 0) and the apps/ui typecheck arm (§10.30) exit 0 — paste both. C4's `Save choices` handler then calls the two-argument form.
