# PACKET CODE-S02-C8-REWORK-R1 — Opus 5 coding seat, REWORK round 1 of max 3 (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on `t_ee948194` with `comments read through: <n>` NOW (`--author CODE-S02-C8-REWORK-R1`); then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` (§10.16–10.46) · the ROUND-1 VERDICT `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S02-C8-r1.md` — its **B1** (lines 67–160), **N1** (163–210) and **N2** (211–236) are this seat's requirements · the original packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S02-C8.md` (§2 constants still bind) · `docs/missions/consent-ui/slices/S02/SPEC.md` (`:612` `focus rings | --focus`; `:637` "Focus rings visible on every control, in both modes") and `PLAN.md` §Cluster S02-C8 (`:1173-1272`) · `BASELINE.md` · `.hermes/TOOLING-TRAPS.md` (absolute path). Mission docs from the MAIN tree; every command in the lane.
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:receiving-code-review` (verify each finding before implementing) · `superpowers:test-driven-development` · `superpowers:systematic-debugging` (B1 is a measurement bug — find the cause the reviewer names before touching a number) · `superpowers:verification-before-completion`. List them in `SKILLS LOADED`.

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_ee948194` (the C8 ticket; round 1 REWORK) · **slice ticket (V's):** `t_9ccf3598` · **seat:** CODE-S02-C8-REWORK-R1 · **role:** worker · **model:** claude-opus-5 · **rework rounds: this is 1 of max 3**
- **lane (cwd for EVERY command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s02-css/dialectical-engine` · **branch:** `slice/consent-s02-css` · **base commit:** `a035f814` (the reviewed C8 head — verify with `git rev-parse --short HEAD`; NEVER amend it; the fix is ONE new commit on top)
- **comment cursor at dispatch:** read all · **review route:** CODE-REV-S02-C8 round 2 (Opus 5, blind, detached worktree — not yours to dispatch)
- **allowed (exhaustive):** `apps/ui/app/globals.css` (INSIDE the S02 block only: the `.70` comment figure at `:7575`, the four `:focus-visible` rules, the orphaned comment at `:7600-7604`) · `tests/unit/consent-s02-style-contract.test.ts` (the `.70` figure at `:297`, the counts at `:51-52`, one new focus-treatment case) · plus (main-tree paths) `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-S02-C8-rework-r1.md` (self-report, NEW file) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append only) · comments on `t_ee948194`
- **forbidden:** every other file — every component, every other test, `globals.css` ABOVE the S02 opening marker (`:7224`; the existing `:focus-visible` rules at `:488-495` are outside your contract — do NOT extend them), both token blocks, `PROGRESS.md`, `BASELINE.md`, `PLAN.md`, `DECISIONS.md` · any push, merge, amend, rebase, Done, ticket split, branch or worktree operation · subagents.

## 2. The work — three findings, each fixed by CLASS (COMMON §10.27)
1. **B1 (BINDING, measured by the reviewer with a four-model α ladder):** your `.70 → 5.61` is FALSE. The shipped test's OWN model (`Math.round` per channel, label and face composited over `--shell`) prints **5.54** at α = .70 in Terracotta — exactly `PLAN.md:1250` / `DECISIONS.md:109`; 5.61 is the floor/trunc-channel artefact (`Math.round(96.5) = 97` vs `Math.floor(96.5) = 96`). Do, in this order: (a) run the shipped test with the opacity set to `.70` in scratch and paste the printed ratio — reproduce 5.54 BEFORE editing (`systematic-debugging`: cause before fix); (b) `globals.css:7575` and `consent-s02-style-contract.test.ts:297`: `5.61` → `5.54`; (c) **RETRACT your F1 on the ticket** in a comment of its own: the PLAN and DECISIONS figures are CORRECT and must not be edited; (d) the class — every measured figure your handoff/self-report/comments state: the `164,567` byte figure (the reviewer measured 164,623 == 164,623; the PROPERTY "nothing above the marker changed" is true, the number is not), and the parenthetical at-rule counts at `consent-s02-style-contract.test.ts:51-52` (`(7)`/`(18)` — shipped state 9/19: correct them or delete the counts). State each figure's corrected value on the ticket (`heartbeat-protocol` §2.6).
2. **N1 (BINDING on the outcome, ADVISORY on grouping):** four of the block's six focusable controls — `.consentPolicyLink` (`:7304`), `.policyClose` (`:7409`), `.policyPill` (`:7448`), `.policyPrimary` (`:7560`) — are matched by NO `:focus-visible` rule anywhere in the stylesheet (class- or element-level; reviewer probe `focus-coverage.mjs`: class-rule=NONE, element-rule=NONE for all four), so they fall back to the UA ring — the only paint on either surface that does not follow the mode toggle, against SPEC `:612` (`--focus`) and `:637`. Add INSIDE the S02 block one rule, e.g. `.consentPolicyLink:focus-visible, .policyClose:focus-visible, .policyPill:focus-visible, .policyPrimary:focus-visible { outline: 2px solid var(--focus); outline-offset: 2px; }` (tokens only — `--focus` exists in both token blocks; verify with `grep -n -- '--focus:' apps/ui/app/globals.css`), and ONE new test case asserting every focusable selector the block styles has a `:focus-visible` rule inside the block referencing `var(--focus)` — RED first (the case fails at HEAD naming the four), GREEN after. Sweep the class: list every focusable control the two S02 surfaces render (the two checkboxes `.consentBox`, the link, `×`, the eight pills, the primary — say which already had a treatment and from where).
3. **N2 (BINDING, measured):** the five-line comment shipped twice; delete the orphaned copy at `globals.css:7600-7604` (TDD-removal residue). Confirm with a grep that the surviving copy sits beside the rule it describes.
4. **Gates:** the cluster command `run S02-C8 1 tests/unit/consent-s02-style-contract.test.ts` ×3 (`.sh` under `/bin/bash` + inline, commit column; the count rises by one — you say what moved); root typecheck delta 0 outside the pin; apps/ui arm exit 0; t9 hit list 1; the three RED-at-base stylesheet suites identical with the block (by failure-name set); markers still exactly one pair, nothing after the closing marker, nothing above the opening marker changed (measure the byte count of the prefix BOTH ways and paste it). Commit: `fix(consent-ui S02-C8): correct the .70 contrast figure, focus rings for the four bare controls, drop the orphaned comment` ending with `Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>`. Restore scratch mutants with `cp` + `diff -q` (COMMON §10.44).

## 3. Handoff
`REWORK READY FOR REVIEW` on `t_ee948194`, OPENING with `SKILLS LOADED`, then: the reproduced 5.54 frame · the retraction pointer · the corrected figures · the RED/GREEN frames for the focus case · the class sweep of focusable controls · the three-run table · gates as deltas · the commit sha · `comments read through`. Self-report first (a NEW file). Stop.
