# PACKET CODE-S01-C6-REWORK-R1 — Opus 5 coding seat, REWORK round 1 of max 3 (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on `t_f46592b6` with `comments read through: <n>` NOW (`--author CODE-S01-C6-REWORK-R1`); then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` (§10.16–10.45) · the ROUND-1 VERDICT `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S01-C6-r1.md` — its **B1** (lines 87–152) is this seat's requirements document; B2/N1–N6 are routed elsewhere and need NO action from you (N5 is the orchestrator's citation slip: the modal's listeners are at `PrivacyPolicyModal.tsx:118,:122`) · the original packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S01-C6.md` (§2 constants still bind) · `docs/missions/consent-ui/slices/S01/SPEC.md` R14/R18/R20 and `PLAN.md` §Cluster S01-C6 (`:471-538`) · `BASELINE.md` · `.hermes/TOOLING-TRAPS.md` (absolute path). Mission docs from the MAIN tree; every command in the lane.
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:receiving-code-review` (you are discharging a verdict — verify the finding before implementing) · `superpowers:test-driven-development` · `superpowers:systematic-debugging` (this IS a bug) · `superpowers:verification-before-completion`. List them in `SKILLS LOADED`.

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_f46592b6` (the C6 ticket; round 1 REWORK) · **slice ticket (V's):** `t_26efb70d` · **seat:** CODE-S01-C6-REWORK-R1 · **role:** worker · **model:** claude-opus-5 · **rework rounds: this is 1 of max 3**
- **lane (cwd for EVERY command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s01/dialectical-engine` · **branch:** `slice/consent-s01` · **base commit:** `ab449cba` (the reviewed C6 head — verify with `git rev-parse --short HEAD`; NEVER amend it; the fix is a NEW commit on top)
- **comment cursor at dispatch:** read all · **review route:** CODE-REV-S01-C6 round 2 (Opus 5, blind, detached worktree — not yours to dispatch)
- **allowed (exhaustive):** `apps/ui/components/consent/CookieConsent.tsx` (the reset line + the comment block at `:80-87`) · `tests/render/consent-policy-link.test.tsx` (new cases) · plus (main-tree paths) `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-S01-C6-rework-r1.md` (self-report, NEW file) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append only) · comments on `t_f46592b6`
- **forbidden:** every other file — `CookiePreferencesCard.tsx`, `CookieBar.tsx`, `consent-mount.test.tsx`, every S02 file (`modalSemantics.ts`, `PrivacyPolicyModal.tsx` read-only), `globals.css`, `PROGRESS.md`, `BASELINE.md` · any push, merge, amend, rebase, Done, ticket split, branch or worktree operation · subagents of any kind.

## 2. The work — B1, fixed by CLASS (COMMON §10.27; `heartbeat-protocol` §2.2)
**The defect (reviewer-measured, 4 probe cases GREEN-because-the-defect-is-present at HEAD):** `policyOpen` (`CookieConsent.tsx:89`) is the ONLY per-open state member never reset at open. Closing the CARD while the policy is open — by the card's own `.consentScrim` (`backdropCloseHandler`) or by `Save choices` — unmounts both, strands `policyOpen = true`, and the NEXT open renders the policy over a freshly opened card (`[role="dialog"]` count 2). The comment at `:80-87` justified deleting the reset with "its scrim covers every control of the card" — a CSS claim about a stylesheet that does not exist in this lane (no S02 block, no `.policyScrim` rule; the tokens `--z-policy-*` are declared and unconsumed), so the pointer route is open today.
1. **RED first with the reviewer's oracle:** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/code-rev-s01-c6-r1-policy-flag.test.tsx` (4 cases: scrim route, Settings + `Save choices` route, control) — read it; write YOUR OWN cases into `tests/render/consent-policy-link.test.tsx` asserting the CORRECT behaviour (open card → open policy → close the CARD by the scrim → reopen → `.policyBezel` is null and `[role="dialog"]` count is 1; the same through Settings with a valid decision stored and `Save choices`; keep the control: close the policy first, then the card, then reopen → one dialog). Run: the two new cases must be **RED at HEAD** (count 2) — paste the frames.
2. **The fix:** restore `setPolicyOpen(false)` as the FIRST statement of `openCard` (`:114-119`), and REWRITE the `:80-87` comment to state the true reason (the flag is per-open state that every exit must leave false; the card can be closed under an open policy). Sweep the class and say so in the handoff: the other four per-open members (`initial`, `opens`, `openerRef`, `surface`) are reset or recomputed at open — quote the lines.
3. **GREEN:** the new cases pass; then the mutant the reviewer's M8 could not find — delete the restored line → the two cases RED, restore with `cp` + `diff -q` (never `git checkout --` over uncommitted work, COMMON §10.44).
4. **Gates:** `CMD-C6` ×3 (`.sh` under `/bin/bash` + inline) — its `n_s02c` arm still reads 1 through the moving-ref defect the reviewer confirmed (N1); measure the arm against `44744d8d` (0) and paste both, verdict reported as the command's defect, not hidden; `CMD-C5` ×3 (the four pinned `t3-library › lists` failures, nothing else); `cd apps/ui && npx tsc --noEmit -p tsconfig.json` exit 0; root typecheck delta 0 outside the pin; t9 hit list 1; all ten consent suites together. Commit: `fix(consent-ui S01-C6): reset the policy flag on every card open; pin the close-under-policy routes` ending with `Co-Authored-By: Claude Fable 5.1 <noreply@anthropic.com>`.

## 3. Handoff
`REWORK READY FOR REVIEW` on `t_f46592b6`, OPENING with `SKILLS LOADED`, then: the RED frames · the class sweep with lines · the mutant frame + restore proof · three-run tables with a commit column · gates as deltas · the commit sha · `comments read through`. Self-report first (a NEW file). Stop.
