# PACKET CODE-REV-S02-C1C2 — blind per-cluster code review (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on your ticket with `comments read through: <n>` NOW; then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` / `PLAN.md` / `DECISIONS.md` · `docs/missions/consent-ui/BASELINE.md` · the design extracts (visual truth).
Skills (Skill tool): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-reviewer` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (when judging a failure) · `superpowers:receiving-code-review` (if contested).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_0b1a0110` · **seat:** CODE-REV-S02-C1C2 · **role:** reviewer · **model:** claude-opus-5, fresh blind session · **round:** 1 of max 3
- **the work under review:** seat CODE-S02-C1C2, ticket `t_eab0c89f`, commit(s) `8fe1e0bc (C1) and 91877847 (C2); HEAD 91877847` on branch `slice/consent-s02`; its dispatching packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S02-C1C2.md` (review it FIRST — constants, `allowed` vs deliverables, base commit); the review package (commit list + stat + full diff) at `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/review-packages/S02-C1C2-r1.diff (893 lines: commits, stat, full diff -U10 — ONE Read)`.
- **your worktree (separate, detached at `8fe1e0bc (C1) and 91877847 (C2); HEAD 91877847`; cwd for every command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c1c2/dialectical-engine` — never the author's lane, never the main tree. node_modules are already cloned there; run `pnpm run generate:contract` first.
- **allowed (exhaustive):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S02-C1C2-r1.md` (verdict) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-REV-S02-C1C2.md` (self-report) · scratch under `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c1c2/dialectical-engine/.review-scratch/` (delete before handoff; prove with `git status --porcelain` = empty) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append) · comments on `t_0b1a0110` and ONE verdict comment on `t_eab0c89f` (`--author CODE-REV-S02-C1C2`) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/` (files named `<seat>-r<round>-*` only — COMMON §10.26; copy your probe kit there BEFORE the verdict comment) · scratch is `<seat>-r<round>/` per §10.11
- **forbidden:** editing the work under review · git writes other than in-scratch probes you fully revert (`git checkout HEAD -- <path>`, then `git status --porcelain` must be empty) · the other slice · the main tree · subagents producing the verdict.

## 2. Probes (`heartbeat-reviewer` §2) — build your own from the CLAIM, never from the author's test
Run every owned cluster command yourself ×3 · re-run the author's mutants AND add mutants of your own derived from the SPEC property (e.g. flip a default, skip the scroll-end check, store the wrong key, check the box on close) · render the component in jsdom yourself with a throwaway test in `.review-scratch/` and assert the SPEC's verbatim copy and both-mode token usage · typecheck delta against BASELINE.md · colour-literal gate hit list · `git diff --stat` vs the cluster's `allowed` surface (any file outside it is blocking) · the `globals.css` block discipline (only the slice's delimited block at the end changed) · registration request shape unchanged (grep the diff for `register(`/`adult_affirmed`) · the author's `SKILLS LOADED` vs the worker floor · constants transcribed match the design extracts · self-report bar · a11y claims (roles, focus, Esc) probed, not read.

## 3. Verdict — `reviews/CODE-REV-S02-C1C2-r1.md`
`SKILLS LOADED` · `Verdict: PASS | REWORK | BLOCKED` · packet findings · B1… · N1… (each: file:line, concrete inputs → wrong outcome, evidence) · what I verified and how (verbatim outputs) · what I did NOT verify · predictions · `comments read through`. Post it as ONE comment on `t_eab0c89f` (`--max-len 80000`); one-line pointer on `t_0b1a0110`. Round 3 REWORK → V DECISIONS PACKET row instead. Self-report first. Stop.

**Remedies (COMMON §10.22):** every B/N finding names its CLASS (binding) and marks its remedy `BINDING (measured: <what you ran>)` or `ADVISORY`. An advisory remedy the author refutes with output is not a NOT ADDRESSED.

## 4. Seat-specific charges (orchestrator, from the author's own handoff — verify, do not trust)
- The author's handoff (newest `READY FOR PEER REVIEW` comment by `CODE-S02-C1C2` on `t_eab0c89f`) claims: both cluster commands three runs verdict 0; the exported surface of `modalSemantics.ts` BYTE-IDENTICAL to the PLAN's fenced block (checked by a script that discriminates a whitespace reflow); `privacyPolicy.ts` exports `POLICY_JUMP`, `POLICY_SECTIONS`, `PolicyJump`, `PolicySection`; S02-S72's three ADR arms green. Re-run `run S02-C1 1 …` and `run S02-C2 1 …` yourself ×3 in YOUR worktree, from a `.sh` under `/bin/bash` and inline (COMMON §10.16).
- **The Esc STACK is the load-bearing behaviour (S01-R20 / S02-R14, B3 of the requirements loop):** a module-level LIFO + exactly ONE `document` keydown listener installed when the stack becomes non-empty; on `Escape` only the TOPMOST surface's `onClose` fires (`preventDefault` + `stopPropagation`); Tab is trapped on the topmost only; focus returns to the opener on close; `openSurfaceCount()` reports depth. Build your OWN jsdom probe with two nested surfaces and assert exactly that — the author's test is not your evidence.
- **`prefersReducedMotion()` guards `window.matchMedia`** (absent in jsdom) — probe it both ways.
- **Copy fidelity (R11/§Copy):** the eleven sections, eight pills, eyebrow `PRIVACY POLICY · v2.1 · EFFECTIVE 12 AUG 2026`, end marker `END OF POLICY · GDPR (EU) 2016/679 · v2.1` and the contact line must be byte-exact to `docs/missions/consent-ui/design/design-data.js:51,57-84` DECODED (`\uXXXX` → characters). Decode and diff them yourself (`python3` or `node`), never by eye; the pill→section mapping per SPEC R11.
- **S01 consumes this helper unchanged after its merge step** — any signature drift, default-export trick or side effect at import time is blocking.
- The ADR is `docs/architecture/01-decisions/ADR-0022-shared-modal-semantics.md` (status Proposed — V ratifies): transcribes DECISIONS + PLAN §DDD, invents nothing, matches the code.
- Typecheck blind spot (COMMON §10.30): the root `pnpm typecheck` cannot see `apps/ui/**`; run `cd <your worktree>/apps/ui && npx tsc --noEmit -p tsconfig.json` and report exit + diagnostics.
- **Author concern F2 (RULE ON IT):** the focus trap manages EVERY Tab inside the surface (not only the two ends) because jsdom implements no sequential focus navigation — under an end-only trap `S02-S06`'s property is RED against a correct implementation. Judge: is the full-Tab management correct in a real browser (does it fight native tab order, does it handle disabled/hidden/`tabindex=-1` elements, does it query focusables "at the moment Tab is pressed, never cached" per DECISIONS)? Say BINDING or ADVISORY and why.
- **Packet correction (orchestrator, F5):** the CODE-S02-C1C2 packet wrongly said "four-member `ModalSurface`" — the type has THREE members (`containerRef`, `initialFocusRef`, `onClose`); the four-member type is `PrivacyPolicyModal`'s prop type (C5). Do not charge the author for that sentence.
