# PACKET CODE-REV-S02-C8 — blind per-cluster code review (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on your ticket with `comments read through: <n>` NOW; then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` / `PLAN.md` / `DECISIONS.md` · `docs/missions/consent-ui/BASELINE.md` · the design extracts (visual truth).
Skills (Skill tool): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-reviewer` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (when judging a failure) · `superpowers:receiving-code-review` (if contested).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_e2bdcddb` · **seat:** CODE-REV-S02-C8 · **role:** reviewer · **model:** claude-opus-5, fresh blind session · **round:** 1 of max 3
- **the work under review:** seat CODE-S02-C8, ticket `t_ee948194`, commit(s) `a035f814 (S02-C8: the S02 style block appended at the end of globals.css + tests/unit/consent-s02-style-contract.test.ts); HEAD a035f814` on branch `slice/consent-s02-css (a sub-lane branched from slice/consent-s02 at 511d30b6 so C8 ran in parallel with C7; the orchestrator merges it back on PASS)`; its dispatching packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S02-C8.md (snapshot: snapshots/packets/CODE-S02-C8.md.at-dispatch; its ten constants came from PLAN §Cluster S02-C8, ticket t_f2a9994f and COMMON §7; the author found three packet defects — an 8th case the PLAN pins as 7, three tokens named that S02 never references, and a contrast figure that does not reproduce)` (review it FIRST — constants, `allowed` vs deliverables, base commit); the review package (commit list + stat + full diff) at `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/review-packages/S02-C8-r1.diff (845 lines: 1 commit, stat, full diff -U10 — ONE Read)`.
- **your worktree (separate, detached at the HEAD commit named last in the commit list above; cwd for every command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c8/dialectical-engine` — never the author's lane, never the main tree. node_modules are already cloned there; run `pnpm run generate:contract` first.
- **allowed (exhaustive):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S02-C8-r1.md` (verdict) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-REV-S02-C8-r1.md` (self-report) · scratch under `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c8/dialectical-engine/.review-scratch/` (delete before handoff; prove with `git status --porcelain` = empty) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append) · comments on `t_e2bdcddb` and ONE verdict comment on `t_ee948194` (`--author CODE-REV-S02-C8`) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/` (files named `<seat>-r<round>-*` only — COMMON §10.26; copy your probe kit there BEFORE the verdict comment) · scratch is `<seat>-r<round>/` per §10.11
- **forbidden:** editing the work under review · git writes other than in-scratch probes you fully revert (`git checkout HEAD -- <path>`, then `git status --porcelain` must be empty) · the other slice · the main tree · subagents producing the verdict.

## 2. Probes (`heartbeat-reviewer` §2) — build your own from the CLAIM, never from the author's test
Run every owned cluster command yourself ×3 · re-run the author's mutants AND add mutants of your own derived from the SPEC property (e.g. flip a default, skip the scroll-end check, store the wrong key, check the box on close) · render the component in jsdom yourself with a throwaway test in `.review-scratch/` and assert the SPEC's verbatim copy and both-mode token usage · typecheck delta against BASELINE.md · colour-literal gate hit list · `git diff --stat` vs the cluster's `allowed` surface (any file outside it is blocking) · the `globals.css` block discipline (only the slice's delimited block at the end changed) · registration request shape unchanged (grep the diff for `register(`/`adult_affirmed`) · the author's `SKILLS LOADED` vs the worker floor · constants transcribed match the design extracts · self-report bar · a11y claims (roles, focus, Esc) probed, not read.

## 3. Verdict — `reviews/CODE-REV-S02-C8-r1.md`
`SKILLS LOADED` · `Verdict: PASS | REWORK | BLOCKED` · packet findings · B1… · N1… (each: file:line, concrete inputs → wrong outcome, evidence) · what I verified and how (verbatim outputs) · what I did NOT verify · predictions · `comments read through`. Post it as ONE comment on `t_ee948194` (`--max-len 80000`); one-line pointer on `t_e2bdcddb`. Round 3 REWORK → V DECISIONS PACKET row instead. Self-report first. Stop.

**Remedies (COMMON §10.22):** every B/N finding names its CLASS (binding) and marks its remedy `BINDING (measured: <what you ran>)` or `ADVISORY`. An advisory remedy the author refutes with output is not a NOT ADDRESSED.

## 4. Seat-specific charges (orchestrator, from the author's own handoff — verify, do not trust)
- Author claims (handoff on `t_ee948194`; self-report `agent-reports/CODE-S02-C8.md`): `run S02-C8 1 tests/unit/consent-s02-style-contract.test.ts` worst `Tests 8 passed (8)`, `Test Files 1 passed (1)`, verdict 0 (×3 `.sh` under `/bin/bash` + ×3 inline, all six identical at a035f814); RED-first frame `No test files found, exiting with code 1`; root typecheck 8 / 0 outside the pin (a `TS2835` ninth diagnostic from a relative `../support/contrast` import was caught by that arm and fixed before commit); apps/ui arm exit 0; t9 `2 failed | 6 passed (8)`, hit list exactly the one `.drawerScrim` line at `:6096`; the three RED-at-base stylesheet suites (`pda-s03-keyboard-accessibility` 2/5, `v2ui-pages` 5/41, `role-token-map` 3/49) IDENTICAL by failure-name set with and without the block; `auth-flow-integration` 18/18; `v2ui-node-runner` 2/2. Re-run everything ×3 in YOUR worktree from a `.sh` and inline (COMMON §10.16, §10.30); measure the three suites with and without the block yourself (remove the block in scratch, run, restore with `cp`, `diff -q`).
- **Block discipline (S02-S59/S60), measured by the orchestrator and to be re-measured by you:** ONE hunk appended at the end of `globals.css` (7222 → 7627 lines; markers at `:7224` and `:7627`; 0 lines after the closing marker; everything above the opening marker byte-identical — the author says 164,567 == 164,567 bytes); inside the block 0 colour literals (`/oklch\(|#[0-9a-f]{3,8}\b|\brgba?\(/i`) and 0 token declarations (`/^\s*--[a-z0-9-]+\s*:/im`). Re-run those two greps; confirm the t9 set equality untouched.
- **S01/S02 selector collision (for the C9 merge):** the orchestrator measured the class tokens shared between S01's block (372 lines, in the S01 lane) and this block: none (`comm -12` empty). Re-measure in your worktree against `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s01/dialectical-engine/apps/ui/app/globals.css`'s S01 block (read-only) and state the shared-selector set; if any selector is styled by both blocks, that is a finding with the cascade consequence spelled out.
- **Design fidelity is the point (10c modal + 8a checkbox group):** `docs/missions/consent-ui/design/turn-10-cookie-consent.html` (`:48,50,52` for the modal geometry), `turn-8a-checkbox-group.html:1-10`, `design-data.js` decoded — diff every S02-S61 geometry value and every S02-S62 checkbox value in the block against the extract byte-exact (`width: min(680px, calc(100vw - 32px))`, `max-height: 92vh`, header `22px 24px 14px`, region `16px 24px 8px`, footer `14px 24px`, tab `52×4` at `top: 0; left: 24px`, `border-radius: var(--r-tab)`; container `1px solid var(--line)` / `11px` / `var(--shell)` / `2px 13px`; row `flex`/`flex-start`/`10px`/`11px 0`/`pointer`/first-row `border-bottom`; square `appearance: none`/`17px`/`5px`/`1.5px solid var(--ok-edge)`; checked `var(--ok-dot)`; glyph `"✓"`/`var(--core)`/`10px`/`800`; label `11.5px`/`1.5`). Then the 29 `.policy*` selectors + 5 `.consent*` selectors the author styled BEYOND the PLAN's named values — spot-check at least the eyebrow, title, lede, pills (`.policyPill`/`.policyJumps`), section head/dot, the primary button and the close control against the design's own CSS in the extract; every token reference resolved through COMMON §7 (the author substituted `var(--shadow-pop)` for the design's `0 30px 70px -25px rgba(0,0,0,.55)` bezel shadow — judge the mapping).
- **Motion + reduced motion (S02-S63, R24):** two `animation:` declarations (`consentPolicyScrimIn` 140ms on `.policyScrim` at block `:105`, `consentPolicyCardIn` 180ms on the card at `:124`) and one `@media (prefers-reduced-motion: reduce)` rule at `:397` setting `animation: none` — assert mechanically that the rule's selector list covers BOTH animated selectors (plant the mutant that drops one); the author's F4 says an `animation:` written as a SECOND `.policyScrim { … }` rule was caught by their own S02-S61 source-text assertion — confirm no duplicate selector blocks remain (each selector once).
- **S02-S64 contrast, recomputed INDEPENDENTLY:** `opacity: .65` on the disabled `.policyPrimary` (`:disabled` and/or `[aria-disabled="true"]` — say which the block uses and whether it matches the component's markup `disabled` + `aria-disabled="true"`); composite label and face over `--shell` per channel with COMMON §7's Terracotta/Chamber values and `tests/support/contrast.ts` — author: 4.79 / 7.17 at .65, 4.13 at .60, **5.61 / 8.09 at .70 (PLAN:1250 and DECISIONS:109 say 5.54)** — reproduce the ladder, state which compositing model reproduces the PLAN's 5.54 if any, and whether the pin (.65) is unaffected. The author's two-file mutant for the arithmetic (stylesheet AND test moved together) — re-run it.
- **`.policyGateHint` (ticket `t_f2a9994f`, N3):** the block carries the `.srOnly` declaration set verbatim (block `:365-374`) and no `display: none` / `visibility: hidden` for it; the test asserts both. Render the modal in jsdom with the stylesheet and confirm the element is still in the accessibility tree (`aria-describedby` resolves; not `display:none`).
- **S02-S65 standing guard:** GREEN before and after; plant a `transform:` on `.authCard` in scratch and watch it fail.
- **Packet defects the author filed (answer each in one line):** (1) the 8th case vs PLAN:1270's `Tests 7 passed (7)` — the orchestrator's addition; docs residue; (2) `--muted-bg`/`--muted-border`/`--shadow-knob` named as referenced tokens although S02 never references them — harmless over-listing, confirm no such reference exists in the block; (3) the `.70` figure; (4) `globals.css:885-902` `.authCheck` dead CSS above the block — out of surface, the orchestrator tickets it; (5) TOOLING-TRAPS `:2092`'s BROKEN arm misclassifying the lawful `No test files found` RED — one sentence.
- **Boundaries:** two files, both in the allowed list; no component touched; `git diff --stat 511d30b6..a035f814` = exactly `globals.css` + the new test. The author's `SKILLS LOADED` is six (floor + `systematic-debugging`; `receiving-code-review` correctly absent at round 0) — the orchestrator's body grep found all six. Probe kit copied to `probes/code-rev-s02-c8-r1-*` (lane from argv) BEFORE the verdict comment.
