# PACKET CODE-S01-C1C2 — Opus 5 coding seat (mission `consent-ui`)

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` (never edit) · `PLAN.md` (the steps you own: S01-S01 … S01-S11 + S01-S47 (cluster S01-C1 = S01-S01…S04; cluster S01-C2 = S01-S05…S11 and S01-S47, the ADR step added in rework round 1 — the PLAN cluster table at its `S01-C2` row is the source of truth); the cluster rows C1C2) · `DECISIONS.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/BASELINE.md` · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` · your ticket's comments through the cursor. The design extracts (COMMON header) are the visual truth; the SPEC's verbatim copy and token map are binding.
Skills (Skill tool, in order): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-worker` · `superpowers:test-driven-development` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (the moment anything is broken) · `superpowers:receiving-code-review` (on rework). List them in `SKILLS LOADED`.

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_8d084df2` · **slice ticket (V's):** `t_26efb70d` · **seat:** CODE-S01-C1C2 · **role:** worker · **model:** claude-opus-5 · **rework rounds: max 3**
- **lane (your cwd for EVERY command; never leave it, never touch the main tree):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/consent-s01/dialectical-engine` · **branch:** `slice/consent-s01` · **base commit:** `2b670d30` (verify with `git rev-parse HEAD` first; a mismatch is a packet defect — report and stop)
- **comment cursor at dispatch:** 0 · **review route:** CODE-REV-S01-C1C2 (Opus 5, blind, separate detached worktree — not yours to dispatch)
- **clusters you own:** C1C2 — their verification commands and file surfaces are in `PLAN.md § Clusters`; run each THREE times, worst run is the verdict.
- **allowed (exhaustive, inside the lane):** **C1:** `apps/ui/app/globals.css` — the two token blocks ONLY (`:root` lines 5-97 and `html[data-mode="chamber"]` lines 99-158; not one character elsewhere in the file) · `tests/unit/t9-mode-tokens.test.ts` (map registrations + the composite-contrast `it()` S01-S03 names; never extend `TEXT_TOKENS`/`LINE_TOKENS`). **C2:** `apps/ui/lib/consent.ts` (create) · `tests/render/consent-storage.test.tsx` (create) · `docs/architecture/01-decisions/ADR-0021-consent-storage-contract.md (ORCHESTRATOR CORRECTION 21:15: the PLAN says 0019/0020 — those numbers are reserved by the halted translation mission; COMMON §10.23 — this packet governs the file name)` (create, status **Proposed — V ratifies**; transcribe the contract from `slices/S01/DECISIONS.md` and SPEC R01–R05/R28 — an orchestrator addition to the PLAN's surface, recorded in the ledger) · plus (main-tree paths) `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-S01-C1C2.md` (self-report) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append only) · comments on `t_8d084df2` (`--author CODE-S01-C1C2`)
- **forbidden:** every other file in the lane — in particular `apps/ui/components/**`, `apps/ui/app/layout.tsx`, `apps/ui/app/settings/page.tsx`, the S01 delimited block in `globals.css` (C3 opens it), `tests/support/contrast.ts` (forbidden by ARCH-S01 — the composite helper is local to the t9 test file), `TEXT_TOKENS`/`LINE_TOKENS` arrays (34-row pin) · every other cluster's surface · the other slice's files · COMMON §3's no-touch surface · protocol docs and skills · `globals.css` above your slice's delimited block · any push, merge, Done, ticket split, branch, worktree or rebase operation · **subagents of any kind** (no helpers, no reviewers — review arrives from the orchestrator after your handoff).

## 2. The work
Implement exactly the PLAN steps named above, RED first (`heartbeat-worker` §2 refutation duty: property → mutant → RED → revert → GREEN → neighbouring mutant not caught; print `git status --porcelain` after every restore). Constants you TRANSCRIBE, never compute: the ten token names and both-mode values from SPEC R08/R24 and PLAN step S01-S02's derivation table (design `tint()` applied to `okC`/`tA.mute`, house leading-dot alpha form, comma-tight) · `--scrim: rgba(10,8,6,.42)` (mode-independent) · the storage key `debateai.consent`, schema `v: 1`, members `v, essential, quality, analytics, decidedAt` (R01) · what each control writes (R04) · the three category records byte-exact per SPEC §Copy / `design-data.js:88-90` decoded (R28) — never retype from memory, copy from the SPEC. Colours only via `var(--token)`; new tokens go inside the two existing token blocks AND into `tests/unit/t9-mode-tokens.test.ts`'s maps (comma-tight). Gates before handoff, in order: (1) `pnpm run generate:contract` — say you ran it and that the tree stayed clean; (2) `pnpm typecheck` — report the DELTA against BASELINE.md (no diagnostic outside the 8 pinned in `tests/unit/s14-ui.test.ts`); (3) `pnpm exec vitest run tests/unit/t9-mode-tokens.test.ts` — the colour-literal hit list is exactly the one pinned line and the other six tests are green; (4) `pnpm exec vitest run tests/render/auth-flow-integration.test.tsx` — 17+ passed, or the SPEC-named updates with their reason; (5) your cluster commands ×3 (table: run 1/2/3, worst). Commit on `slice/consent-s01` ONLY when all owned clusters are GREEN on the worst run, message ``feat(consent-ui S01-C1): declare the consent token contract` then `feat(consent-ui S01-C2): consent storage domain module` (one commit per cluster, C1 first)`; one commit per cluster is fine; never amend a reviewed commit. Write as you go (COMMON §4b).

## 3. Handoff
`READY FOR PEER REVIEW` on `t_8d084df2`, OPENING with `SKILLS LOADED`, then: every RED frame (verbatim) · suites as `passed/total` (failures named, pre-existing dated) · the three-run cluster table · gates (1)-(4) results verbatim · constants disclosed · refutation evidence · packet defects · unexpected findings (file:line) · the commit sha(s) · `comments read through`. Self-report first (COMMON §5). Stop.
