# PACKET CODE-REV-S02-C9 — blind per-cluster code review (mission `consent-ui`)

**STEP 0 — CLAIM before you read anything else (COMMON §10.29):** post `CLAIM` on your ticket with `comments read through: <n>` NOW; then read the packet.

Read FIRST, in full: `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/COMMON.md` · `docs/missions/consent-ui/INSTRUCTIONS.md` · the slice `SPEC.md` / `PLAN.md` / `DECISIONS.md` · `docs/missions/consent-ui/BASELINE.md` · the design extracts (visual truth).
Skills (Skill tool): `superpowers:using-superpowers` · `heartbeat-protocol` · `heartbeat-reviewer` · `superpowers:verification-before-completion` · `superpowers:systematic-debugging` (when judging a failure) · `superpowers:receiving-code-review` (if contested).

## 1. Ticket state
- **board:** `consent-ui` · **ticket:** `t_f55ce0ad` · **seat:** CODE-REV-S02-C9 · **role:** reviewer · **model:** claude-opus-5, fresh blind session · **round:** 1 of max 3
- **the work under review:** seat CODE-S02-C9, ticket `t_d36df457`, commit(s) `2127c4ad (the ONE test-only commit: C7 pins t_31623705 / t_c0fd0601 / t_086c1d78, the C8 number-compare t_e7801ab7 + the duplicate-comment assertion, the S01-C3 end-of-file assertion relaxed) on the S02-S66 merge 19cc8e77; HEAD 2127c4ad — C9 itself (S02-S66…S02-S69) writes no product file` on branch `slice/consent-s02 (the merged lane: S01 @ 4ddc350c merged at 19cc8e77 after the C8 sub-lane merge e8bf0658)`; its dispatching packet `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/consent-ui/packets/CODE-S02-C9.md (snapshot: snapshots/packets/CODE-S02-C9.md.at-dispatch; its measured-truth section states why run_c9's two merge arms cannot pass as written and what property replaces them)` (review it FIRST — constants, `allowed` vs deliverables, base commit); the review package (commit list + stat + full diff) at `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/review-packages/S02-C9-r1.diff (428 lines: 1 commit, stat, full diff -U10 — ONE Read)`.
- **your worktree (separate, detached at the HEAD commit named last in the commit list above; cwd for every command):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c9/dialectical-engine` — never the author's lane, never the main tree. node_modules are already cloned there; run `pnpm run generate:contract` first.
- **allowed (exhaustive):** `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/docs/missions/consent-ui/reviews/CODE-REV-S02-C9-r1.md` (verdict) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/agent-reports/CODE-REV-S02-C9-r1.md` (self-report) · scratch under `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-s02-c9/dialectical-engine/.review-scratch/` (delete before handoff; prove with `git status --porcelain` = empty) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/TOOLING-TRAPS.md` (append) · comments on `t_f55ce0ad` and ONE verdict comment on `t_d36df457` (`--author CODE-REV-S02-C9`) · `/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/consent-ui/probes/` (files named `<seat>-r<round>-*` only — COMMON §10.26; copy your probe kit there BEFORE the verdict comment) · scratch is `<seat>-r<round>/` per §10.11
- **forbidden:** editing the work under review · git writes other than in-scratch probes you fully revert (`git checkout HEAD -- <path>`, then `git status --porcelain` must be empty) · the other slice · the main tree · subagents producing the verdict.

## 2. Probes (`heartbeat-reviewer` §2) — build your own from the CLAIM, never from the author's test
Run every owned cluster command yourself ×3 · re-run the author's mutants AND add mutants of your own derived from the SPEC property (e.g. flip a default, skip the scroll-end check, store the wrong key, check the box on close) · render the component in jsdom yourself with a throwaway test in `.review-scratch/` and assert the SPEC's verbatim copy and both-mode token usage · typecheck delta against BASELINE.md · colour-literal gate hit list · `git diff --stat` vs the cluster's `allowed` surface (any file outside it is blocking) · the `globals.css` block discipline (only the slice's delimited block at the end changed) · registration request shape unchanged (grep the diff for `register(`/`adult_affirmed`) · the author's `SKILLS LOADED` vs the worker floor · constants transcribed match the design extracts · self-report bar · a11y claims (roles, focus, Esc) probed, not read.

## 3. Verdict — `reviews/CODE-REV-S02-C9-r1.md`
`SKILLS LOADED` · `Verdict: PASS | REWORK | BLOCKED` · packet findings · B1… · N1… (each: file:line, concrete inputs → wrong outcome, evidence) · what I verified and how (verbatim outputs) · what I did NOT verify · predictions · `comments read through`. Post it as ONE comment on `t_d36df457` (`--max-len 80000`); one-line pointer on `t_f55ce0ad`. Round 3 REWORK → V DECISIONS PACKET row instead. Self-report first. Stop.

**Remedies (COMMON §10.22):** every B/N finding names its CLASS (binding) and marks its remedy `BINDING (measured: <what you ran>)` or `ADVISORY`. An advisory remedy the author refutes with output is not a NOT ADDRESSED.

## 4. Seat-specific charges (orchestrator, from the author's own handoff — verify, do not trust)
- **This is the INTEGRATION review of the merged lane.** Author claims (handoff + ADDENDUM cursor correction on `t_d36df457`; self-report `agent-reports/CODE-S02-C9.md`): `run_c9 10 …` ×3 (`.sh` under `/bin/bash` + inline): vitest half `Tests 105 passed (105)`, `Test Files 10 passed (10)`; the two merge arms read `--scrim:=1` / `S02markers=1` so run_c9 AS WRITTEN = VERDICT 1 on those arms alone, and the PROPERTY (`--scrim:` ≥ 1, S01 open/end 1/1, S02 open/end 1/1, S01's end before S02's open, 0 lines after S02's end) = VERDICT 0 ×3 — the PLAN's arm defect is ticketed (`t_4f97ca86`); the sixteen consent files `Test Files 16 passed (16)`, `Tests 181 passed (181)` at 2127c4ad (was `1 failed | 178 passed (179)` at the base — the S01-C3 end-of-file assertion); root typecheck 8 / 0 outside; apps/ui arm exit 0; t9 `2 failed | 7 passed (9)` with the hit line now at `:6116`; the three RED-at-base stylesheet suites unchanged by name. Re-run ALL of it ×3 in YOUR worktree (`.sh` + inline; COMMON §10.16, §10.30) and state the property yourself.
- **The one commit, RED-first per pin (each restore by `cp` + `diff -q`):** (a) `t_31623705` — S02-S50/S51 now dismiss and assert `document.activeElement` is the privacy input; mutant R9 (`if (event.target === input) input.focus()`) must go RED — plant it; (b) `t_c0fd0601` — the tracker pin: after ONE cancelled click, `(input as any)._valueTracker.getValue() === "false"`; RED with the `queueMicrotask` block (`SignUpFlow.tsx:150-153`) removed — plant it; judge the React-internal coupling's labelling (the S02 DECISIONS ruling accepts it in a TEST only); (c) `t_086c1d78` — a DISPATCHED `new MouseEvent("click", { bubbles: true })` on the row text in the CHECKED state: the row handler runs once and the box ends unchecked; RED with the re-entrancy guard (`event.target !== input`) removed — plant it; (d) `t_e7801ab7` — S02-S64's assertion compares the NUMBER and formats only for the message; the duplicate-comment assertion `expect(new Set(comments).size).toBe(comments.length)` is the suite's first line of the edit — duplicate a comment in scratch and watch it RED; (e) the S01-C3 case in `consent-bar.test.tsx` relaxed to "whitespace or S02's delimited block follows S01's closing marker" while still asserting exactly ONE S01 block — append junk after S02's closing marker in scratch → the S02 contract goes RED and the S01 case stays as designed; remove S02's block in scratch → the S01 case must still pass (nothing but whitespace follows). **No existing assertion weakened anywhere** — diff every changed `it()` against 19cc8e77.
- **S02-S66 recorded, not performed:** the ticket carries `4ddc350c` and `19cc8e77`; the seat ran no git write beyond its commit (`git reflog` in your worktree is not the lane's — check the lane's branch log: `git log --oneline 19cc8e77..2127c4ad` = one commit; no merge, no rebase).
- **S02-S69:** the author reports either the three commands' outputs or the literal `UNVERIFIED — dev stack not serving this branch`; confirm which and that no dev-stack process was started/stopped by the seat (the dev stack is V's; note for V's test point either way).
- **Cross-slice integration, probed yourself in jsdom (own fixture):** with the merged stylesheet loaded (`tests/support/tokenContract.ts`'s `styledDocument()` if it serves; else a byte scan), the two blocks coexist: S01's `.consentBar`/`.consentCard` rules and S02's `.policy*`/`.consent{Group,Row,Box,Text,PolicyLink}` rules resolve with no shared selector (the C8 reviewers measured EMPTY — re-measure at the merged head, both blocks now in one file), both token blocks carry S01's C1 tokens once each (`--ok-edge:` 2, `--scrim:` 1, `--z-policy-*:` 1), t9's set equality holds. Render the sign-up card and the cookie surfaces in one document: the Esc stack with the cookie card open and the policy opened from `Privacy notice` (S01-S40) still closes only the policy; the sign-up page's modal still opens in `mode="consent"`.
- **Author's packet/PLAN defects and unexpected findings (handoff §§ after the tables):** answer each in one line — true or not, ticketable or not.
- **Boundaries:** three files, all tests; zero product files (the orchestrator measured 0); `PROGRESS.md`/`PLAN.md` untouched; the author's `SKILLS LOADED` (seven) vs the floor. Probe kit copied to `probes/code-rev-s02-c9-r1-*` (lane from argv) BEFORE the verdict comment; comment bodies passed as `"$(cat file)"` (COMMON §10.47).
