from pathlib import Path
import json,subprocess,datetime
S=Path('/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine');D=S/'docs/missions/support-conversation-20260914';E=S/'.hermes/reports/support-conversation-20260914/evidence';b=json.loads((D/'board-ids.json').read_text());h=['/Users/vladmihaimiron/.local/bin/hermes','kanban','--board',b['board']]
def run(*a):return subprocess.check_output(h+list(a),text=True)
new=[('V_P3_DECISION','[V] DECISION CP1 security correction after final review cap','Final separate review pass3/3 at5cbfc6d leaves three reproduced security boundary failures: coordinator-bearing supplied-value residue, positive additive security-operation scope, and decoded path forms after assignment delimiters. Evidence reviews/REV2-p3.md B1-B3. Owner decision needed to authorize a focused Sol correction plus fresh separate Sol review beyond current cap; retain one-attempt reviewed recovery, existing model and all safeguards. No repair/review automatically dispatched; no risk waiver or CP1 acceptance.','high',True),('COMPAT_P3_STATE','[gpt-5.6-sol] Finding: benign credential state word over-redacted','REV2-p3 N1: synthetic benign password-unavailable statement is over-redacted by the legacy one-token pattern overriding the typed exclusion. Security-conservative compatibility issue; no leak. Deferred owner-decision row, no implementation dispatch.','low',False),('COPY_P3_RO','[gpt-5.6-sol] Finding: minor Romanian Settings draft typo','REV3-p3 N1: saved actual LIVE_P2 Romanian Settings response says lucruuri instead of lucruri. Nonblocking; meaning/product facts accurate. Retain finite sample, no retry; future copy/model-quality work only when authorized.','low',False),('PROC_REV1_P3_SCOPE','[process residue] Reviewer dependency link exceeded explicit packet list','REV1_P3 used a temporary apps/runner/node_modules symlink outside four explicitly allowed links while running the degraded fixture. Reviewer disclosed and removed it; no tracked/target-byte change reported and primary/detached5cb clean. Root must derive needed workspace dependency links before dispatch and workers must surface contract gaps before creating extra links. Nonblocking process residue, no product repair or pass4.','low',False)]
for key,title,body,risk,human in new:
 assert key not in b['tickets'];args=['create',title,'--body',body,'--workspace','dir:'+str(S),'--created-by','Astra','--idempotency-key',b['board']+':'+key,'--json']
 args+=['--assignee','human'] if human else ['--triage']
 r=json.loads(run(*args));tid=r.get('id') or r['task']['id'];b['tickets'][key]=tid;(D/'board-ids.json').write_text(json.dumps(b,indent=2)+'\n')
 if not human:run('assign',tid,'none')
 state={'ticket':tid,'node':key,'risk_tier':risk,'status':'waiting_human' if human else 'queued','owner':{'agent':'human' if human else 'Astra','session':None},'model':'gpt-6-astra' if not human else None,'authority_epoch':1,'rework_round':2,'final_review_pass':3,'contract':{'allowed':['owner decision only' if human else 'recorded finding only; no implementation dispatch'],'forbidden':'all_others','human_review':human},'comments_read_through':0,'human_acceptance':'PENDING' if human else 'NOT_APPLICABLE'}
 run('comment',tid,'STATE\n'+json.dumps(state,indent=2),'--author','Astra')
 if human:run('block',tid,'Final pass3 REWORK requires an explicit owner decision; no further correction or review dispatched.','--kind','needs_input');run('link',tid,b['tickets']['CP1'])
 print(key,tid)
for n,verdict in [(1,'PASS named correctness'),(2,'REWORK security; B1-B3 open'),(3,'BLOCKED on DEST; product-truth portion PASS')]:
 key=f'REV{n}_P3';tid=b['tickets'][key];cp=E/f'REV{n}-p3-consumption.json';c=json.loads(cp.read_text());msg=f'CONSUMED final pass3 {verdict} at5cbfc6d483aae0f56eabfdee00a6829e09e76c3d. Root verified all180 GATE inputs,108 product paths, indexed artifacts and six actual native skill bodies. Consumer {cp.name}. Review work complete; substantive limitations/findings retained. No CP1 acceptance.';run('comment',tid,msg,'--author','Astra');run('complete',tid,'--result',msg)
closed={'LIVE_GUIDANCE':'REV1+REV3: one finite seven-once actual matrix now useful/grounded, six accepted drafts and one exact reviewed recovery; not model-improvement proof.','OBS_CORRELATION':'REV1+REV2: fixed bounded seven-key projection and strict isolated-cursor consumer; ambiguous on duplicate/extra records. No API-event join or discarded-byte proof.','TYPE_P2_REGRESSION':'REV1: mission TS2532 corrected at606b; exact inherited76 diagnostics remain, project typecheck still fails.','INT_P2_DEGRADED':'REV1: projection-only fixture repair preserves every assertion. Independent8/8 and admitted/absent projection control prove call/refusal/usage/health distinction. Original977/1/1 whole-suite frame retained.','SEC_ENCODED_CREDENTIAL':'REV2: demonstrated single/deeper encoded-credential members reject in answer/summary. No arbitrary-encoding guarantee.','LIVE2_ACTION_ID':'REV2+REV3:35 exact IDs and bounded transforms reject,52 labels accepted, aliases request-bound; actual seven visible replies clean and both creation actions canonical.'}
for key,why in closed.items():
 tid=b['tickets'][key];msg='RESOLVED within demonstrated final pass3 scope at5cbfc6d: '+why+' See REV1/2/3-p3 reports and consumers; other security blockers and Forgot remain.';run('comment',tid,msg,'--author','Astra');run('complete',tid,'--result',msg)
openfind={'SEC_P1':'B1: coordinator-bearing supplied credential-value tail remains in synthetic user storage/model transit. Partial fixes retained.','SEC_CREDENTIAL_POLICY':'B2: positive finite/modal English/Romanian plus-groups inherit prior negation and pass screening.','SEC_P2':'B2+B3: shared case-summary sink accepts additive positive security operations and assignment-prefixed decoded paths; reviewed answer recovery does not cover summaries.','SEC_P3':'B3: encoded backslash/drive/UNC forms after equals pass screens and synthetic answer storage/return; no clickability/execution claim.'}
for key,why in openfind.items():
 tid=b['tickets'][key];msg='FINAL PASS3 REMAINS OPEN at5cbfc6d. '+why+' Exact evidence REV2-p3.md and final-security-boundary-attempt3.log. Routed to V_P3_DECISION '+b['tickets']['V_P3_DECISION']+'; no hidden fourth correction/review or safety waiver.';run('comment',tid,msg,'--author','Astra');run('block',tid,'Owner decision after final review cap; '+why,'--kind','needs_input')
run('comment',b['tickets']['SOURCE_CUSTODY'],'Final REV3 retains historical source custody UNVERIFIED; no restoration/actor inference. The old56-path forward window is historical. Its final receipt observes81 current dirty paths; later ROOT-source-custody-p3-observation.json records82 with same sourceHEAD/index and clean isolated product5cb. No unrelated contents inspected; current shared-source changes are preserved.','--author','Astra')
run('comment',b['tickets']['CP1'],'Final separate review pass3 consumed: correctness PASS; security REWORK B1-B3; product truth PASS but DEST blocked. CP1 NOT READY, NOT ACCEPTED. Six demonstrated findings resolved; four security tickets remain open, V_P3_DECISION '+b['tickets']['V_P3_DECISION']+' records cap decision. Existing Forgot question remains unanswered and is not repeated. CP2/CP3 remain gated.','--author','Astra')
run('block',b['tickets']['CP1'],'Existing Forgot destination and final-pass security decision remain unresolved. Not ready for user verification or acceptance.','--kind','needs_input')
keys=[*closed,*openfind,'REV1_P3','REV2_P3','REV3_P3','CP1','DEST','V_P3_DECISION','COMPAT_P3_STATE','COPY_P3_RO','PROC_REV1_P3_SCOPE','SOURCE_CUSTODY'];rows=[]
for key in keys:
 r=json.loads(run('show',b['tickets'][key],'--json'));rows.append({'key':key,'ticket':b['tickets'][key],'status':r['task']['status'],'lastComment':r['comments'][-1] if r['comments'] else None})
assert all(x['status']=='done' for x in rows if x['key'] in closed or x['key'].startswith('REV'))
assert all(x['status']=='blocked' for x in rows if x['key'] in openfind or x['key'] in ['CP1','DEST','V_P3_DECISION'])
p=E/'P3-disposition-board.json';assert not p.exists();p.write_text(json.dumps({'at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'rows':rows},indent=2)+'\n');print(json.dumps({'newTickets':4,'closedFindings':len(closed),'openSecurityFindings':len(openfind),'reviewNodesDone':3,'cp1':'blocked'}))
