ALTER TABLE obs.occurrence
  DROP CONSTRAINT IF EXISTS occurrence_taxonomy_class_check,
  ADD CONSTRAINT occurrence_taxonomy_class_check CHECK (taxonomy_class IN (
    'PROCESS_DEATH', 'HTTP_FAILURE', 'JOB_FAILURE', 'PROVIDER_EXHAUSTED', 'DB_FAILURE',
    'PARSE_SCHEMA_FAILURE', 'STALL_DETECTED', 'SILENT_NOOP', 'SUSPICIOUS_SUCCESS',
    'CLIENT_FAILURE', 'CAPTURE_SELF', 'ORIGIN_UNKNOWN', 'JOB_LIFECYCLE'
  ));
