-- Explicit NEW recovery facet: current password + issued prior website-verified
-- bound email proof. This qualifies only this new path, not legacy T1/T2 rules.
-- Familiar IP/UA is an optional operational heuristic, never an authenticator.
DO $$ BEGIN
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='debateai_mfa_recovery_owner') THEN CREATE ROLE debateai_mfa_recovery_owner NOLOGIN NOINHERIT;END IF;
 IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='debateai_mfa_recovery_runtime') THEN CREATE ROLE debateai_mfa_recovery_runtime NOLOGIN NOINHERIT;END IF;
END $$;
GRANT USAGE ON SCHEMA identity,staff,register,core TO debateai_mfa_recovery_owner;
GRANT USAGE ON SCHEMA identity TO debateai_mfa_recovery_runtime;
CREATE TABLE identity.mfa_recovery_control(
 challenge_id uuid PRIMARY KEY,recovery_request_id uuid UNIQUE REFERENCES identity.account_recovery_request ON DELETE CASCADE,
 user_id uuid NOT NULL REFERENCES identity."user" ON DELETE CASCADE,register_version bigint NOT NULL REFERENCES register.register_version,policy jsonb NOT NULL,
 password_snapshot text NOT NULL,security_epoch bigint NOT NULL,email_index_snapshot bytea NOT NULL,primary_snapshot jsonb NOT NULL,backup_snapshot jsonb,channel_inventory_snapshot jsonb NOT NULL,
 channel_id uuid NOT NULL REFERENCES identity.channel_binding DEFERRABLE INITIALLY DEFERRED,channel_snapshot jsonb NOT NULL,channel_type text NOT NULL,channel_verified_at timestamptz NOT NULL,
 original_factor_id uuid NOT NULL REFERENCES identity.mfa_factor DEFERRABLE INITIALLY DEFERRED,factor_snapshot jsonb NOT NULL,factor_verified_at timestamptz NOT NULL,
 link_hash text NOT NULL UNIQUE CHECK(link_hash ~ '^sha256:[0-9a-f]{64}$'),cancel_hash text NOT NULL UNIQUE CHECK(cancel_hash ~ '^sha256:[0-9a-f]{64}$'),
 session_hash text UNIQUE CHECK(session_hash ~ '^sha256:[0-9a-f]{64}$'),csrf_hash text CHECK(csrf_hash ~ '^sha256:[0-9a-f]{64}$'),
 email_expires_at timestamptz NOT NULL,expires_at timestamptz NOT NULL,paired_at timestamptz,link_used_at timestamptz,completed_at timestamptz,
 stage text NOT NULL DEFAULT 'EMAIL_REQUIRED' CHECK(stage IN('EMAIL_REQUIRED','FACTOR_REQUIRED','TOTP_REQUIRED','CODES_REQUIRED','ACK_REQUIRED','READY','COMPLETED','CANCELLED','REFUSED','EXPIRED')),
 failures integer NOT NULL DEFAULT 0 CHECK(failures>=0),new_factor_id uuid REFERENCES identity.mfa_factor DEFERRABLE INITIALLY DEFERRED,new_factor_snapshot jsonb
);
CREATE TABLE identity.mfa_recovery_staged_code(recovery_request_id uuid NOT NULL REFERENCES identity.mfa_recovery_control(recovery_request_id) ON DELETE CASCADE,slot smallint NOT NULL CHECK(slot BETWEEN 1 AND 10),code_hash text NOT NULL,PRIMARY KEY(recovery_request_id,slot),UNIQUE(recovery_request_id,code_hash));
CREATE TABLE identity.mfa_recovery_notice_binding(challenge_id uuid NOT NULL REFERENCES identity.mfa_recovery_control ON DELETE CASCADE,channel_id uuid NOT NULL REFERENCES identity.channel_binding DEFERRABLE INITIALLY DEFERRED,payload_ciphertext jsonb NOT NULL CHECK(core.is_content_envelope(payload_ciphertext)),cancel_authorized boolean NOT NULL,cancel_payload_ciphertext jsonb CHECK(cancel_payload_ciphertext IS NULL OR core.is_content_envelope(cancel_payload_ciphertext)),PRIMARY KEY(challenge_id,channel_id));
CREATE TABLE identity.mfa_recovery_notice(notice_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),challenge_id uuid NOT NULL REFERENCES identity.mfa_recovery_control ON DELETE CASCADE,user_id uuid NOT NULL REFERENCES identity."user" ON DELETE CASCADE,channel_id uuid NOT NULL REFERENCES identity.channel_binding DEFERRABLE INITIALLY DEFERRED,event_kind text NOT NULL CHECK(event_kind IN('PROOF','STARTED','COMPLETED','CANCELLED','REFUSED')),payload_ciphertext jsonb NOT NULL CHECK(core.is_content_envelope(payload_ciphertext)),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),available_at timestamptz NOT NULL DEFAULT clock_timestamp(),lease_id uuid,lease_until timestamptz,attempts integer NOT NULL DEFAULT 0,sent_at timestamptz,dead_at timestamptz,UNIQUE(challenge_id,channel_id,event_kind));
CREATE TABLE identity.mfa_recovery_source_window(source_digest text PRIMARY KEY,window_started_at timestamptz NOT NULL,uses integer NOT NULL);
CREATE FUNCTION identity.mfa_recovery_rules(p_register bigint) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE v jsonb;BEGIN PERFORM identity.password_recovery_rules(p_register);SELECT value_json INTO v FROM register.register_row r JOIN register.register_version rv USING(register_version) WHERE r.register_version=p_register AND r.row_key='mfaRecoveryPolicy' AND rv.sealed AND rv.row_count=(SELECT count(*) FROM register.register_row x WHERE x.register_version=rv.register_version);
 IF v IS DISTINCT FROM '{"kind":"MFA_RECOVERY_POLICY","policy_version":1,"proof":"CURRENT_PASSWORD_AND_ISSUED_PRIOR_VERIFIED_BOUND_EMAIL","tier_qualification":"FRESH_PROOF_PAIR_WITH_ACCOUNT_RISK_CHECKS","email_challenge_ttl_ms":1800000,"replacement_ttl_ms":300000,"recognized_context_required":false,"recognized_context_lookback_ms":2592000000,"risk_retention_ms":7776000000,"maximum_risk_signals":128,"adverse_kinds":["SESSION_CONTEXT_CHANGED","RECOVERY_PROOF_FAILED"],"adverse_rule":"AFTER_LATEST_COMPLETED_LOGIN_OR_ANY_WITHOUT_LOGIN","per_source_across_accounts":20,"source_window_ms":300000,"proof_failures_per_attempt":5,"cancel_cooldown_ms":86400000,"failure_cooldown_ms":300000,"preserve_password":true,"ordinary_only":true}'::jsonb THEN RAISE EXCEPTION 'MFA_RECOVERY_POLICY_UNRESOLVED';END IF;RETURN v;
END $$;
CREATE FUNCTION identity.mfa_recovery_eligible(p_user uuid) RETURNS boolean LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT identity.backup_email_eligible(p_user) AND NOT EXISTS(SELECT 1 FROM staff.subject WHERE user_id=p_user) AND NOT EXISTS(SELECT 1 FROM identity.password_recovery_retry_lock WHERE user_id=p_user AND locked_until>clock_timestamp()) $$;
CREATE FUNCTION identity.mfa_recovery_channel_inventory(p_user uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT COALESCE(jsonb_agg(jsonb_build_object('id',channel_binding_id,'type',channel_type,'address',address_ciphertext,'state',state,'verifiedAt',verified_at) ORDER BY channel_binding_id),'[]'::jsonb) FROM identity.channel_binding WHERE user_id=p_user AND channel_type IN('email','recovery_email') $$;
CREATE FUNCTION identity.mfa_recovery_snapshot_current(p_id uuid) RETURNS identity.mfa_recovery_control LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;u identity."user"%ROWTYPE;BEGIN
 SELECT * INTO c FROM identity.mfa_recovery_control WHERE challenge_id=p_id;IF c.challenge_id IS NULL THEN RETURN NULL;END IF;
 PERFORM identity.lock_security_subjects(ARRAY[c.user_id]);PERFORM identity.lock_account_t9_internal(c.user_id,true);SELECT * INTO u FROM identity."user" WHERE user_id=c.user_id;SELECT * INTO c FROM identity.mfa_recovery_control WHERE challenge_id=p_id FOR UPDATE;
 IF c.expires_at<=clock_timestamp() OR c.stage IN('COMPLETED','CANCELLED','REFUSED','EXPIRED') OR NOT identity.mfa_recovery_eligible(c.user_id)
 OR u.recovery_email_ciphertext IS DISTINCT FROM c.backup_snapshot OR identity.mfa_recovery_channel_inventory(c.user_id) IS DISTINCT FROM c.channel_inventory_snapshot OR u.password_hash IS DISTINCT FROM c.password_snapshot OR u.email_blind_index IS DISTINCT FROM c.email_index_snapshot OR u.email_ciphertext IS DISTINCT FROM c.primary_snapshot OR COALESCE((SELECT security_epoch FROM identity.account_security_hold WHERE user_id=c.user_id),0)<>c.security_epoch
 OR NOT EXISTS(SELECT 1 FROM identity.channel_binding WHERE channel_binding_id=c.channel_id AND user_id=c.user_id AND channel_type=c.channel_type AND state='verified' AND verified_at=c.channel_verified_at AND address_ciphertext=c.channel_snapshot)
 OR (CASE WHEN c.channel_type='email' THEN u.email_ciphertext ELSE u.recovery_email_ciphertext END) IS DISTINCT FROM c.channel_snapshot
 OR NOT EXISTS(SELECT 1 FROM identity.mfa_factor WHERE mfa_factor_id=c.original_factor_id AND user_id=c.user_id AND factor_type='totp' AND state='active' AND secret_ciphertext=c.factor_snapshot AND verified_at=c.factor_verified_at)
 OR c.original_factor_id IS DISTINCT FROM (SELECT mfa_factor_id FROM identity.mfa_factor WHERE user_id=c.user_id AND factor_type='totp' AND state='active' AND verified_at IS NOT NULL ORDER BY created_at DESC,mfa_factor_id DESC LIMIT 1)
 OR c.paired_at IS NOT NULL AND NOT EXISTS(SELECT 1 FROM identity.account_recovery_binding WHERE recovery_request_id=c.recovery_request_id AND user_id=c.user_id AND closed_at IS NULL)
 THEN RETURN NULL;END IF;RETURN c;
END $$;
CREATE FUNCTION identity.mfa_recovery_current(p_session text) RETURNS identity.mfa_recovery_control LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE id uuid;BEGIN SELECT challenge_id INTO id FROM identity.mfa_recovery_control WHERE session_hash=p_session;RETURN identity.mfa_recovery_snapshot_current(id);END $$;
CREATE FUNCTION identity.mfa_recovery_risk_user(p_user uuid) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE rows jsonb;t timestamptz;BEGIN t:=clock_timestamp();SELECT COALESCE(jsonb_agg(jsonb_build_object('riskSignalId',r.risk_signal_id,'kind',r.signal_kind,'ciphertext',r.context_ciphertext,'observedAt',r.observed_at,'expiresAt',r.expires_at) ORDER BY r.risk_signal_id),'[]'::jsonb) INTO rows FROM(SELECT * FROM identity.authentication_risk_signal WHERE user_id=p_user AND expires_at>t ORDER BY observed_at DESC,risk_signal_id DESC LIMIT 129) r;
 RETURN jsonb_build_object('userId',p_user,'evaluatedAt',t,'signals',rows,'fingerprint',encode(sha256(convert_to(rows::text,'UTF8')),'hex'));
END $$;
CREATE FUNCTION identity.mfa_recovery_risk(p_selector text,p_kind text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN
 IF p_kind='link' THEN SELECT * INTO c FROM identity.mfa_recovery_control WHERE link_hash=p_selector AND stage='EMAIL_REQUIRED';ELSIF p_kind='session' THEN SELECT * INTO c FROM identity.mfa_recovery_control WHERE session_hash=p_selector;ELSE RETURN NULL;END IF;
 IF c.challenge_id IS NULL THEN RETURN NULL;END IF;PERFORM identity.lock_security_subjects(ARRAY[c.user_id]);RETURN identity.mfa_recovery_risk_user(c.user_id);
END $$;
CREATE FUNCTION identity.mfa_recovery_risk_matches(p_user uuid,p_fingerprint text) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE risk jsonb;last_login timestamptz;BEGIN risk:=identity.mfa_recovery_risk_user(p_user);
 IF jsonb_array_length(risk->'signals')>128 OR p_fingerprint IS DISTINCT FROM risk->>'fingerprint' THEN RETURN false;END IF;
 SELECT max(observed_at) INTO last_login FROM identity.authentication_risk_signal WHERE user_id=p_user AND signal_kind='LOGIN_SUCCESS' AND expires_at>clock_timestamp();
 RETURN NOT EXISTS(SELECT 1 FROM identity.authentication_risk_signal WHERE user_id=p_user AND expires_at>clock_timestamp() AND signal_kind IN('SESSION_CONTEXT_CHANGED','RECOVERY_PROOF_FAILED') AND (last_login IS NULL OR observed_at>=last_login));
END $$;
-- Existing writers perform only unlocked scope reads before INSERT. The BEFORE
-- INSERT guard takes the shared subject lock before RI/user-row work; no audit,
-- session, factor, or control row lock is held by those record functions.
CREATE FUNCTION identity.mfa_recovery_risk_insert_guard() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN PERFORM identity.lock_security_subjects(ARRAY[NEW.user_id]);RETURN NEW;END $$;
CREATE TRIGGER mfa_recovery_risk_insert_guard BEFORE INSERT ON identity.authentication_risk_signal FOR EACH ROW EXECUTE FUNCTION identity.mfa_recovery_risk_insert_guard();
CREATE FUNCTION identity.mfa_recovery_cancel_channel_current(p_user uuid,p_channel uuid) RETURNS boolean LANGUAGE sql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$ SELECT EXISTS(SELECT 1 FROM identity.channel_binding c JOIN identity."user" u USING(user_id) WHERE c.user_id=p_user AND c.channel_binding_id=p_channel AND u.state='active' AND c.state='verified' AND c.verified_at IS NOT NULL AND(c.channel_type='email' AND c.address_ciphertext=u.email_ciphertext OR c.channel_type='recovery_email' AND c.address_ciphertext=u.recovery_email_ciphertext)) $$;
CREATE FUNCTION identity.mfa_recovery_prepare(p_index bytea,p_destination text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE u identity."user"%ROWTYPE;ch identity.channel_binding%ROWTYPE;BEGIN
 SELECT * INTO u FROM identity."user" WHERE email_blind_index=p_index;IF u.user_id IS NULL OR NOT identity.mfa_recovery_eligible(u.user_id) OR p_destination NOT IN('primary','backup') THEN RETURN NULL;END IF;
 SELECT * INTO ch FROM identity.channel_binding WHERE user_id=u.user_id AND channel_type=CASE WHEN p_destination='primary' THEN 'email' ELSE 'recovery_email' END AND state='verified' AND verified_at IS NOT NULL AND address_ciphertext=CASE WHEN p_destination='primary' THEN u.email_ciphertext ELSE u.recovery_email_ciphertext END ORDER BY created_at DESC,channel_binding_id DESC LIMIT 1;IF ch.channel_binding_id IS NULL THEN RETURN NULL;END IF;
 RETURN jsonb_build_object('userId',u.user_id,'channels',(SELECT jsonb_agg(jsonb_build_object('channelId',channel_binding_id,'channelType',channel_type,'addressCiphertext',address_ciphertext,'proof',channel_binding_id=ch.channel_binding_id,'cancelAuthorized',identity.mfa_recovery_cancel_channel_current(u.user_id,channel_binding_id)) ORDER BY channel_binding_id) FROM identity.channel_binding WHERE user_id=u.user_id AND channel_type IN('email','recovery_email')));
END $$;
CREATE FUNCTION identity.mfa_recovery_start(p_index bytea,p_destination text,p_candidate uuid,p_channels uuid[],p_link text,p_cancel text,p_notices jsonb,p_source jsonb,p_register bigint,p_id uuid) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE u identity."user"%ROWTYPE;ch identity.channel_binding%ROWTYPE;f identity.mfa_factor%ROWTYPE;candidate jsonb;rules jsonb;item jsonb;t timestamptz;BEGIN
 rules:=identity.mfa_recovery_rules(p_register);SELECT * INTO u FROM identity."user" WHERE email_blind_index=p_index;IF u.user_id IS NULL THEN RETURN false;END IF;PERFORM identity.lock_security_subjects(ARRAY[u.user_id]);PERFORM identity.lock_account_t9_internal(u.user_id,true);SELECT * INTO u FROM identity."user" WHERE user_id=u.user_id;candidate:=identity.mfa_recovery_prepare(p_index,p_destination);t:=clock_timestamp();
 IF candidate IS NULL OR u.user_id IS DISTINCT FROM p_candidate OR u.email_blind_index IS DISTINCT FROM p_index OR p_id IS NULL OR (p_link ~ '^sha256:[0-9a-f]{64}$' AND p_cancel ~ '^sha256:[0-9a-f]{64}$' AND p_link<>p_cancel AND jsonb_typeof(p_notices)='array') IS NOT TRUE THEN RETURN false;END IF;
 IF p_channels IS DISTINCT FROM (SELECT array_agg(channel_binding_id ORDER BY channel_binding_id) FROM identity.channel_binding WHERE user_id=u.user_id AND channel_type IN('email','recovery_email')) OR p_channels IS DISTINCT FROM(SELECT array_agg((x->>'channelId')::uuid ORDER BY(x->>'channelId')::uuid) FROM jsonb_array_elements(p_notices) x) THEN RETURN false;END IF;
 SELECT c.* INTO ch FROM identity.channel_binding c WHERE c.channel_binding_id=(SELECT(x->>'channelId')::uuid FROM jsonb_array_elements(candidate->'channels') x WHERE (x->>'proof')::boolean);
 SELECT * INTO f FROM identity.mfa_factor WHERE user_id=u.user_id AND factor_type='totp' AND state='active' AND verified_at IS NOT NULL ORDER BY created_at DESC,mfa_factor_id DESC LIMIT 1;
 FOR item IN SELECT value FROM jsonb_array_elements(p_notices) LOOP IF core.is_content_envelope(item->'envelope') IS NOT TRUE OR ((item->>'channelId')::uuid=ch.channel_binding_id AND core.is_content_envelope(item->'proofEnvelope') IS NOT TRUE) OR ((item->>'channelId')::uuid<>ch.channel_binding_id AND item?'proofEnvelope') OR (identity.mfa_recovery_cancel_channel_current(u.user_id,(item->>'channelId')::uuid) AND core.is_content_envelope(item->'cancelEnvelope') IS NOT TRUE) OR(NOT identity.mfa_recovery_cancel_channel_current(u.user_id,(item->>'channelId')::uuid) AND item?'cancelEnvelope') THEN RETURN false;END IF;END LOOP;
 INSERT INTO identity.mfa_recovery_control(challenge_id,user_id,register_version,policy,password_snapshot,security_epoch,email_index_snapshot,primary_snapshot,backup_snapshot,channel_inventory_snapshot,channel_id,channel_snapshot,channel_type,channel_verified_at,original_factor_id,factor_snapshot,factor_verified_at,link_hash,cancel_hash,email_expires_at,expires_at) VALUES(p_id,u.user_id,p_register,rules,u.password_hash,COALESCE((SELECT security_epoch FROM identity.account_security_hold WHERE user_id=u.user_id),0),u.email_blind_index,u.email_ciphertext,u.recovery_email_ciphertext,identity.mfa_recovery_channel_inventory(u.user_id),ch.channel_binding_id,ch.address_ciphertext,ch.channel_type,ch.verified_at,f.mfa_factor_id,f.secret_ciphertext,f.verified_at,p_link,p_cancel,t+interval '30 minutes',t+interval '30 minutes');
 FOR item IN SELECT value FROM jsonb_array_elements(p_notices) LOOP INSERT INTO identity.mfa_recovery_notice_binding VALUES(p_id,(item->>'channelId')::uuid,item->'envelope',identity.mfa_recovery_cancel_channel_current(u.user_id,(item->>'channelId')::uuid),item->'cancelEnvelope');IF(item->>'channelId')::uuid=ch.channel_binding_id THEN INSERT INTO identity.mfa_recovery_notice(challenge_id,user_id,channel_id,event_kind,payload_ciphertext) VALUES(p_id,u.user_id,ch.channel_binding_id,'PROOF',item->'proofEnvelope');END IF;END LOOP;RETURN true;
END $$;
CREATE FUNCTION identity.mfa_recovery_prepare_exchange(p_link text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN SELECT * INTO c FROM identity.mfa_recovery_control WHERE link_hash=p_link AND stage='EMAIL_REQUIRED';c:=identity.mfa_recovery_snapshot_current(c.challenge_id);IF c.challenge_id IS NULL THEN RETURN NULL;END IF;RETURN jsonb_build_object('userId',c.user_id,'passwordHash',c.password_snapshot,'channels',(SELECT array_agg(channel_binding_id ORDER BY channel_binding_id) FROM identity.channel_binding WHERE user_id=c.user_id AND channel_type IN('email','recovery_email')));END $$;
CREATE FUNCTION identity.mfa_recovery_notice_event(p_id uuid,p_event text) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
BEGIN IF p_event NOT IN('STARTED','COMPLETED','CANCELLED','REFUSED') THEN RAISE EXCEPTION 'MFA_RECOVERY_NOTICE_INVALID';END IF;INSERT INTO identity.mfa_recovery_notice(challenge_id,user_id,channel_id,event_kind,payload_ciphertext) SELECT c.challenge_id,c.user_id,b.channel_id,p_event,CASE WHEN p_event='STARTED' AND b.cancel_authorized AND identity.mfa_recovery_cancel_channel_current(c.user_id,b.channel_id) THEN b.cancel_payload_ciphertext ELSE b.payload_ciphertext END FROM identity.mfa_recovery_control c JOIN identity.mfa_recovery_notice_binding b USING(challenge_id) WHERE c.challenge_id=p_id ON CONFLICT DO NOTHING;END $$;
CREATE FUNCTION identity.mfa_recovery_close(p_id uuid,p_stage text) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;t timestamptz;BEGIN SELECT * INTO c FROM identity.mfa_recovery_control WHERE challenge_id=p_id FOR UPDATE;t:=clock_timestamp();IF c.challenge_id IS NULL OR c.stage IN('COMPLETED','CANCELLED','REFUSED','EXPIRED') THEN RETURN;END IF;IF p_stage NOT IN('CANCELLED','REFUSED','EXPIRED') THEN RAISE EXCEPTION 'MFA_RECOVERY_CLOSE_INVALID';END IF;UPDATE identity.mfa_recovery_control SET stage=p_stage,csrf_hash=NULL WHERE challenge_id=p_id;UPDATE identity.mfa_factor SET state='revoked',revoked_at=t WHERE mfa_factor_id=c.new_factor_id AND state IN('pending','verified_pending_recovery');IF c.recovery_request_id IS NOT NULL THEN UPDATE identity.account_recovery_binding SET closed_at=t WHERE recovery_request_id=c.recovery_request_id AND closed_at IS NULL;INSERT INTO identity.account_recovery_state_event(recovery_request_id,state) VALUES(c.recovery_request_id,p_stage);END IF;IF p_stage<>'EXPIRED' THEN INSERT INTO identity.password_recovery_retry_lock(user_id,locked_until) VALUES(c.user_id,t+((CASE WHEN p_stage='CANCELLED' THEN c.policy->>'cancel_cooldown_ms' ELSE c.policy->>'failure_cooldown_ms' END)::bigint*interval '1 millisecond')) ON CONFLICT(user_id) DO UPDATE SET locked_until=GREATEST(identity.password_recovery_retry_lock.locked_until,EXCLUDED.locked_until);PERFORM identity.mfa_recovery_notice_event(p_id,p_stage);END IF;END $$;
CREATE FUNCTION identity.mfa_recovery_exchange(p_link text,p_password text,p_session text,p_csrf text,p_refs jsonb,p_risk text,p_source jsonb) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;r record;channels uuid[];id uuid;t timestamptz;BEGIN
 SELECT * INTO c FROM identity.mfa_recovery_control WHERE link_hash=p_link;c:=identity.mfa_recovery_snapshot_current(c.challenge_id);IF c.challenge_id IS NULL OR c.stage<>'EMAIL_REQUIRED' OR c.link_used_at IS NOT NULL OR p_password IS DISTINCT FROM c.password_snapshot OR (p_session ~ '^sha256:[0-9a-f]{64}$' AND p_csrf ~ '^sha256:[0-9a-f]{64}$' AND p_session<>p_csrf AND p_session<>c.link_hash AND p_session<>c.cancel_hash AND p_csrf<>c.link_hash AND p_csrf<>c.cancel_hash AND core.is_content_envelope(p_refs)) IS NOT TRUE THEN RETURN 'INVALID';END IF;
 IF NOT identity.mfa_recovery_risk_matches(c.user_id,p_risk) THEN RETURN 'INVALID';END IF;
 SELECT array_agg(channel_binding_id ORDER BY channel_binding_id) INTO channels FROM identity.channel_binding WHERE user_id=c.user_id AND channel_type IN('email','recovery_email');PERFORM identity.begin_runtime_audit_attempt();SELECT * INTO r FROM identity.start_account_recovery(c.email_index_snapshot,c.user_id,channels,p_refs,p_source);IF r.start_status<>'CREATED' THEN RETURN 'INVALID';END IF;
 SELECT recovery_request_id INTO id FROM identity.account_recovery_request WHERE public_handle=r.public_handle;t:=clock_timestamp();IF c.email_expires_at<=t THEN RAISE EXCEPTION 'MFA_RECOVERY_EMAIL_EXPIRED_AFTER_PAIR';END IF;
 UPDATE identity.mfa_recovery_control SET recovery_request_id=id,stage='FACTOR_REQUIRED',session_hash=p_session,csrf_hash=p_csrf,paired_at=t,link_used_at=t,expires_at=t+interval '5 minutes' WHERE challenge_id=c.challenge_id;
 INSERT INTO identity.account_recovery_state_event(recovery_request_id,state) VALUES(id,'TIER_PINNED'),(id,'PROOF_PENDING');PERFORM identity.mfa_recovery_notice_event(c.challenge_id,'STARTED');RETURN 'FACTOR_REQUIRED';
END $$;
CREATE FUNCTION identity.mfa_recovery_read(p_session text) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN c:=identity.mfa_recovery_current(p_session);IF c.challenge_id IS NULL THEN SELECT p.* INTO c FROM identity.mfa_recovery_control p JOIN identity.account_recovery_binding b USING(recovery_request_id) WHERE p.session_hash=p_session AND p.stage IN('COMPLETED','CANCELLED','REFUSED') AND p.expires_at>clock_timestamp() AND b.closed_at IS NOT NULL;IF c.challenge_id IS NULL THEN RETURN NULL;END IF;RETURN jsonb_build_object('stage',c.stage,'expiresAt',c.expires_at,'csrfHash',c.csrf_hash);END IF;
 RETURN jsonb_build_object('stage',c.stage,'expiresAt',c.expires_at,'csrfHash',c.csrf_hash,'userId',c.user_id,'emailCiphertext',c.primary_snapshot,'factorId',c.new_factor_id,'factorSecret',c.new_factor_snapshot,'lastAcceptedStep',(SELECT last_accepted_step FROM identity.mfa_factor WHERE mfa_factor_id=c.new_factor_id),'nowMs',floor(extract(epoch FROM clock_timestamp())*1000));END $$;
CREATE FUNCTION identity.mfa_recovery_stage_factor(p_session text,p_factor uuid,p_secret jsonb,p_source jsonb) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;t timestamptz;BEGIN c:=identity.mfa_recovery_current(p_session);t:=clock_timestamp();IF c.challenge_id IS NULL OR c.stage NOT IN('FACTOR_REQUIRED','TOTP_REQUIRED') OR p_factor IS NULL OR core.is_content_envelope(p_secret) IS NOT TRUE THEN RETURN false;END IF;UPDATE identity.mfa_factor SET state='revoked',revoked_at=t WHERE mfa_factor_id=c.new_factor_id AND state='pending';INSERT INTO identity.mfa_factor(mfa_factor_id,user_id,factor_type,secret_ciphertext,state,created_at) VALUES(p_factor,c.user_id,'totp',p_secret,'pending',t);UPDATE identity.mfa_recovery_control SET new_factor_id=p_factor,new_factor_snapshot=p_secret,stage='TOTP_REQUIRED' WHERE challenge_id=c.challenge_id;RETURN true;END $$;
CREATE FUNCTION identity.mfa_recovery_verify_factor(p_session text,p_factor uuid,p_secret jsonb,p_last bigint,p_step bigint,p_source jsonb) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;f identity.mfa_factor%ROWTYPE;t timestamptz;BEGIN c:=identity.mfa_recovery_current(p_session);IF c.challenge_id IS NULL OR c.stage<>'TOTP_REQUIRED' OR p_factor IS DISTINCT FROM c.new_factor_id OR p_secret IS DISTINCT FROM c.new_factor_snapshot THEN RETURN false;END IF;SELECT * INTO f FROM identity.mfa_factor WHERE mfa_factor_id=p_factor AND user_id=c.user_id FOR UPDATE;t:=clock_timestamp();IF c.expires_at<=t OR f.state<>'pending' OR f.secret_ciphertext IS DISTINCT FROM p_secret OR f.last_accepted_step IS DISTINCT FROM p_last OR p_step IS NULL OR abs(p_step-floor(extract(epoch FROM t)/30))>1 OR p_step<=COALESCE(f.last_accepted_step,-1) THEN RETURN false;END IF;UPDATE identity.mfa_factor SET state='verified_pending_recovery',verified_at=t,last_accepted_step=p_step WHERE mfa_factor_id=p_factor;UPDATE identity.mfa_recovery_control SET stage='CODES_REQUIRED' WHERE challenge_id=c.challenge_id;RETURN true;END $$;
CREATE FUNCTION identity.mfa_recovery_read_code(p_session text,p_slot integer) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;r jsonb;BEGIN c:=identity.mfa_recovery_current(p_session);IF c.challenge_id IS NULL OR c.stage NOT IN('ACK_REQUIRED','READY') THEN RETURN NULL;END IF;SELECT jsonb_build_object('codeHash',code_hash,'slot',slot) INTO r FROM identity.mfa_recovery_staged_code WHERE recovery_request_id=c.recovery_request_id AND slot=p_slot;RETURN r;END $$;
CREATE FUNCTION identity.mfa_recovery_complete(p_session text,p_risk text,p_source jsonb) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;t timestamptz;BEGIN c:=identity.mfa_recovery_current(p_session);IF c.challenge_id IS NULL OR c.stage<>'READY' OR NOT identity.mfa_recovery_risk_matches(c.user_id,p_risk) THEN RETURN 'INVALID';END IF;t:=clock_timestamp();IF c.expires_at<=t OR NOT EXISTS(SELECT 1 FROM identity.mfa_factor WHERE mfa_factor_id=c.new_factor_id AND user_id=c.user_id AND state='verified_pending_recovery' AND secret_ciphertext=c.new_factor_snapshot AND verified_at IS NOT NULL AND last_accepted_step IS NOT NULL) OR(SELECT count(*) FROM identity.mfa_recovery_staged_code WHERE recovery_request_id=c.recovery_request_id)<>10 THEN RETURN 'INVALID';END IF;
 UPDATE identity.mfa_factor SET state='active' WHERE mfa_factor_id=c.new_factor_id;UPDATE identity.mfa_factor SET state='revoked',revoked_at=t WHERE user_id=c.user_id AND mfa_factor_id<>c.new_factor_id AND state<>'revoked';UPDATE identity.recovery_code SET revoked_at=t WHERE user_id=c.user_id AND revoked_at IS NULL;INSERT INTO identity.recovery_code(user_id,code_hash,code_slot,created_at) SELECT c.user_id,code_hash,slot,t FROM identity.mfa_recovery_staged_code WHERE recovery_request_id=c.recovery_request_id;
 UPDATE identity.session SET revoked_at=t WHERE user_id=c.user_id AND revoked_at IS NULL;UPDATE identity.login_challenge SET consumed_at=t WHERE user_id=c.user_id AND consumed_at IS NULL;UPDATE identity.step_up_grant SET consumed_at=t WHERE user_id=c.user_id AND consumed_at IS NULL;
 INSERT INTO identity.account_security_hold(user_id,held,security_epoch,changed_at) VALUES(c.user_id,false,c.security_epoch+1,t) ON CONFLICT(user_id) DO UPDATE SET security_epoch=identity.account_security_hold.security_epoch+1,changed_at=t;
 UPDATE identity.mfa_recovery_control SET stage='COMPLETED',completed_at=t WHERE challenge_id=c.challenge_id;UPDATE identity.account_recovery_binding SET closed_at=t WHERE recovery_request_id=c.recovery_request_id AND closed_at IS NULL;INSERT INTO identity.account_recovery_state_event(recovery_request_id,state) VALUES(c.recovery_request_id,'COMPLETED_FULL');PERFORM identity.mfa_recovery_notice_event(c.challenge_id,'COMPLETED');RETURN 'COMPLETED';END $$;
CREATE FUNCTION identity.mfa_recovery_cancel(p_cancel text,p_source jsonb) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN SELECT * INTO c FROM identity.mfa_recovery_control WHERE cancel_hash=p_cancel;IF c.challenge_id IS NULL THEN RETURN 'INVALID';END IF;PERFORM identity.lock_security_subjects(ARRAY[c.user_id]);SELECT * INTO c FROM identity.mfa_recovery_control WHERE challenge_id=c.challenge_id FOR UPDATE;IF c.expires_at<=clock_timestamp() THEN PERFORM identity.mfa_recovery_close(c.challenge_id,'EXPIRED');RETURN 'INVALID';END IF;IF c.stage='CANCELLED' THEN RETURN 'CANCELLED';END IF;IF c.stage IN('COMPLETED','REFUSED','EXPIRED') THEN RETURN 'INVALID';END IF;PERFORM identity.mfa_recovery_close(c.challenge_id,'CANCELLED');RETURN 'CANCELLED';END $$;
CREATE FUNCTION identity.mfa_recovery_cancel_session(p_session text,p_source jsonb) RETURNS text LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN c:=identity.mfa_recovery_current(p_session);IF c.challenge_id IS NULL THEN RETURN 'INVALID';END IF;PERFORM identity.mfa_recovery_close(c.challenge_id,'CANCELLED');RETURN 'CANCELLED';END $$;
CREATE FUNCTION identity.mfa_recovery_failure(p_selector text,p_kind text,p_source jsonb) RETURNS void LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN IF p_kind='link' THEN SELECT * INTO c FROM identity.mfa_recovery_control WHERE link_hash=p_selector;ELSE SELECT * INTO c FROM identity.mfa_recovery_control WHERE session_hash=p_selector;END IF;IF c.challenge_id IS NULL THEN RETURN;END IF;PERFORM identity.lock_security_subjects(ARRAY[c.user_id]);SELECT * INTO c FROM identity.mfa_recovery_control WHERE challenge_id=c.challenge_id FOR UPDATE;IF c.stage IN('COMPLETED','CANCELLED','REFUSED','EXPIRED') THEN RETURN;END IF;UPDATE identity.mfa_recovery_control SET failures=failures+1 WHERE challenge_id=c.challenge_id;IF c.failures+1>=5 THEN PERFORM identity.mfa_recovery_close(c.challenge_id,'REFUSED');END IF;END $$;
CREATE FUNCTION identity.mfa_recovery_admit(p_source jsonb,p_register bigint) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE r identity.mfa_recovery_source_window%ROWTYPE;digest text;t timestamptz;BEGIN PERFORM identity.mfa_recovery_rules(p_register);digest:=p_source->>'ipArgon2id';IF p_source IS NULL OR p_source<>jsonb_build_object('ipArgon2id',digest,'userAgentArgon2id',p_source->>'userAgentArgon2id') OR COALESCE(digest,'') !~ '^argon2id-audit:v1:[0-9a-f]{64}$' OR COALESCE(p_source->>'userAgentArgon2id','') !~ '^argon2id-audit:v1:[0-9a-f]{64}$' THEN RETURN false;END IF;PERFORM pg_advisory_xact_lock(hashtextextended('mfa-recovery:source:'||digest,0));SELECT * INTO r FROM identity.mfa_recovery_source_window WHERE source_digest=digest FOR UPDATE;t:=clock_timestamp();IF r.source_digest IS NULL THEN PERFORM pg_advisory_xact_lock(hashtextextended('mfa-recovery:source-capacity',0));IF(SELECT count(*) FROM identity.mfa_recovery_source_window)>=65536 THEN RETURN false;END IF;INSERT INTO identity.mfa_recovery_source_window VALUES(digest,t,1);RETURN true;END IF;IF r.window_started_at<=t-interval '5 minutes' THEN r.window_started_at:=t;r.uses:=0;END IF;r.uses:=LEAST(r.uses+1,21);UPDATE identity.mfa_recovery_source_window SET window_started_at=r.window_started_at,uses=r.uses WHERE source_digest=digest;RETURN r.uses<=20;END $$;
CREATE FUNCTION identity.mfa_recovery_expire(p_batch integer) RETURNS integer LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c record;n integer:=0;BEGIN IF p_batch IS NULL OR p_batch NOT BETWEEN 1 AND 1000 THEN RAISE EXCEPTION 'MFA_RECOVERY_BATCH_INVALID';END IF;FOR c IN SELECT challenge_id,user_id FROM identity.mfa_recovery_control WHERE expires_at<=clock_timestamp() AND stage NOT IN('COMPLETED','CANCELLED','REFUSED','EXPIRED') ORDER BY expires_at,challenge_id LIMIT p_batch LOOP PERFORM identity.lock_security_subjects(ARRAY[c.user_id]);PERFORM identity.mfa_recovery_close(c.challenge_id,'EXPIRED');n:=n+1;END LOOP;FOR c IN SELECT source_digest FROM identity.mfa_recovery_source_window WHERE window_started_at<=clock_timestamp()-interval '5 minutes' LIMIT p_batch LOOP PERFORM pg_advisory_xact_lock(hashtextextended('mfa-recovery:source:'||c.source_digest,0));DELETE FROM identity.mfa_recovery_source_window WHERE source_digest=c.source_digest AND window_started_at<=clock_timestamp()-interval '5 minutes';END LOOP;RETURN n;END $$;
-- Staged code capabilities and mail leases are appended below by this migration.

CREATE FUNCTION identity.mfa_recovery_stage_codes(p_session text,p_codes jsonb,p_source jsonb) RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN
 c:=identity.mfa_recovery_current(p_session);
 IF c.recovery_request_id IS NULL OR c.stage NOT IN('CODES_REQUIRED','ACK_REQUIRED') OR jsonb_typeof(p_codes)<>'array' OR jsonb_array_length(p_codes)<>10 THEN RETURN false;END IF;
 IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_codes) x WHERE (x->>'slot')::integer NOT BETWEEN 1 AND 10 OR COALESCE(x->>'hash','') !~ '^\$argon2id\$v=19\$m=[0-9]+,t=[0-9]+,p=[0-9]+\$[A-Za-z0-9+/]{22,86}\$[A-Za-z0-9+/]{43,86}$') OR (SELECT count(DISTINCT x->>'slot') FROM jsonb_array_elements(p_codes) x)<>10 THEN RETURN false; END IF;
 DELETE FROM identity.mfa_recovery_staged_code WHERE recovery_request_id=c.recovery_request_id;
 INSERT INTO identity.mfa_recovery_staged_code(recovery_request_id,slot,code_hash) SELECT c.recovery_request_id,(x->>'slot')::smallint,x->>'hash' FROM jsonb_array_elements(p_codes) x;
 UPDATE identity.mfa_recovery_control SET stage='ACK_REQUIRED' WHERE recovery_request_id=c.recovery_request_id;
RETURN true;
END $$;

CREATE FUNCTION identity.mfa_recovery_ack_code(p_session text,p_slot integer,p_hash text,p_source jsonb) RETURNS boolean
LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE c identity.mfa_recovery_control%ROWTYPE;BEGIN
 c:=identity.mfa_recovery_current(p_session);
 IF c.recovery_request_id IS NULL OR c.stage<>'ACK_REQUIRED' OR NOT EXISTS(SELECT 1 FROM identity.mfa_recovery_staged_code WHERE recovery_request_id=c.recovery_request_id AND slot=p_slot AND code_hash=p_hash) THEN RETURN false;END IF;
 UPDATE identity.mfa_recovery_control SET stage='READY' WHERE recovery_request_id=c.recovery_request_id;
RETURN true;
END $$;

CREATE FUNCTION identity.mfa_recovery_claim_notice(p_lease integer) RETURNS jsonb LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n identity.mfa_recovery_notice%ROWTYPE;l uuid;t timestamptz;BEGIN
 IF p_lease IS NULL OR p_lease NOT BETWEEN 1000 AND 60000 THEN RAISE EXCEPTION 'EMAIL_NOTICE_LEASE_INVALID';END IF;t:=clock_timestamp();
 UPDATE identity.mfa_recovery_notice a SET dead_at=t WHERE a.event_kind='PROOF' AND sent_at IS NULL AND dead_at IS NULL AND NOT EXISTS(SELECT 1 FROM identity.mfa_recovery_control c WHERE c.challenge_id=a.challenge_id AND c.stage='EMAIL_REQUIRED' AND c.expires_at>t);
 SELECT * INTO n FROM identity.mfa_recovery_notice WHERE sent_at IS NULL AND dead_at IS NULL AND available_at<=t AND(lease_until IS NULL OR lease_until<=t) ORDER BY created_at,notice_id LIMIT 1 FOR UPDATE SKIP LOCKED;IF n.notice_id IS NULL THEN RETURN NULL;END IF;l:=gen_random_uuid();UPDATE identity.mfa_recovery_notice SET lease_id=l,lease_until=t+(p_lease*interval '1 millisecond'),attempts=attempts+1 WHERE notice_id=n.notice_id;
 RETURN jsonb_build_object('noticeId',n.notice_id,'leaseId',l,'userId',n.user_id,'channelId',n.channel_id,'event',n.event_kind,'cancelAllowed',n.event_kind='STARTED' AND (identity.mfa_recovery_cancel_channel_current(n.user_id,n.channel_id) AND (SELECT cancel_authorized FROM identity.mfa_recovery_notice_binding WHERE challenge_id=n.challenge_id AND channel_id=n.channel_id)),'payload',CASE WHEN n.event_kind='STARTED' AND NOT (identity.mfa_recovery_cancel_channel_current(n.user_id,n.channel_id) AND (SELECT cancel_authorized FROM identity.mfa_recovery_notice_binding WHERE challenge_id=n.challenge_id AND channel_id=n.channel_id)) THEN(SELECT payload_ciphertext FROM identity.mfa_recovery_notice_binding WHERE challenge_id=n.challenge_id AND channel_id=n.channel_id) ELSE n.payload_ciphertext END,'expiresAt',(SELECT expires_at FROM identity.mfa_recovery_control WHERE challenge_id=n.challenge_id));END $$;
CREATE FUNCTION identity.mfa_recovery_finish_notice(p_notice uuid,p_lease uuid,p_sent boolean,p_retry integer,p_max integer) RETURNS boolean LANGUAGE plpgsql VOLATILE SECURITY DEFINER SET search_path=pg_catalog AS $$
DECLARE n identity.mfa_recovery_notice%ROWTYPE;t timestamptz;BEGIN IF p_sent IS NULL OR p_retry IS NULL OR p_retry NOT BETWEEN 1000 AND 3600000 OR p_max IS NULL OR p_max NOT BETWEEN 1 AND 3 THEN RETURN false;END IF;SELECT * INTO n FROM identity.mfa_recovery_notice WHERE notice_id=p_notice FOR UPDATE;t:=clock_timestamp();IF n.notice_id IS NULL OR n.lease_id IS DISTINCT FROM p_lease OR n.sent_at IS NOT NULL OR n.dead_at IS NOT NULL OR n.lease_until<=t THEN RETURN false;END IF;UPDATE identity.mfa_recovery_notice SET sent_at=CASE WHEN p_sent THEN t ELSE NULL END,dead_at=CASE WHEN NOT p_sent AND n.attempts>=p_max THEN t ELSE NULL END,available_at=t+(p_retry*interval '1 millisecond'),lease_until=NULL WHERE notice_id=p_notice;RETURN true;END $$;
ALTER FUNCTION identity.mfa_recovery_claim_notice(integer) OWNER TO debateai_mfa_recovery_owner;
ALTER FUNCTION identity.mfa_recovery_finish_notice(uuid,uuid,boolean,integer,integer) OWNER TO debateai_mfa_recovery_owner;
REVOKE ALL ON FUNCTION identity.mfa_recovery_claim_notice(integer),identity.mfa_recovery_finish_notice(uuid,uuid,boolean,integer,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION identity.mfa_recovery_claim_notice(integer),identity.mfa_recovery_finish_notice(uuid,uuid,boolean,integer,integer) TO debateai_mfa_recovery_runtime;

GRANT SELECT ON identity."user",identity.channel_binding,identity.mfa_factor,identity.recovery_code,identity.session,identity.login_challenge,identity.step_up_grant,identity.account_security_hold,identity.account_erasure_request,identity.account_recovery_request,identity.account_recovery_binding,identity.authentication_risk_signal,staff.subject,register.register_row,register.register_version TO debateai_mfa_recovery_owner;
GRANT INSERT,UPDATE ON identity.mfa_factor,identity.recovery_code,identity.account_security_hold,identity.password_recovery_retry_lock TO debateai_mfa_recovery_owner;
GRANT SELECT ON identity.password_recovery_retry_lock TO debateai_mfa_recovery_owner;
GRANT UPDATE(revoked_at) ON identity.session TO debateai_mfa_recovery_owner;
GRANT UPDATE(consumed_at) ON identity.login_challenge,identity.step_up_grant TO debateai_mfa_recovery_owner;
GRANT UPDATE(closed_at) ON identity.account_recovery_binding TO debateai_mfa_recovery_owner;
GRANT INSERT ON identity.account_recovery_state_event TO debateai_mfa_recovery_owner;
GRANT USAGE ON SEQUENCE identity.account_recovery_state_event_event_sequence_seq TO debateai_mfa_recovery_owner;
GRANT EXECUTE ON FUNCTION identity.lock_security_subjects(uuid[]),identity.lock_account_t9_internal(uuid,boolean),identity.read_account_security_hold(uuid),identity.backup_email_eligible(uuid),identity.password_recovery_rules(bigint),identity.begin_runtime_audit_attempt(),identity.start_account_recovery(bytea,uuid,uuid[],jsonb,jsonb),core.is_content_envelope(jsonb) TO debateai_mfa_recovery_owner;
DO $$ DECLARE r record;BEGIN
 FOR r IN SELECT oid::regclass AS object FROM pg_class WHERE relnamespace='identity'::regnamespace AND relkind='r' AND relname LIKE 'mfa_recovery_%' LOOP EXECUTE format('ALTER TABLE %s OWNER TO debateai_mfa_recovery_owner',r.object);EXECUTE format('REVOKE ALL ON %s FROM PUBLIC',r.object);END LOOP;
 FOR r IN SELECT oid::regprocedure AS object,proname FROM pg_proc WHERE pronamespace='identity'::regnamespace AND proname LIKE 'mfa_recovery_%' LOOP EXECUTE format('ALTER FUNCTION %s OWNER TO debateai_mfa_recovery_owner',r.object);EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC',r.object);IF r.proname IN('mfa_recovery_prepare','mfa_recovery_start','mfa_recovery_prepare_exchange','mfa_recovery_risk','mfa_recovery_exchange','mfa_recovery_read','mfa_recovery_stage_factor','mfa_recovery_verify_factor','mfa_recovery_stage_codes','mfa_recovery_read_code','mfa_recovery_ack_code','mfa_recovery_complete','mfa_recovery_cancel','mfa_recovery_cancel_session','mfa_recovery_admit','mfa_recovery_failure','mfa_recovery_expire','mfa_recovery_claim_notice','mfa_recovery_finish_notice') THEN EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO debateai_mfa_recovery_runtime',r.object);END IF;END LOOP;
END $$;
