/**
 * GENERATED by `apps/ui/scripts/generate-legal-data.mjs` from `apps/ui/legal/de/terms-of-service.md`.
 * Do not edit by hand: edit the draft and run `pnpm generate:legal`.
 *
 * The document as DATA. The modal that shows it renders from this module and holds no legal
 * prose of its own. Square brackets are the draft's own marks for what counsel still has to
 * fill in; they are rendered verbatim so the product never claims a fact the draft does not.
 */

import type { LegalDocument, LegalJump, LegalSection } from "../../legalDocument.js";

export const TERMS_JUMP: readonly LegalJump[] = [
  { label: "WER WIR SIND", target: "terms-section-01" },
  { label: "ZUSTIMMUNG", target: "terms-section-03" },
  { label: "WAS ES IST", target: "terms-section-05" },
  { label: "IHR KONTO", target: "terms-section-06" },
  { label: "ZULÄSSIGE NUTZUNG", target: "terms-section-07" },
  { label: "IHRE INHALTE", target: "terms-section-08" },
  { label: "VERÖFFENTLICHUNG", target: "terms-section-09" },
  { label: "MELDUNGEN", target: "terms-section-10" },
  { label: "HAFTUNG", target: "terms-section-15" },
  { label: "ANWENDBARES RECHT", target: "terms-section-18" }
];

export const TERMS_SECTIONS: readonly LegalSection[] = [
  {
    no: "00",
    title: "Kurz gesagt",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Sie müssen mindestens 18 Jahre alt sein. DebateAI erstellt Argumente mithilfe von KI-Modellen, und alles, was es erzeugt, kann falsch sein – es handelt sich nicht um Beratung. Ihre Debatten sind privat, sofern Sie sie nicht veröffentlichen; wenn Sie sie veröffentlichen, kann jede Person sie lesen. Von Ihnen übermittelter Text wird an die in unserem Verzeichnis aufgeführten KI-Anbieter gesendet und nicht zum Trainieren von Modellen verwendet. Melden Sie rechtswidrige Inhalte unter [abuse@dezbatere.ro], unabhängig davon, ob Sie ein Konto haben. Es gilt rumänisches Recht, Ihre örtlichen Verbraucherschutzrechte bleiben Ihnen jedoch erhalten." }
    ]
  },
  {
    no: "01",
    title: "Wer wir sind und wie Sie uns erreichen",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "DebateAI wird von DebateAIRO S.R.L., einem in Rumänien eingetragenen Unternehmen, betrieben." },
      {
        kind: "list",
        items: [
        "Eingetragener Sitz — [street, number, sector, postal code], Bukarest, Rumänien",
        "Handelsregisternummer — [J40/…/…]",
        "Einheitlicher Registrierungscode (CUI) — […] · USt.: [RO… / not VAT-registered]",
        "Stammkapital — [RON …]",
        "Allgemeiner Kontakt — [hello@dezbatere.ro]",
        "Rechtliche Mitteilungen — [legal@dezbatere.ro]",
        "Datenschutz — privacy@dezbatere.ro",
        "Meldung rechtswidriger Inhalte — [abuse@dezbatere.ro] – siehe Abschnitt 10",
        "Kontaktstelle für Behörden — [dsa@dezbatere.ro] – Rumänisch und Englisch",
        "Vertreter in anderen Ländern — In Anhang A für die Regionen aufgeführt, in denen wir einen Vertreter bestellt haben"
        ]
      },
      { kind: "p", text: "Diese Angaben werden auch dauerhaft auf der Website unter [dezbatere.ro/legal] angezeigt. Sie können stets einen Menschen erreichen und nicht nur unseren Assistenten; Abschnitt 10 erläutert, wie dies möglich ist." }
    ]
  },
  {
    no: "02",
    title: "Wo wir DebateAI anbieten",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Wir bieten DebateAI Personen an, die in [the European Union and the European Economic Area] [and: the United Kingdom / the United States / Canada / Australia and New Zealand / Singapore / Japan / South Korea] leben. Anderswo bieten wir den Dienst nicht an. Wenn Sie außerhalb dieser Länder leben, können Sie die Website möglicherweise aufrufen, aber wir richten den Dienst nicht an Sie, nehmen keine Zahlungen von Ihnen an, und diese Nutzungsbedingungen sowie unsere Datenschutzerklärung sind nicht an das Recht Ihres Landes angepasst. Anhang A legt fest, was in den einzelnen Regionen gilt, in denen wir den Dienst anbieten." }
    ]
  },
  {
    no: "03",
    title: "Zustimmung zu diesen Nutzungsbedingungen",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Sie stimmen diesen Nutzungsbedingungen zu, indem Sie das Kästchen „Ich akzeptiere nach Kenntnisnahme die Nutzungsbedingungen“ markieren und auf Konto erstellen klicken. Dadurch kommt ein Vertrag zwischen Ihnen und DebateAIRO S.R.L. zustande. Zu den Nutzungsbedingungen gehören die Regeln zur zulässigen Nutzung in Abschnitt 7, die Regeln zur Veröffentlichung in Abschnitt 9, die Haftungsbestimmungen in Abschnitt 15, die Bestimmungen zum anwendbaren Recht und zu Streitigkeiten in Abschnitt 18 sowie, falls Sie in den Vereinigten Staaten leben, die Schiedsvereinbarung in Anhang A.3. Wie in unserer Datenschutzerklärung erläutert, halten wir fest, welcher Fassung Sie wann zugestimmt haben." },
      { kind: "p", text: "Unsere Datenschutzerklärung unter [dezbatere.ro/privacy] erläutert, wie wir personenbezogene Daten verarbeiten. Dabei handelt es sich um Informationen, die wir Ihnen schulden, nicht um einen Vertrag, dem Sie zustimmen, und nichts in diesen Nutzungsbedingungen macht daraus eine Einwilligung in die Verarbeitung. Unsere Cookie-Richtlinie unter [dezbatere.ro/cookies] und unser Verzeichnis der KI-Anbieter unter [dezbatere.ro/providers] werden durch Verweis Bestandteil dieser Nutzungsbedingungen." },
      { kind: "p", text: "Bevor Sie elektronisch einen Vertrag mit uns schließen, zeigt Ihnen die Benutzeroberfläche die einzelnen Schritte, ermöglicht Ihnen, Ihre Eingaben vor dem Absenden zu überprüfen und zu berichtigen, und nennt Ihnen die Sprachen, in denen der Vertrag geschlossen werden kann. Diese Nutzungsbedingungen stehen in einer Form zur Verfügung, die Sie speichern und ausdrucken können; wir senden Ihnen die von Ihnen angenommene Fassung per E-Mail, und Sie können jederzeit eine Kopie anfordern. Nichts in diesen Nutzungsbedingungen beschränkt Rechte nach rumänischem oder EU-Verbraucherrecht oder nach dem Recht des Landes, in dem Sie leben, die vertraglich nicht beschränkt werden können." }
    ]
  },
  {
    no: "04",
    title: "Wer DebateAI nutzen darf",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Sie müssen mindestens 18 Jahre alt sein, um ein Konto zu erstellen, und bestätigen dies bei der Registrierung. DebateAI richtet sich nicht an Kinder, und wir stellen den Dienst wissentlich niemandem unter 18 Jahren bereit. Erfahren wir, dass ein Konto einer Person unter 18 Jahren gehört, schließen wir es. In manchen Regionen ist mehr als eine Bestätigung erforderlich; Anhang A legt fest, was jeweils gilt." },
      { kind: "p", text: "Sie müssen geschäftsfähig sein, um diesen Vertrag zu schließen. Wenn Sie DebateAI im Namen einer Organisation nutzen, bestätigen Sie, dass Sie befugt sind, diese zu verpflichten; „Sie“ bezeichnet dann diese Organisation." },
      { kind: "p", text: "Eine veröffentlichte Debatte dürfen alle lesen. Dafür ist kein Konto erforderlich, es handelt sich jedoch um eine Nutzung des Dienstes, auf die die Abschnitte 7, 15, 16 und 18 Anwendung finden." }
    ]
  },
  {
    no: "05",
    title: "Was DebateAI leistet und was nicht",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Sie übermitteln eine Frage oder eine Behauptung. DebateAI sendet sie an mehrere KI-Modelle von Drittanbietern, die darum herum einen Argumentationsgraphen erstellen: Behauptungen, Gegenbehauptungen, Kritiken, Evidenzverweise, Bewertungen und ein Urteil mit einem Konfidenzbereich. Sie können einzelne Behauptungen anfechten, die weitere Untersuchung eines Punktes verlangen und entscheiden, ob Sie das Ergebnis veröffentlichen." },
      { kind: "p", text: "Alles in einer Debatte wird von KI erzeugt. Die Argumente, Kritiken, Evidenzverweise, Bewertungen, Urteile und Antworten des Support-Assistenten werden maschinell erzeugt. Sie können falsch, unvollständig, veraltet oder mit großer Bestimmtheit unzutreffend sein und Verzerrungen der Modelle widerspiegeln. Sie werden von niemandem geprüft, bevor sie Ihnen angezeigt oder veröffentlicht werden, und keine namentlich genannte Person trägt dafür die redaktionelle Verantwortung. Erzeugte Inhalte werden im Produkt, auf veröffentlichten Seiten und in Exporten als KI-generiert gekennzeichnet." },
      { kind: "p", text: "DebateAI ist keine Beratung. Es handelt sich weder um Rechts-, Medizin-, Finanz-, Steuer-, psychologische, Sicherheits- noch sonstige Fachberatung, und ein Urteil ist keine Tatsachenfeststellung. Verwenden Sie eine Debatte nicht als Grundlage für eine Entscheidung, die für Ihre Gesundheit, Sicherheit, finanzielle Lage, Rechtsposition oder das Wohlergehen anderer von Bedeutung ist, ohne Primärquellen und gegebenenfalls eine qualifizierte Fachperson zu konsultieren. Ein hoher Konfidenzbereich bedeutet, dass die Modelle die Auslegung anhand des ihnen vorliegenden Materials als gefestigt eingestuft haben; er garantiert nicht, dass sie wahr ist." },
      { kind: "p", text: "Wozu wir uns verpflichten. Wir stellen den Dienst mit angemessener Sorgfalt und Sachkenntnis sowie gemäß der von uns veröffentlichten Beschreibung bereit. Soweit das Gesetz Ihnen eine Gewährleistung dafür einräumt, dass der Dienst seiner Beschreibung entspricht und für seinen gewöhnlichen Zweck geeignet ist, gilt diese Gewährleistung, und nichts in diesen Nutzungsbedingungen hebt sie auf. Wir versprechen jedoch nicht, dass ein bestimmtes Ergebnis richtig ist: Dies ist eine Eigenschaft des erzeugten Inhalts und keine Frage der Funktionsfähigkeit des Dienstes." },
      { kind: "p", text: "Modelle ändern sich. Wir können die von uns verwendeten KI-Modelle ergänzen, entfernen oder ersetzen und ändern, wie das System eine Antwort zusammensetzt. Abschnitt 14 erläutert, wann Ihnen aus einer Änderung Rechte entstehen." }
    ]
  },
  {
    no: "06",
    title: "Ihr Konto",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Sie registrieren sich mit einer E-Mail-Adresse, einem Passwort, einer Wiederherstellungs-E-Mail-Adresse und einer verpflichtenden Zwei-Faktor-Authentifizierung. Sie wählen ein Pseudonym, das bei allem angezeigt wird, was Sie veröffentlichen; einmal festgelegte Pseudonyme können nicht geändert werden. Bewahren Sie Ihr Passwort, Ihre Authentifizierungs-App und Ihre Wiederherstellungscodes sicher auf. Sie sind für Aktivitäten unter Ihrem Konto verantwortlich, es sei denn, diese sind auf ein Versäumnis unsererseits zurückzuführen." },
      { kind: "p", text: "Sie dürfen nur ein Konto führen, sofern wir nichts anderes vereinbaren. Sie dürfen es nicht teilen, verkaufen oder übertragen." },
      { kind: "p", text: "Wenn Sie den Zugang verlieren, erfolgt die Kontowiederherstellung nach dem im Produkt veröffentlichten Verfahren, das Wartefristen vorsieht, um Kontoübernahmen zu erschweren. Wir können einen Wiederherstellungsantrag ablehnen, wenn wir nicht in zumutbarer Weise feststellen können, dass er von Ihnen stammt." },
      { kind: "p", text: "Sie können Ihr Konto jederzeit unter Einstellungen → Konto schließen. Die Schließung wird nach einer siebentägigen Schonfrist wirksam, während der Sie sie abbrechen können; wir benachrichtigen Sie über jeden Ihrer registrierten Kanäle. Abschnitt 11 erläutert, was durch die Schließung gelöscht wird und was nicht." }
    ]
  },
  {
    no: "07",
    title: "Zulässige Nutzung",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Diese Regeln gelten für Ihre Eingaben, Ihre Nutzung des Dienstes und Ihre Veröffentlichungen." },
      { kind: "p", text: "Übermitteln Sie keine personenbezogenen Daten anderer Personen. Fragen Sie nach Themen, Argumenten und öffentlichen Fragestellungen statt nach identifizierbaren Privatpersonen. Geben Sie keine Namen, Kontaktdaten, Identifikationsnummern, Bilder, Gesundheits-, Finanz- oder sonstigen Angaben an, anhand derer eine Person identifiziert werden kann, und verwenden Sie DebateAI nicht, um einen Fall, ein Profil oder ein Dossier über eine Person zu erstellen. Fragen über Personen des öffentlichen Lebens in Ausübung ihrer öffentlichen Funktion sind zulässig; Fragen, die auf eine Privatperson abzielen, sind es nicht. Wenn Sie solche Daten dennoch übermitteln, sind Sie dafür verantwortlich, und wir können die Inhalte entfernen." },
      { kind: "p", text: "Ihre eigenen sensiblen Informationen. Ihre Fragen können Ihre eigene Gesundheit, Ihre Überzeugungen, Ihre politischen Ansichten oder andere sensible Angelegenheiten betreffen. Dem haben Sie bei der Registrierung zugestimmt. Wenn Sie an einem Ort mit besonderen Vorschriften für Gesundheitsdaten leben, verweist Anhang A gegebenenfalls auf einen gesonderten Hinweis." },
      { kind: "p", text: "Übermitteln oder veröffentlichen Sie keine rechtswidrigen Inhalte, einschließlich verleumderischer Inhalte, Aufrufen zu Gewalt oder Hass, Belästigungen oder Drohungen, ohne Einwilligung geteilter intimer Abbildungen, Verletzungen geistigen Eigentums oder der Vertraulichkeit, Offenlegungen von Geschäftsgeheimnissen, Darstellungen sexuellen Kindesmissbrauchs oder Verstößen gegen Sanktionen oder Ausfuhrkontrollen." },
      { kind: "p", text: "Verwenden Sie DebateAI nicht zur Täuschung. Stellen Sie erzeugte Ergebnisse nicht als von Menschen verfasst dar, wenn dies irreführend wäre, entfernen Sie nicht deren Kennzeichnung als KI-generiert und verwenden Sie sie nicht, um einen vermeintlichen Konsens, gefälschte Beweise oder eine Identitätstäuschung zu erzeugen." },
      { kind: "p", text: "Greifen Sie den Dienst nicht an. Kein automatisierter Zugriff, Scraping, Crawling oder massenhaftes Extrahieren veröffentlichter Debatten über das hinaus, was unsere Robots-Datei zulässt; keine Umgehung von Ratenbegrenzungen, Authentifizierungs- oder Veröffentlichungskontrollen; keine Versuche, Prompts oder Systemanweisungen zu extrahieren; keine Prompt-Injection mit dem Ziel, das System dazu zu bringen, seine Beschränkungen zu missachten; keine Sondierungen oder Lasttests ohne unsere schriftliche Genehmigung." },
      { kind: "p", text: "Verkaufen Sie den Dienst nicht weiter und versehen Sie ihn nicht mit einer anderen Marke, und verwenden Sie ihn ohne unsere schriftliche Vereinbarung auch nicht zum Aufbau eines konkurrierenden Systems, etwa indem Sie Ergebnisse als Trainingsdaten nutzen." },
      { kind: "p", text: "Verwenden Sie DebateAI nicht für Entscheidungen über die Gesundheit, Sicherheit, gesetzlichen Rechte, Beschäftigung, Kreditwürdigkeit, Wohnsituation oder den Einwanderungsstatus einer Person. Der Dienst wurde dafür nicht entwickelt, und seine Ergebnisse sind dafür keine sichere Grundlage." },
      { kind: "p", text: "Örtliches Recht am Ort der Veröffentlichung. Sie sind dafür verantwortlich, sicherzustellen, dass alles, was Sie veröffentlichen, dem Recht des Landes entspricht, in dem Sie sich befinden. Wir können die Veröffentlichung bestimmter Themen in bestimmten Regionen beschränken." },
      { kind: "p", text: "Wenn Sie nicht sicher sind, ob etwas erlaubt ist, fragen Sie uns, bevor Sie es veröffentlichen." }
    ]
  },
  {
    no: "08",
    title: "Ihre Inhalte und die KI-Anbieter, die sie verarbeiten",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Ihre Inhalte bleiben Ihre Inhalte. Sie behalten alle Rechte, die Sie an den von Ihnen übermittelten Fragen, Behauptungen, Anmerkungen und Anfechtungen haben. Sie räumen uns eine nicht ausschließliche, weltweite und unentgeltliche Lizenz ein, diese Inhalte zum Betrieb des Dienstes zu hosten, zu speichern, zu vervielfältigen, anzupassen und zu verarbeiten: um die Debatte durchzuführen, sie zu speichern, damit Sie sie erneut öffnen und wiedergeben können, Support zu leisten, unsere gesetzlichen Pflichten zu erfüllen und – nur wenn Sie sich für eine Veröffentlichung entscheiden – für die in Abschnitt 9 genannten Zwecke. Diese Lizenz endet mit der Löschung der Inhalte, soweit Abschnitt 9 oder das Gesetz nichts anderes erfordert." },
      { kind: "p", text: "Wir trainieren nicht mit Ihren Inhalten. Wir trainieren keine Modelle mit Ihren Inhalten, und unsere Verträge mit KI-Anbietern schließen die Nutzung Ihrer Inhalte zum Trainieren oder Verbessern ihrer Modelle aus. [Publish this paragraph only once every active provider route has been verified against its signed terms and account settings — see the Provider Register.]" },
      { kind: "p", text: "Wie Ihre Inhalte KI-Anbieter erreichen. Zur Durchführung einer Debatte senden wir Text an einen oder mehrere externe Modellanbieter. Ein Anbieter erhält Ihre Frage, die von Ihnen festgelegten Steuerungsanmerkungen und Aussagen, die das System während der Debatte zusammensetzt – ein Anbieter sieht also Text, der aus Ihren Eingaben abgeleitet und um sie herum aufgebaut wurde, nicht nur Ihre ursprünglichen Worte. Ihre E-Mail-Adresse, Ihre Kontokennungen, Ihre Sitzungsaufzeichnungen oder Ihre Zahlungsdaten erhält er niemals." },
      { kind: "p", text: "Welche Anbieter und wo. Unser Verzeichnis der KI-Anbieter unter [dezbatere.ro/providers] ist Bestandteil dieser Nutzungsbedingungen. Es führt jeden Anbieter auf, den wir verwenden können: seinen Rechtsträger und sein Land; welche Daten er zu welchem Zweck erhält; wo er sie verarbeitet; seine Aufbewahrungsbedingungen; ob für den von uns verwendeten Endpunkt eine Null-Daten-Aufbewahrung aktiv ist; ob er Eingaben nach unserem Vertrag für Trainingszwecke verwenden darf; auf welchen Übermittlungsmechanismus wir uns stützen und wann wir den jeweiligen Eintrag zuletzt überprüft haben. Anbieter können sich außerhalb Ihres Landes und außerhalb des Europäischen Wirtschaftsraums befinden. Unsere Datenschutzerklärung erläutert die Schutzmaßnahmen." },
      { kind: "p", text: "Drei verschiedene Dinge. „Nicht zum Trainieren von Modellen verwendet“, „für einen begrenzten Zeitraum aus Sicherheits-, Missbrauchspräventions- oder rechtlichen Gründen aufbewahrt“ und „Null-Daten-Aufbewahrung – nach der Verarbeitung nicht gespeichert“ sind unterschiedliche Sachverhalte. Bewahrt ein Anbieter Eingaben für einen begrenzten Zeitraum auf, nennt das Verzeichnis Dauer und Grund. Ist eine Null-Daten-Aufbewahrung aktiv, nennt das Verzeichnis dies und die davon erfassten Funktionen. Wir werden Ihnen nicht mitteilen, Inhalte würden nicht aufbewahrt, wenn dies nicht zutrifft." },
      { kind: "p", text: "Ergebnisse. Im Verhältnis zwischen Ihnen und uns dürfen Sie das Ergebnis Ihrer eigenen Debatten für jeden rechtmäßigen Zweck verwenden, und wir beanspruchen kein Eigentum an erzeugtem Text. Beachten Sie, dass erzeugte Ergebnisse in vielen Rechtsordnungen möglicherweise nicht urheberrechtlich geschützt werden können, dass ähnliche Ergebnisse für andere Personen erzeugt werden können, dass Ergebnisse Material Dritter wiedergeben oder diesem ähneln können und dass für bestimmtes Ausgangsmaterial, das ein KI-Anbieter abruft, Beschränkungen für die Weiterverwendung gelten können. Sie sind dafür verantwortlich, dies zu prüfen, bevor Sie sich auf Ergebnisse verlassen oder sie erneut veröffentlichen." }
    ]
  },
  {
    no: "09",
    title: "Veröffentlichung einer Debatte",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Debatten sind standardmäßig privat. Nichts, was Sie erstellen, ist für andere sichtbar, sofern Sie es nicht veröffentlichen." },
      { kind: "p", text: "Was eine Veröffentlichung bewirkt. Die Veröffentlichung ist eine bewusste Handlung, die gesondert bestätigt wird. Bei einer Veröffentlichung erstellen wir eine unveränderliche Momentaufnahme der Debatte und machen sie für alle – auch ohne Konto – lesbar. [Search engines may index it. / Published debates are not indexed by search engines unless you choose to allow it.] Die Momentaufnahme zeigt Ihr Pseudonym, Ihre Frage in Ihrem Wortlaut, den Argumentationsbaum, die Bewertungen, das Urteil und den Konfidenzbereich sowie einen sichtbaren Hinweis, dass der Inhalt KI-generiert ist. Sie zeigt weder Ihre E-Mail-Adresse noch Ihre Sitzungsaufzeichnungen oder Ihren Kontoverlauf." },
      { kind: "p", text: "Eine Veröffentlichung ist in der Praxis faktisch unumkehrbar. Sobald eine Debatte öffentlich ist, können andere Personen sie lesen, zitieren, als Bildschirmfoto aufnehmen, archivieren und zwischenspeichern. Durch die Aufhebung der Veröffentlichung wird sie aus DebateAI entfernt und der Schlüssel zu unserer Kopie vernichtet; Kopien, die bereits anderswo vorhanden sind, werden davon jedoch nicht erfasst. Veröffentlichen Sie nichts, was Sie nicht dauerhaft mit Ihrem Pseudonym in Verbindung gebracht sehen möchten." },
      { kind: "p", text: "Veröffentlichte Debatten bei Schließung Ihres Kontos. Wenn Ihr Konto geschlossen wird, entfernen wir jede von Ihnen veröffentlichte Debatte unverzüglich und in jedem Fall innerhalb von 30 Tagen aus dem öffentlichen Zugriff, sofern das Gesetz nicht verlangt, dass wir schneller handeln oder einen bestimmten Inhalt aufbewahren. Kopien, die andere vor der Entfernung angefertigt haben, liegen außerhalb unserer Kontrolle. Wenn eine Debatte auch nach Ihrem Ausscheiden verfügbar bleiben soll, laden Sie sie vorher herunter. [This is Option B from the earlier drafts, as recommended in the second-opinion review. It is a product change to implement, not a description of the current system, which keeps published snapshots readable after erasure.]" },
      { kind: "p", text: "Wir können veröffentlichte Inhalte jederzeit entfernen. Wir können eine veröffentlichte Debatte entfernen oder den Zugriff darauf beschränken, wenn das Gesetz dies verlangt, ein Gericht oder eine zuständige Behörde dies anordnet oder die Debatte gegen diese Nutzungsbedingungen verstößt oder rechtswidrig ist. Nichts in diesem Abschnitt hindert uns daran, aufgrund eines wirksamen Hinweises nach Abschnitt 10 tätig zu werden, und nichts darin ist eine Zusage, dass eine veröffentlichte Debatte verfügbar bleibt." },
      { kind: "p", text: "Lizenz für veröffentlichte Inhalte. Durch die Veröffentlichung räumen Sie uns eine nicht ausschließliche, weltweite und unentgeltliche Lizenz ein, die Momentaufnahme zu hosten, zu speichern, zu vervielfältigen, anzuzeigen und öffentlich zugänglich zu machen sowie anderen zu gestatten, sie zu lesen und zu zitieren, solange sie veröffentlicht bleibt. Diese Lizenz besteht, damit wir die öffentlichen Seiten betreiben können; sie gestattet uns weder, Ihre Inhalte zu verkaufen, noch sie für das Produkt einer anderen Person zu lizenzieren." },
      { kind: "p", text: "Wenn eine Debatte Sie betrifft. Wenn eine auf DebateAI veröffentlichte Debatte personenbezogene Daten über Sie enthält, verleumderisch oder anderweitig rechtswidrig ist, können Sie unabhängig davon, ob Sie ein Konto haben, über Abschnitt 10 oder unter privacy@dezbatere.ro deren Entfernung verlangen. Wir werden bei hinreichend belegten Anträgen tätig und verlangen nicht, dass Sie sich registrieren, um einen solchen Antrag zu stellen." }
    ]
  },
  {
    no: "10",
    title: "Meldung von Inhalten, Moderation und Beschwerden",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Alle können Inhalte melden. Sie benötigen kein Konto. Schreiben Sie an [abuse@dezbatere.ro] oder verwenden Sie die Schaltfläche Melden bei einer veröffentlichten Debatte. Damit wir tätig werden können, teilen Sie uns Folgendes mit: warum Sie den Inhalt für rechtswidrig oder einen Verstoß gegen diese Nutzungsbedingungen halten, und zwar so ausführlich, dass wir die Beanstandung nachvollziehen können; den genauen Ort – die vollständige URL und, soweit möglich, die Passage; Ihren Namen und Ihre E-Mail-Adresse (bei Meldungen von Darstellungen sexuellen Kindesmissbrauchs nicht erforderlich); sowie Ihre nach Treu und Glauben abgegebene Erklärung, dass Ihre Meldung richtig und vollständig ist." },
      { kind: "p", text: "Wir bestätigen jede Meldung unverzüglich. Wir bearbeiten Meldungen zeitnah, sorgfältig, objektiv und frei von Willkür, teilen Ihnen unsere Entscheidung mit und erläutern, wie Sie sie anfechten können. Wenn wir eine Meldung mit automatisierten Mitteln bearbeiten oder entscheiden, weisen wir darauf hin. Auf Meldungen intimer Abbildungen, die ohne Einwilligung geteilt wurden, reagieren wir innerhalb von 48 Stunden nach Eingang eines wirksamen Antrags." },
      { kind: "p", text: "Zwei Arten automatisierter Entscheidungen, die getrennt bleiben." },
      {
        kind: "list",
        items: [
        "Entscheidungen innerhalb des Systems. Das System trifft maschinelle Entscheidungen über Argumente: Es kann die Beantwortung einer Frage ablehnen, in einem Endstatus anhalten – etwa wenn eine Frage auf einer falschen Voraussetzung beruht oder eher eine Wertfrage als eine empirische Frage ist –, einen Konfidenzbereich begrenzen, wenn keine unabhängige Kritik verfügbar war, oder eine Antwort als mangelhaft kennzeichnen, wenn der erzeugte Text die Konformitätsprüfung nicht bestanden hat. Dabei arbeitet das Produkt wie vorgesehen; diese Entscheidungen sind für Sie in der Debatte sichtbar und betreffen nicht Ihre Person.",
        "Moderationsentscheidungen über Inhalte und Konten. Die Entfernung oder Beschränkung einer veröffentlichten Debatte oder die Sperrung oder Schließung eines Kontos ist eine Entscheidung, die wir anhand dieser Nutzungsbedingungen oder des Gesetzes treffen. An jeder solchen Entscheidung, die Ihr Konto betrifft, ist ein Mensch beteiligt. Abschnitt 11 beschreibt die Gründe."
        ]
      },
      { kind: "p", text: "Begründung. Wenn wir Ihre Inhalte entfernen oder deren Sichtbarkeit beschränken oder Ihr Konto sperren oder kündigen, geben wir Ihnen eine Begründung: was wir getan haben und wie weit die Maßnahme reicht, auf welche Tatsachen wir uns gestützt haben und ob diese aus einer Meldung oder unseren eigenen Prüfungen stammen, ob automatisierte Mittel eingesetzt wurden, auf welcher gesetzlichen oder vertraglichen Grundlage die Maßnahme beruht und wie Sie die Entscheidung anfechten können." },
      { kind: "p", text: "Beschwerde gegen eine Entscheidung. Wenn Sie mit einer Moderationsentscheidung nicht einverstanden sind, antworten Sie innerhalb von sechs Monaten auf die Begründung oder schreiben Sie an [appeals@dezbatere.ro]. Eine Person, die an der ursprünglichen Entscheidung nicht beteiligt war, überprüft sie, und wir teilen Ihnen das begründete Ergebnis mit. Ihr Recht, ein Gericht anzurufen oder die alternative Streitbeilegung nach Abschnitt 18 zu nutzen, bleibt davon unberührt. Über den Beschwerdeweg können Sie auch beanstanden, dass wir auf eine Meldung nicht reagiert haben, ein Inhalt zu Unrecht entfernt, ein Konto zu Unrecht eingeschränkt oder Ihr Inhalt durch ein automatisiertes Werkzeug zu Unrecht beeinträchtigt wurde." },
      { kind: "p", text: "Kontakt mit einem Menschen. Unser Support-Assistent ist ein KI-System und weist darauf hin. Sie können jederzeit darum bitten, mit einem Menschen zu sprechen, und jedes Support-Gespräch bietet diesen Weg an. Wir verlassen uns bei der Kommunikation mit Ihnen nicht ausschließlich auf automatisierte Werkzeuge." },
      { kind: "p", text: "Ernsthafte Gefahr für Leben oder Sicherheit. Wenn wir Kenntnis von Informationen erlangen, die auf eine Straftat mit einer Gefahr für das Leben oder die Sicherheit einer Person hindeuten, informieren wir die zuständigen Behörden." }
    ]
  },
  {
    no: "11",
    title: "Sperrung und Kündigung",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Durch Sie. Schließen Sie Ihr Konto jederzeit in den Einstellungen, wie in Abschnitt 6 beschrieben. Sie benötigen keinen Grund." },
      { kind: "p", text: "Durch uns. Wir können Ihr Konto sperren oder schließen oder Ihre Inhalte entfernen oder beschränken, wenn Sie wesentlich gegen diese Nutzungsbedingungen, insbesondere Abschnitt 7, verstoßen; Ihre Inhalte rechtswidrig sind oder das Gesetz, ein Gericht oder eine Behörde unser Tätigwerden verlangt; Ihre Nutzung die Sicherheit, Integrität oder Verfügbarkeit des Dienstes oder die Rechte anderer gefährdet; Ihr Konto seit [24 months] inaktiv ist und wir Sie benachrichtigt haben; oder wir die Bereitstellung des Dienstes vollständig oder in Ihrem Land einstellen." },
      { kind: "p", text: "Sofern der Verstoß nicht schwerwiegend ist, das Gesetz kein sofortiges Handeln verlangt und eine Verzögerung keinen Schaden verursachen würde, teilen wir Ihnen das Problem mit und geben Ihnen eine angemessene Gelegenheit, es zu beheben, bevor wir das Konto sperren oder schließen. Wir geben stets eine Begründung nach Abschnitt 10, und Sie können die Entscheidung anfechten." },
      { kind: "p", text: "Wenn wir den Dienst vollständig einstellen oder ihn aus Ihrem Land zurückziehen, kündigen wir dies mindestens 30 Tage im Voraus an, erstatten alle für den Zeitraum nach der Einstellung vorausgezahlten Beträge und ermöglichen Ihnen zuvor, Ihre Debatten zu exportieren." },
      { kind: "p", text: "Folgen der Schließung. Bei Schließung eines Kontos vernichten wir die Verschlüsselungsschlüssel für Ihre Kontodaten und Ihre privaten Debatten, wodurch diese dauerhaft unlesbar werden, löschen Ihren Kontodatensatz und entfernen Ihre veröffentlichten Debatten aus dem öffentlichen Zugriff, wie in Abschnitt 9 beschrieben. Einige Daten bleiben erhalten, und Sie sollten wissen, welche: Einträge in unseren nur ergänzbaren Prüf- und Sicherheitsprotokollen, die zur Erfüllung unserer eigenen gesetzlichen und sicherheitsbezogenen Pflichten aufbewahrt werden; Aufzeichnungen, zu deren Aufbewahrung wir gesetzlich verpflichtet sind, einschließlich der Nachweise über Annahme und Einwilligung; sowie bei einer kleinen Zahl älterer Debatten, die vor Einführung unseres Verschlüsselungsverfahrens entstanden sind, Aufzeichnungen, deren Löschung nur eingeschränkt möglich ist – wir teilen Ihnen mit, falls dies auf Ihr Konto zutrifft. Die Datenschutzerklärung beschreibt all dies in datenschutzrechtlichen Begriffen und erläutert Ihr Recht auf Löschung." },
      { kind: "p", text: "Die Abschnitte 8 (hinsichtlich bereits veröffentlichter Inhalte), 15, 16 und 18 gelten auch nach der Kündigung fort." }
    ]
  },
  {
    no: "12",
    title: "Kostenpflichtige Tarife",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "[Inactive until a paid plan exists. Do not launch a paid tier without completing every bracket here and the checkout interface it describes.]" },
      { kind: "p", text: "DebateAI bietet einen kostenlosen Tarif an. Ein kostenpflichtiger Premium-Tarif [is / will be] verfügbar, der die vollständige Modellauswahl freischaltet und Ihnen erlaubt, die Regler der Debatte selbst einzustellen." },
      { kind: "p", text: "Bevor Sie bezahlen, zeigen wir Ihnen unmittelbar über der Zahlungsschaltfläche Folgendes: den Tarif; den Gesamtpreis einschließlich der anwendbaren Steuern; den Abrechnungszeitraum; den Hinweis, dass der Tarif bis zur Kündigung automatisch verlängert wird; das Enddatum eines etwaigen kostenlosen Testzeitraums und den anschließend berechneten Betrag; sowie die Kündigungsmöglichkeiten. Sie bestätigen die Verlängerungsbedingungen durch Markieren eines gesonderten Kästchens. Die Schaltfläche trägt die Aufschrift Kostenpflichtig abonnieren (auf Rumänisch Comandă cu obligație de plată). Wir senden Ihnen eine Bestätigung auf einem dauerhaften Datenträger, die dieselben Informationen, diese Nutzungsbedingungen und das Widerrufsformular enthält." },
      { kind: "p", text: "Erinnerungen. Wir senden Ihnen mindestens [5] Tage vor der Umwandlung eines kostenlosen Testzeitraums in einen kostenpflichtigen Tarif eine E-Mail, bei fortlaufenden Tarifen mindestens einmal jährlich und zwischen 30 und 45 Tagen vor jeder Verlängerung einer Laufzeit von mindestens zwölf Monaten. Jede Erinnerung enthält den Preis, das Datum und einen Link zur Kündigung." },
      { kind: "p", text: "Kündigung. Sie können jederzeit unter Einstellungen → Abonnement mit einem Bestätigungsklick oder über die Kündigungsseite unter [dezbatere.ro/cancel], für die keine Anmeldung erforderlich ist, kündigen. Die Kündigung wird zum Ende des laufenden Abrechnungszeitraums wirksam; bis dahin behalten Sie den Zugang. Wir werden die Kündigung nicht schwieriger gestalten als den Abschluss des Abonnements." },
      { kind: "p", text: "Preisänderungen werden nur bei einer Verlängerung wirksam. Wir informieren Sie mindestens 30 Tage im Voraus per E-Mail über den neuen Preis und fügen einen Kündigungslink bei. Soweit das Recht Ihres Landes Ihre ausdrückliche Zustimmung zu einer Preisänderung verlangt, holen wir diese ein; andernfalls gilt der neue Preis ab der nächsten Verlängerung, wenn Sie nichts unternehmen. Anhang A weist auf regionale Vorschriften hin." },
      { kind: "p", text: "Fehlgeschlagene Zahlungen. Wenn eine Zahlung fehlschlägt, versuchen wir sie [7] Tage lang erneut und warnen Sie per E-Mail, bevor wir Ihr Konto auf den kostenlosen Tarif herabstufen. Wir löschen Ihre Debatten nicht wegen einer fehlgeschlagenen Zahlung." },
      { kind: "p", text: "Steuern und Zahlungsempfänger. Die Preise [include / exclude] Mehrwertsteuer, GST oder Umsatzsteuer; dies hängt von Ihrem Wohnort ab und wird vor der Zahlung angezeigt. [If a merchant of record is used: Your purchase is processed by [Paddle / …], which is the seller of record for the transaction; its terms apply to payment, tax, invoicing, refunds and payment disputes. DebateAIRO remains responsible for the service itself and for these Terms.]" },
      { kind: "p", text: "Rückbuchungen. Wenn Sie eine Belastung bei Ihrem Kartenaussteller beanstanden, können wir kostenpflichtige Funktionen aussetzen, solange die Streitigkeit geklärt wird. Hierfür erheben wir keine Gebühren." },
      { kind: "p", text: "Gesetzliche Rechte gehen vor. Wenn der Dienst nicht dem entspricht, was wir zugesagt haben, haben Sie nach Maßgabe des Gesetzes Anspruch auf Herstellung der Vertragsmäßigkeit oder auf eine verhältnismäßige Preisminderung oder Erstattung. Darüber hinaus gilt [state your discretionary refund policy]. Die Nutzungslimits beider Tarife werden im Produkt veröffentlicht; wir informieren Sie, bevor wir sie in einer Weise verschärfen, die Sie wesentlich beeinträchtigt." }
    ]
  },
  {
    no: "13",
    title: "Ihr Widerrufsrecht",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Wenn Sie in der EU, im EWR oder im Vereinigten Königreich leben, können Sie ein kostenpflichtiges Abonnement innerhalb von 14 Tagen nach Abschluss ohne Angabe von Gründen widerrufen. Verwenden Sie die Seite Vertrag widerrufen unter [dezbatere.ro/withdraw], das Musterformular in der Bestätigungs-E-Mail oder schreiben Sie an [support@dezbatere.ro]; wir bestätigen den Eingang auf einem dauerhaften Datenträger." },
      { kind: "p", text: "Wenn Sie uns – durch Markieren des Kästchens beim Bezahlvorgang – aufgefordert haben, sofort mit der Leistung zu beginnen, und anschließend widerrufen, zahlen Sie für den bis zum Tag des Widerrufs erbrachten Teil des Dienstes, anteilig berechnet anhand des Preises für den Abrechnungszeitraum; den Rest erstatten wir. Sie verlieren das Widerrufsrecht nicht dadurch, dass Sie den Dienst während der 14 Tage nutzen." },
      { kind: "p", text: "Wenn Sie anderswo leben, nennt Anhang A das in Ihrer Region gegebenenfalls geltende Widerrufs- oder Rücktrittsrecht und andernfalls unsere Erstattungsrichtlinie. Gesetzliche Rechte in Ihrem Land gehen stets vor." }
    ]
  },
  {
    no: "14",
    title: "Änderungen des Dienstes und dieser Nutzungsbedingungen",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Änderungen des Dienstes. Wir entwickeln DebateAI kontinuierlich weiter; routinemäßige Verbesserungen, Fehlerbehebungen und Änderungen der Modellauswahl erfolgen ohne Ankündigung. Eine Änderung, die über die Aufrechterhaltung des beschriebenen Betriebs des Dienstes hinausgeht, nehmen wir nur aus einem der folgenden Gründe vor: um einer gesetzlichen oder regulatorischen Vorgabe nachzukommen; um auf ein Sicherheits- oder Missbrauchsproblem zu reagieren; weil ein Modellanbieter ein Modell oder eine Funktion, von dem beziehungsweise der wir abhängig sind, ändert, beschränkt oder zurückzieht; um uns an eine technische Umgebung anzupassen, die wir nicht kontrollieren; oder um eine Funktion ohne zusätzliche Kosten für Sie hinzuzufügen, zu verbessern oder einzustellen." },
      { kind: "p", text: "Wir teilen Ihnen im Voraus auf einem dauerhaften Datenträger mit, was sich wann ändert. Hat die Änderung mehr als geringfügige nachteilige Auswirkungen auf Ihren Zugang zum Dienst oder dessen Nutzung, können Sie innerhalb von 30 Tagen nach der Mitteilung oder nach Inkrafttreten der Änderung, je nachdem, welcher Zeitpunkt später liegt, kostenlos kündigen; wir erstatten alle für den ungenutzten Zeitraum vorausgezahlten Beträge." },
      { kind: "p", text: "Änderungen dieser Nutzungsbedingungen. Wir können diese Nutzungsbedingungen aus denselben Arten von Gründen ändern. Bei Änderungen, die Ihre Rechte nicht einschränken, veröffentlichen wir die neue Fassung mit einer Zusammenfassung der Änderungen und senden Ihnen mindestens 30 Tage vor ihrem Inkrafttreten eine E-Mail; wenn Sie DebateAI nach diesem Datum weiterhin nutzen, stimmen Sie der Änderung zu, und Sie können Ihr Konto vorher schließen. Bei Änderungen, die Ihre Rechte einschränken – darunter Preiserhöhungen für einen bestehenden Tarif, niedrigere Limits, entfernte Funktionen, neue Nutzungen Ihrer Inhalte oder Änderungen der Haftung, des anwendbaren Rechts oder der Streitbeilegung – bitten wir Sie, der neuen Fassung bei Ihrer nächsten Anmeldung ausdrücklich zuzustimmen; die Änderung gilt nur für die Zukunft. Wir nehmen Änderungen niemals rückwirkend vor und verwenden diesen Abschnitt niemals dazu, den Kern Ihrer bereits bezahlten Leistung während der Laufzeit zu ändern, ohne Ihnen eine Beendigungsmöglichkeit einzuräumen. Frühere Fassungen bleiben unter [dezbatere.ro/terms/versions] verfügbar." }
    ]
  },
  {
    no: "15",
    title: "Haftung",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Was wir nicht beschränken. Nichts in diesen Nutzungsbedingungen schließt unsere Haftung aus oder beschränkt sie für Tod oder Körperverletzung, die durch unsere Fahrlässigkeit verursacht wurden, für Betrug oder arglistige Täuschung, für grobe Fahrlässigkeit oder Vorsatz oder für sonstige Umstände, bei denen eine Beschränkung rechtlich unzulässig ist. Wenn Sie Verbraucher sind, entzieht Ihnen nichts hierin Ihre gesetzlichen Rechte, einschließlich des Rechts auf Herstellung der Vertragsmäßigkeit eines nicht vertragsgemäßen Dienstes oder auf Preisminderung oder Erstattung sowie jeglicher Gewährleistung nach dem Recht des Landes, in dem Sie leben." },
      { kind: "p", text: "Erzeugte Inhalte. Der Dienst erzeugt Material, das Sie beurteilen sollen, keine Schlussfolgerungen, nach denen Sie ungeprüft handeln können; Abschnitt 5 stellt dies unmissverständlich klar. Vorbehaltlich des vorstehenden Absatzes haften wir nicht für Entscheidungen, die Sie auf Grundlage erzeugter Argumente, Bewertungen oder Urteile treffen, wenn Sie nicht die in Abschnitt 5 beschriebenen angemessenen Schritte zu deren Überprüfung unternommen haben." },
      { kind: "p", text: "Ihre Inhalte und Ihre Nutzung. Sie sind für das verantwortlich, was Sie übermitteln und veröffentlichen, einschließlich dafür, dass Sie zur Übermittlung berechtigt sind und Abschnitt 7 einhalten." },
      { kind: "p", text: "Ereignisse außerhalb unserer Kontrolle. Wir begehen keine Vertragsverletzung, wenn wir durch einen Umstand außerhalb unserer zumutbaren Kontrolle an der Leistung gehindert werden. Ein Ausfall oder Rückzug eines externen Modellanbieters ist nicht automatisch ein solches Ereignis; führt er zur Nichtverfügbarkeit des Dienstes, gilt Abschnitt 14, und Sie können wie dort beschrieben kündigen und eine Erstattung erhalten." },
      { kind: "p", text: "[No monetary cap and no general exclusion of indirect loss apply to consumers. If a business tier is ever offered, negotiated allocations belong in a separate order form.]" }
    ]
  },
  {
    no: "16",
    title: "Geistiges Eigentum",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Der Dienst selbst – die Software, das System, die Bewertungsmethode, die Benutzeroberfläche, die Namen DebateAI und DebateAIRO sowie unsere Logos – gehört uns oder unseren Lizenzgebern. Diese Nutzungsbedingungen gestatten Ihnen die Nutzung des Dienstes, übertragen Ihnen jedoch kein Eigentum daran." },
      { kind: "p", text: "Sie dürfen veröffentlichte Debatten unter Nennung von DebateAI und mit einem Link zur ursprünglichen Seite zitieren und verlinken. Das massenhafte Kopieren, die systematische Vervielfältigung des öffentlichen Bestands und die Verwendung veröffentlichter Debatten als Trainingsdaten sind ohne unsere schriftliche Vereinbarung unzulässig." },
      { kind: "p", text: "Abschnitt 8 behandelt Ihre Inhalte und den Status erzeugter Ergebnisse. Wenn Sie der Ansicht sind, dass etwas auf DebateAI Ihr geistiges Eigentum verletzt, nutzen Sie den Meldeweg nach Abschnitt 10. [If the United States is inside section 2: our designated agent under the Digital Millennium Copyright Act is [name, address, email], registered with the US Copyright Office; we terminate the accounts of repeat infringers.]" }
    ]
  },
  {
    no: "17",
    title: "Personenbezogene Daten",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Wie wir personenbezogene Daten verarbeiten, ist in der Datenschutzerklärung unter [dezbatere.ro/privacy] dargelegt. Sie erläutert, was wir erheben, auf welcher Rechtsgrundlage die einzelnen Zwecke beruhen, wie lange wir Daten aufbewahren, wer Daten empfängt, welche Übermittlungen stattfinden und wie Sie Ihre Rechte ausüben können. Drei Punkte gehören ebenfalls hierher. Abschnitt 7 fordert Sie auf, keine personenbezogenen Daten anderer Personen in eine Frage aufzunehmen; tun Sie es dennoch, sind Sie dafür verantwortlich, und wir können den Inhalt entfernen. Enthält eine auf DebateAI veröffentlichte Debatte personenbezogene Daten über Sie, können Sie auch ohne Konto deren Entfernung verlangen (Abschnitt 9). Außerdem halten wir Ihre Zustimmung zu diesen Nutzungsbedingungen – Fassung, Zeitpunkt und technische Einzelheiten der Sitzung – als Nachweis des Vertrags fest, wie die Datenschutzerklärung erläutert." }
    ]
  },
  {
    no: "18",
    title: "Anwendbares Recht und Gerichtsstand",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Anwendbares Recht. Diese Nutzungsbedingungen sowie alle daraus oder aus ihrem Gegenstand entstehenden Streitigkeiten oder Ansprüche, einschließlich außervertraglicher Ansprüche, unterliegen dem Recht Rumäniens." },
      { kind: "p", text: "Ihre örtlichen Schutzrechte bleiben unberührt. Wenn Sie Verbraucher sind, entzieht Ihnen die Wahl rumänischen Rechts nicht den Schutz zwingender Verbraucherschutzvorschriften des Landes Ihres gewöhnlichen Aufenthalts – beispielsweise Vorschriften über missbräuchliche Klauseln, Widerrufs- und Kündigungsrechte oder Gewährleistungen –, soweit diese Vorschriften unabhängig von der Rechtswahl gelten, einschließlich nach Artikel 6 Absatz 2 der Verordnung (EG) Nr. 593/2008, wenn Sie in der EU leben, oder nach den entsprechenden Vorschriften des Vereinigten Königreichs. Sie können sich zusätzlich zum rumänischen Recht auf diese Vorschriften berufen." },
      { kind: "p", text: "Gerichte, wenn Sie in der EU, im EWR oder im Vereinigten Königreich leben. Sie können uns entweder vor den Gerichten Rumäniens oder vor den Gerichten des Landes verklagen, in dem Sie leben. Wir können Sie ausschließlich vor den Gerichten des Landes verklagen, in dem Sie leben." },
      { kind: "p", text: "Verbraucher in anderen Ländern. Wenn Sie außerhalb der EU, des EWR und des Vereinigten Königreichs leben, beschränkt nichts in diesen Nutzungsbedingungen Ihr nach dem Recht Ihres Landes bestehendes Recht, einen Anspruch vor dessen Gerichten geltend zu machen, oder ein Recht nach diesem Recht, auf das nicht verzichtet werden kann – einschließlich, wenn Sie in Australien oder Neuseeland leben, Ihrer Rechte aus Verbrauchergarantien; wenn Sie in Brasilien leben, des Código de Defesa do Consumidor; und wenn Sie in den Vereinigten Staaten leben, der Verbraucherschutzgesetze Ihres Bundesstaats." },
      { kind: "p", text: "Einwohner der Vereinigten Staaten. Anhang A.3 enthält eine Schiedsvereinbarung und einen Verzicht auf Sammelklagen, die dem Federal Arbitration Act unterliegen. Sie gelten nur für Einwohner der Vereinigten Staaten und nur, soweit sie durchsetzbar sind. Sie gelten nicht für Verbraucher in der EU, im EWR oder im Vereinigten Königreich." },
      { kind: "p", text: "Vor Anrufung eines Gerichts. Kontaktieren Sie uns unter [legal@dezbatere.ro]; die meisten Probleme lassen sich beheben, und wir bemühen uns um eine Antwort innerhalb von [5] Werktagen. Wenn Sie Verbraucher in Rumänien oder der EU sind, können Sie die alternative Streitbeilegung über [the ANPC – named SAL entity, website] nutzen; wir verpflichten uns [do / do not], an diesem Verfahren teilzunehmen. Für Beschwerden über Moderationsentscheidungen gilt der gesonderte Weg nach Abschnitt 10." }
    ]
  },
  {
    no: "19",
    title: "Sonstige Bestimmungen",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Übertragung. Sie dürfen Ihre Rechte aus diesen Nutzungsbedingungen nicht übertragen. Wir dürfen unsere Rechte auf ein Unternehmen übertragen, das den Dienst übernimmt, sofern Ihre Rechte dadurch nicht eingeschränkt werden; wir informieren Sie darüber, und Sie können Ihr Konto schließen." },
      { kind: "p", text: "Salvatorische Klausel. Wird eine Bestimmung dieser Nutzungsbedingungen für undurchsetzbar befunden, findet diese Bestimmung keine Anwendung, während die übrigen Nutzungsbedingungen in Kraft bleiben." },
      { kind: "p", text: "Kein Verzicht. Wenn wir eine Bestimmung nicht sofort durchsetzen, verlieren wir nicht das Recht, sie später durchzusetzen." },
      { kind: "p", text: "Gesamte Vereinbarung. Diese Nutzungsbedingungen bilden zusammen mit der Cookie-Richtlinie und dem Verzeichnis der KI-Anbieter die gesamte Vereinbarung zwischen uns über den Dienst. Verpflichtungen, die wir in der Datenschutzerklärung eingehen, sind für uns verbindlich. Nichts in diesem Absatz schließt die Haftung für arglistige Täuschung aus." },
      { kind: "p", text: "Sprache. Diese Nutzungsbedingungen werden auf Englisch [and Romanian] veröffentlicht. [State which version prevails for which users; Annex A notes where a local language is required.]" },
      { kind: "p", text: "Kontakt. [legal@dezbatere.ro] · DebateAIRO S.R.L., [address], Bukarest, Rumänien." }
    ]
  },
  {
    no: "A",
    title: "Anhang A – Regionale Bestimmungen",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Jeder Eintrag gilt nur, wenn seine Region in Abschnitt 2 aufgeführt ist, und nennt ausschließlich Abweichungen vom allgemeinen Teil. Widersprechen sich ein Eintrag und der allgemeine Teil, gilt für Personen in dieser Region der Eintrag." }
    ]
  },
  {
    no: "A.1",
    title: "Europäische Union und Europäischer Wirtschaftsraum",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Der allgemeine Teil dieser Nutzungsbedingungen ist für Sie abgefasst. Zusätzlich gilt: Sie können vor den Gerichten des Landes klagen, in dem Sie leben; das Widerrufsrecht nach Abschnitt 13 findet Anwendung; alternative Streitbeilegung ist über [the ANPC – named entity, website] möglich. Deutschland: Über die Kündigungsschaltfläche unter [dezbatere.ro/cancel] können Sie ein Abonnement ohne Anmeldung beenden; Vertragslaufzeiten, Verlängerungszeiträume und Kündigungsfristen entsprechen §309(9) BGB [state them]. Frankreich: Sie können ein Abonnement online in drei Schritten unter [URL] beenden; [the mediator named at URL] steht Ihnen zur Verfügung. Italien: Die Klauseln zur Haftung (15), Sperrung (11), zu Änderungen (14) und zum anwendbaren Recht (18) bedürfen Ihrer gesonderten Zustimmung, die Sie durch eine separate Bestätigung bei der Registrierung erteilen. Niederlande: Diese Nutzungsbedingungen werden vor Vertragsschluss in speicherbarer Form bereitgestellt. Polen: Eine polnische Fassung ist unter [URL] verfügbar." }
    ]
  },
  {
    no: "A.2",
    title: "Vereinigtes Königreich (nur wenn in Abschnitt 2 aufgeführt)",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Unser Vertreter im Vereinigten Königreich nach Artikel 27 UK GDPR ist [name, address, email]. Der Consumer Rights Act 2015 gilt für Sie, und nichts in diesen Nutzungsbedingungen beschränkt Ihre Rechte daraus; ab [January 2027] gelten für kostenpflichtige Tarife die Abonnementvorschriften des Digital Markets, Competition and Consumers Act 2024, einschließlich eines Rücktrittsrechts nach Verlängerungen und nach kostenlosen Testzeiträumen. Wie wir nutzende Personen vor rechtswidrigen Inhalten schützen: [terrorism content — …; child sexual exploitation and abuse content — …; other priority illegal content — …; intimate image content — removed within 48 hours of a valid report]. Von uns eingesetzte proaktive Technologie: [describe, or \"none\"]. Altersprüfung: [describe what is used; if only self-declaration, state that the service is treated as accessible to children for the purposes of the Online Safety Act 2023]. Das Beschwerdeverfahren nach Abschnitt 10 erfasst Beschwerden über rechtswidrige Inhalte, die unrechtmäßige Entfernung Ihrer Inhalte, Beschränkungen Ihres Kontos, den Einsatz automatisierter Werkzeuge mit Auswirkungen auf Ihre Inhalte und jede Altersprüfung, durch die Sie zu Unrecht gesperrt werden. Es steht auch Personen offen, die von Inhalten betroffen sind, ohne den Dienst selbst zu nutzen." }
    ]
  },
  {
    no: "A.3",
    title: "Vereinigte Staaten (nur wenn in Abschnitt 2 aufgeführt)",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Schiedsvereinbarung und Verzicht auf Sammelklagen. Wenn Sie in den Vereinigten Staaten leben, vereinbaren Sie und DebateAIRO, alle Streitigkeiten aus diesen Nutzungsbedingungen oder dem Dienst durch ein verbindliches individuelles Schiedsverfahren beizulegen, das von [the American Arbitration Association / JAMS] nach deren Verbraucherschiedsordnung durchgeführt wird, statt vor Gericht; beide Parteien dürfen jedoch einen individuellen Anspruch vor einem Gericht für geringfügige Forderungen geltend machen. Sie können widersprechen, indem Sie innerhalb von 30 Tagen nach der erstmaligen Annahme dieser Nutzungsbedingungen eine E-Mail an [address] senden. Diese Vereinbarung unterliegt dem Federal Arbitration Act. Wir tragen die Anmeldegebühren des Schiedsverfahrens. Auf Sammel-, Kollektiv- und Verbandsklagen wird im gesetzlich zulässigen Umfang verzichtet. Dieser Abschnitt gilt nur für die Zukunft und nicht für Ansprüche, die vor seiner Annahme entstanden sind." },
      { kind: "p", text: "Mitteilungen und Entfernung. Intime Abbildungen, die ohne Einwilligung veröffentlicht wurden, können ohne Konto unter [URL] gemeldet werden und werden innerhalb von 48 Stunden nach Eingang eines wirksamen Antrags entfernt. Urheberrechtsbeschwerden sind an unseren in Abschnitt 16 genannten Beauftragten zu richten." },
      { kind: "p", text: "Bundesstaatsspezifische Regelungen. Kalifornien: Es gelten die Bestimmungen zur automatischen Verlängerung in Abschnitt 12; Sie können jederzeit online kündigen; wir bewahren Ihre Zustimmung zu den Verlängerungsbedingungen mindestens drei Jahre lang auf. New York: Sie können innerhalb von 14 Tagen nach jeder Abbuchung zu einem erhöhten Preis kündigen und eine anteilige Erstattung erhalten. Texas und Nebraska: Wir verkaufen keine sensiblen personenbezogenen Daten; sollte sich dies jemals ändern, holen wir zuvor Ihre Einwilligung ein [statutory notice language]. Washington: Unser Datenschutzhinweis zu Verbrauchergesundheitsdaten unter [URL] gilt für gesundheitsbezogene Informationen. Colorado: Der Dienst trifft keine Entscheidungen mit erheblichen Folgen über Sie." }
    ]
  },
  {
    no: "A.4",
    title: "Kanada und Quebec (nur wenn aufgeführt)",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Unser Datenschutzbeauftragter ist [name, email]. Quebec: Diese Nutzungsbedingungen sind auf Französisch unter [URL] verfügbar, und Ihnen wurde die französische Fassung zuerst vorgelegt; die Einstellungen, mit denen Ihre Debatten privat bleiben, sind standardmäßig aktiviert; Sie können die Entfernung personenbezogener Informationen über Sie aus Suchmaschinenindizes verlangen." }
    ]
  },
  {
    no: "A.5",
    title: "Australien und Neuseeland (nur wenn aufgeführt)",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Für unsere Dienste gelten Garantien, die nach dem australischen Verbraucherrecht nicht ausgeschlossen werden können. Bei wesentlichen Leistungsstörungen sind Sie berechtigt, zu kündigen und eine Erstattung für den ungenutzten Anteil oder einen Ausgleich für den geminderten Wert zu erhalten; Sie haben außerdem Anspruch auf Ersatz aller anderen vernünftigerweise vorhersehbaren Verluste oder Schäden. Stellt die Leistungsstörung keine wesentliche Leistungsstörung dar, haben Sie Anspruch auf Behebung der Probleme mit dem Dienst innerhalb angemessener Zeit und, falls dies nicht geschieht, auf Kündigung und Erstattung. Soweit Abschnitt 64A dies zulässt, ist unsere Haftung für die Verletzung einer Garantie auf die erneute Erbringung des Dienstes oder die Zahlung der dafür anfallenden Kosten beschränkt. Über die Rechte aus Abschnitt 12 hinaus besteht für den kostenpflichtigen Tarif kein Rücktrittsrecht; unsere Erstattungsrichtlinie lautet […]. Neuseeland: Der Consumer Guarantees Act 1993 gilt, und nichts in diesen Nutzungsbedingungen schließt ihn aus; schädliche digitale Kommunikation kann uns nach Abschnitt 10 oder Netsafe gemeldet werden." }
    ]
  },
  {
    no: "A.6",
    title: "Lateinamerika (spanischsprachiger Anhang; nur wenn aufgeführt)",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "[Published in Spanish.] Die Einwilligung ist die Grundlage der Verarbeitung, soweit keine Notwendigkeit zur Vertragserfüllung besteht; bei der Registrierung willigen Sie ausdrücklich in die Verarbeitung aller sensiblen Daten ein, die Sie aufnehmen möchten. Sie können Ihre ARCO-Rechte unter [address] ausüben; Antworten erfolgen innerhalb von [Mexico 20 business days / Colombia 10–15 business days / Argentina 10 business days / Chile per Law 21.719]. Mexiko: Der vollständige aviso de privacidad ist unter [URL] verfügbar; Widerruf innerhalb von [5] Tagen. Argentinien: [AAIP legend]; verwenden Sie innerhalb von 10 Tagen den botón de arrepentimiento unter [URL]. Kolumbien: Die política de tratamiento ist unter [URL] verfügbar; Widerruf innerhalb von 5 Tagen. Chile (ab 1. Dezember 2026): Die Kontaktangaben der Behörde lauten […]; Sie können mit denselben Mitteln kündigen, mit denen Sie das Abonnement abgeschlossen haben; für digitale Dienste besteht kein Widerrufsrecht." }
    ]
  },
  {
    no: "A.7",
    title: "Golfregion — Vereinigte Arabische Emirate und Saudi-Arabien (nur wenn aufgeführt)",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Soweit wir Ihre Daten zu anderen Zwecken als zur Bereitstellung des Dienstes verarbeiten, erfolgt dies mit Ihrer Einwilligung, die Sie widerrufen können. Ihre Daten werden außerhalb von [UAE / Kingdom of Saudi Arabia], unter anderem in der Europäischen Union und den Vereinigten Staaten, auf Grundlage von [SDAIA standard contractual clauses / the mechanism in the Register] verarbeitet. Sie sind dafür verantwortlich, sicherzustellen, dass alles, was Sie veröffentlichen, dem Recht des Landes entspricht, in dem Sie sich befinden, einschließlich der Gesetze zu Religion, öffentlicher Ordnung und Sittlichkeit; wir können die Veröffentlichung von Debatten zu solchen Themen in Ihrer Region beschränken." }
    ]
  },
  {
    no: "A.8",
    title: "Asien-Pazifik (nur die Zeilen für aufgeführte Regionen)",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Singapur: Unser Datenschutzbeauftragter ist [name, email]; Übermittlungen beruhen auf vertraglichen Schutzvorkehrungen, die mit dem PDPA vergleichbar sind; für den kostenpflichtigen Tarif besteht kein gesetzliches Rücktrittsrecht, und unsere Erstattungsrichtlinie lautet […]. Japan: Die gesetzliche Offenlegung nach dem Specified Commercial Transactions Act ist unter [URL] verfügbar; für Online-Abonnements besteht kein allgemeines Rücktrittsrecht, und unsere Erstattungsrichtlinie lautet […]; Ihre Inhalte können an Anbieter in [named countries] übermittelt werden, und Sie stimmen dem durch die Einwilligungen bei der Registrierung zu. Südkorea: Einwilligungen in optionale Verarbeitung und Werbung werden getrennt von den Angaben eingeholt, die für den Betrieb des Dienstes erforderlich sind; unser Datenschutzbeauftragter ist [name]; Sie können einen kostenpflichtigen Tarif nach Maßgabe des E-Commerce Act innerhalb von 7 Tagen nach Abschluss widerrufen; vor jeder wiederkehrenden Preiserhöhung oder Umwandlung eines kostenlosen in einen kostenpflichtigen Tarif holen wir erneut Ihre Einwilligung ein; soweit der AI Basic Act dies verlangt, informieren wir Sie im Voraus, dass der Dienst KI-basiert ist, und kennzeichnen Ergebnisse. Indien (sobald die DPDP-Vorschriften gelten): Der Einwilligungshinweis unter [URL] findet Anwendung; Personen unter 18 Jahren benötigen eine nachprüfbare elterliche Einwilligung. Thailand: Unser Vertreter in Thailand ist [name] [if appointed]. Philippinen: Unsere Unternehmensidentifikation und unser Beschwerdemechanismus nach dem Internet Transactions Act sind unter [URL] verfügbar; Beschwerden können bei der National Privacy Commission eingereicht werden." }
    ]
  },
  {
    no: "A.9",
    title: "Vorbehalten",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Die Türkei, Brasilien und Indonesien erfordern jeweils einen Anhang in der Landessprache, einen Vertreter oder eine Registrierung sowie Einreichungen. Diese Länder sind hier nicht ausgearbeitet und liegen außerhalb von Abschnitt 2, bis sie ausdrücklich aufgenommen werden. In China, Vietnam und Russland wird der Dienst nicht angeboten." }
    ]
  }
];

export const TERMS_OF_SERVICE: LegalDocument = {
  key: "terms",
  eyebrow: "NUTZUNGSBEDINGUNGEN · v2.0 · GÜLTIG AB [DATE]",
  title: "Womit Sie sich einverstanden erklären",
  lede: "Der Vertrag zwischen Ihnen und DebateAIRO S.R.L. in verständlicher Sprache. Neunzehn Abschnitte und Anhang A – scrollen Sie bis zum Ende.",
  endMarker: "ENDE DER NUTZUNGSBEDINGUNGEN · v2.0",
  contact: "[legal@dezbatere.ro]",
  bodyLabel: "Text der Nutzungsbedingungen",
  sectionIdPrefix: "terms-section-",
  titleId: "terms-modal-title",
  gateHintId: "terms-modal-gate-hint",
  jumps: TERMS_JUMP,
  sections: TERMS_SECTIONS
};
