import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";
import { TypedDomainError } from "../../packages/kernel/src/index.js";
import {
  ProviderCallFailedError,
  ProviderContentUnacceptedError
} from "../../packages/providers/src/index.js";
import { apiOperationalErrorDiagnostic } from "../../apps/api/src/index.js";

// Synthetic sensitive content. None of these is a real credential; each is shaped
// like a value that the removed rules would have emitted verbatim.
const FAKE_TOKEN = "AKIAIOSFODNN7EXAMPLE";
const FAKE_DIGEST = "DEADBEEFCAFEBABE0123456789ABCDEF";
const SQL_FRAGMENT = "SELECT_PASSWORD_HASH_FROM_IDENTITY_USER";
const FILE_PATH = "/var/run/secrets/dialectical-api.key";


// EXPECTED MEMBERSHIP — the canonical copy for BOTH formatter tests.
//
// codex r1b F2 charged the previous version of these tests with taking their
// positive-control list FROM THE IMPLEMENTATION, so they affirmed whatever the map
// happened to contain, including three literals that are not domain codes at all.
// These two lists are generated from the PRODUCER CITATIONS, not from the map, and
// the maps are checked against them in both directions — a wrong member and a
// missing member each turn a test red.
//
// Source: logs/diag-bounded/r2-03-domain-code-citations.log and
// r0-03-allow-list-citations.log, both swept at dev
// d5b4f7f568aceec55a9cfca72b62473e7ee26c19.
// tests/unit/dev-runner-reconciliation.test.ts reads these arrays out of THIS
// file's source text rather than importing them, because importing a test module
// would register its suites a second time.
const EXPECTED_DOMAIN_CODES: readonly string[] = Object.freeze([
  "ABSENT_SIGNAL_HAS_FRESHNESS",
  "ADAPTIVE_STOPPING_CONTROLS_INVALID",
  "ADAPTIVE_STOPPING_CONTROLS_PROVENANCE_MISSING",
  "ADAPTIVE_STOPPING_CONTROLS_UNRESOLVED",
  "ADAPTIVE_STOPPING_UNRESOLVED",
  "ALGORITHM_REGISTER_ROWS_INVALID",
  "AMENDED_QUERY_REQUIRED",
  "AMENDMENT_REASON_REQUIRED",
  "ANSWER_INDEX_PAGE_INVALID",
  "ANSWER_MEMORY_OBSERVATION_FAILED",
  "ANSWER_PERSIST_FAILED",
  "ARROW_ENDPOINT_ABSENT",
  "ATTEMPT_ACCESS_DEPTH_MISSING",
  "AUTH_POLICY_INVALID",
  "AUTH_POLICY_UNRESOLVED",
  "BAND_CEILING_BAND_UNKNOWN",
  "BAND_CEILING_BASIS_INVALID",
  "BAND_CEILING_BASIS_MISMATCH",
  "BAND_CEILING_CUT_EMPTY",
  "BAND_CEILING_CUT_INVALID",
  "BAND_CEILING_DECISION_INVALID",
  "BAND_CEILING_FLOOR_BAND_INVALID",
  "BAND_CEILING_FLOOR_UNDESCRIBED",
  "BAND_CEILING_LABELS_INVALID",
  "BAND_CEILING_LABEL_INVALID",
  "BAND_CEILING_LABEL_UNKNOWN",
  "BAND_CEILING_LIFT_PATH_INVALID",
  "BAND_CEILING_ROW_INVALID",
  "BAND_CEILING_SOURCE_INVALID",
  "BAND_CEILING_VERSION_INVALID",
  "BAND_LABEL_INVALID",
  "BAND_LABEL_UNKNOWN",
  "BAND_ORDER_INVALID",
  "BLANK_QUERY_REFUSED",
  "BLOCKED_TERMINAL_RETIRED",
  "BRANCH_FREEZE_EPSILON_PROVENANCE_MISSING",
  "BUDGET_SKIP_AFFECTED_NODES_REQUIRED",
  "CALIBRATION_STRATEGY_INVALID",
  "CALL_BUDGET_EXHAUSTED",
  "CATCH_UP_ANSWER_NOT_FOUND",
  "CATCH_UP_DISCLOSURE_MISMATCH",
  "CATCH_UP_SOURCE_VERSION_CHANGED",
  "CATEGORICAL_SPAWN_CHILD_MISSING",
  "CLAIM_TYPE_COMPOSITION_MAP_INVALID",
  "CLAIM_TYPE_COMPOSITION_MAP_PROVENANCE_MISSING",
  "CLAIM_TYPE_COMPOSITION_MAP_UNRESOLVED",
  "COMPLETENESS_GATE_FAILED",
  "COMPOSITION_BUDGET_UNRESOLVED",
  "COMPOSITION_CONTRACT_ERROR",
  "COMPOSITION_UNRESOLVED",
  "CONDITION_MARK_AFFECTED_NODES_REQUIRED",
  "CONDITION_MARK_RECORD_REQUIRED",
  "CONDITION_MARK_RECORD_WITHOUT_MARK",
  "CONDITION_MARK_REVIEW_REASON_UNTRUE",
  "CONDITION_MARK_TRANSPORT_REASON_UNTRUE",
  "CONFIGURED_PROVIDER_SET_INVALID",
  "CONFIGURED_PROVIDER_SET_UNRESOLVED",
  "CONSUMER_AUTHORIZATION_FAILED",
  "CONSUMER_CONTENT_REFUSED",
  "CONSUMER_PROVIDER_FAILED",
  "CONSUMER_PROVIDER_TIMED_OUT",
  "CONSUMER_PUBLIC_CIPHER_UNAVAILABLE",
  "CONSUMER_PUBLIC_SAMPLE_UNAVAILABLE",
  "CONTENT_CIPHER_UNAVAILABLE",
  "CONTENT_LEASE_SCOPE_CHANGED",
  "CONTENT_LEASE_SCOPE_EXPANSION_FORBIDDEN",
  "CONVERGENCE_CONTROLS_INVALID",
  "CONVERGENCE_CONTROLS_PROVENANCE_MISSING",
  "CONVERGENCE_CONTROLS_UNRESOLVED",
  "CRITERION_ID_DUPLICATE",
  "CRITERION_ID_INVALID",
  "CRITERION_LABEL_INVALID",
  "CRITIC_UNAVAILABLE_BAND_CAP_UNRESOLVED",
  "CRITIQUE_CONTEXT_NOT_ISOLATED",
  "DAILY_COST_ENVELOPE_REACHED",
  "DATABASE_POOL_FAILED",
  "DEBATE_EXPANSION_PARENT_MISSING",
  "DEBATE_MAKER_UNRESOLVED",
  "DEBATE_ROOT_MISSING",
  "DECISION_IDEMPOTENCY_CONFLICT",
  "DECISION_IDENTITY_UNSERIALIZABLE",
  "DECISION_SPAWN_COUNT_INVALID",
  "DEEPENING_IDENTITY_MISSING",
  "DEEPENING_ROUND_INVALID",
  "DEPLOYMENT_REGISTER_UNAVAILABLE",
  "DERIVED_STANDING_RECORD_INVALID",
  "DIFFERENT_MAKER_REVIEWER_UNAVAILABLE",
  "DIGEST_NODE_IDS_NOT_UNIQUE",
  "DIGEST_NODE_SET_EMPTY",
  "DIGEST_SERVED_ROOT_ABSENT",
  "DISPUTED_RESOLUTION_REQUIRES_HUMAN",
  "DISTINCT_CERTIFICATION_CAPTURES_REQUIRED",
  "DUPLICATE_SNAPSHOT_NODE",
  "EDGE_BEARING_OUT_OF_RANGE",
  "EDGE_IDENTITY_CONFLICT",
  "EDGE_INTEGRITY_ERROR",
  "EDGE_MEASURED_MAGNITUDE_MISSING",
  "EDGE_MEASUREMENT_REFUSED",
  "EDGE_TARGET_MISSING",
  "EMPIRICAL_FINDINGS_MISSING",
  "EMPIRICAL_SETTLEMENT_MISSING",
  "EMPTY_DECISION_REASON",
  "EMPTY_EVENT_STREAM",
  "EMPTY_OVERLAY_OWNER",
  "EMPTY_PROPAGATION",
  "ENVELOPE_EXHAUSTED_WITHOUT_VERIFIED_COMPONENTS",
  "ENVELOPE_FORMULA_INPUTS_INVALID",
  "ENVELOPE_FORMULA_INPUTS_PROVENANCE_MISSING",
  "ENVELOPE_FORMULA_INPUTS_UNRESOLVED",
  "ENVELOPE_TERMINAL_OVER_SERVED_STATEMENT",
  "ENVELOPE_VERIFIED_NODE_SET_EMPTY",
  "EVALUATOR_ADDON_OUTPUT_INVALID",
  "EVALUATOR_ADDON_POLICY_INVALID",
  "EVALUATOR_ADDON_RUN_ID_INVALID",
  "EVALUATOR_CATALOG_UNAVAILABLE",
  "EVALUATOR_CONSUMER_MODEL_NOT_ENUMERATED",
  "EVALUATOR_CONTRACT_ERROR",
  "EVALUATOR_DOMAIN_ASSIGNMENT_ADMISSION_MISMATCH",
  "EVALUATOR_DOMAIN_ID_INVALID",
  "EVALUATOR_DOMAIN_MODEL_ID_INVALID",
  "EVALUATOR_DOMAIN_MODEL_VERSION_INVALID",
  "EVALUATOR_DOMAIN_PROPOSAL_ARTIFACT_MISMATCH",
  "EVALUATOR_DOMAIN_PROVENANCE_INVALID",
  "EVALUATOR_DOMAIN_PROVIDER_INVALID",
  "EVALUATOR_DOMAIN_REFUSAL_REASON_INVALID",
  "EVALUATOR_DOMAIN_RUN_ID_INVALID",
  "EVALUATOR_GROWN_DOMAIN_PROVENANCE_REQUIRED",
  "EVALUATOR_HARVEST_RUN_ID_INVALID",
  "EVALUATOR_MAKER_PANEL_COLLISION",
  "EVALUATOR_OBJECTION_MISSING",
  "EVALUATOR_PROFILE_DERIVATION_CONFLICT",
  "EVALUATOR_PROFILE_STRATEGY_ROW_KEY_INVALID",
  "EVALUATOR_PROFILE_STRATEGY_SOURCE_REF_INVALID",
  "EVALUATOR_PROVIDER_ENDPOINT_FORBIDDEN",
  "EVALUATOR_PROVIDER_FAMILY_INVALID",
  "EVALUATOR_PROVIDER_FAMILY_UNRESOLVED",
  "EVALUATOR_PROVIDER_PANEL_COLLISION",
  "EVALUATOR_PROVIDER_SCOPE_UNAUTHORIZED",
  "EVALUATOR_RANK_DERIVATION_CONFLICT",
  "EVALUATOR_TAGGER_ARTIFACT_REQUIRED",
  "EVALUATOR_TAGGER_MAKER_MISMATCH",
  "EVALUATOR_TAGGER_OUTPUT_INVALID",
  "EVALUATOR_TAG_EVENT_REASON_INVALID",
  "EVALUATOR_TAG_INPUT_HASH_INVALID",
  "EVALUATOR_TAG_PROVENANCE_INVALID",
  "EVALUATOR_TAG_QUESTION_INVALID",
  "EVALUATOR_TAG_RUN_ID_INVALID",
  "EVALUATOR_VERDICT_INCOHERENT",
  "EVIDENCE_ITEM_REF_REQUIRED",
  "EVIDENCE_REPLAY_HANDLE_REQUIRED",
  "EXPLORATION_FLOOR_INVALID",
  "EXTERNAL_RESOLVER_REQUIRED",
  "FIXED_SINGLE_ROOT_SERVE_VIOLATED",
  "FRESHNESS_BOUND_INVALID",
  "FRESHNESS_REGISTER_ROW_REQUIRED",
  "FRESHNESS_SOURCE_MISSING",
  "GRAPH_CHILD_STRUCTURE_INVALID",
  "GRAPH_CYCLE_DETECTED",
  "GRAPH_CYCLE_WRITE_REJECTED",
  "GRAPH_PARENT_NOT_FOUND",
  "GRAPH_ROOT_STRUCTURE_INVALID",
  "GRAPH_RUN_MISMATCH",
  "HIDDEN_CONDITION_MARK_RECORD_INVALID",
  "HONESTY_FIELD_MISSING",
  "INCONSISTENT_PRE_COMPOSITION_EVIDENCE",
  "INDEPENDENT_BUDGET_MARKS_CONFLATED",
  "INSTRUMENT_REF_REQUIRED",
  "INVALID_COMPOSITION_ATTEMPT",
  "JUDGEMENT_POLICY_UNRESOLVED",
  "JUDGE_PARSE_FAILURE",
  "JUDGE_SCHEMA_FAILURE",
  "LABEL_BASIS_DISCLOSURE_MISMATCH",
  "LEVERAGE_ROOT_SCOPE_EMPTY",
  "LEVERAGE_ROUND_INCOMPLETE",
  "LEVERAGE_SUBTREE_ROOT_UNRECORDED",
  "LIFT_TARGET_ABSENT",
  "LIVENESS_AFFECTED_EMPTY",
  "LIVENESS_NODE_NOT_FOUND",
  "LIVENESS_PARENT_CYCLE",
  "LIVENESS_POLICY_INVALID",
  "LIVENESS_POLICY_PROVENANCE_MISSING",
  "LIVENESS_POLICY_UNRESOLVED",
  "LIVENESS_QUERY_INVALID",
  "LIVENESS_THRESHOLD_INVALID",
  "LIVENESS_TIME_INVALID",
  "MAKER_INVENTORY_UNSATISFIED",
  "MAKER_POLICY_INVALID",
  "MAKER_POSITION_UNAVAILABLE",
  "MALFORMED_ARROW_ORDER",
  "MEMORY_ASKER_SCOPE_MISMATCH",
  "MEMORY_DIFFERENCE_REQUIRED",
  "MEMORY_DISCLOSURE_GATE_FAILED",
  "MEMORY_MATCH_FACT_REQUIRED",
  "MEMORY_PRIOR_ANSWER_MISSING",
  "MEMORY_PULL_CAP_EXCEEDED",
  "MEMORY_PULL_POLICY_INVALID",
  "MEMORY_PULL_UNPINNED",
  "MEMORY_QUESTION_EMPTY",
  "MEMORY_QUESTION_NOT_CANONICAL",
  "MEMORY_RUN_NOT_FOUND",
  "MEMORY_RUN_NOT_OWNED",
  "MISSING_COMPOSITION_ARTIFACT",
  "MODEL_ASSERTED_EVIDENCE_SCORE_REFUSED",
  "MODEL_FAMILY_REQUIRED",
  "MULTI_MAKER_PLAN_REQUIRES_MULTIPLE_MAKERS",
  "NEGATIVE_CAPTURE_REQUIRED",
  "NODE_ID_REQUIRED",
  "NODE_REVIEW_PARSE_FAILURE",
  "NODE_REVIEW_SCHEMA_FAILURE",
  "NODE_REVIEW_UNAVAILABLE",
  "NONSPAWNING_DECISION_HAS_CHILD",
  "NO_ELIGIBLE_MODEL",
  "NO_SERVABLE_MAKER_POSITION_AFTER_REVIEW",
  "NO_USABLE_JUDGEMENTS",
  "OFF_PLAN_QUERY_REFUSED",
  "OFF_SUBJECT_SHARE_REQUIRED",
  "OPERATOR_RESOLUTION_MISSING",
  "OPPOSITION_QUERY_REQUIRED",
  "OPTION_CRITERION_UNRESOLVED",
  "OPTION_ID_DUPLICATE",
  "OPTION_ID_INVALID",
  "OPTION_LABEL_INVALID",
  "ORG_POLICY_PROFILE_INVALID",
  "OVERLAY_DETACHMENT_VIOLATION",
  "OVERLAY_RUN_MISMATCH",
  "OWNER_ASK_ADMISSION_SCOPE_EXPANSION_FORBIDDEN",
  "OWNER_PRIVATE_HISTORY_SCAN_SATURATED",
  "PANEL_DISCOVERY_POLICY_UNRESOLVED",
  "PANEL_WEIGHTING_CONTROLS_INVALID",
  "PANEL_WEIGHTING_CONTROLS_PROVENANCE_MISSING",
  "PANEL_WEIGHTING_CONTROLS_UNRESOLVED",
  "PANEL_WEIGHTING_UNRESOLVED",
  "PARTIAL_SCORE_RUN_IDENTITY",
  "POSITIVE_CAPTURE_REQUIRED",
  "PRESENT_SIGNAL_FRESHNESS_UNKNOWN",
  "PRIVATE_CONTENT_ERASED",
  "PRODUCER_GRADING_FORBIDDEN",
  "PRODUCING_RUN_REQUIRED",
  "PRODUCT_ROLE_POLICY_DUPLICATE",
  "PRODUCT_ROLE_POLICY_INVALID",
  "PRODUCT_ROLE_POLICY_PROVENANCE_MISSING",
  "PRODUCT_ROLE_POLICY_REGISTER_COUNT_MISMATCH",
  "PRODUCT_ROLE_POLICY_REGISTER_UNSEALED",
  "PRODUCT_ROLE_POLICY_UNRESOLVED",
  "PROPAGATION_MAGNITUDE_INVALID",
  "PROPAGATION_RECEIPT_INVALID",
  "PROPAGATION_RECEIPT_MISSING",
  "PROPAGATION_STRENGTH_INVALID",
  "PROPER_SCORE_INVALID",
  "PROTECTED_CITATION_COMPARE_SKIPPED",
  "PROVIDER_CALL_FAILED",
  "PROVIDER_CALL_INSIDE_TRANSACTION",
  "PROVIDER_CONTENT_UNACCEPTED",
  "PROVIDER_RUN_REQUIRED",
  "PROVIDER_USAGE_INVALID",
  "PROVIDER_USAGE_UNREPORTED",
  "PUBLICATION_LEASE_SCOPE_EXPANSION_FORBIDDEN",
  "QUERY_SET_REF_REQUIRED",
  "RAW_ARTIFACT_RUN_REQUIRED",
  "RECONSTRUCTION_INPUT_MISSING",
  "RECOVERY_POLICY_DUPLICATE",
  "RECOVERY_POLICY_INVALID",
  "RECOVERY_POLICY_PROVENANCE_MISSING",
  "RECOVERY_POLICY_REGISTER_COUNT_MISMATCH",
  "RECOVERY_POLICY_REGISTER_UNSEALED",
  "RECOVERY_POLICY_UNRESOLVED",
  "REGENERATION_POLICY_MISMATCH",
  "REGENERATION_POLICY_UNRECORDED",
  "REGENERATION_REJECTION_EVIDENCE_MISSING",
  "RETIRED_SERVED_ROOT_RULE_NOT_WRITABLE",
  "REVISION_TRIGGER_NOT_FOUND",
  "RISK_TIER_POLICY_INVALID",
  "RISK_TIER_POLICY_PROVENANCE_MISSING",
  "RISK_TIER_POLICY_UNRESOLVED",
  "RIVAL_CARVER_UNAVAILABLE",
  "RUNNER_DISCLOSURE_PIPELINE_FAILED",
  "RUNNER_FAILURE_STATE_NOT_RECORDED",
  "RUN_CONTENT_ENCRYPTION_REQUIRED",
  "RUN_CONTENT_ROLLBACK_INCOMPLETE",
  "RUN_COST_ENVELOPE_EXHAUSTED",
  "RUN_COST_ENVELOPE_MONEY_REACHED",
  "RUN_COST_ENVELOPE_UNRESOLVED",
  "RUN_DEPTH_PARAMS_INVALID",
  "RUN_DISCOVERED_PANEL_EMPTY_AT_CLAIM",
  "RUN_ENVELOPE_BASIS_INVALID",
  "RUN_FROZEN_HEAD_READ_FAILED",
  "RUN_HOLD_RECORDER_UNRESOLVED",
  "RUN_LEGACY_ASKER_INVALID",
  "RUN_MAKER_COUNT_INVALID",
  "RUN_NOT_FOUND",
  "RUN_OWNER_INVALID",
  "RUN_OWNER_RAW_ID_FORBIDDEN",
  "RUN_OWNER_REF_INVALID",
  "RUN_PRINCIPAL_SESSION_MISMATCH",
  "SCALAR_DECISION_CANNOT_SPAWN",
  "SCORECARD_INTERVAL_INVALID",
  "SCORECARD_TASK_CLASS_AMBIGUOUS",
  "SCORECARD_TASK_CLASS_MAP_INVALID",
  "SCORECARD_TASK_CLASS_UNRESOLVED",
  "SCORED_REJECTED_EVIDENCE_REFUSED",
  "SCORING_OPERATOR_UNRESOLVED",
  "SELF_ROUTING_FORBIDDEN",
  "SENSITIVITY_FEEDBACK_ORDER_INVALID",
  "SEQUENCE_ALLOCATION_FAILED",
  "SERVED_NUMBER_NOT_FOUND",
  "SERVED_ROOT_JUDGEMENT_UNRESOLVED",
  "SERVED_ROOT_STRENGTH_UNRESOLVED",
  "SERVED_ROOT_UNRESOLVED",
  "SERVED_STATEMENT_CITES_NO_VERIFIED_NODE",
  "SERVE_GATE_CHAIN_FAILED",
  "SERVE_ITEMS_NOT_A_LIST",
  "SERVE_ITEM_INVALID",
  "SERVE_ITEM_OUT_OF_NODE_SET",
  "SERVE_LEDGER_APPEND_FAILED",
  "SERVE_NODE_IDS_NOT_UNIQUE",
  "SERVE_NODE_SET_EMPTY",
  "SERVE_OUTPUT_NOT_FROM_LEDGER",
  "SERVE_POLICY_UNRESOLVED",
  "SERVE_STATUS_UNKNOWN",
  "SESSION_POLICY_INVALID",
  "SESSION_POLICY_UNRESOLVED",
  "SETTLEMENT_FIELD_REQUIRED",
  "SETTLEMENT_IDENTITY_INVALID",
  "SETTLEMENT_NUMBER_INVALID",
  "SETTLEMENT_PROVENANCE_INVALID",
  "SETTLEMENT_RACE_WITHOUT_WINNER",
  "SETTLEMENT_READ_BACK_FAILED",
  "SHADOW_SUBJECT_REQUIRED",
  "SHADOW_UNLOCK_REQUIRED",
  "SOURCE_REF_REQUIRED",
  "SPAWN_SLOT_IDENTITY_CONFLICT",
  "STOPPING_DEPTH_CEILING_INVALID",
  "STOPPING_EXPECTED_ROOT_COUNT_INVALID",
  "STOPPING_MEASURED_EDGE_COUNT_INVALID",
  "STOPPING_PREVIOUS_ROUND_MISSING",
  "STOPPING_ROOT_SCOPE_EMPTY",
  "STOPPING_ROOT_SCOPE_MAKER_COUNT_INVALID",
  "STOPPING_ROOT_SCOPE_OVERFULL",
  "STOPPING_ROOT_STRENGTH_UNRESOLVED",
  "STOPPING_ROUND_COUNT_INVALID",
  "STORED_RESULT_MISSING",
  "STRENGTH_LINEAGE_UNRESOLVED",
  "STRUCTURAL_CEILING_BRANCHINGFACTOR_INVALID",
  "STRUCTURAL_CEILING_COMPOSITIONSEGMENTCAP_INVALID",
  "STRUCTURAL_CEILING_COMPOSITION_SHAPE_INCOHERENT",
  "STRUCTURAL_CEILING_DEPTH_ABOVE_SEALED_MAXIMUM",
  "STRUCTURAL_CEILING_DEPTH_INVALID",
  "STRUCTURAL_CEILING_EVALUATORMAXROUNDS_INVALID",
  "STRUCTURAL_CEILING_FINALRETRYATTEMPTS_INVALID",
  "STRUCTURAL_CEILING_FIXEDORGANSPERCOMPOSITION_INVALID",
  "STRUCTURAL_CEILING_INPUTS_UNRESOLVED",
  "STRUCTURAL_CEILING_JUDGEMAXATTEMPTS_INVALID",
  "STRUCTURAL_CEILING_MAXCOOLDOWNHOLDSPERRUN_INVALID",
  "STRUCTURAL_CEILING_MAXDEPTH_INVALID",
  "STRUCTURAL_CEILING_MAXRECOMPOSE_INVALID",
  "STRUCTURAL_CEILING_ORGANMAXATTEMPTS_INVALID",
  "STRUCTURAL_CEILING_PANELSIZE_INVALID",
  "STRUCTURAL_CEILING_REVIEWERCALLSPERNODE_INVALID",
  "STRUCTURAL_CEILING_SYNTHESIS_ROUNDS_INCOHERENT",
  "STRUCTURAL_CEILING_SYNTHESIZERMAXROUNDS_INVALID",
  "STRUCTURAL_CEILING_TREE_INVALID",
  "SUPERSEDED_ANSWER_IDENTITY_MISMATCH",
  "SUPERSEDED_ANSWER_NOT_FOUND",
  "SYNTHESIS_CANDIDATE_REF_MISSING",
  "SYNTHESIS_LOOP_PRODUCED_NO_CANDIDATE",
  "SYNTHESIS_NO_ARTIFACT",
  "SYNTHESIS_REQUEST_NOT_FRESH_CONTEXT",
  "SYNTHESIS_ROLE_CONTROLS_INVALID",
  "SYNTHESIS_ROLE_CONTROLS_PROVENANCE_MISSING",
  "SYNTHESIS_ROLE_CONTROLS_UNRESOLVED",
  "SYNTHESIS_ROLE_PROVIDER_ABSENT_AT_CLAIM",
  "SYNTHESIS_ROLE_PROVIDER_UNRESOLVED",
  "SYNTHESIS_ROUND_ARTIFACT_UNRESOLVED",
  "SYNTHESIS_TRANSPORT_DEATH",
  "TERMINAL_ACTIVATION_DRAIN_FAILED",
  "TERMINAL_ACTIVATION_EVALUATION_FAILED",
  "TERMINAL_ACTIVATION_EVALUATOR_UNRESOLVED",
  "TERMINAL_ACTIVATION_UNRESOLVED",
  "TERMINAL_FACT_READ_FAILED",
  "TERMINAL_ROW_NOT_EVALUATABLE",
  "TERMINAL_STATE_READ_FAILED",
  "TIER_PROVENANCE_MISSING",
  "UNDERCUT_TARGET_INVALID",
  "UNSERVED_MAKER_POSITION_UNRESOLVED",
  "UNSUPPRESSED_BAND_REQUIRED",
  "VALUE_CRITERIA_EMPTY",
  "VALUE_OPTIONS_INSUFFICIENT",
  "VALUE_PHASE_NOT_READY",
  "VERDICT_LABEL_BASIS_UNRESOLVED",
  "VERDICT_LABEL_CONTROLS_INVALID",
  "VERDICT_LABEL_CONTROLS_PROVENANCE_MISSING",
  "VERDICT_LABEL_CONTROLS_UNRESOLVED",
  "VERDICT_LABEL_INPUT_INVALID",
  "WAIT_RESOLUTION_INCOMPLETE",
  "WAIT_RESOLUTION_NOT_CURRENT",
  "WAY_OF_KNOWING_DOWNGRADE_NODE_UNRESOLVED",
  "WEIGHT_CRITERION_INVALID",
  "WEIGHT_VALUE_INVALID",
  "WEIGHT_VECTOR_CRITERIA_MISMATCH",
  "WEIGHT_VECTOR_EMPTY",
  "WEIGHT_VECTOR_ZERO",
  "WORK_ITEM_WITHOUT_RUN"
]);

/** Plain-error message constants, from the r0 producer citations. */
const EXPECTED_FAILURE_CONSTANTS: readonly string[] = Object.freeze([
  "ACCOUNT_CREATE_OUTCOME_MISSING",
  "ACCOUNT_CREATE_RECEIPT_INVALID",
  "ACCOUNT_DUPLICATE_ID_MISSING",
  "ACCOUNT_ERASURE_PREPARED",
  "ACCOUNT_NOTIFICATION_CHANNEL_REQUIRED",
  "ACCOUNT_NOT_ACTIVE",
  "ACCOUNT_RECOVERY_BINDING_IMMUTABLE",
  "ADDON_GRADING_LINEAGE_UNRESOLVED",
  "ARGON2_POOL_CAPACITY_INVALID",
  "ARGON2_POOL_WORKER_COUNT_INVALID",
  "ASK_ADMISSION_DATABASE_POOLS_MUST_BE_SEPARATE",
  "ATTEMPT_LEDGER_CONSUMPTION_INVALID",
  "ATTEMPT_LEDGER_PENDING_INVALID",
  "AUDIT_ATTEMPT_NOT_CONSUMED",
  "AUDIT_ATTEMPT_REQUIRED",
  "AUDIT_CANONICAL_VALUE_INVALID",
  "AUDIT_CHAIN_INVALID",
  "AUDIT_CONTEXT_DIGEST_INVALID",
  "AUDIT_EVENT_INVALID",
  "AUDIT_EVENT_SEMANTICS_INVALID",
  "AUDIT_EVENT_TARGET_INVALID",
  "AUDIT_EVENT_TYPE_RESERVED",
  "AUDIT_OPERATION_CAPABILITY_REQUIRED",
  "AUDIT_SUCCESS_REQUIRES_DOMAIN_CAPABILITY",
  "AUDIT_TOKEN_MUST_BE_RANDOM_UUID_V4",
  "AUTHORIZATION_DATABASE_URL_MUST_BE_SEPARATE",
  "AUTHORIZATION_DATABASE_URL_REQUIRED",
  "AUTH_RATE_LIMIT_POLICY_INVALID",
  "AUTH_RISK_SIGNAL_CONTEXT_INVALID",
  "AUTH_RISK_SIGNAL_CROSS_ACCOUNT",
  "AUTH_RISK_SIGNAL_IMMUTABLE",
  "AUTH_RISK_SIGNAL_KIND_INVALID",
  "AUTH_RISK_SIGNAL_POISONED",
  "AUTH_RISK_SIGNAL_PURGE_LIMIT_INVALID",
  "AUTH_RISK_SIGNAL_PURGE_OUTCOME_INVALID",
  "AUTH_RISK_SIGNAL_SCAN_SATURATED",
  "AUTH_RISK_SIGNAL_SCOPE_AMBIGUOUS",
  "AUTH_RISK_SIGNAL_SCOPE_UNRESOLVED",
  "BLIND_SAMPLE_REASONS_INVALID",
  "CAPTURE_QUEUE_CAPACITY_INVALID",
  "CONFIGURED_PROVIDER_DUPLICATE",
  "CONSUMER_OUTPUT_WRITE_FAILED",
  "CONSUMER_PROVIDER_ISOLATION_FAILED",
  "CONTENT_ATTESTATION_INVALID",
  "CONTENT_ATTESTATION_REQUIRED",
  "CONTENT_ATTESTATION_RUN_UNRESOLVED",
  "CONTENT_ATTESTATION_SCOPE_UNRESOLVED",
  "CONTENT_ATTESTATION_SECRET_UNRESOLVED",
  "CONTENT_ATTESTATION_STATE_INVALID",
  "CONTENT_BLIND_INDEX_CARRIER_UNDECLARED",
  "CONTENT_BLIND_INDEX_STATE_INVALID",
  "CONTENT_BLIND_INDEX_V1_KEY_MUST_BE_RETIRED",
  "CONTENT_BLIND_INDEX_V1_ROWS_FORBIDDEN",
  "CONTENT_CIPHER_ALREADY_CONFIGURED",
  "CONTENT_DERIVED_LOCATOR_CARRIER_UNDECLARED",
  "CONTENT_DERIVED_LOCATOR_V1_ROWS_FORBIDDEN",
  "CONTENT_ENCRYPTION_KEY_PATHS_REQUIRED",
  "CONTENT_LEASE_RUN_REQUIRED",
  "CONTENT_LEASE_UNLOCK_FAILED",
  "CONTENT_LOCATOR_RUN_UNRESOLVED",
  "CONTENT_PROVISION_DATABASE_ROLE_ATTESTATION_FAILED",
  "CONTENT_PROVISION_DATABASE_ROLE_MUST_BE_ISOLATED",
  "CONTENT_PROVISION_DATABASE_URL_MUST_BE_SEPARATE",
  "CONVERGENCE_EPSILON_INVALID",
  "ENCRYPTED_RUN_OWNER_INVALID",
  "ENCRYPTED_RUN_OWNER_TRANSFER_REQUIRES_REWRAP",
  "ERASURE_DATABASE_ROLE_ATTESTATION_FAILED",
  "ERASURE_DATABASE_ROLE_MUST_BE_ISOLATED",
  "ERASURE_DATABASE_URL_MUST_BE_SEPARATE",
  "ERASURE_NOTIFICATION_BINDING_IMMUTABLE",
  "ERASURE_NOTIFICATION_CHANNEL_INVALID",
  "ERASURE_NOTIFICATION_ERROR_CODE_INVALID",
  "ERASURE_NOTIFICATION_LEASE_UNLOCK_FAILED",
  "ERASURE_NOTIFICATION_REQUEST_INVALID",
  "EVALUATOR_ADDON_ADVISORY_UNLOCK_FAILED",
  "EVALUATOR_ADDON_OBSERVATION_CONFLICT",
  "EVALUATOR_ADDON_RUN_ORDINAL_INVALID",
  "EVALUATOR_ADDON_SAMPLE_INTERVAL_INVALID",
  "EVALUATOR_ADDON_TIME_INVALID",
  "EVALUATOR_CONSUMER_SELECTION_INVALID",
  "EVALUATOR_CONSUMER_SELECTION_TIME_INVALID",
  "EVALUATOR_DEV_MENU_DATABASE_URL_REQUIRED",
  "EVALUATOR_DEV_MENU_PRODUCTION_FORBIDDEN",
  "EVALUATOR_DEV_MENU_REGISTER_VERSION_REQUIRED",
  "EVALUATOR_HARVEST_TIME_INVALID",
  "EVALUATOR_JUDGE_RANK_INVALID",
  "EVALUATOR_JUDGE_SEAT_COUNT_INVALID",
  "EVALUATOR_LEDGER_SCOPE_UNAUTHORIZED",
  "EVALUATOR_PRIVATE_CONSUMER_OUTPUT_FORBIDDEN",
  "EVALUATOR_PROFILE_DERIVATION_VERSION_INVALID",
  "EVALUATOR_PROFILE_TIME_INVALID",
  "EVALUATOR_PUBLIC_AGGREGATE_OUTPUT_REQUIRED",
  "EVALUATOR_REGISTER_VERSION_INVALID",
  "EVALUATOR_SEAT_COUNT_INVALID",
  "EVALUATOR_SEAT_SHARE_CANDIDATE_DUPLICATE",
  "EVALUATOR_SEAT_SHARE_DEPTH_INVALID",
  "EVALUATOR_SEAT_SHARE_FORMULA_VERSION_INVALID",
  "EVALUATOR_SEAT_SHARE_POLICY_RECEIPT_INVALID",
  "EVALUATOR_SEAT_SHARE_PREMIUM_DEPTH_INVALID",
  "EVALUATOR_SEAT_SHARE_PROWESS_RANK_INVALID",
  "EVALUATOR_SEAT_SHARE_RELATIVE_COST_INVALID",
  "EVALUATOR_SEAT_SHARE_WEIGHT_INVALID",
  "EVALUATOR_SHADOW_DECISION_WRITE_FAILED",
  "IDENTITY_CHANNEL_UNSUPPORTED",
  "IDENTITY_CHILD_PARENT_IMMUTABLE",
  "IDENTITY_OWNER_REF_IMMUTABLE",
  "IDENTITY_PSEUDONYM_IMMUTABLE",
  "IDENTITY_USER_NOT_FOUND",
  "LEGACY_RUN_CLAIM_INVALID",
  "LEGACY_RUN_CLAIM_RESULT_INVALID",
  "LOGIN_RISK_SIGNAL_SCOPE_UNRESOLVED",
  "MAIL_OPERATOR_CODE_INVALID",
  "MFA_FAILURE_REASON_INVALID",
  "MFA_POLICY_UNRESOLVED",
  "MFA_RECOVERY_CODE_SET_INVALID",
  "MODEL_CALL_USAGE_EMPTY",
  "MODEL_CALL_USAGE_INVALID",
  "MODEL_CALL_USAGE_TOKEN_INVALID",
  "MODEL_CALL_USAGE_TOTAL_MISMATCH",
  "MODEL_CALL_USAGE_WRITE_FAILED",
  "OBS_CAPTURE_SELF_TEMPLATE_MISSING",
  "OWNED_RUN_LOCK_SCOPE_INVALID",
  "OWNER_ASK_ADMISSION_LEASE_UNLOCK_FAILED",
  "OWNER_REF_UNRESOLVED",
  "OWN_MAIL_CONFIGURATION_INVALID",
  "PASSKEY_CREDENTIAL_BINDING_IMMUTABLE",
  "PASSKEY_SIGNATURE_COUNTER_DECREASE",
  "PRIVATE_CONTENT_ERASED",
  "PRIVATE_CONTENT_OWNER_INACTIVE",
  "PRIVATE_ERASURE_AUDIT_BINDING_REQUIRED",
  "PRODUCER_GRADING_FORBIDDEN",
  "PROVIDER_DISCOVERY_TARGETS_INVALID",
  "PROVIDER_DISCOVERY_TARGETS_REQUIRED",
  "PROVIDER_DISCOVERY_TARGET_BASE_URL_INVALID",
  "PROVIDER_DISCOVERY_TARGET_DUPLICATE",
  "PROVIDER_DISCOVERY_TARGET_SET_MISMATCH",
  "PROVIDER_PROBE_FRESHNESS_INVALID",
  "PROVIDER_PROBE_INVALID",
  "PROVIDER_PROBE_RESPONSE_INVALID",
  "PROVIDER_PROBE_TIMEOUT_INVALID",
  "PROVIDER_PROBE_UNAVAILABLE",
  "PSEUDONYM_ALLOCATION_EXHAUSTED",
  "PUBLICATION_AUDIT_HEAD_CHANGED",
  "PUBLICATION_CLEANUP_DATABASE_ROLE_INVALID",
  "PUBLICATION_CLEANUP_DATABASE_URL_MUST_BE_SEPARATE",
  "PUBLICATION_CLEANUP_DATABASE_URL_REQUIRED",
  "PUBLICATION_DATABASE_ROLES_MUST_BE_SEPARATE",
  "PUBLICATION_DATABASE_ROLE_ATTESTATION_FAILED",
  "PUBLICATION_KEY_DOMAIN_MUST_BE_SEPARATE",
  "PUBLICATION_KEY_EXISTS",
  "PUBLICATION_KEY_PATHS_REQUIRED",
  "PUBLICATION_KEY_PROVISION_CLEANUP_PENDING",
  "PUBLICATION_KEY_PROVISION_INTENT_INCOMPLETE",
  "PUBLICATION_KEY_STORE_PATH_REQUIRED",
  "PUBLICATION_LEASE_REF_REQUIRED",
  "PUBLICATION_LEASE_UNLOCK_FAILED",
  "PUBLICATION_REF_ALLOCATION_FAILED",
  "PUBLICATION_REF_REPLAY",
  "PUBLICATION_REQUIRES_CONTENT_ENCRYPTION",
  "PUBLICATION_V2_AUDIT_BINDING_REQUIRED",
  "PUBLICATION_V2_REF_BINDING_REQUIRED",
  "PUBLIC_AGGREGATE_PROVIDER_CONFIGURATION_INVALID",
  "RATE_LIMIT_REFUSAL_AGGREGATE_INVALID",
  "RAW_ARTIFACT_RUN_REQUIRED",
  "RECOVERY_ENUMERATION_FLOOR_INVALID",
  "RECOVERY_PUBLIC_RESPONSE_POLICY_INVALID",
  "RECOVERY_RISK_SIGNAL_SCOPE_UNRESOLVED",
  "RECOVERY_START_CANDIDATE_AMBIGUOUS",
  "RECOVERY_START_INPUT_INVALID",
  "RECOVERY_START_OUTCOME_INVALID",
  "REDACTOR_RETURNED_UNBRANDED_ENVELOPE",
  "REGISTER_REQUIRED_ROW_VERSION_INVALID",
  "REGISTRATION_HASH_CANCELLED",
  "RELATIVE_COST_RUNTIME_CLASS_MISMATCH",
  "RELATIVE_COST_WINDOW_INVALID",
  "RELATIVE_COST_WINDOW_ORDER_INVALID",
  "RESEND_COOLDOWN_INVALID",
  "RESEND_RECEIPT_INVALID",
  "RUN_CONTENT_KEY_EXISTS",
  "RUN_CONTENT_KEY_OWNER_REF_INVALID",
  "RUN_CONTENT_KEY_RUN_ID_INVALID",
  "RUN_CONTENT_KEY_STORE_PATH_REQUIRED",
  "RUN_CONTENT_KEY_USER_ID_INVALID",
  "RUN_EXECUTION_REF_ALLOCATION_FAILED",
  "RUN_EXECUTION_REF_REQUIRED",
  "RUN_KEY_PROVISION_INTENT_INCOMPLETE",
  "RUN_LEGACY_ASKER_INVALID",
  "RUN_OWNERSHIP_OWNER_REF_NOT_ACTIVE",
  "RUN_OWNERSHIP_OWNER_REF_NOT_UUID_V4",
  "RUN_OWNERSHIP_PRINCIPAL_INVALID",
  "RUN_OWNERSHIP_RUN_NOT_FOUND",
  "RUN_OWNER_REF_INVALID",
  "S10_ENCRYPTED_RUN_OWNER_REWRAP_REQUIRED",
  "S10_IDENTITY_SESSION_REF_MIGRATION_REQUIRED",
  "S10_PUBLICATION_ACTOR_REF_MIGRATION_REQUIRED",
  "S10_WHATSAPP_CHANNEL_UNSUPPORTED",
  "S7_RAW_USER_ID_IN_IMMUTABLE_MEMORY",
  "S7_RAW_USER_ID_IN_IMMUTABLE_RUN",
  "SERVER_RUN_ENCRYPTION_INTENT_REQUIRED",
  "SESSION_BINDING_KEY_INVALID",
  "SESSION_CREDENTIAL_HASH_INVALID",
  "SETTLEMENT_WATCH_HANDLE_REQUIRED",
  "SPOOL_ENVELOPE_MAX_BYTES_INVALID",
  "SPOOL_ENVELOPE_TOO_LARGE",
  "SPOOL_FD_IDENTITY_CHANGED",
  "SPOOL_FD_INVALID",
  "SPOOL_REQUIRES_POST_REDACTION_ENVELOPE",
  "SPOOL_REQUIRES_PREPARED_POST_REDACTION_RECORD",
  "SPOOL_STREAM_POISONED",
  "SPOOL_WRITE_INCOMPLETE",
  "USER_DEK_STORE_PATH_REQUIRED",
  "USER_DEK_STORE_USER_ID_INVALID",
  "VERIFICATION_DELIVERY_OUTCOME_INVALID",
  "ZONE_FLUSH_INTERVAL_INVALID",
  "ZONE_FLUSH_JITTER_INVALID"
]);

const ALPHABET_BEGIN = "// ─── BEGIN OPERATIONAL DIAGNOSTIC ALPHABET";
const ALPHABET_END = "// ─── END OPERATIONAL DIAGNOSTIC ALPHABET";

function diagnosticAlphabetBlock(source: string): string {
  const start = source.indexOf(ALPHABET_BEGIN);
  const end = source.indexOf(ALPHABET_END);
  expect(start).toBeGreaterThanOrEqual(0);
  expect(end).toBeGreaterThan(start);
  return source.slice(start, end + ALPHABET_END.length);
}

function declaredList(block: string, name: string): readonly string[] {
  const declaration = block.slice(block.indexOf(`const ${name}`));
  const body = declaration.slice(declaration.indexOf("["), declaration.indexOf("]);"));
  return Object.freeze([...body.matchAll(/"([A-Z][A-Z0-9_]*)"/gu)].map((match) => match[1]!));
}

describe("API operational error diagnostics", () => {
  it("retains bounded codes without retaining raw exception messages", () => {
    // CHANGED (F-DIAG-OPERATIONAL-REGEX): was `DEPENDENCY_42501`. `DEPENDENCY_${code}`
    // forwarded the five-character code the SERVER chose; the code rule is now an
    // allow-list keyed by the published SQLSTATE class.
    expect(apiOperationalErrorDiagnostic(Object.assign(new Error("secret SQL text"), { code: "42501" })))
      .toBe("DEPENDENCY_SQL_42_ACCESS_OR_SYNTAX");
    expect(apiOperationalErrorDiagnostic(new TypeError("PROVIDER_PROBE_RESPONSE_INVALID")))
      .toBe("PROVIDER_PROBE_RESPONSE_INVALID");
    expect(apiOperationalErrorDiagnostic(new Error("private question text")))
      .toBe("ERROR");
  });

  it("emits no synthetic sensitive content placed in code, message or name", () => {
    // A credential-shaped `code`: satisfied /^[A-Z0-9_]{2,32}$/u and was emitted.
    const tokenInCode = apiOperationalErrorDiagnostic(
      Object.assign(new Error("boom"), { code: FAKE_TOKEN })
    );
    expect(tokenInCode).not.toContain(FAKE_TOKEN);
    expect(tokenInCode).toBe("ERROR");

    // A digest-shaped `message`: satisfied /^[A-Z][A-Z0-9_]{2,63}$/u and was emitted.
    const digestInMessage = apiOperationalErrorDiagnostic(new Error(FAKE_DIGEST));
    expect(digestInMessage).not.toContain(FAKE_DIGEST);
    expect(digestInMessage).toBe("ERROR");

    // An upper-cased SQL fragment: constant-SHAPED, but not a known constant.
    const sqlInMessage = apiOperationalErrorDiagnostic(new TypeError(SQL_FRAGMENT));
    expect(sqlInMessage).not.toContain(SQL_FRAGMENT);
    expect(sqlInMessage).toBe("TYPE_ERROR");

    // A secret-bearing class `name`: was camel-to-SNAKE upper-cased and emitted.
    const tokenInName = apiOperationalErrorDiagnostic(
      Object.assign(new Error("boom"), { name: "TokenAkiaiosfodnn7" })
    );
    expect(tokenInName).not.toContain("AKIAIOSFODNN7");
    expect(tokenInName).toBe("UNEXPECTED_ERROR");

    // A driver rejection naming a relation: the class, never the server's text.
    const relationInMessage = apiOperationalErrorDiagnostic(Object.assign(
      new Error('relation "identity_user" does not exist'),
      { code: "42P01", name: "error" }
    ));
    expect(relationInMessage).not.toContain("identity_user");
    expect(relationInMessage).not.toContain("42P01");
    expect(relationInMessage).toBe("DEPENDENCY_SQL_42_ACCESS_OR_SYNTAX");

    // A filesystem path in the message reaches the fixed class category.
    const pathInMessage = apiOperationalErrorDiagnostic(new Error(FILE_PATH));
    expect(pathInMessage).not.toContain("secrets");
    expect(pathInMessage).toBe("ERROR");
  });

  it("still maps every allow-listed failure constant, whatever produced it", async () => {
    const block = diagnosticAlphabetBlock(await readFile("apps/api/src/index.ts", "utf8"));
    const constants = declaredList(block, "KNOWN_FAILURE_CONSTANTS");
    // Same independence rule as the domain list: the expectation is generated from
    // the producer citations, not read back out of the implementation.
    expect([...constants].sort()).toEqual([...EXPECTED_FAILURE_CONSTANTS].sort());

    // Cited producers, one per admitted category.
    expect(constants).toContain("PROVIDER_PROBE_RESPONSE_INVALID"); // packages/providers/src/provider-probe.ts:104
    expect(constants).toContain("PSEUDONYM_ALLOCATION_EXHAUSTED"); // apps/api/src/registration.ts:1275
    expect(constants).toContain("CONTENT_ATTESTATION_INVALID"); // migrations/0040_account_erasure.sql:608

    // A PostgreSQL RAISE arrives with the constant in `message` and a SQLSTATE in
    // `code`; the named constant is the more specific answer and must win.
    expect(apiOperationalErrorDiagnostic(Object.assign(
      new Error("CONTENT_ATTESTATION_INVALID"),
      { code: "22023", name: "error" }
    ))).toBe("CONTENT_ATTESTATION_INVALID");

    for (const constant of EXPECTED_FAILURE_CONSTANTS) {
      expect(apiOperationalErrorDiagnostic(new Error(constant))).toBe(constant);
    }
  });

  it("maps a declared domain code and refuses an undeclared typed code", async () => {
    // codex r1 F1: `TypedDomainError`'s `code` is typed `string`
    // (packages/kernel/src/index.ts:388), so this branch used to return whatever
    // the constructor was handed. Control first — a declared code keeps its
    // diagnostic, which is the whole point of not simply dropping the branch.
    expect(apiOperationalErrorDiagnostic(
      new TypedDomainError("RUN_CONTENT_ROLLBACK_INCOMPLETE", "Run rollback did not complete")
    )).toBe("RUN_CONTENT_ROLLBACK_INCOMPLETE");
    expect(apiOperationalErrorDiagnostic(
      new TypedDomainError("COMPOSITION_CONTRACT_ERROR", "composition contract")
    )).toBe("COMPOSITION_CONTRACT_ERROR");

    // Rejection — the reviewer's own probe value, which is not a declared code.
    expect(apiOperationalErrorDiagnostic(new TypedDomainError("DIAG_REVIEW_SENTINEL", "probe")))
      .toBe("UNRECOGNIZED_DOMAIN_ERROR");

    // Rejection — a credential-shaped typed code must not survive the branch.
    const tokenTyped = apiOperationalErrorDiagnostic(new TypedDomainError(FAKE_TOKEN, "probe"));
    expect(tokenTyped).not.toContain(FAKE_TOKEN);
    expect(tokenTyped).toBe("UNRECOGNIZED_DOMAIN_ERROR");

    // Rejection — an upper-cased SQL fragment carried as a typed code.
    const sqlTyped = apiOperationalErrorDiagnostic(new TypedDomainError(SQL_FRAGMENT, "probe"));
    expect(sqlTyped).not.toContain(SQL_FRAGMENT);
    expect(sqlTyped).toBe("UNRECOGNIZED_DOMAIN_ERROR");

    // Non-code literals that were wrongly admitted (codex r1b F2). Each is a real
    // literal in packages/evaluator — a decision value, a phase-order member and a
    // grade verdict — and none is a domain error code.
    for (const notACode of ["MATCHED_EXISTING", "PROWESS_RANK", "UNASSESSABLE"]) {
      expect(apiOperationalErrorDiagnostic(new TypedDomainError(notACode, "probe")))
        .toBe("UNRECOGNIZED_DOMAIN_ERROR");
    }

    // The map must equal the independently generated expectation, both ways.
    const block = diagnosticAlphabetBlock(await readFile("apps/api/src/index.ts", "utf8"));
    const codes = declaredList(block, "KNOWN_DOMAIN_CODES");
    expect([...codes].sort()).toEqual([...EXPECTED_DOMAIN_CODES].sort());
    for (const code of EXPECTED_DOMAIN_CODES) {
      expect(apiOperationalErrorDiagnostic(new TypedDomainError(code, "declared"))).toBe(code);
    }
  });

  /**
   * I2 (review round 2) — THE SPEND CODES, SWEPT FROM THE SOURCE THAT RAISES
   * THEM RATHER THAN RESTATED IN A LITERAL.
   *
   * `EXPECTED_DOMAIN_CODES` above is a hand-committed list, so the doc comment's
   * promise that "a missing member turns a test red" was false for a code nobody
   * had added to BOTH lists: V-28 shipped three that reached the boundary as
   * `RUNNER_EXECUTION_FAILED:UNRECOGNIZED_DOMAIN_ERROR`, which tells an operator
   * that the engine broke when it had in fact enforced a ceiling.
   *
   * This row sweeps the modules that RAISE the spend refusals — the money
   * arithmetic, the persisted-spend guard, the gateway's own refusal inventory
   * and the runner's envelope-stop map — and requires every code it finds to be
   * recognised by the formatter. No literal to keep in step: a fourth spend code
   * added tomorrow reddens this row on the day it is written.
   *
   * SCOPE, stated rather than implied: this sweeps the V-28 family, not the
   * whole tree. A whole-tree sweep of `new TypedDomainError("…")` finds about
   * 244 further codes that are not in `KNOWN_DOMAIN_CODES`, because that list is
   * deliberately scoped to codes which can REACH this boundary (its own comment
   * cites the producer log it was generated from). Widening it is a separate
   * piece of work and is named in the task report, not smuggled in here.
   */
  it("recognises every spend refusal its own source can raise (V-28)", async () => {
    const sources = await Promise.all([
      "packages/budget/src/cost-envelope.ts",
      "packages/budget/src/model-spend.ts",
      "packages/providers/src/index.ts",
      "apps/runner/src/index.ts"
    ].map((path) => readFile(path, "utf8")));
    const swept = new Set<string>();
    for (const source of sources) {
      // The three shapes these modules declare a spend refusal in: an exported
      // code constant, a member of the gateway's refusal inventory, and a key of
      // the runner's envelope-stop map.
      for (const match of source.matchAll(
        /"((?:RUN_COST_ENVELOPE|DAILY_COST_ENVELOPE|PROVIDER_USAGE)_[A-Z_]+)"/gu
      )) swept.add(match[1]!);
    }

    // The sweep must actually find something, or it is a test that cannot fail.
    expect(swept.size).toBeGreaterThanOrEqual(3);
    for (const code of swept) {
      expect(apiOperationalErrorDiagnostic(new TypedDomainError(code, "swept"))).toBe(code);
    }
  });

  it("preserves a declared provider subclass code without its raw fields", () => {
    // codex r1b F3. Both classes extend TypedDomainError and declare their code in
    // super(), which a `new TypedDomainError(` sweep never visits. They satisfy
    // instanceof, so the typed lookup answers first and the class-name map cannot
    // repair an omission here.
    const called = new ProviderCallFailedError(
      new Error("upstream 10.0.0.9:443 refused: key sk-live-EXAMPLE"),
      3,
      "FAILED",
      "ledger:abc123"
    );
    expect(apiOperationalErrorDiagnostic(called)).toBe("PROVIDER_CALL_FAILED");

    const unaccepted = new ProviderContentUnacceptedError(
      2,
      "SCHEMA_FAILED",
      "unexpected token at line 4: {\"secret\":\"sk-live-EXAMPLE\"}",
      "artifact:raw-9f8ae2",
      "ledger:def456"
    );
    const diagnostic = apiOperationalErrorDiagnostic(unaccepted);
    expect(diagnostic).toBe("PROVIDER_CONTENT_UNACCEPTED");
    // The parse error IS this error's message; the diagnostic must not carry it.
    expect(diagnostic).not.toContain("secret");
    expect(diagnostic).not.toContain("sk-live-EXAMPLE");
    expect(diagnostic).not.toContain("artifact:raw-9f8ae2");
    expect(apiOperationalErrorDiagnostic(called)).not.toContain("10.0.0.9");
  });

  it("keeps the api and runner diagnostic alphabets byte-identical", async () => {
    const [api, runner] = await Promise.all([
      readFile("apps/api/src/index.ts", "utf8"),
      readFile("apps/runner/src/index.ts", "utf8")
    ]);
    expect(diagnosticAlphabetBlock(runner)).toBe(diagnosticAlphabetBlock(api));
  });

  it("records provider recovery through the narrow runtime capability", async () => {
    const [repository, migration] = await Promise.all([
      readFile("packages/db/src/index.ts", "utf8"),
      readFile("migrations/0048_provider_probe_capability.sql", "utf8")
    ]);
    expect(repository).toContain("SELECT core.record_provider_probe($1,$2,$3,$4,$5,$6,$7)");
    expect(repository).not.toMatch(/INSERT INTO core\.provider_probe/);
    expect(migration).toContain("SECURITY DEFINER");
    expect(migration).toContain("GRANT EXECUTE ON FUNCTION core.record_provider_probe");
    expect(migration).toContain("TO debateai_runtime");
  });
});
