import{expect,it}from"vitest";import{buildApi,type AskApplication}from"../../apps/api/src/index.js";
it("exposes a separate origin-bound MFA start without ordinary session authority",async()=>{const origin="https://preview.example.test",api=buildApi({application:{}as AskApplication,allowedOrigin:origin,mfaRecovery:{async start(){return{message:"If this account can be recovered, instructions will arrive through an eligible channel."};}}as never});try{const r=await api.inject({method:"POST",url:"/v1/auth/mfa-recovery/start",headers:{origin},payload:{email:"owned@example.test",destination:"primary"}});expect(r.statusCode).toBe(202);expect(r.headers["set-cookie"]).toBeUndefined();expect((await api.inject({method:"POST",url:"/v1/auth/mfa-recovery/start",headers:{origin:"https://evil.example.test"},payload:{email:"owned@example.test",destination:"primary"}})).statusCode).toBe(403);}finally{await api.close();}});
// Owner ruling 2026-10-09: completing starts a 24-hour wait; the emailed finish link plus the current password finishes it.
import{describe,vi}from"vitest";import{EmailRecoveryError}from"../../apps/api/src/email-mfa-recovery.js";
describe("the 24-hour wait over HTTP",()=>{
 const origin="https://preview.example.test",TOKEN="F".repeat(43),SESSION="S".repeat(43),CSRF="X".repeat(43);
 function api(mfa:Record<string,unknown>){return buildApi({application:{}as AskApplication,allowedOrigin:origin,mfaRecovery:{assertCsrf:async()=>undefined,...mfa}as never});}
 it("answers complete with the waiting state and the time it can be finished",async()=>{const complete=vi.fn(async()=>({status:"waiting",not_before:"2026-10-10T12:00:00.000Z"})),a=api({complete});try{const r=await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/complete",headers:{origin,cookie:`__Host-debateai-mfa-recovery=${SESSION}; __Host-debateai-mfa-recovery-csrf=${CSRF}`,"x-mfa-recovery-csrf-token":CSRF},payload:{}});expect(r.statusCode).toBe(200);expect(r.json()).toEqual({status:"waiting",not_before:"2026-10-10T12:00:00.000Z"});expect(complete).toHaveBeenCalledWith({sessionToken:SESSION},expect.objectContaining({userAgent:expect.any(String)}));}finally{await a.close();}});
 it("reads a finish link from a trusted origin only, without any cookie",async()=>{const prepareFinish=vi.fn(async()=>({status:"waiting",not_before:"2026-10-10T12:00:00.000Z"})),a=api({prepareFinish});try{const r=await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish/status",headers:{origin},payload:{token:TOKEN}});expect(r.statusCode).toBe(200);expect(r.headers["cache-control"]).toBe("no-store");expect(r.json()).toEqual({status:"waiting",not_before:"2026-10-10T12:00:00.000Z"});expect(prepareFinish).toHaveBeenCalledWith({token:TOKEN},expect.anything());expect((await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish/status",headers:{origin:"https://evil.example.test"},payload:{token:TOKEN}})).statusCode).toBe(403);expect((await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish/status",headers:{origin},payload:{token:"short"}})).statusCode).toBe(400);expect(prepareFinish).toHaveBeenCalledTimes(1);}finally{await a.close();}});
 it("finishes with the finish link and the current password",async()=>{const finish=vi.fn(async()=>({status:"completed"})),a=api({finish});try{const r=await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish",headers:{origin},payload:{token:TOKEN,password:"current password"}});expect(r.statusCode).toBe(200);expect(r.json()).toEqual({status:"completed"});expect(r.headers["set-cookie"]).toBeUndefined();expect(finish).toHaveBeenCalledWith({token:TOKEN,password:"current password"},expect.anything());expect((await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish",headers:{origin},payload:{token:TOKEN}})).statusCode).toBe(400);}finally{await a.close();}});
 it.each([["MFA_RECOVERY_TOO_EARLY",409],["MFA_RECOVERY_PROOF_INVALID",401],["MFA_RECOVERY_INVALID",410],["MFA_RECOVERY_RATE_LIMITED",429]])("maps %s to %i",async(code,status)=>{const a=api({finish:async()=>{throw new EmailRecoveryError(code);}});try{const r=await a.inject({method:"POST",url:"/v1/auth/mfa-recovery/finish",headers:{origin},payload:{token:TOKEN,password:"current password"}});expect(r.statusCode).toBe(status);expect(r.json()).toEqual({error:code});}finally{await a.close();}});
});
