import { describe, expect, it } from 'vitest';
const native=await import('../../deploy/'+'preview-auth-dev/v1/native-peer.mjs');
const receipt=await import('../../deploy/'+'preview-auth-dev/v1/runtime-receipt.mjs');
const turnstile=await import('../../deploy/'+'preview-auth-dev/v1/turnstile-custody.mjs');
const hash='a'.repeat(64);
const publication={publicationId:'11111111-1111-4111-8111-111111111111',publicationKind:'GENERAL',baseRegisterVersion:'8',registerVersion:'12',requestSha256:hash,snapshotSha256:'b'.repeat(64),rowCount:68,recordedAt:'2026-10-06T12:00:00.000Z',outcome:'CREATED'};
const binding={sourceRevision:'a'.repeat(40),sourceTree:'b'.repeat(40),sourceManifestSha256:hash,operatorManifestSha256:hash,contractSha256:hash,apiMainSha256:hash};
const identity={pid:123,uid:456,bootId:'11111111-1111-4111-8111-111111111111',startTicks:'10001'};
const selection={REGISTER_VERSION:'12',DEBATEAI_DEPLOYMENT_MODE:'local'};
describe('preview operator boundaries',()=>{
 it('awaits the guard on EVERY query/connect before SQL and releases every acquired client',async()=>{const events:string[]=[];let acquired=0;const pool={async connect(){const n=++acquired;events.push('acquire'+n);return {async query(sql:string){events.push(sql+n);return {rows:[]};},release(){events.push('release'+n);}};},async end(){events.push('end');}};await native.withGuardedPool(pool,async()=>{await new Promise(r=>setTimeout(r,3));events.push('guard'+acquired);},async(p:any)=>{await p.query('one');const c=await p.connect();try{await c.query('two');}finally{c.release();}});expect(events).toEqual(['acquire1','guard1','one1','release1','acquire2','guard2','two2','release2','end']);});
 it('releases a failed guarded acquisition and ends the private pool without running pending SQL',async()=>{let sql=0,released=0,ended=0;const pool={async connect(){return{query(){sql++;},release(){released++;}};},async end(){ended++;}};await expect(native.withGuardedPool(pool,async()=>{throw Error('refused');},async(p:any)=>p.query('pending'))).rejects.toThrow();expect({sql,released,ended}).toEqual({sql:0,released:1,ended:1});});
 it('emits only after successful awaited same-process import with stable normalized selection',async()=>{let loaded=false;const events:unknown[]=[];await receipt.afterApiListen({binding,publication,identity,readSelection:()=>selection,importMain:async()=>{await new Promise(r=>setTimeout(r,3));loaded=true;},emit:(event:unknown)=>{expect(loaded).toBe(true);events.push(event);}});expect(events).toHaveLength(1);expect(events[0]).toMatchObject({...binding,...identity,selectedRegisterVersion:'12',service:'api',deploymentMode:'local',nativeSnapshotSha256:publication.snapshotSha256});expect(JSON.stringify(events)).not.toMatch(/path|secret|recipient|environment/i);});
 it.each(['import','selection'] as const)('emits nothing on %s failure',async kind=>{let version='12';const events:unknown[]=[];await expect(receipt.afterApiListen({binding,publication,identity,readSelection:()=>({...selection,REGISTER_VERSION:version}),importMain:async()=>{if(kind==='import')throw Error('boot');version='11';},emit:(x:unknown)=>events.push(x)})).rejects.toThrow();expect(events).toEqual([]);});
 it.each(['pid','uid','bootId','startTicks','sourceRevision','nativeSnapshotSha256','selectedRegisterVersion'] as const)('refuses independent readback mismatch in %s',async key=>{let event:any;await receipt.afterApiListen({binding,publication,identity,readSelection:()=>selection,importMain:async()=>{},emit:(x:unknown)=>{event=x;}});const observed={...event,[key]:key==='pid'||key==='uid'?999:'wrong'};expect(()=>receipt.verifyRuntimeReadback(event,observed,{unit:'debateai-preview-api.service',expectedUnit:'debateai-preview-api.service',rootMatched:true,listenerMatched:true,httpStatus:401,publication})).toThrow();});
 it('rejects stale unit/root/listener evidence even with a matching event',async()=>{let event:any;await receipt.afterApiListen({binding,publication,identity,readSelection:()=>selection,importMain:async()=>{},emit:(x:unknown)=>{event=x;}});for(const patch of [{unit:'other'},{rootMatched:false},{listenerMatched:false},{httpStatus:0}])expect(()=>receipt.verifyRuntimeReadback(event,event,{unit:'debateai-preview-api.service',expectedUnit:'debateai-preview-api.service',rootMatched:true,listenerMatched:true,httpStatus:401,publication,...patch})).toThrow();});
 it('accepts only exact approved preview credential envelope and zeroes extracted bytes after consumption',async()=>{const input={schema:'dialectical-turnstile-credentials-v1',environment:'preview',hostname:'v3-preview.dezbatere.ro',siteKey:'0x4AAAAAAFNg9KPm2tECytqZ',secretKey:'synthetic-secret-material-for-tests'};let held:Buffer|undefined;await turnstile.withExtractedSecret(Buffer.from(JSON.stringify(input)),(bytes:Buffer)=>{expect(bytes.toString()).toBe(input.secretKey);held=bytes;});expect(held?.every(n=>n===0)).toBe(true);});
 it.each([{environment:'production'},{environment:'PREVIEW'},{schema:'dialectical-turnstile-credentials-v2'},{hostname:'dezbatere.ro'},{siteKey:'test'},{secretKey:'1x'+'0'.repeat(35)},{extra:'unknown'}])('rejects credential domain or schema drift',async patch=>{const input={schema:'dialectical-turnstile-credentials-v1',environment:'preview',hostname:'v3-preview.dezbatere.ro',siteKey:'0x4AAAAAAFNg9KPm2tECytqZ',secretKey:'synthetic-secret-material-for-tests',...patch};await expect(turnstile.withExtractedSecret(Buffer.from(JSON.stringify(input)),()=>true)).rejects.toThrow(/^PREVIEW_TURNSTILE_REFUSED$/);});
});
