import { describe,expect,it } from 'vitest';
const plans=await import('../../deploy/'+'preview-auth-dev/v1/launch-plan.mjs');
const native=await import('../../deploy/'+'preview-auth-dev/v1/native-attestation.mjs');
const stage=await import('../../deploy/'+'preview-auth-dev/v1/stage-plan.mjs');
const digest='a'.repeat(64),revision='a'.repeat(40),tree='b'.repeat(40);
const publication={publicationId:'11111111-1111-4111-8111-111111111111',publicationKind:'GENERAL',baseRegisterVersion:'8',registerVersion:'12',requestSha256:digest,snapshotSha256:digest,rowCount:68,recordedAt:'2026-10-06T12:00:00Z'};
const file={path:'/opt/debateai-v3-preview/artifacts/v1/source.json',sha256:digest};
const plan={schema:'preview-auth-dev-launch-v1',service:'api',artifact:'candidate',sourceRoot:'/opt/debateai-v3-preview/releases/auth-dev-candidate-v1',sourceRevision:revision,sourceTree:tree,serviceUid:1001,serviceGid:1001,sourceManifest:file,nativeAttestation:{...file,path:'/opt/debateai-v3-preview/artifacts/v1/native.json'},uiBuild:null,publication,operatorManifestSha256:digest,environment:{path:'/etc/debateai-v3-preview/auth-dev-v1/api.env',root:'/etc/debateai-v3-preview/auth-dev-v1',uid:0,gid:1001,mode:0o640,parentUid:0},apiPort:'3101',uiPort:'3100',mailExecutable:'/opt/debateai-v3-preview/releases/auth-dev-candidate-v1/dialectical-engine/deploy/preview-auth-dev/v1/mail-handoff.mjs',mailFrom:'noreply@dezbatere.ro'};
describe('reviewed artifact and isolated stage plans',()=>{
 it('binds independent artifact roots to real native version, service identity and protected artifact references',()=>expect(plans.validateLaunchPlan(plan)).toEqual(plan));
 it.each([{sourceRoot:'/opt/debateai/dialectical-engine'},{sourceRevision:'bad'},{serviceUid:0},{artifact:'old106'},{service:'other'},{publication:{...publication,registerVersion:'8'}}])('refuses mismatched runtime plan',patch=>expect(()=>plans.validateLaunchPlan({...plan,...patch})).toThrow());
 it('keeps candidate and fallback distinct and a separate fixed PG18 cluster instead of a second live database',()=>{const value={schema:'preview-auth-dev-stage-v1',candidateRoot:plan.sourceRoot,fallbackRoot:'/opt/debateai-v3-preview/releases/auth-dev-fallback-v1',sourceRevision:revision,sourceTree:tree,cluster:'debateai-preview-auth-dev-stage-v1',database:'debateai_preview_auth_dev_stage',socket:'/run/debateai-preview-auth-dev-stage/postgresql',dataDirectory:'/var/lib/postgresql/18/preview-auth-dev-stage',port:55434,apiPort:55431,uiPort:55430,postgresMajor:18};expect(stage.validateStagePlan(value)).toEqual(value);for(const patch of [{fallbackRoot:value.candidateRoot},{port:5434},{socket:'/run/debateai-v3-preview/postgresql'},{dataDirectory:'/var/lib/postgresql/18/v3-preview'},{cluster:'debateai-v3-preview-15fccd74'}])expect(()=>stage.validateStagePlan({...value,...patch})).toThrow();});
 it('requires fresh truthful current-native evidence and never accepts a historical106 attestation relabel',()=>{const now=Date.parse('2026-10-06T12:00:01Z');const evidence={schema:'preview-auth-dev-native-v1',sourceRevision:revision,sourceTree:tree,nativeSourceSha256:digest,verifiedAt:'2026-10-06T12:00:00Z',postgresMajor:18,executorRole:'debateai_prod_migrator',executorOid:16388,ledgerOwnerOid:16388,billingOwnerOid:16388,defaultOwnerCount:6,ledgerCount:128,resolutionCount:1,forwardCount:1,catalogSha256:digest,ledgerSha256:digest,resolutionSha256:digest,forwardSha256:digest,cohortCount:0,capabilityCounts:{api:10,runner:11},currentContractVerified:true,publication};expect(native.validateNativeAttestation(evidence,{sourceRevision:revision,sourceTree:tree,nativeSourceSha256:digest,publication},now)).toEqual(evidence);expect(native.validateNativeAttestation({...evidence,publication:{...publication,recordedAt:'2026-10-06T14:00:00+02:00'}},{sourceRevision:revision,sourceTree:tree,nativeSourceSha256:digest,publication:{...publication,recordedAt:new Date(publication.recordedAt)}},now)).toBeTruthy();for(const patch of [{verifiedAt:'2026-10-06T11:55:00Z'},{executorOid:1},{forwardCount:0},{currentContractVerified:false},{sourceRevision:'c'.repeat(40)},{publication:{...publication,registerVersion:'13'}},{publication:{...publication,recordedAt:'2026-10-06T12:00:00.001Z'}}])expect(()=>native.validateNativeAttestation({...evidence,...patch},{sourceRevision:revision,sourceTree:tree,nativeSourceSha256:digest,publication},now)).toThrow();});
});

describe('complete actual-main stage receipts',()=>{
 const stagePlan={schema:'preview-auth-dev-stage-v1',...stage.STAGE,candidateRoot:'/opt/debateai-v3-preview/releases/auth-dev-candidate-v1',fallbackRoot:'/opt/debateai-v3-preview/releases/auth-dev-fallback-v1',sourceRevision:revision,sourceTree:tree};
 const proof={passed:true,receiptSha256:digest};
 const leaf=()=>({schema:'preview-auth-dev-full-runtime-v1',fullAccountMatrixAccepted:true,installedCustodyAccepted:false,genuineCloudflareAccepted:false,nativeMailAccepted:false,runnerStarted:false,behaviorProofs:Object.fromEntries(stage.STAGE_REQUIRED_PROOFS.filter((name:string)=>!name.endsWith('-listen')).map((name:string)=>[name,{...proof}]))});
 const value=()=>({schema:'preview-auth-dev-stage-result-v2',platform:'linux',sourceRevision:revision,sourceTree:tree,...stage.STAGE,candidateRoot:stagePlan.candidateRoot,fallbackRoot:stagePlan.fallbackRoot,proofs:Object.fromEntries(stage.STAGE_REQUIRED_PROOFS.map((name:string)=>[name,{...proof}])),receipts:{candidate:leaf(),fallback:leaf()},runnerStarted:false,realMailSent:false,providerNetworkCalled:false,fullAccountMatrixAccepted:true,installedCustodyAccepted:false,nativeMailAccepted:false,genuineCloudflareAccepted:false});
 it('requires every finite behavioral proof independently from both full main lifecycles',()=>expect(stage.assertStageCompletion(value(),stagePlan)).toBe(true));
 it.each(['candidate','fallback'])('refuses missing, failed, smoke or installed-claim %s leaf',(artifact)=>{
  for(const kind of ['missing','failed','smoke','custody']){const r:any=value();if(kind==='missing')delete r.receipts[artifact].behaviorProofs['legacy-primary-recovery'];if(kind==='failed')r.receipts[artifact].behaviorProofs['legacy-primary-recovery'].passed=false;if(kind==='smoke')r.receipts[artifact].schema='preview-auth-dev-runtime-exercise-v1';if(kind==='custody')r.receipts[artifact].installedCustodyAccepted=true;expect(()=>stage.assertStageCompletion(r,stagePlan)).toThrow('PREVIEW_STAGE_INCOMPLETE');}
 });
});
