import { afterEach, describe, it, expect, vi } from 'vitest';
import { createStaffWebAuthnBrowser, staffEncodeBase64url, staffDecodeBase64url } from '../../apps/ui/lib/staffWebAuthn.js';
import { fixture, b64, origin, rpId } from '../support/staffWebAuthnFixtures.js';
const f = fixture(), challenge = b64(Buffer.alloc(32, 1)), handle = b64(Buffer.alloc(32, 2));
const registration = { challenge_handle: handle, options: { challenge, rp: { id: rpId, name: 'Staff' }, user: { id: b64(f.handle), name: 'Hardware key', displayName: 'Hardware key' }, pubKeyCredParams: [{ type: 'public-key' as const, alg: -7 as const }, { type: 'public-key' as const, alg: -257 as const }] as [
            {
                type: 'public-key';
                alg: -7;
            },
            {
                type: 'public-key';
                alg: -257;
            }
        ], timeout: 300000 as const, attestation: 'none' as const, authenticatorSelection: { userVerification: 'required' as const, authenticatorAttachment: 'cross-platform' as const }, excludeCredentials: [{ type: 'public-key' as const, id: f.expected.credentialId, transports: ['usb' as const] }] } };
const authentication = { challenge_handle: handle, options: { challenge, rpId, timeout: 300000 as const, userVerification: 'required' as const, allowCredentials: [{ type: 'public-key' as const, id: f.expected.credentialId }] } };
const buffer = (bytes: Uint8Array) => Uint8Array.from(bytes).buffer;
const credential = (reg: boolean) => ({ id: f.expected.credentialId, rawId: buffer(f.id), type: 'public-key', response: reg ? { clientDataJSON: buffer(f.client('webauthn.create')), attestationObject: buffer(Buffer.from(f.registration.response.attestationObject, 'base64url')), getTransports: () => ['usb'], getPublicKey: () => { throw new Error('CONVENIENCE_AUTHORITY_USED'); } } : { clientDataJSON: buffer(f.client('webauthn.get')), authenticatorData: buffer(f.auth(5)), signature: buffer(Buffer.from(f.assertion({}).response.signature, 'base64url')), userHandle: buffer(f.handle) }, getClientExtensionResults: () => ({}) });
afterEach(() => vi.unstubAllGlobals());
function native(create: (input: CredentialCreationOptions) => Promise<unknown>, get: (input: CredentialRequestOptions) => Promise<unknown>) { vi.stubGlobal('navigator', { credentials: { create, get } }); vi.stubGlobal('PublicKeyCredential', class {
}); }
describe('native owned staff browser ceremony', () => {
    it('converts exact raw binary options and serializes registration without convenience key authority', async () => { let sent: CredentialCreationOptions | undefined; native(async (x) => { sent = x; return credential(true); }, async () => null); const browser = createStaffWebAuthnBrowser(), result = await browser.register(registration); expect(sent?.publicKey?.attestation).toBe('none'); expect(sent?.publicKey?.authenticatorSelection?.userVerification).toBe('required'); expect(b64(new Uint8Array(sent!.publicKey!.challenge as ArrayBuffer))).toBe(challenge); expect(result.response.attestationObject).toBe(f.registration.response.attestationObject); expect(result.response).not.toHaveProperty('publicKey'); expect(sent?.signal).toBeInstanceOf(AbortSignal); });
    it('requires explicit allowlist and user verification for authentication', async () => { let sent: CredentialRequestOptions | undefined; native(async () => null, async (x) => { sent = x; return credential(false); }); const result = await createStaffWebAuthnBrowser().authenticate(authentication); expect(sent?.publicKey?.userVerification).toBe('required'); expect(sent?.publicKey?.rpId).toBe(rpId); expect(sent?.publicKey?.allowCredentials).toHaveLength(1); expect(result.id).toBe(f.expected.credentialId); expect(result.response.userHandle).toBe(b64(f.handle)); });
    it('preserves byte views and rejects oversized/noncanonical inputs before native invocation', async () => { const offset = Uint8Array.of(9, 1, 2, 3, 9).subarray(1, 4); expect(staffEncodeBase64url(offset, 3)).toBe('AQID'); expect([...new Uint8Array(staffDecodeBase64url('AQID', 3))]).toEqual([1, 2, 3]); let calls = 0; native(async () => { calls++; return null; }, async () => { calls++; return null; }); for (const input of [{ ...authentication, options: { ...authentication.options, challenge: 'AB' } }, { ...authentication, options: { ...authentication.options, allowCredentials: [] } }, { ...authentication, options: { ...authentication.options, extensions: {} } }, { ...authentication, options: { ...authentication.options, userVerification: 'preferred' } }])
        await expect(createStaffWebAuthnBrowser().authenticate(input as never)).rejects.toThrow('STAFF_WEBAUTHN_INVALID'); expect(calls).toBe(0); expect(() => staffEncodeBase64url(new Uint8Array(769), 768)).toThrow(); });
    it('cancels active and replaced ceremonies even if native callback returns a credential later', async () => { const pending: Array<(value: unknown) => void> = []; const signals: AbortSignal[] = []; native(async () => null, x => new Promise(resolve => { pending.push(resolve); signals.push(x.signal!); })); const browser = createStaffWebAuthnBrowser(), first = browser.authenticate(authentication); const firstRejected = expect(first).rejects.toThrow('STAFF_WEBAUTHN_CANCELLED'); const second = browser.authenticate(authentication); const secondRejected = expect(second).rejects.toThrow('STAFF_WEBAUTHN_CANCELLED'); expect(signals[0]?.aborted).toBe(true); browser.cancel(); expect(signals[1]?.aborted).toBe(true); pending.forEach(resolve => resolve(credential(false))); await firstRejected; await secondRejected; });
    it('fails unsupported, null, native failures and oversized output without fallback', async () => { vi.stubGlobal('navigator', {}); await expect(createStaffWebAuthnBrowser().authenticate(authentication)).rejects.toThrow('STAFF_WEBAUTHN_UNSUPPORTED'); native(async () => null, async () => null); await expect(createStaffWebAuthnBrowser().authenticate(authentication)).rejects.toThrow(); native(async () => null, async () => { throw new Error('native detail'); }); await expect(createStaffWebAuthnBrowser().authenticate(authentication)).rejects.toThrow('STAFF_WEBAUTHN_FAILED'); native(async () => null, async () => ({ ...credential(false), response: { ...(credential(false).response), signature: buffer(new Uint8Array(513)) } })); await expect(createStaffWebAuthnBrowser().authenticate(authentication)).rejects.toThrow('STAFF_WEBAUTHN_INVALID'); });
});
