import { describe, it, expect } from 'vitest';
import { verifyRegistration, verifyAssertion } from '../../apps/api/src/staff/webauthn-verifier.js';
import { b64, cbor, digest, fixture, key } from '../support/staffWebAuthnFixtures.js';
describe('owned native WebAuthn verifier', () => {
    for (const alg of [-7, -257] as const)
        describe(String(alg), () => {
            it('accepts independently generated keys and genuine signatures', () => { const f = fixture(key(alg)); const registered = verifyRegistration(f.registration, f.expected); expect(registered).toEqual({ credentialId: f.expected.credentialId, publicKey: b64(f.k.wire), counter: 1, algorithm: alg }); expect(verifyAssertion(f.assertion({}), { publicKey: b64(f.k.wire), ...f.expected }, f.expected)).toEqual({ credentialId: f.expected.credentialId, counter: 1 }); });
            it('rejects forged signature, unrelated key and signed wrong-origin/challenge/RP', () => { const f = fixture(key(alg)), stored = { publicKey: b64(f.k.wire), ...f.expected }; for (const custom of [{ signature: Buffer.alloc(alg === -7 ? 64 : 256) }, { privateKey: key(alg).privateKey }, { client: Buffer.from(JSON.stringify({ type: 'webauthn.get', challenge: f.challenge, origin: 'https://other.test' })) }, { client: Buffer.from(JSON.stringify({ type: 'webauthn.get', challenge: b64(Buffer.alloc(32, 5)), origin: f.expected.origin })) }, { auth: Buffer.from(f.auth(5)).fill(9, 0, 32) }])
                expect(() => verifyAssertion(f.assertion(custom), stored, f.expected)).toThrow(); });
            it('enforces counter zero/zero and strictly increasing nonzero counters', () => { const f = fixture(key(alg)); expect(verifyAssertion(f.assertion({ auth: f.auth(5, 0) }), { publicKey: b64(f.k.wire), ...f.expected }, f.expected).counter).toBe(0); for (const n of [0, 1])
                expect(() => verifyAssertion(f.assertion({ auth: f.auth(5, n) }), { publicKey: b64(f.k.wire), ...f.expected, counter: 1 }, f.expected)).toThrow(); });
        });
    it('rejects cross-origin/top-origin, wrong type, malformed tokenBinding and duplicate client fields', () => { const f = fixture(), stored = { publicKey: b64(f.k.wire), ...f.expected }; for (const fields of [{ crossOrigin: true }, { topOrigin: 'https://x' }, { type: 'webauthn.create' }, { tokenBinding: { status: 'present' } }, { tokenBinding: { status: 'not-supported' } }, { crossOrigin: 'false' }])
        expect(() => verifyAssertion(f.assertion({ client: Buffer.from(JSON.stringify({ type: 'webauthn.get', challenge: f.challenge, origin: f.expected.origin, ...fields })) }), stored, f.expected)).toThrow(); });
    it('binds rawId, ID, selected stored credential and opaque user handle', () => { const f = fixture(), stored = { publicKey: b64(f.k.wire), ...f.expected }; expect(() => verifyAssertion({ ...f.assertion({}), id: 'AQ' }, stored, f.expected)).toThrow(); const a = f.assertion({}); expect(() => verifyAssertion({ ...a, response: { ...a.response, userHandle: b64(Buffer.alloc(32)) } }, stored, f.expected)).toThrow(); expect(verifyAssertion({ ...a, response: { ...a.response, userHandle: null } }, stored, f.expected).counter).toBe(1); expect(() => verifyAssertion(a, { ...stored, credentialId: 'AQ' }, f.expected)).toThrow(); });
    it('requires none attestation/empty statement and credential ID in authentic data', () => { const f = fixture(); for (const map of [new Map<string, unknown>([['fmt', 'packed'], ['attStmt', new Map()], ['authData', f.regAuth]]), new Map<string, unknown>([['fmt', 'none'], ['attStmt', new Map([[1, 1]])], ['authData', f.regAuth]])])
        expect(() => verifyRegistration({ ...f.registration, response: { ...f.registration.response, attestationObject: b64(cbor(map)) } }, f.expected)).toThrow(); expect(() => verifyRegistration({ ...f.registration, id: 'AQ', rawId: 'AQ' }, f.expected)).toThrow(); });
    it('rejects algorithm/curve/type confusion, private COSE members and RSA noncanonical unsigned values', () => { const f = fixture(); for (const mutate of [(m: Map<number, unknown>) => m.set(3, -257), (m: Map<number, unknown>) => m.set(-1, 2), (m: Map<number, unknown>) => m.set(-4, Buffer.alloc(32)), (m: Map<number, unknown>) => m.set(-2, Buffer.alloc(31))]) {
        const map = new Map(f.k.map);
        mutate(map);
        expect(() => verifyAssertion(f.assertion({}), { publicKey: b64(cbor(map)), ...f.expected }, f.expected)).toThrow();
    } const r = fixture(key(-257)); for (const map of [new Map(r.k.map).set(-2, Buffer.from([0, 1, 0, 1])), new Map(r.k.map).set(-2, Buffer.from([2])), new Map(r.k.map).set(-1, Buffer.alloc(128, 255))])
        expect(() => verifyAssertion(r.assertion({}), { publicKey: b64(cbor(map)), ...r.expected }, r.expected)).toThrow(); });
    it('rejects malformed/trailing DER, RSA wrong length and oversize wrappers/fields', () => { const f = fixture(); for (const signature of [Buffer.from([0x30, 0]), Buffer.concat([Buffer.from(f.assertion({}).response.signature, 'base64url'), Buffer.from([0])]), Buffer.alloc(73)])
        expect(() => verifyAssertion(f.assertion({ signature }), { publicKey: b64(f.k.wire), ...f.expected }, f.expected)).toThrow(); const r = fixture(key(-257)); expect(() => verifyAssertion(r.assertion({ signature: Buffer.alloc(255) }), { publicKey: b64(r.k.wire), ...r.expected }, r.expected)).toThrow(); expect(() => verifyRegistration({ ...f.registration, response: { ...f.registration.response, clientDataJSON: b64(Buffer.alloc(4097)) } }, f.expected)).toThrow(); expect(() => verifyRegistration({ ...f.registration, response: { ...f.registration.response, attestationObject: 'A'.repeat(32769) } }, f.expected)).toThrow(); });
    it('verifies supported RSA4096 and exact credential/client bounds using original BOM bytes', () => { const rsa = fixture(key(-257, 4096)), stored = { ...rsa.expected, publicKey: b64(rsa.k.wire) }, client = Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), rsa.client('webauthn.get')]); expect(verifyAssertion(rsa.assertion({ client }), stored, rsa.expected).counter).toBe(1); const f = fixture(key(), 1, Buffer.alloc(768, 7)); expect(verifyRegistration(f.registration, f.expected).credentialId).toHaveLength(1024); const fields = { type: 'webauthn.get', challenge: f.challenge, origin: f.expected.origin, future: '' }, base = JSON.stringify(fields), exact = Buffer.from(JSON.stringify({ ...fields, future: 'a'.repeat(4096 - Buffer.byteLength(base)) })); expect(exact.length).toBe(4096); expect(verifyAssertion(f.assertion({ client: exact }), { ...f.expected, publicKey: b64(f.k.wire) }, f.expected).counter).toBe(1); expect(() => verifyAssertion(f.assertion({ client: Buffer.concat([exact, Buffer.from(' ')]) }), { ...f.expected, publicKey: b64(f.k.wire) }, f.expected)).toThrow('STAFF_WEBAUTHN_INVALID'); });
    it('rejects oversized decoded fields and aggregate/serialized wrappers before trust', () => { const f = fixture(); for (const change of [{ attestationObject: b64(Buffer.alloc(16385)) }, { authenticatorData: b64(Buffer.alloc(8193)) }, { publicKey: b64(Buffer.alloc(8193)) }, { clientDataJSON: b64(Buffer.alloc(4097)) }, { publicKey: b64(Buffer.alloc(8192)), authenticatorData: b64(Buffer.alloc(8192)), attestationObject: b64(Buffer.alloc(16384)) }])
        expect(() => verifyRegistration({ ...f.registration, response: { ...f.registration.response, ...change } }, f.expected)).toThrow('STAFF_WEBAUTHN_INVALID'); const oversized = fixture(key(), 1, Buffer.alloc(769)); expect(() => verifyRegistration(oversized.registration, oversized.expected)).toThrow('STAFF_WEBAUTHN_INVALID'); });
    it('normalizes mismatched decoded ID lengths and invalid configured origin to one error', () => { const f = fixture(); expect(() => verifyRegistration({ ...f.registration, id: 'AQ', rawId: 'AQ' }, f.expected)).toThrow('STAFF_WEBAUTHN_INVALID'); expect(() => verifyRegistration(f.registration, { ...f.expected, origin: 'invalid' })).toThrow('STAFF_WEBAUTHN_INVALID'); });
    it('ignores contract permitted non-authoritative browser convenience data', () => { const f = fixture(); expect(verifyRegistration({ ...f.registration, response: { ...f.registration.response, publicKey: b64(Buffer.from('fake')), publicKeyAlgorithm: -257, authenticatorData: b64(Buffer.from('fake')) }, clientExtensionResults: { credProps: { rk: true } } }, f.expected).algorithm).toBe(-7); });
});
