/**
 * GENERATED by `apps/ui/scripts/generate-legal-data.mjs` from `apps/ui/legal/pt/terms-of-service.md`.
 * Do not edit by hand: edit the draft and run `pnpm generate:legal`.
 *
 * The document as DATA. The modal that shows it renders from this module and holds no legal
 * prose of its own. Square brackets are the draft's own marks for what counsel still has to
 * fill in; they are rendered verbatim so the product never claims a fact the draft does not.
 */

import type { LegalDocument, LegalJump, LegalSection } from "../../legalDocument.js";

export const TERMS_JUMP: readonly LegalJump[] = [
  { label: "QUEM SOMOS", target: "terms-section-01" },
  { label: "ACEITAÇÃO", target: "terms-section-03" },
  { label: "O QUE É", target: "terms-section-05" },
  { label: "A SUA CONTA", target: "terms-section-06" },
  { label: "UTILIZAÇÃO ACEITÁVEL", target: "terms-section-07" },
  { label: "O SEU CONTEÚDO", target: "terms-section-08" },
  { label: "PUBLICAÇÃO", target: "terms-section-09" },
  { label: "DENÚNCIAS", target: "terms-section-10" },
  { label: "RESPONSABILIDADE", target: "terms-section-15" },
  { label: "LEI APLICÁVEL", target: "terms-section-18" }
];

export const TERMS_SECTIONS: readonly LegalSection[] = [
  {
    no: "00",
    title: "Em resumo",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Tem de ter pelo menos 18 anos. A DebateAI constrói argumentos com modelos de IA e tudo o que gera pode estar errado — não constitui aconselhamento. Os seus debates são privados, a menos que os publique; se os publicar, qualquer pessoa poderá lê-los. O texto que envia é transmitido aos fornecedores de IA indicados no nosso Registo de Fornecedores e não é utilizado para treinar modelos. Denuncie conteúdos ilegais através de [abuse@dezbatere.ro], tenha ou não uma conta. É aplicável a lei romena, mas as proteções locais de que beneficia enquanto consumidor mantêm-se." }
    ]
  },
  {
    no: "01",
    title: "Quem somos e como nos contactar",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "A DebateAI é operada pela DebateAIRO S.R.L., uma sociedade registada na Roménia." },
      {
        kind: "list",
        items: [
        "Sede social — [street, number, sector, postal code], Bucareste, Roménia",
        "Número do Registo Comercial — [J40/…/…]",
        "Código único de registo (CUI) — […] · IVA: [RO… / not VAT-registered]",
        "Capital social — [RON …]",
        "Contacto geral — [hello@dezbatere.ro]",
        "Notificações legais — [legal@dezbatere.ro]",
        "Privacidade e proteção de dados — privacy@dezbatere.ro",
        "Denúncia de conteúdos ilegais — [abuse@dezbatere.ro] — consulte a secção 10",
        "Ponto de contacto para autoridades — [dsa@dezbatere.ro] — romeno e inglês",
        "Representantes noutros países — Indicados no Anexo A relativamente às regiões em que nomeámos um representante"
        ]
      },
      { kind: "p", text: "Estes dados também são apresentados permanentemente no sítio, em [dezbatere.ro/legal]. Pode sempre contactar uma pessoa, e não apenas o nosso assistente; a secção 10 explica como." }
    ]
  },
  {
    no: "02",
    title: "Onde disponibilizamos a DebateAI",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Disponibilizamos a DebateAI a pessoas que residam na [the European Union and the European Economic Area] [and: the United Kingdom / the United States / Canada / Australia and New Zealand / Singapore / Japan / South Korea]. Não a disponibilizamos noutros locais. Se residir fora desses países, poderá conseguir aceder ao sítio, mas não dirigimos o serviço a si, não aceitamos pagamentos seus e estes Termos e a nossa Política de Privacidade não estão adaptados à legislação do seu país. O Anexo A estabelece o que se aplica em cada região que servimos." }
    ]
  },
  {
    no: "03",
    title: "Aceitação destes Termos",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Aceita estes Termos ao assinalar a caixa «Li e aceito os Termos de Serviço» e clicar em Criar conta. Isto cria um contrato entre si e a DebateAIRO S.R.L. Os Termos incluem as regras de utilização aceitável da secção 7, as regras de publicação da secção 9, as disposições sobre responsabilidade da secção 15, as disposições sobre lei aplicável e litígios da secção 18 e, caso resida nos Estados Unidos, a convenção de arbitragem constante do Anexo A.3. Conservamos um registo da versão que aceitou e do momento em que a aceitou, conforme explicado na nossa Política de Privacidade." },
      { kind: "p", text: "A nossa Política de Privacidade, disponível em [dezbatere.ro/privacy], explica como tratamos os dados pessoais. Trata-se de informação que lhe devemos prestar, não de um contrato que aceite, e nada nestes Termos a transforma em consentimento para o tratamento. A nossa Política de Cookies, disponível em [dezbatere.ro/cookies], e o nosso Registo de Fornecedores de IA, disponível em [dezbatere.ro/providers], fazem parte destes Termos por remissão." },
      { kind: "p", text: "Antes de celebrar eletronicamente qualquer contrato connosco, a interface mostra-lhe as etapas envolvidas, permite-lhe rever e corrigir o que introduziu antes de o enviar e informa-o dos idiomas em que o contrato pode ser celebrado. Estes Termos são disponibilizados num formato que pode guardar e imprimir, enviamos-lhe por correio eletrónico a versão que aceitou e pode solicitar uma cópia a qualquer momento. Nada nestes Termos limita os direitos de que beneficia ao abrigo do direito romeno ou da UE em matéria de consumo, ou do direito do país onde reside, que não possam ser limitados por contrato." }
    ]
  },
  {
    no: "04",
    title: "Quem pode utilizar a DebateAI",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Tem de ter pelo menos 18 anos para criar uma conta e confirma esse facto quando se regista. A DebateAI não se destina a crianças e não a disponibilizamos conscientemente a menores de 18 anos. Se soubermos que uma conta pertence a uma pessoa com menos de 18 anos, encerrá-la-emos. Algumas regiões exigem mais do que uma confirmação; o Anexo A indica o que se aplica em cada local." },
      { kind: "p", text: "Tem de possuir capacidade jurídica para celebrar este contrato. Se utilizar a DebateAI em nome de uma organização, confirma que está autorizado a vinculá-la, passando «utilizador» a designar essa organização." },
      { kind: "p", text: "Qualquer pessoa pode ler um debate que tenha sido publicado. A leitura não exige uma conta, mas constitui utilização do serviço, sendo-lhe aplicáveis as secções 7, 15, 16 e 18." }
    ]
  },
  {
    no: "05",
    title: "O que faz a DebateAI e o que não é",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "O utilizador envia uma pergunta ou uma alegação. A DebateAI envia-a a vários modelos de IA de terceiros, que constroem em seu redor um grafo argumentativo: alegações, contra-alegações, críticas, referências a elementos de prova, pontuações e um veredito com uma faixa de confiança. Pode contestar alegações individuais, pedir que um ponto seja investigado mais aprofundadamente e decidir se pretende publicar o resultado." },
      { kind: "p", text: "Tudo num debate é gerado por IA. Os argumentos, as críticas, as referências a elementos de prova, as pontuações, os vereditos e as respostas do assistente de apoio são gerados por máquina. Podem estar errados, incompletos ou desatualizados, ou apresentar erros com aparente segurança, e podem refletir enviesamentos dos modelos. Nenhuma pessoa os revê antes de lhe serem apresentados ou publicados, e nenhuma pessoa identificada assume responsabilidade editorial pelos mesmos. O conteúdo gerado é identificado como gerado por IA no produto, nas páginas publicadas e nas exportações." },
      { kind: "p", text: "A DebateAI não presta aconselhamento. Não presta aconselhamento jurídico, médico, financeiro, fiscal, psicológico, de segurança ou qualquer outro aconselhamento profissional, e um veredito não constitui uma constatação de facto. Não utilize um debate como base para uma decisão relevante para a sua saúde, segurança, situação financeira ou jurídica, ou para o bem-estar de terceiros, sem consultar fontes primárias e, quando adequado, um profissional qualificado. Uma faixa de confiança elevada significa que os modelos consideraram a interpretação bem assente com base nos materiais que analisaram; não garante que seja verdadeira." },
      { kind: "p", text: "Aquilo a que nos comprometemos. Prestaremos o serviço com o cuidado e a competência razoavelmente exigíveis e em conformidade com a descrição que publicamos. Quando a lei lhe conceder uma garantia de que o serviço está em conformidade com a respetiva descrição e é adequado à sua finalidade habitual, essa garantia aplica-se e nada nestes Termos a elimina. O que não prometemos é que um determinado resultado seja exato: isso é uma característica do conteúdo gerado, não do funcionamento do serviço." },
      { kind: "p", text: "Os modelos mudam. Podemos adicionar, remover ou substituir os modelos de IA que utilizamos e alterar a forma como o motor compõe uma resposta. A secção 14 explica quando uma alteração lhe confere direitos." }
    ]
  },
  {
    no: "06",
    title: "A sua conta",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Regista-se com um endereço de correio eletrónico, uma palavra-passe, um endereço de correio eletrónico de recuperação e autenticação de dois fatores, que é obrigatória. Escolhe um pseudónimo, que é o nome apresentado em tudo o que publicar; os pseudónimos não podem ser alterados depois de definidos. Mantenha em segurança a sua palavra-passe, a aplicação de autenticação e os códigos de recuperação. É responsável pela atividade realizada através da sua conta, salvo quando resulte de uma falha nossa." },
      { kind: "p", text: "Só pode ser titular de uma conta, salvo acordo em contrário. Não a partilhe, venda ou transfira." },
      { kind: "p", text: "Se perder o acesso, a recuperação da conta seguirá o procedimento publicado no produto, que inclui períodos de espera destinados a dificultar a apropriação indevida da conta. Podemos recusar um pedido de recuperação quando não conseguirmos determinar razoavelmente que provém de si." },
      { kind: "p", text: "Pode encerrar a sua conta a qualquer momento em Definições → Conta. O encerramento produz efeitos após um período de tolerância de 7 dias, durante o qual pode cancelá-lo, e notificá-lo-emos através de cada um dos seus canais registados. A secção 11 explica o que o encerramento elimina e o que não elimina." }
    ]
  },
  {
    no: "07",
    title: "Utilização aceitável",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Estas regras aplicam-se ao que envia, à forma como utiliza o serviço e ao que publica." },
      { kind: "p", text: "Não envie dados pessoais de outras pessoas. Coloque questões sobre temas, argumentos e assuntos públicos, e não sobre pessoas singulares privadas identificáveis. Não inclua nomes, contactos, números de identificação, imagens, dados de saúde ou financeiros, nem outros elementos que identifiquem alguém, e não utilize a DebateAI para construir um caso, perfil ou dossiê sobre uma pessoa. São aceitáveis perguntas sobre figuras públicas no exercício da sua função pública; não são aceitáveis perguntas dirigidas a uma pessoa singular privada. Se enviar esses dados, será responsável por eles e poderemos remover o conteúdo." },
      { kind: "p", text: "As suas próprias informações sensíveis. As perguntas que coloca podem incidir sobre a sua própria saúde, convicções, orientação política ou outras matérias sensíveis. Prestou consentimento para esse tratamento quando se registou. Se residir num local com regras específicas relativas a dados de saúde, o Anexo A poderá remetê-lo para um aviso separado." },
      { kind: "p", text: "Não envie nem publique conteúdos ilícitos, incluindo conteúdos difamatórios, que incitem à violência ou ao ódio, assediem ou ameacem, constituam imagens íntimas partilhadas sem consentimento, violem direitos de propriedade intelectual ou a confidencialidade, divulguem segredos comerciais, constituam material de abuso sexual de crianças ou violem sanções ou controlos de exportação." },
      { kind: "p", text: "Não utilize a DebateAI para enganar. Não apresente resultados gerados como tendo sido escritos por uma pessoa quando isso for enganoso, não lhes retire a identificação de conteúdo gerado por IA, nem os utilize para fabricar uma aparência de consenso, elementos de prova falsos ou uma usurpação de identidade." },
      { kind: "p", text: "Não ataque o serviço. É proibido o acesso automatizado, a recolha automatizada, o varrimento ou a extração em massa de debates publicados além do permitido pelo nosso ficheiro de robots; é proibido contornar limites de utilização, autenticação ou controlos de publicação; tentar extrair comandos ou instruções de sistema; realizar injeção de comandos destinada a fazer com que o motor ignore as suas limitações; ou efetuar sondagens ou testes de carga sem a nossa autorização escrita." },
      { kind: "p", text: "Não revenda nem altere a marca do serviço, nem o utilize para construir um motor concorrente, nomeadamente usando os resultados como dados de treino, sem o nosso acordo escrito." },
      { kind: "p", text: "Não utilize a DebateAI para tomar decisões sobre a saúde, segurança, direitos legais, emprego, crédito, habitação ou estatuto de imigração de uma pessoa. Não foi concebida para esse efeito e os seus resultados não constituem uma base segura para tais decisões." },
      { kind: "p", text: "Legislação do local onde publica. É responsável por garantir que tudo o que publica respeita a legislação do país onde se encontra. Podemos restringir a publicação de determinados temas em certas regiões." },
      { kind: "p", text: "Se tiver dúvidas sobre se algo é permitido, pergunte-nos antes de o publicar." }
    ]
  },
  {
    no: "08",
    title: "O seu conteúdo e os fornecedores de IA que o tratam",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "O seu conteúdo continua a pertencer-lhe. Mantém quaisquer direitos que detenha sobre as perguntas, alegações, anotações e contestações que envia. Concede-nos uma licença não exclusiva, mundial e gratuita para alojar, armazenar, reproduzir, adaptar e tratar esse conteúdo para efeitos de funcionamento do serviço: executar o debate, armazená-lo para que possa voltar a abri-lo e reproduzi-lo, prestar apoio, cumprir as nossas obrigações legais e — apenas se optar por publicar — prosseguir as finalidades da secção 9. Esta licença termina quando o conteúdo é eliminado, salvo na medida exigida pela secção 9 ou pela lei." },
      { kind: "p", text: "Não treinamos modelos com o seu conteúdo. Não treinamos modelos com o seu conteúdo e os nossos contratos com fornecedores de IA excluem a utilização do seu conteúdo para treinar ou melhorar os respetivos modelos. [Publish this paragraph only once every active provider route has been verified against its signed terms and account settings — see the Provider Register.]" },
      { kind: "p", text: "Como o seu conteúdo chega aos fornecedores de IA. Para executar um debate, enviamos texto a um ou mais fornecedores externos de modelos. O que um fornecedor recebe é a sua pergunta, as anotações de orientação que definiu e as alegações que o motor compõe durante o debate — pelo que o fornecedor vê texto derivado e construído em torno do que escreveu, e não apenas as suas palavras originais. Nunca recebe o seu endereço de correio eletrónico, os identificadores da sua conta, os registos de sessão ou os dados de pagamento." },
      { kind: "p", text: "Quais os fornecedores e onde operam. O nosso Registo de Fornecedores de IA, disponível em [dezbatere.ro/providers], faz parte destes Termos. Indica, para cada fornecedor que podemos utilizar: a respetiva entidade jurídica e país; o que recebe e porquê; onde efetua o tratamento; as respetivas condições de conservação; se está ativa a conservação zero de dados para o ponto terminal que utilizamos; se pode utilizar dados de entrada para treino ao abrigo do nosso contrato; o mecanismo de transferência em que nos baseamos; e a data em que verificámos pela última vez cada entrada. Os fornecedores podem estar localizados fora do seu país e fora do Espaço Económico Europeu. A nossa Política de Privacidade explica as salvaguardas." },
      { kind: "p", text: "Três coisas diferentes. «Não utilizado para treinar modelos», «conservado durante um período limitado por motivos de segurança, prevenção de abusos ou razões legais» e «conservação zero de dados — não persistem após o tratamento» são situações diferentes. Quando um fornecedor conserva comandos durante um período limitado, o Registo indica por quanto tempo e porquê. Quando está ativa a conservação zero de dados, o Registo indica esse facto e as funcionalidades a que se aplica. Não afirmaremos que um conteúdo não é conservado quando este for efetivamente conservado." },
      { kind: "p", text: "Resultados. Na relação entre o utilizador e nós, pode utilizar os resultados dos seus próprios debates para qualquer finalidade lícita e não reivindicamos a titularidade do texto gerado. Tenha em conta que os resultados gerados podem não ser protegidos por direitos de autor em muitas jurisdições; que podem ser gerados resultados semelhantes para outros utilizadores; que os resultados podem reproduzir ou assemelhar-se a materiais de terceiros; e que alguns materiais de origem obtidos por um fornecedor de IA podem estar sujeitos a restrições de reutilização. É responsável por efetuar verificações antes de se basear nos resultados ou de os voltar a publicar." }
    ]
  },
  {
    no: "09",
    title: "Publicação de um debate",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Os debates são privados por predefinição. Nada do que criar será visível para qualquer outra pessoa, a menos que o publique." },
      { kind: "p", text: "Efeito da publicação. A publicação é uma ação deliberada, confirmada separadamente. Quando publica, criamos uma versão publicada imutável do debate e tornamo-la legível por qualquer pessoa, sem necessidade de uma conta. [Search engines may index it. / Published debates are not indexed by search engines unless you choose to allow it.] A versão publicada mostra o seu pseudónimo, a sua pergunta tal como a escreveu, a árvore de argumentos, as pontuações, o veredito e a faixa de confiança, e apresenta uma indicação visível de que o conteúdo é gerado por IA. Não mostra o seu endereço de correio eletrónico, os registos de sessão ou o histórico da sua conta." },
      { kind: "p", text: "Na prática, a publicação é efetivamente irreversível. Quando um debate se torna público, outras pessoas podem lê-lo, citá-lo, fazer capturas de ecrã, arquivá-lo e guardá-lo em cache. O cancelamento da publicação remove-o da DebateAI e destrói a chave da nossa cópia, mas não permite alcançar cópias que já existam noutros locais. Não publique nada que não queira ver permanentemente associado ao seu pseudónimo." },
      { kind: "p", text: "Debates publicados quando encerra a sua conta. Quando a sua conta for encerrada, removeremos do acesso público todos os debates que tenha publicado sem demora injustificada e, em qualquer caso, no prazo de 30 dias, salvo se a lei nos obrigar a agir mais rapidamente ou a conservar um elemento específico. As cópias efetuadas por terceiros antes da remoção estão fora do nosso controlo. Se pretender que um debate permaneça disponível depois de sair, descarregue-o primeiro. [This is Option B from the earlier drafts, as recommended in the second-opinion review. It is a product change to implement, not a description of the current system, which keeps published snapshots readable after erasure.]" },
      { kind: "p", text: "Podemos sempre retirar conteúdos publicados. Podemos remover ou restringir o acesso a um debate publicado quando a lei o exigir, quando um tribunal ou uma autoridade competente o ordenar, ou quando viole estes Termos ou seja ilegal. Nada nesta secção nos impede de agir em resposta a uma notificação válida nos termos da secção 10 e nada nesta secção constitui uma promessa de que um debate publicado permanecerá disponível." },
      { kind: "p", text: "Licença relativa a conteúdo publicado. A publicação concede-nos uma licença não exclusiva, mundial e gratuita para alojar, armazenar, reproduzir, apresentar e disponibilizar publicamente a versão publicada, bem como para permitir que terceiros a leiam e citem, enquanto permanecer publicada. Esta licença existe para nos permitir operar as páginas públicas; não nos permite vender o seu conteúdo nem licenciá-lo para o produto de terceiros." },
      { kind: "p", text: "Se um debate for sobre si. Se um debate publicado contiver dados pessoais a seu respeito, for difamatório ou de outro modo ilícito, pode pedir a sua remoção, tenha ou não uma conta, através da secção 10 ou de privacy@dezbatere.ro. Damos seguimento a pedidos fundamentados e não exigimos que se registe para apresentar um pedido." }
    ]
  },
  {
    no: "10",
    title: "Denúncia de conteúdos, moderação e reclamações",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Qualquer pessoa pode denunciar conteúdos. Não necessita de uma conta. Escreva para [abuse@dezbatere.ro] ou utilize o controlo Denunciar em qualquer debate publicado. Para que possamos agir, indique-nos: por que motivo considera que o conteúdo é ilegal ou viola estes Termos, com pormenor suficiente para compreendermos o fundamento da denúncia; a localização exata — o URL completo e, se possível, a passagem; o seu nome e endereço de correio eletrónico (não exigidos para denúncias de material de abuso sexual de crianças); e que acredita, de boa-fé, que a sua denúncia é exata e completa." },
      { kind: "p", text: "Acusamos a receção de todas as denúncias sem demora injustificada. Tratamos as denúncias de forma atempada, diligente, não arbitrária e objetiva, comunicamos-lhe a nossa decisão e indicamos-lhe como a pode contestar. Quando utilizamos meios automatizados para tratar uma denúncia ou tomar uma decisão sobre a mesma, informamo-lo desse facto. Atuamos relativamente às denúncias de imagens íntimas partilhadas sem consentimento no prazo de 48 horas após um pedido válido." },
      { kind: "p", text: "Dois tipos de decisão automatizada, mantidos separados." },
      {
        kind: "list",
        items: [
        "Decisões no interior do motor. O motor toma decisões automáticas sobre argumentos: pode recusar responder a uma pergunta, parar num percurso terminal — por exemplo, quando uma pergunta assenta num pressuposto falso ou constitui uma questão de valores e não uma questão empírica — limitar uma faixa de confiança quando não estiver disponível uma crítica independente, ou assinalar uma resposta como defeituosa quando o texto gerado não tiver passado na verificação de conformidade. Estas decisões correspondem ao funcionamento do produto tal como concebido; são-lhe visíveis no debate e não são decisões sobre si.",
        "Decisões de moderação sobre conteúdos e contas. A remoção ou restrição de um debate publicado, ou a suspensão ou encerramento de uma conta, é uma decisão que tomamos ao abrigo destes Termos ou da lei. Uma pessoa intervém em todas as decisões dessa natureza que afetem a sua conta. A secção 11 descreve os fundamentos."
        ]
      },
      { kind: "p", text: "Exposição dos motivos. Sempre que removemos ou restringimos a visibilidade do seu conteúdo, ou suspendemos ou encerramos a sua conta, fornecemos-lhe uma exposição dos motivos: o que fizemos e o respetivo alcance, os factos em que nos baseámos e se provêm de uma denúncia ou das nossas próprias verificações, se foram utilizados meios automatizados, o fundamento legal ou contratual e a forma como pode contestar a decisão." },
      { kind: "p", text: "Reclamação de uma decisão. Se discordar de uma decisão de moderação, responda à exposição dos motivos ou escreva para [appeals@dezbatere.ro] no prazo de seis meses. Uma pessoa que não tenha participado na decisão original procederá à sua revisão e comunicar-lhe-emos o resultado, com a respetiva fundamentação. Isto não afeta o seu direito de recorrer aos tribunais ou a mecanismos de resolução alternativa de litígios ao abrigo da secção 18. A via de reclamação aceita igualmente reclamações de que não demos seguimento a uma denúncia, de que um conteúdo foi indevidamente removido, de que uma conta foi indevidamente restringida ou de que uma ferramenta automatizada afetou indevidamente o seu conteúdo." },
      { kind: "p", text: "Contactar uma pessoa. O nosso assistente de apoio é um sistema de IA e identifica-se como tal. Pode pedir para falar com uma pessoa a qualquer momento, e todas as conversas com o apoio disponibilizam essa opção. Não dependemos exclusivamente de ferramentas automatizadas para comunicar consigo." },
      { kind: "p", text: "Risco grave para a vida ou a segurança. Se tomarmos conhecimento de informações que sugiram a prática de uma infração penal que envolva uma ameaça à vida ou à segurança de alguém, informaremos as autoridades competentes." }
    ]
  },
  {
    no: "11",
    title: "Suspensão e cessação",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Pelo utilizador. Encerre a sua conta a qualquer momento nas Definições, conforme descrito na secção 6. Não necessita de apresentar um motivo." },
      { kind: "p", text: "Por nós. Podemos suspender ou encerrar a sua conta, ou remover ou restringir o seu conteúdo, quando: violar substancialmente estes Termos, em especial a secção 7; o seu conteúdo for ilegal, ou a lei, um tribunal ou uma autoridade nos obrigar a agir; a sua utilização ameaçar a segurança, a integridade ou a disponibilidade do serviço, ou os direitos de terceiros; a sua conta estiver inativa há [24 months] e o tivermos notificado; ou deixarmos de prestar o serviço, ou de o prestar no seu país." },
      { kind: "p", text: "Salvo quando a violação for grave, a lei exigir uma ação imediata ou um atraso puder causar danos, informá-lo-emos do problema e dar-lhe-emos uma oportunidade razoável para o corrigir antes de suspendermos ou encerrarmos a conta. Forneceremos sempre uma exposição dos motivos nos termos da secção 10, e poderá contestar a decisão." },
      { kind: "p", text: "Se encerrarmos totalmente o serviço ou deixarmos de o disponibilizar no seu país, daremos um pré-aviso de pelo menos 30 dias, reembolsaremos qualquer montante pré-pago relativo ao período posterior ao encerramento e disponibilizaremos previamente uma forma de exportar os seus debates." },
      { kind: "p", text: "Efeitos do encerramento. Quando uma conta é encerrada, destruímos as chaves de cifragem dos dados da sua conta e dos seus debates privados, tornando-os permanentemente ilegíveis, eliminamos o registo da sua conta e removemos os seus debates publicados do acesso público, conforme descrito na secção 9. Alguns elementos subsistem, e deve saber quais: entradas nos nossos registos de auditoria e segurança, que são exclusivamente aditivos, conservadas para cumprirmos as nossas próprias obrigações legais e de segurança; registos que a lei nos obriga a conservar, incluindo registos de aceitação e consentimento; e, relativamente a um pequeno número de debates antigos anteriores ao nosso sistema de cifragem, registos cuja eliminação é mais limitada — informá-lo-emos se isto se aplicar à sua conta. A Política de Privacidade descreve tudo isto em termos de proteção de dados e explica o seu direito ao apagamento." },
      { kind: "p", text: "As secções 8 (relativamente a conteúdo já publicado), 15, 16 e 18 mantêm-se em vigor após a cessação." }
    ]
  },
  {
    no: "12",
    title: "Planos pagos",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "[Inactive until a paid plan exists. Do not launch a paid tier without completing every bracket here and the checkout interface it describes.]" },
      { kind: "p", text: "A DebateAI oferece um plano gratuito. Está [is / will be] disponível um plano Premium pago, que desbloqueia o conjunto completo de modelos e lhe permite definir diretamente os parâmetros do debate." },
      { kind: "p", text: "Antes do pagamento, mostramos-lhe, imediatamente acima do botão de pagamento: o plano; o preço total, incluindo os impostos aplicáveis; o período de faturação; o facto de o plano se renovar automaticamente até ser cancelado; a data em que termina qualquer período experimental gratuito e o montante que lhe será então cobrado; e como cancelar. Confirma as condições de renovação assinalando uma caixa separada. O botão contém a indicação Subscrever e pagar (em romeno, Comandă cu obligație de plată). Enviamos-lhe uma confirmação num suporte duradouro que contém as mesmas informações, estes Termos e o formulário de retratação." },
      { kind: "p", text: "Lembretes. Enviamos-lhe uma mensagem de correio eletrónico pelo menos [5] dias antes de um período experimental gratuito se converter num plano pago; pelo menos uma vez por ano para planos contínuos; e entre 30 e 45 dias antes de qualquer renovação de um prazo igual ou superior a doze meses. Cada lembrete inclui o preço, a data e uma ligação de cancelamento." },
      { kind: "p", text: "Cancelamento. Cancele a qualquer momento em Definições → Subscrição, com um clique de confirmação, ou através da página de cancelamento em [dezbatere.ro/cancel], que não exige que inicie sessão. O cancelamento produz efeitos no final do período de faturação em curso, e o utilizador mantém o acesso até essa data. Não tornaremos o cancelamento mais difícil do que a subscrição." },
      { kind: "p", text: "Alterações de preço só produzem efeitos aquando de uma renovação. Damos um pré-aviso de pelo menos 30 dias por correio eletrónico, com o novo preço e uma ligação de cancelamento. Quando a legislação do seu país exigir o seu consentimento expresso para uma alteração de preço, solicitá-lo-emos; caso contrário, se nada fizer, o novo preço será aplicável a partir da renovação seguinte. O Anexo A assinala as regras regionais." },
      { kind: "p", text: "Pagamentos falhados. Se um pagamento falhar, repetiremos a tentativa durante [7] dias e avisá-lo-emos por correio eletrónico antes de convertermos a sua conta para o plano gratuito. Não eliminaremos os seus debates devido a uma falha de pagamento." },
      { kind: "p", text: "Impostos e entidade a quem paga. Os preços [include / exclude] IVA, GST ou imposto sobre vendas, conforme o local onde reside, sendo essa informação apresentada antes do pagamento. [If a merchant of record is used: Your purchase is processed by [Paddle / …], which is the seller of record for the transaction; its terms apply to payment, tax, invoicing, refunds and payment disputes. DebateAIRO remains responsible for the service itself and for these Terms.]" },
      { kind: "p", text: "Estornos. Se contestar uma cobrança junto do emissor do seu cartão, podemos suspender as funcionalidades pagas enquanto o litígio estiver a ser resolvido. Não cobramos taxas por esse motivo." },
      { kind: "p", text: "Prevalência dos direitos legais. Quando o serviço não estiver em conformidade com o que prometemos, tem direito a que seja reposta a conformidade, ou a uma redução proporcional do preço ou a um reembolso, nos termos previstos na lei. Além disso, [state your discretionary refund policy]. Os limites de utilização de qualquer dos planos são publicados no produto; avisá-lo-emos antes de os restringir de uma forma que o afete substancialmente." }
    ]
  },
  {
    no: "13",
    title: "O seu direito de retratação",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Se residir na UE, no EEE ou no Reino Unido, pode retratar-se de uma subscrição paga no prazo de 14 dias após a subscrição, sem necessidade de indicar um motivo. Utilize a página Retratar-se do contrato, disponível em [dezbatere.ro/withdraw], o formulário-modelo constante da mensagem de confirmação, ou escreva para [support@dezbatere.ro]; confirmamos a receção num suporte duradouro." },
      { kind: "p", text: "Se nos tiver solicitado que iniciássemos o serviço imediatamente — assinalando a caixa no momento do pagamento — e depois exercer o direito de retratação, pagará a parte do serviço prestada até ao dia em que se retratar, calculada proporcionalmente com base no preço do período de faturação, e reembolsaremos o restante. Não perde o direito de retratação por utilizar o serviço durante os 14 dias." },
      { kind: "p", text: "Se residir noutro local, o Anexo A indica o direito de retratação ou o período de reflexão aplicável na sua região, caso exista, e, nos restantes casos, a nossa política de reembolso. Os direitos legais vigentes no seu país prevalecem sempre." }
    ]
  },
  {
    no: "14",
    title: "Alterações ao serviço e a estes Termos",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Ao serviço. Desenvolvemos continuamente a DebateAI, e as melhorias de rotina, correções e alterações ao conjunto de modelos ocorrem sem aviso. Quando introduzimos uma alteração que vai além da manutenção do funcionamento do serviço conforme descrito, fazemo-lo apenas por um dos seguintes motivos: cumprir um requisito legal ou regulamentar; responder a um problema de segurança ou abuso; um fornecedor de modelos alterar, restringir ou retirar um modelo ou uma funcionalidade de que dependemos; adaptar o serviço a um ambiente técnico que não controlamos; ou adicionar, melhorar ou retirar uma funcionalidade sem lhe impor custos." },
      { kind: "p", text: "Informá-lo-emos previamente, num suporte duradouro, sobre o que será alterado e quando. Se a alteração tiver um efeito negativo mais do que ligeiro no seu acesso ao serviço ou na sua utilização, poderá resolver o contrato sem encargos no prazo de 30 dias após ser informado, ou após a produção de efeitos da alteração, consoante a data que for posterior, e reembolsaremos qualquer montante pré-pago relativo ao período não utilizado." },
      { kind: "p", text: "A estes Termos. Podemos alterar estes Termos pelos mesmos tipos de motivos. No caso de alterações que não reduzam os seus direitos, publicamos a nova versão com um resumo das alterações e enviamos-lhe uma mensagem de correio eletrónico pelo menos 30 dias antes de produzir efeitos; a utilização continuada da DebateAI depois dessa data significa que a aceita; pode encerrar a sua conta antes dessa data. No caso de alterações que reduzam os seus direitos — incluindo aumentos de preço de um plano existente, redução de limites, remoção de funcionalidades, novas utilizações do seu conteúdo ou alterações relativas à responsabilidade, à lei aplicável ou à resolução de litígios — pedimos-lhe que aceite expressamente a nova versão quando voltar a iniciar sessão, e a alteração só se aplica daí em diante. Nunca aplicamos uma alteração retroativamente e nunca utilizamos esta secção para alterar, durante o respetivo prazo, o essencial daquilo por que pagou sem lhe oferecer uma forma de sair. As versões anteriores permanecem disponíveis em [dezbatere.ro/terms/versions]." }
    ]
  },
  {
    no: "15",
    title: "Responsabilidade",
    accent: "--con",
    blocks: [
      { kind: "p", text: "O que não limitamos. Nada nestes Termos exclui ou limita a nossa responsabilidade por morte ou lesões corporais causadas pela nossa negligência, por fraude ou declaração fraudulenta, por negligência grave ou dolo, ou por qualquer outra matéria cuja limitação não seja legalmente permitida. Se for consumidor, nada do que aqui consta elimina os seus direitos legais, incluindo o direito a que seja reposta a conformidade de um serviço não conforme, a uma redução do preço ou a um reembolso, ou qualquer garantia aplicável ao abrigo da legislação do país onde reside." },
      { kind: "p", text: "Conteúdo gerado. O serviço produz materiais para que os avalie, e não conclusões com base nas quais possa agir sem verificação, conforme expressamente referido na secção 5. Sem prejuízo do parágrafo anterior, não somos responsáveis por decisões que tome com base em argumentos, pontuações ou vereditos gerados quando não tiver adotado as medidas razoáveis de verificação descritas na secção 5." },
      { kind: "p", text: "O seu conteúdo e a sua utilização. É responsável pelo que envia e publica, incluindo por ter o direito de o enviar e por cumprir a secção 7." },
      { kind: "p", text: "Acontecimentos fora do nosso controlo. Não estaremos em incumprimento quando formos impedidos de cumprir por uma circunstância fora do nosso controlo razoável. A falha ou retirada por parte de um fornecedor de modelos terceiro não constitui automaticamente uma circunstância dessa natureza; quando tornar o serviço indisponível, aplica-se a secção 14, e o utilizador pode resolver o contrato e ser reembolsado nos termos aí descritos." },
      { kind: "p", text: "[No monetary cap and no general exclusion of indirect loss apply to consumers. If a business tier is ever offered, negotiated allocations belong in a separate order form.]" }
    ]
  },
  {
    no: "16",
    title: "Propriedade intelectual",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "O próprio serviço — o software, o motor, o método de pontuação, a interface, os nomes DebateAI e DebateAIRO e os nossos logótipos — pertence-nos ou aos nossos licenciantes. Estes Termos concedem-lhe autorização para utilizar o serviço, não a propriedade do mesmo." },
      { kind: "p", text: "Pode citar debates publicados e incluir ligações para os mesmos, com atribuição à DebateAI e uma ligação para a página original. A cópia em massa, a reprodução sistemática do acervo público e a utilização de debates publicados como dados de treino não são permitidas sem o nosso acordo escrito." },
      { kind: "p", text: "A secção 8 abrange o seu conteúdo e o estatuto dos resultados gerados. Se considerar que algo na DebateAI viola os seus direitos de propriedade intelectual, utilize a via de denúncia indicada na secção 10. [If the United States is inside section 2: our designated agent under the Digital Millennium Copyright Act is [name, address, email], registered with the US Copyright Office; we terminate the accounts of repeat infringers.]" }
    ]
  },
  {
    no: "17",
    title: "Dados pessoais",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "A forma como tratamos dados pessoais é estabelecida na Política de Privacidade, disponível em [dezbatere.ro/privacy]. Esta explica o que recolhemos, o fundamento jurídico de cada finalidade, durante quanto tempo conservamos os elementos, quem recebe os dados, as transferências envolvidas e como exercer os seus direitos. Há também três pontos que pertencem a esta secção. A secção 7 pede-lhe que não inclua dados pessoais de terceiros numa pergunta; se o fizer, será responsável por esses dados e poderemos remover o conteúdo. Se um debate publicado na DebateAI contiver dados pessoais a seu respeito, pode pedir-nos que os removamos sem ter uma conta (secção 9). Conservamos ainda um registo da sua aceitação destes Termos — a versão, a hora e os dados técnicos da sessão — como prova do contrato, conforme explicado na Política de Privacidade." }
    ]
  },
  {
    no: "18",
    title: "Lei aplicável e tribunais competentes para os litígios",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "Lei aplicável. Estes Termos, bem como qualquer litígio ou pretensão deles decorrente ou relacionado com o respetivo objeto, incluindo pretensões extracontratuais, são regidos pela legislação da Roménia." },
      { kind: "p", text: "As suas proteções locais não são afetadas. Se for consumidor, a escolha da lei romena não o priva da proteção conferida por quaisquer normas imperativas de defesa do consumidor do país da sua residência habitual — por exemplo, normas sobre cláusulas abusivas, direitos de retratação e cancelamento ou garantias — quando essas normas se apliquem independentemente desta escolha, incluindo nos termos do artigo 6.º, n.º 2, do Regulamento (CE) n.º 593/2008, caso resida na UE, ou das normas equivalentes do Reino Unido. Pode invocar essas normas para além da lei romena." },
      { kind: "p", text: "Tribunais, se residir na UE, no EEE ou no Reino Unido. Pode intentar uma ação contra nós nos tribunais da Roménia ou nos tribunais do país onde reside. Só podemos intentar uma ação contra si nos tribunais do país onde reside." },
      { kind: "p", text: "Consumidores noutros locais. Se residir fora da UE, do EEE e do Reino Unido, nada nestes Termos limita qualquer direito que detenha ao abrigo da legislação do seu país de intentar uma ação nos respetivos tribunais, ou qualquer direito conferido por essa legislação que não possa ser objeto de renúncia — incluindo, se residir na Austrália ou na Nova Zelândia, os seus direitos relativos a garantias do consumidor; se residir no Brasil, o Código de Defesa do Consumidor; e, se residir nos Estados Unidos, as leis de defesa do consumidor do seu estado." },
      { kind: "p", text: "Residentes nos Estados Unidos. O Anexo A.3 contém uma convenção de arbitragem e uma renúncia a ações coletivas regidas pelo Federal Arbitration Act. Aplica-se apenas a residentes nos Estados Unidos e apenas quando for exequível. Não se aplica a consumidores na UE, no EEE ou no Reino Unido." },
      { kind: "p", text: "Antes de recorrer aos tribunais. Contacte-nos através de [legal@dezbatere.ro]; a maioria das questões pode ser resolvida e procuramos responder no prazo de [5] dias úteis. Se for consumidor na Roménia ou na UE, pode recorrer à resolução alternativa de litígios através de [the ANPC – named SAL entity, website]; comprometemo-nos [do / do not] a participar nesse procedimento. As reclamações relativas a decisões de moderação seguem a secção 10, que constitui uma via separada." }
    ]
  },
  {
    no: "19",
    title: "Outras disposições",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Cessão. Não pode transferir os direitos que lhe assistem ao abrigo destes Termos. Podemos transferir os nossos direitos para uma sociedade que assuma o serviço, desde que os seus direitos não sejam reduzidos; informá-lo-emos se tal acontecer e poderá encerrar a sua conta." },
      { kind: "p", text: "Divisibilidade. Se alguma disposição destes Termos for considerada inexequível, essa disposição não será aplicável e as restantes disposições dos Termos permanecerão em vigor." },
      { kind: "p", text: "Não renúncia. Se não exigirmos de imediato o cumprimento de uma disposição, não perdemos o direito de exigir o seu cumprimento posteriormente." },
      { kind: "p", text: "Acordo integral. Estes Termos, juntamente com a Política de Cookies e o Registo de Fornecedores de IA, constituem o acordo integral entre nós relativamente ao serviço. Os compromissos que assumimos na Política de Privacidade vinculam-nos. Nada neste parágrafo exclui a responsabilidade por declaração fraudulenta." },
      { kind: "p", text: "Idioma. Estes Termos são publicados em inglês [and Romanian]. [State which version prevails for which users; Annex A notes where a local language is required.]" },
      { kind: "p", text: "Contacto. [legal@dezbatere.ro] · DebateAIRO S.R.L., [address], Bucareste, Roménia." }
    ]
  },
  {
    no: "A",
    title: "Anexo A — Termos regionais",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "Cada entrada aplica-se apenas se a respetiva região estiver indicada na secção 2 e estabelece somente aquilo que difere do corpo do documento. Em caso de conflito entre uma entrada e o corpo, a entrada aplica-se às pessoas dessa região." }
    ]
  },
  {
    no: "A.1",
    title: "União Europeia e Espaço Económico Europeu",
    accent: "--con",
    blocks: [
      { kind: "p", text: "O corpo destes Termos foi redigido para si. Adicionalmente: pode intentar ações nos tribunais do país onde reside; aplica-se o direito de retratação previsto na secção 13; a resolução alternativa de litígios está disponível através de [the ANPC – named entity, website]. Alemanha: o botão de cancelamento em [dezbatere.ro/cancel] permite-lhe terminar uma subscrição sem iniciar sessão; os prazos da subscrição, os períodos de renovação e os prazos de pré-aviso cumprem o §309(9) BGB [state them]. França: pode terminar uma subscrição em linha em três passos, em [URL]; [the mediator named at URL] está à sua disposição. Itália: as cláusulas relativas a responsabilidade (15), suspensão (11), alterações (14) e lei aplicável (18) exigem a sua aprovação específica, que presta através da confirmação separada no momento do registo. Países Baixos: estes Termos são disponibilizados num formato suscetível de conservação antes da celebração. Polónia: está disponível uma versão em polaco em [URL]." }
    ]
  },
  {
    no: "A.2",
    title: "Reino Unido (apenas se indicado na secção 2)",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "O nosso representante no Reino Unido ao abrigo do artigo 27.º do RGPD do Reino Unido é [name, address, email]. O Consumer Rights Act 2015 é-lhe aplicável e nada nestes Termos limita os direitos que lhe confere; a partir de [January 2027], as regras relativas a subscrições do Digital Markets, Competition and Consumers Act 2024 aplicam-se aos planos pagos, incluindo um período de reflexão após renovações e períodos experimentais gratuitos. Como protegemos os utilizadores contra conteúdos ilegais: [terrorism content — …; child sexual exploitation and abuse content — …; other priority illegal content — …; intimate image content — removed within 48 hours of a valid report]. Tecnologia proativa que utilizamos: [describe, or \"none\"]. Verificação da idade: [describe what is used; if only self-declaration, state that the service is treated as accessible to children for the purposes of the Online Safety Act 2023]. O procedimento de reclamação da secção 10 aceita reclamações relativas a conteúdos ilegais, remoção indevida do seu conteúdo, restrições à sua conta, utilização de ferramentas automatizadas que afetem o seu conteúdo e qualquer avaliação etária que o bloqueie indevidamente. Está disponível a pessoas afetadas por conteúdos que não sejam utilizadores." }
    ]
  },
  {
    no: "A.3",
    title: "Estados Unidos (apenas se indicados na secção 2)",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "Convenção de arbitragem e renúncia a ações coletivas. Se residir nos Estados Unidos, o utilizador e a DebateAIRO concordam em resolver qualquer litígio decorrente destes Termos ou do serviço através de arbitragem individual vinculativa administrada por [the American Arbitration Association / JAMS] ao abrigo das respetivas regras de arbitragem de consumo, em vez de recorrer aos tribunais, com a exceção de que qualquer uma das partes pode apresentar uma pretensão individual num tribunal de pequenas causas. Pode optar pela não aplicação enviando uma mensagem para [address] no prazo de 30 dias após a primeira aceitação destes Termos. Esta convenção é regida pelo Federal Arbitration Act. Suportamos as taxas de apresentação da arbitragem. Há renúncia a ações coletivas, conjuntas e representativas na medida permitida por lei. Esta secção aplica-se apenas para o futuro e não se aplica a pretensões surgidas antes da sua aceitação." },
      { kind: "p", text: "Notificações e remoções. As imagens íntimas não consentidas podem ser denunciadas em [URL] sem uma conta e são removidas no prazo de 48 horas após um pedido válido. As reclamações relativas a direitos de autor são dirigidas ao nosso agente designado referido na secção 16." },
      { kind: "p", text: "Disposições específicas de cada estado. Califórnia: aplicam-se as condições de renovação automática da secção 12; pode cancelar em linha a qualquer momento; conservamos o seu consentimento para as condições de renovação durante pelo menos três anos. Nova Iorque: pode cancelar no prazo de 14 dias após qualquer cobrança a um preço aumentado e receber um reembolso proporcional. Texas e Nebraska: não vendemos dados pessoais sensíveis; se isso alguma vez mudar, obteremos primeiro o seu consentimento [statutory notice language]. Washington: o nosso Aviso de Privacidade de Dados de Saúde dos Consumidores, disponível em [URL], aplica-se a informações relacionadas com a saúde. Colorado: nada no serviço toma decisões com consequências significativas a seu respeito." }
    ]
  },
  {
    no: "A.4",
    title: "Canadá e Quebeque (apenas se indicados)",
    accent: "--ok-dot",
    blocks: [
      { kind: "p", text: "O nosso responsável pela privacidade é [name, email]. Quebeque: estes Termos estão disponíveis em francês em [URL] e a versão francesa foi-lhe apresentada em primeiro lugar; as definições que mantêm os seus debates privados estão ativadas por predefinição; pode pedir a desindexação de informações pessoais a seu respeito." }
    ]
  },
  {
    no: "A.5",
    title: "Austrália e Nova Zelândia (apenas se indicadas)",
    accent: "--gold",
    blocks: [
      { kind: "p", text: "Os nossos serviços beneficiam de garantias que não podem ser excluídas ao abrigo da Australian Consumer Law. Em caso de falhas graves do serviço, tem direito a cancelar e a obter o reembolso da parte não utilizada, ou a uma indemnização pela redução do seu valor; tem igualmente direito a indemnização por quaisquer outros prejuízos ou danos razoavelmente previsíveis. Se a falha não constituir uma falha grave, tem direito a que os problemas do serviço sejam corrigidos num prazo razoável e, se isso não acontecer, a cancelar e obter um reembolso. Na medida permitida pela secção 64A, a nossa responsabilidade por violação de uma garantia limita-se a prestar novamente o serviço ou a pagar o custo dessa nova prestação. Não se aplica ao plano pago qualquer período de reflexão além do concedido pela secção 12; a nossa política de reembolso é […]. Nova Zelândia: o Consumer Guarantees Act 1993 é aplicável e nada nestes Termos o exclui; as comunicações digitais prejudiciais podem ser-nos denunciadas ao abrigo da secção 10 ou comunicadas à Netsafe." }
    ]
  },
  {
    no: "A.6",
    title: "América Latina (anexo em língua espanhola; apenas se indicada)",
    accent: "--reasoning",
    blocks: [
      { kind: "p", text: "[Published in Spanish.] O consentimento constitui o fundamento do tratamento quando não exista necessidade contratual; no momento do registo, presta consentimento expresso para quaisquer dados sensíveis que opte por incluir. Os seus direitos ARCO podem ser exercidos em [address], com respostas no prazo de [Mexico 20 business days / Colombia 10–15 business days / Argentina 10 business days / Chile per Law 21.719]. México: o aviso de privacidad completo está disponível em [URL]; retratação no prazo de [5] dias. Argentina: [AAIP legend]; utilize o botón de arrepentimiento em [URL] no prazo de 10 dias. Colômbia: a política de tratamiento está disponível em [URL]; retratação no prazo de 5 dias. Chile (a partir de 1 de dezembro de 2026): o contacto da Agência é […]; pode cancelar através dos mesmos meios que utilizou para subscrever; não se aplica qualquer direito de retratação a serviços digitais." }
    ]
  },
  {
    no: "A.7",
    title: "Golfo — Emirados Árabes Unidos e Arábia Saudita (apenas se indicados)",
    accent: "--con",
    blocks: [
      { kind: "p", text: "Quando tratamos os seus dados para finalidades distintas da prestação do serviço, fazemo-lo com o seu consentimento, que pode retirar. Os seus dados são tratados fora dos [UAE / Kingdom of Saudi Arabia], incluindo na União Europeia e nos Estados Unidos, ao abrigo de [SDAIA standard contractual clauses / the mechanism in the Register]. É responsável por garantir que tudo o que publica cumpre a legislação do país onde se encontra, incluindo a legislação relativa a religião, ordem pública e moralidade; podemos restringir a publicação de debates sobre esses temas na sua região." }
    ]
  },
  {
    no: "A.8",
    title: "Ásia-Pacífico (apenas as linhas relativas às regiões indicadas)",
    accent: "--ink",
    blocks: [
      { kind: "p", text: "Singapura: o nosso Encarregado da Proteção de Dados é [name, email]; as transferências assentam em proteções contratuais comparáveis às da PDPA; não se aplica ao plano pago qualquer período legal de reflexão e a nossa política de reembolso é […]. Japão: a divulgação legal ao abrigo do Specified Commercial Transactions Act está disponível em [URL]; não se aplica um período geral de reflexão às subscrições em linha e a nossa política de reembolso é […]; o seu conteúdo pode ser transferido para fornecedores em [named countries], e o utilizador concorda com essa transferência através dos consentimentos prestados no momento do registo. Coreia do Sul: os consentimentos para tratamento facultativo e marketing são recolhidos separadamente dos elementos necessários ao funcionamento do serviço; o nosso Responsável pela Privacidade é [name]; pode retratar-se de um plano pago no prazo de 7 dias após a subscrição, nos termos do E-Commerce Act; obtemos novamente o seu consentimento antes de qualquer aumento de preço recorrente ou conversão de gratuito para pago; quando o AI Basic Act o exigir, informá-lo-emos previamente de que o serviço se baseia em IA e identificaremos os resultados. Índia (quando as regras DPDP forem aplicáveis): aplica-se o aviso de consentimento disponível em [URL]; os utilizadores com menos de 18 anos necessitam de consentimento parental verificável. Tailândia: o nosso representante na Tailândia é [name] [if appointed]. Filipinas: a nossa identificação comercial e o mecanismo de reparação ao abrigo do Internet Transactions Act estão disponíveis em [URL]; podem ser apresentadas reclamações à National Privacy Commission." }
    ]
  },
  {
    no: "A.9",
    title: "Reservado",
    accent: "--muted",
    blocks: [
      { kind: "p", text: "A Turquia, o Brasil e a Indonésia exigem, cada um, um anexo no idioma local, um representante ou registo e formalidades. Esses elementos não estão aqui redigidos e esses países permanecem fora da secção 2 até serem deliberadamente incluídos. A China, o Vietname e a Rússia não são abrangidos pela oferta." }
    ]
  }
];

export const TERMS_OF_SERVICE: LegalDocument = {
  key: "terms",
  eyebrow: "TERMOS DE SERVIÇO · v2.0 · EM VIGOR DESDE [DATE]",
  title: "Aquilo com que concorda",
  lede: "O contrato entre si e a DebateAIRO S.R.L., em linguagem clara. Dezanove secções e o Anexo A — desloque-se até ao fim.",
  endMarker: "FIM DOS TERMOS · v2.0",
  contact: "[legal@dezbatere.ro]",
  bodyLabel: "Texto dos Termos de Serviço",
  sectionIdPrefix: "terms-section-",
  titleId: "terms-modal-title",
  gateHintId: "terms-modal-gate-hint",
  jumps: TERMS_JUMP,
  sections: TERMS_SECTIONS
};
