#!/bin/zsh
# ARCH-FIX-PES-S01-p3 · the C1, C2 and C4 commands as they stand (unchanged by Revision 3), run in the lane as it stands
# (HEAD 3e6f438b5 = C1+C2 built, + BUILD S01-C3's 4 uncommitted paths). C4's created suite is omitted (S01-21 creates it).
# Their tests/architecture pair is 719:6 in the plan's text for C1/C2; C3's uncommitted work makes the directory 722/7
# here (4 boundary cases + the C3-F1 failure), so the pair is recorded as measured, not as planned.
export PATH="/opt/homebrew/bin:$PATH"
cd /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/pes-s01/dialectical-engine || exit 3
echo "===== C1 $(date '+%T')"; LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/provider-env-selection/probes/ARCH-FIX-PES-S01-p3/lane-C1.log zsh /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.claude/skills/heartbeat-orchestrator/scripts/run-suites.sh tests/unit/pes-s01-operator-command-environment.test.ts:3:0 tests/architecture:719:6 tests/unit/v9-deployment-mode.test.ts:201:0 tests/unit/production-environment-floors.test.ts:24:0 tests/unit/dl7-f7-boot-custody.test.ts:14:0 tests/unit/v20-optional-primary-provider-keys.test.ts:11:0
echo "===== C2 $(date '+%T')"; LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/provider-env-selection/probes/ARCH-FIX-PES-S01-p3/lane-C2.log zsh /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.claude/skills/heartbeat-orchestrator/scripts/run-suites.sh tests/unit/pes-s01-hosted-provider-set.test.ts:37:0 tests/architecture:719:6 tests/unit/v9-configured-provider-set-deployment.test.ts:14:0 tests/unit/text-control-bytes.test.ts:3:0
echo "===== C4 $(date '+%T')"; LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/provider-env-selection/probes/ARCH-FIX-PES-S01-p3/lane-C4.log zsh /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.claude/skills/heartbeat-orchestrator/scripts/run-suites.sh tests/architecture:723:6 tests/unit/text-control-bytes.test.ts:3:0
echo "===== lane dirty after: $(git status --porcelain | wc -l | tr -d ' ') · HEAD $(git rev-parse --short HEAD) · $(date '+%T')"
(shasum -a 256 package.json apps/runner/src/hosted-provider-set-publish-cli.ts tests/architecture/pes-s01-hosted-publish-boundary.test.ts tests/integration/pes-s01-hosted-provider-set-publish.test.ts | diff - /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/provider-env-selection/probes/ARCH-FIX-PES-S01-p3/dirty-before.sha && echo "4 dirty paths byte-identical")
