"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { ContractHttpError, createBackupEmailClient, type BackupEmailClient } from "@debateai/contract";
import { AuthShell } from "@/components/AuthShell";
import { API_BASE } from "@/lib/api";
import { t, type MessageCatalog } from "@/lib/i18n/translate";
import en from "@/messages/en/mfa-recovery.json";
import ro from "@/messages/ro/mfa-recovery.json";
const browserClient = createBackupEmailClient(fetch, API_BASE);
export function BackupEmailVerification({ locale = "en", client = browserClient, catalog = locale === "ro" ? ro : en }: Readonly<{ locale?: string; client?: BackupEmailClient; catalog?: MessageCatalog }>) {
  const [state, setState] = useState<Awaited<ReturnType<BackupEmailClient["status"]>> | null>(null), [password, setPassword] = useState(""), [code, setCode] = useState(""), [busy, setBusy] = useState(false), [notice, setNotice] = useState<string | null>(null), [error, setError] = useState<string | null>(null);
  const [unknown, setUnknown] = useState(false);
  const mounted = useRef(true), inFlight = useRef(false); const text = (key: string) => t(catalog, key);
  useEffect(() => { mounted.current = true; void client.status().then(value => { if (mounted.current) setState(value); }).catch(() => { if (mounted.current) setError(text("backup.error")); }); return () => { mounted.current = false; }; }, [client]);
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (inFlight.current || unknown) return; if (!/^[0-9]{6}$/.test(code)) { setError(text("error.code")); return; } inFlight.current = true; setBusy(true); setError(null); try { await client.startVerification(password, code); if (mounted.current) setNotice(text("backup.sent")); } catch (failure) { if (mounted.current) { const expected = failure instanceof ContractHttpError && [400, 401, 403, 410, 429].includes(failure.status); setUnknown(!expected); setError(text(expected ? "error.proof" : "backup.error")); } } finally { inFlight.current = false; if (mounted.current) { setPassword(""); setCode(""); setBusy(false); } } }
  return <section className="setPanel recoveryActivity" aria-labelledby="backup-email-title"><div className="setPanelCore"><h2 id="backup-email-title">{text("backup.title")}</h2><p>{text("backup.description")}</p>{state?.email && <p>{state.email}</p>}{state && <p role="status">{text(`backup.${state.status}`)}</p>}{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}{unknown && <button className="authSecondary recoveryCancel" type="button" disabled={busy} onClick={() => { setBusy(true); void client.status().then(value => { if (mounted.current) { setState(value); setUnknown(false); setError(null); } }).catch(() => { if (mounted.current) setError(text("backup.error")); }).finally(() => { if (mounted.current) setBusy(false); }); }}>{text("backup.check")}</button>}{state?.status === "pending" && <form className="authForm" method="post" action="/settings" onSubmit={send}><div className="authField"><label htmlFor="backup-current-password">{text("password")}</label><input id="backup-current-password" name="backup-password" type="password" autoComplete="current-password" required disabled={busy || unknown} value={password} onChange={event => setPassword(event.target.value)} /></div><div className="authField"><label htmlFor="backup-current-code">{text("backup.code")}</label><input id="backup-current-code" name="backup-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={12} required disabled={busy || unknown} value={code} onChange={event => setCode(event.target.value.replace(/\s/g, ""))} /></div><button className="authPrimary" disabled={busy || unknown}>{busy ? text("working") : text("backup.button")}</button></form>}</div></section>;
}
export function BackupEmailConfirmation({ catalog = en, locale = "en", client = browserClient }: Readonly<{ catalog?: MessageCatalog; locale?: "en" | "ro"; client?: BackupEmailClient }>) {
  const token = useRef<string | null>(null), mounted = useRef(true), inFlight = useRef(false); const [phase, setPhase] = useState<"link" | "done" | "expired">("expired"), [busy, setBusy] = useState(false), [unknown, setUnknown] = useState(false), [error, setError] = useState<string | null>(null); const text = (key: string) => t(catalog, key);
  useEffect(() => { mounted.current = true; const hash = location.hash.slice(1); if (hash) { history.replaceState(null, "", location.pathname + location.search); const entries = [...new URLSearchParams(hash).entries()]; if (entries.length === 1 && entries[0]![0] === "token" && /^[A-Za-z0-9_-]{43}$/.test(entries[0]![1])) { token.current = entries[0]![1]; setPhase("link"); } } return () => { mounted.current = false; queueMicrotask(() => { if (!mounted.current) token.current = null; }); }; }, []);
  async function confirm() { if (inFlight.current || !token.current) return; inFlight.current = true; setBusy(true); setError(null); try { await client.confirm(token.current); if (mounted.current) { token.current = null; setUnknown(false); setPhase("done"); } } catch (failure) { if (!mounted.current) return; if (failure instanceof ContractHttpError && [401, 403, 410].includes(failure.status)) { token.current = null; setPhase("expired"); setUnknown(false); } else { setUnknown(true); setError(text("backup.confirm.unknown")); } } finally { inFlight.current = false; if (mounted.current) setBusy(false); } }
  return <AuthShell lang={locale} eyebrow={text("backup.title")} title={text(`backup.${phase}.title`)} description={text(`backup.${phase}.description`)} footer={<p><a href="/settings">{text("backup.settings")}</a></p>}>{error && <div className="authAlert" role="alert">{error}</div>}{phase === "link" && <button className="authPrimary" type="button" disabled={busy} onClick={() => void confirm()}>{busy ? text("working") : unknown ? text("backup.confirm.check") : text("continue")}</button>}</AuthShell>;
}
