#!/bin/zsh
REPO=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine
BRIEF=$REPO/.hermes/reports/public-debate-access/packets/ARCH-01-rev05.md
SID=17d6551f-b33c-4a98-bad5-8082e402dbfa
LOG=$REPO/.hermes/planning/public-debate-access/logs/ARCH-01-rev05-claude.log
[ -f "$BRIEF" ] || { echo "FATAL: brief missing at $BRIEF"; exit 1; }
cd "$REPO" || exit 1
echo "ARCH-01 REV-05 findings B2 + N1 · tickets t_57891ca5, t_a9d1deeb"
claude --resume "$SID" -p "REV-05 FINDINGS, ROUND 1 of 3. Your brief is at $BRIEF - read it IN FULL first and follow it exactly. The blind Grok lens reviewed S03's code and returned REWORK with three findings. B1 belongs to the coding seat and is ALREADY IN REWORK in .worktrees/s03-code right now, so do not touch it and do not touch tests/unit/pda-s03-keyboard-accessibility.test.ts. Two findings are yours. B2 IS BLOCKING AND IT IS AGAINST YOUR DESIGN, not against the coder: the lens shows that role=tablist plus role=tab plus aria-selected on next/link navigation links, with no tabpanel, no aria-controls and no arrow-key behaviour, is LESS accessible than plain links, citing the WAI-ARIA APG tabs pattern and Using ARIA rule 1, no ARIA is better than bad ARIA. The Router verified before routing that YOUR PLAN mandates this markup at lines 88 to 91 and gives the literal element at 193 to 204, so the seat implemented what it was told. Read your own justification against the finding: you argued for anchors because they are natively keyboard reachable WITHOUT custom key-handling code, which is exactly the lens's point - you took the ARIA tab contract while declining the ARIA tab behaviour, so a screen-reader user told tab 1 of 2 will reach for arrow keys that do nothing. Note it is pinned TWICE, by the S03-C1 node -e acceptance requiring those literal strings and by the new test, so any fix must move the acceptance with it or the acceptance will condemn the fix. Choose between dropping the tab ARIA for plain links with aria-current, implementing the real pattern with tabpanels and roving tabindex and arrow keys, or defending the current choice - but if you defend it you must rebut rule 1 with a citation and not with convenience. Say WHAT the markup should be; the coding seat implements it on its own ticket. N1 IS THE SECOND: from a hand-enumerated token by sessionConfirmed by tab matrix, an anonymous visitor who clicks Your Debates sees NEITHER list, because one panel gates on sessionConfirmed and tab equals yours and the other on tab equals public. The sign-in banner still shows but the selected tab's content area is blank. Measure that against V's literal acceptance criterion 2, clicking either will show the user their debates or the public debates, and rule on it - and if you conclude it is really a SCOPE question about what an account-less visitor is entitled to see, say so plainly and the Router will route it to V as a DECISIONS row rather than you deciding it. SCOPE: S03 PLAN and DECISIONS only plus whatever the acceptance change requires. No product code, no test files, no worktrees, no other slice. SPECs remain FROZEN. Do not disturb .worktrees/s03-code, a coding seat is live in it. Handoff opens with SKILLS LOADED. Return control at REWORK READY FOR REVIEW or a genuine blocker." \
  --permission-mode bypassPermissions 2>&1 | tee "$LOG"
echo "=== ARCH-01 rev05 round exited. Log: $LOG ==="
