#!/bin/zsh
REPO=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine
BRIEF=$REPO/.hermes/reports/public-debate-access/packets/ARCH-01-bundle.md
SID=17d6551f-b33c-4a98-bad5-8082e402dbfa
LOG=$REPO/.hermes/planning/public-debate-access/logs/ARCH-01-bundle-claude.log
[ -f "$BRIEF" ] || { echo "FATAL: brief missing at $BRIEF"; exit 1; }
cd "$REPO" || exit 1
echo "ARCH-01 bundle round · t_5d2a4e79 t_63f6e7e6 t_7539734e t_899df0d3"
claude --resume "$SID" -p "FOUR ITEMS, ONE ROUND. Your brief is at $BRIEF - read it IN FULL first and follow it exactly. Three are small; one is not, and it is the reason this round exists. THE BLOCKING ONE, t_5d2a4e79: the S02 seat's correct refactor moves PublicAnswerDisclosure out of the public page.tsx into the new PublicDebatePageClient.tsx, which breaks line 170 of tests/architecture/s8-publication-contract.test.ts - measured, 1 failed and 4 passed in the S02 worktree. The seat could not fix it and was right: that file is outside S02's authorized surface, and Row 7 grants factual PLAN corrections, not surface expansion, which is scope. It also named and refused the two product-only workarounds, gaming the assertion or duplicating disclosure content just to satisfy a stale oracle. Note that NOBODY owns line 170 - S04 owns 120 to 138 and S03's PLAN says its design explicitly avoids the 140 to 175 block. Rule the instance three ways: widen S02's surface, change the assertion to read the client component, or reject the refactor. THEN RULE THE CLASS, WHICH MATTERS MORE: all four PLANs verified their WRITE surfaces were disjoint and that verification was CORRECT, the Router re-checked it when a suspected S02/S03 collision proved a false alarm - but DISJOINT WRITE SURFACES DO NOT IMPLY INDEPENDENT EFFECTS. S02 wrote only files it owns and still broke a test in a file no slice claimed. No step in this mission's design asks which STANDING tests read the files each slice writes. Say whether that check should exist and what it looks like, and the Router will ticket it. Do not re-derive one thing I already checked: line 159 asserts home contains Published debates, the heading S03 replaced, and S03's page.tsx still contains that string twice with the suite at 5 passed in its worktree, so there is no second conflict. ITEM 2, t_63f6e7e6: S03-C1-4 still calls the test source-text based with no DOM-render path when it is now renderToStaticMarkup plus JSDOM - third instance of the stale-record disease in this mission. ITEMS 3 AND 4: ratify or reject, with reasons, the two provisional Row 7 corrections the seats disclosed - t_7539734e, the escaped-pipe node -e in S03-C1, and t_899df0d3, S02-C3-2's oracle which asserted reversal_point visibility while S02-C1-4 requires that same string on the base page, verified by the Router at PublicDebatePageClient.tsx line 177. SCOPE: PLAN and DECISIONS files plus whatever item 1 requires. NO product code, NO test files, NO worktrees - two coding seats are live in .worktrees/s02-code and .worktrees/s03-code. SPECs remain FROZEN. Handoff opens with SKILLS LOADED. Return control at REWORK READY FOR REVIEW or a genuine blocker." \
  --permission-mode bypassPermissions 2>&1 | tee "$LOG"
echo "=== ARCH-01 bundle exited. Log: $LOG ==="
