#!/bin/zsh
WT=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-05/dialectical-engine
PACKET=$WT/.hermes/reports/public-debate-access/packets/REV-05.md
LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/public-debate-access/logs/REV-05-grok.log
[ -f "$PACKET" ] || { echo "FATAL: packet missing at $PACKET"; exit 1; }
[ -d "$WT" ]     || { echo "FATAL: worktree missing at $WT"; exit 1; }
[ -f "$WT/packages/contract/generated/client.ts" ] || { echo "FATAL: generated client missing — run pnpm run generate:contract first"; exit 1; }
cd "$WT" || exit 1
echo "REV-05 · BLIND CODE REVIEW of S03 · Grok · ticket t_32616c74 · worktree $WT"
~/.grok/bin/grok -p "You are the blind CODE REVIEW seat on mission public-debate-access, board public-debate-access, ticket t_32616c74. Your complete goal packet is at $PACKET . Read that packet IN FULL before anything else, then follow it exactly. Your handoff must OPEN with the line 'SKILLS LOADED:' naming every skill you actually loaded; naming one you did not load is a fabrication finding against you. Read .hermes/TOOLING-TRAPS.md early - it is in your worktree and it holds the eight distinct ways an acceptance has passed in this mission while verifying nothing, including one trap filed on your behalf about lens worktrees needing generate:contract, which has been done for you. You are a BLIND lens: you did not write this code, you did not write the plan, and the author's self-report was deliberately withheld from your worktree. DEFAULT POSTURE REFUTE. THE SINGLE QUESTION THAT MATTERS MOST, phrased exactly this way because this framing found both blocking defects in the previous slice: construct a change to page.tsx that keeps the new keyboard-accessibility test GREEN while making the tabs unreachable to a real user. That test does not render anything - it reads page.tsx as TEXT and regex-matches Link blocks - so ask whether its PASS traces to the one fact it claims or whether some other state of the world can produce it. The author already mutation-tested it and showed it catches a Link to div swap, so do not repeat that; find the mutation it is NOT sensitive to. Also construct a state where a user selects one tab and sees the other tab's content or neither, enumerating the token and sessionConfirmed combinations by hand rather than sampling, and pay particular attention to what an anonymous visitor who clicks Your Debates actually sees. And decide with a citation, not an opinion, whether role=tab on navigation links inside role=tablist makes these controls more or less accessible than plain links, since accessible is V's literal acceptance word and the new test PINS that choice. Reproduce before you report; a finding without a reproduction is a hypothesis. Do NOT condemn a regression-baseline or verification-only step for being legitimately green. Do NOT stop, restart or reconfigure the server on port 3000 and do not touch apps/runner - V has already ruled that live probes are deferred to QA, so the UNVERIFIED-BY-RUNTIME records are a closed decision and not a defect, but DO say whether the source-level evidence is sufficient to believe the tabs are mutually exclusive or whether that claim is currently unverified by anything at all. Do not edit product code; you are a lens, you report. Say plainly what you could not do rather than inferring it. Write your self-report inside this worktree before finishing. Return control at your verdict, a genuine blocker, or an IMPORTANT OPERATION; otherwise keep working and keep the session alive and resumable." \
  -m grok-4.5 --permission-mode bypassPermissions 2>&1 | tee "$LOG"
echo "=== REV-05 seat exited. Log: $LOG ==="
