#!/bin/zsh
WT=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/s02-code/dialectical-engine
LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/public-debate-access/logs/S02-CODE-go-codex.log
[ -d "$WT" ] || { echo "FATAL: worktree missing"; exit 1; }
cd "$WT" || exit 1
echo "S02-CODE · Codex · ticket t_83443bb1 · public debate detail page, read parity"
codex exec -s danger-full-access "You are the S02-CODE seat on ticket t_83443bb1. Read your SKILLS first and open your handoff with SKILLS LOADED.

WHERE YOU ARE. Your worktree is /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/s02-code/dialectical-engine, detached at commit 4138f72. Real pnpm install and generate:contract are both already done. Your plan is /Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/s02-code/dialectical-engine/docs/missions/public-debate-access/slices/S02/PLAN.md, 933 lines, and it comes from the commit itself, so there is no copied-file sync question.

WHAT YOU ARE BUILDING. V's third acceptance criterion: public debates can be accessed just the same as the user's own debates. S02 is the DETAIL page half of that. You build a parallel component tree, a new PublicDebatePageClient, that reaches READ parity with the owner debate page while carrying no mutation affordance at all. Six clusters, twenty acceptance steps, every one already categorized in your plan.

WHAT S01 GAVE YOU. S01 is DONE and COMMITTED at 4138f72. The public envelope now carries the argument tree, redacted. Two real anonymous-data leaks were found and closed there by blind review, so treat the redaction shape as load-bearing law, not as something to reshape: owner-only provenance pointers are REDACTED_OWNER_ONLY by a value-provenance rule that is RECURSIVE and was iterated to a fixed point. If you find a field that carries an owner-only value into anonymous hands, that is a BLOCKING finding, not a cleanup.

YOU ARE RUNNING IN PARALLEL WITH S03, RIGHT NOW. The S03 seat is live in a different worktree and owns apps/ui/app/page.tsx, the debates list page with the Your Debates and Public Debates tabs. That file is NOT yours. Do not read-modify-write it, do not reformat it, do not touch it even if it looks wrong. Your file surface is fixed by your plan at its Single-writer check: apps/ui/lib/v3/adapter.ts signature-only, the four debate components as additive optional props only, a new PublicHonestyDrawer, a new apps/ui/lib/v3/publicAnswerExport.ts, PublicAnswerDisclosure, DebatePageClient.tsx for an export keyword on two lines, and your own apps/ui/app/public/debate/[id]/ tree. You ALSO write the five test files your plan mandates, and they are authorized: tests/render/pda-s02-public-page.test.tsx, tests/render/pda-s02-public-tree.test.tsx, tests/render/pda-s02-honesty-export.test.tsx, tests/render/pda-s02-scoring-chrome.test.tsx, and tests/unit/pda-s02-affordance-drift.test.ts. That is tests/** and it is yours. Both plans independently verified those surfaces are disjoint from S03. Keep them disjoint.

THE WARNING THAT MATTERS MOST, because it cost S01 seven blocks. Acceptance commands in this fleet have failed SIX distinct ways while still looking like verification: a path that was gitignored so the command could never observe its own change; a reporter flag deleted in vitest 4.1.10 so the run crashed before starting; a live grep pipe that both crashed the run and stole its exit status; an unanchored guard that matched a skipped test TITLE instead of the summary; a markdown-escaped pipe in a name filter that matched nothing; and absolute line ranges that observe the wrong place and go SILENT when the assertion is negative. Your plan has been checked against all six and is believed clean, but belief is not evidence. If an acceptance command cannot DISCRIMINATE, meaning it would pass before your change, or targets the wrong place, or its guard can be satisfied by text that is not the result, then BLOCK AND SAY SO on your ticket. Do not make it pass. The S01 seat blocked seven times, was right seven times, and spent zero rework rounds doing it. That is the behaviour this fleet wants from you.

WHAT MY PRE-DISPATCH GATE COULD NOT CHECK, said plainly rather than left as a silent gap. The gate ran nine acceptance commands at your paths and all four render-test clusters plus C5 and C6 are genuinely RED or correctly GREEN as your plan predicts. But acceptance steps S02-C6-1 and S02-C6-2 state their acceptance in PROSE, not as a runnable command, so the gate could not execute them and I have verified only the C6 CLUSTER command, which is RED because the file does not exist yet. Those two steps are categorized FEATURE-ASSERTION, so it is on YOU to confirm each one genuinely discriminates: that the affordance-inventory assertion and the pinned section-count assertion each FAIL before your change and pass after, rather than passing vacuously. ONE SPECIFIC RISK I AM HANDING YOU RATHER THAN FIXING, because the Router may not author a fix to a plan. Your S02-C5 command is a bare recursive grep over apps/ui/app/public/debate/ for forbidden mutation imports, and your plan reads its exit status with the convention that non-zero means no match means PASS. Note that grep also exits non-zero, with status 2, when the PATH DOES NOT EXIST. So if a file ever lands in a different directory than the one that command scans, S02-C5 goes green while the forbidden imports sit entirely unchecked. That is the same shape as the gitignored-path variant above. Reproduce it before you accept it, judge whether it is real, and if it is, say so on the ticket with your evidence. Under the standing rule you MAY correct a demonstrably factual error in the plan in place, provisionally, with your evidence on the ticket, but only a factual error, never design, scope, or acceptance categories.

HOW TO WORK. RED before GREEN on every FEATURE-ASSERTION: clusters C1, C2, C3, C4 and C6 are all genuinely RED right now and must be seen RED before you make them green. C5 is VERIFICATION-ONLY, it is correctly GREEN today and must STAY green, so do not fix it. Three-run law on every cluster and the WORST run is the verdict, never the best. Reproduce first on any rework. Rework rounds max 3.

WHAT YOU MAY NOT DO. No push. No merge. No commit to main. V performs every merge personally. Do not stash, commit, or discard any other mission's in-flight work you may encounter.

WHEN YOU FINISH. Write your own self-report, ten to twenty honest lines covering what went well, what fought you, and what you would change, as S02-CODE-codex.md inside the directory .hermes/reports/public-debate-access/agent-reports/ under the main repo. Then post READY FOR PEER REVIEW on ticket t_83443bb1. Return control at a spine handoff, a genuine blocker, or an IMPORTANT OPERATION, but keep the goal alive and resumable. Silence is normal and unchanged state needs no message." \
  < /dev/null 2>&1 | tee "$LOG"
echo "=== S02-CODE exited. Log: $LOG ==="
