#!/bin/zsh
REPO=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine
BRIEF=$REPO/.hermes/reports/public-debate-access/packets/ARCH-01-strict.md
SID=17d6551f-b33c-4a98-bad5-8082e402dbfa
LOG=$REPO/.hermes/planning/public-debate-access/logs/ARCH-01-strict-claude.log
[ -f "$BRIEF" ] || { echo "FATAL: brief missing at $BRIEF"; exit 1; }
cd "$REPO" || exit 1
echo "ARCH-01 .strict() step (V Row 9) · ticket t_a00a162e"
claude --resume "$SID" -p "V HAS RULED, DECISIONS Row 9: the contract's lone .passthrough() becomes .strict(), chosen deliberately over silent stripping and over deferral. THE DECISION IS MADE - do not re-litigate it. Your brief is at $BRIEF - read it IN FULL and follow it exactly. Your job is to AUTHOR THE STEP that implements the ruling correctly, on S01, whose surface is packages/contract. THE FINDING, reproduced by the Router and committed as a probe at .hermes/reports/public-debate-access/probes/passthrough-probe.mts: packages/contract/src/index.ts line 434 inside NodeSchema at 424, which PublicDebateSchema reaches through answer.nodes, is the ONLY passthrough in the contract while everything else on the anonymous path is strict. The probe parses successfully with keys_that_survived showing check_status AND a smuggled SMUGGLED_OWNER_SECRET whose value is ledger colon abc-123, so an owner-shaped value survives validation into the parsed public envelope - which buildPublicAnswerExport then spreads wholesale into a downloadable file for anonymous readers. THREE THINGS THE STEP MUST HAVE. First a REAL RED-before-GREEN acceptance: a test asserting an unknown key under stranger_restatement is REJECTED, which must FAIL against the current contract and PASS after the change, and you must verify that by RUNNING it both ways rather than by reasoning. Take the Router's probe as a starting point and not as the acceptance, and note it took three attempts to build a VALID fixture - way_of_knowing is an enum of LOOKED_UP RAN REASONING, LabeledNumberSchema needs value and kind and producer, and NodeSchema needs relevant_as_of - because an invalid fixture fails for the wrong reason and proves nothing, which is this mission's signature defect. Second a BLAST RADIUS answer that is MEASURED and not assumed: which callers parse NodeSchema, and does any producer or test currently pass an extra key under stranger_restatement, because strict turns a silent widening into a hard failure and if anything does pass one it breaks - V accepted that trade-off knowingly but the fleet still needs the number. Third, say plainly in DECISIONS that this REOPENS committed and already-reviewed S01 at 4138f72, and why that was judged worth it. SCOPE: S01 PLAN and DECISIONS only. No product code, no test files, no worktrees - a coding seat implements afterwards. A seat is live in .worktrees/s02-code; do not disturb it. SPECs remain FROZEN. Handoff opens with SKILLS LOADED. Return control at REWORK READY FOR REVIEW or a genuine blocker." \
  --permission-mode bypassPermissions 2>&1 | tee "$LOG"
echo "=== ARCH-01 strict exited. Log: $LOG ==="
