#!/bin/zsh
WT=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/rev-04/dialectical-engine
PACKET=$WT/.hermes/reports/public-debate-access/packets/REV-04.md
LOG=/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/planning/public-debate-access/logs/REV-04-grok.log
[ -f "$PACKET" ] || { echo "FATAL: packet missing at $PACKET"; exit 1; }
[ -d "$WT" ]     || { echo "FATAL: worktree missing at $WT"; exit 1; }
[ -f "$WT/packages/contract/generated/client.ts" ] || { echo "FATAL: generated client missing — run pnpm run generate:contract first"; exit 1; }
cd "$WT" || exit 1
echo "REV-04 · BLIND CODE REVIEW of S01 · Grok · ticket t_f3f1767a · worktree $WT"
~/.grok/bin/grok -p "You are the blind CODE REVIEW seat on mission public-debate-access, board public-debate-access, ticket t_f3f1767a. Your complete goal packet is at $PACKET . Read that packet IN FULL before anything else, then follow it exactly. Your handoff must OPEN with the line 'SKILLS LOADED:' naming every skill you actually loaded; naming one you did not load is a fabrication finding against you. Read .hermes/TOOLING-TRAPS.md early - it is in your worktree and it already contains the traps this mission has paid for, including one filed on your behalf: a lens worktree needs generate:contract as well as install, which has been done for you, so the publication tests really do run here. You are a BLIND lens: you did not write this code and you did not write the plan. DEFAULT POSTURE REFUTE. THE SINGLE QUESTION THAT MATTERS MOST, and phrase it to yourself exactly this way because this framing is what found the last blocking defect: construct a case where an OWNER-ONLY VALUE REACHES AN ANONYMOUS READER despite the projection. Do not review the redaction - try to defeat it. If you find one it is blocking. Also try to break back-compat against the single existing publication, the disclosed answer-only legacy path where both a silent 404 and a silent answer-only page are banned, and RED-first reality: apply the wholesale-spread mutant yourself and confirm the residual tests actually fail, because if they pass the redaction is not pinned. Reproduce before you report; a finding without a reproduction is a hypothesis. Say plainly what you could not do rather than inferring it. Do NOT condemn a regression-baseline or verification-only step for being legitimately green. Write your self-report inside this worktree before finishing. Return control at your verdict, a genuine blocker, or an IMPORTANT OPERATION; otherwise keep working and keep the session alive and resumable." \
  -m grok-4.5 --permission-mode bypassPermissions 2>&1 | tee "$LOG"
echo "=== REV-04 seat exited. Log: $LOG ==="
