import { execFileSync,spawnSync } from 'node:child_process';
import { readFile,writeFile } from 'node:fs/promises';
const R='/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.hermes/reports/support-conversation-20260914',W='/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine/.worktrees/support-conversation-cp1/dialectical-engine',revision='0d34f82f4a2188d0ce1db04655b693798ffd2169';
const ports=[3100,3101,55433,7177,8988,8890,8891,8892,8893,8894,8895,8896];const start=JSON.parse(await readFile(`${R}/evidence/GUIDE_PREVIEW_BIND32-runtime-start.json`,'utf8')),before=JSON.parse(await readFile(`${R}/evidence/GUIDE_PREVIEW_BIND32-pre-reload.json`,'utf8'));const wait=ms=>new Promise(r=>setTimeout(r,ms));
const run=(f,a,o={})=>execFileSync(f,a,{encoding:'utf8',...o}).trim();
function listeners(){const x=spawnSync('/usr/sbin/lsof',['-nP','-iTCP','-sTCP:LISTEN','-Fpcn'],{encoding:'utf8'});if(x.status!==0)throw new Error('GUIDE_PREVIEW_BIND32_LISTENER_INVENTORY_FAILED');const rows=[];let pid=null,command=null;for(const line of x.stdout.split('\n')){if(line.startsWith('p'))pid=Number(line.slice(1));else if(line.startsWith('c'))command=line.slice(1);else if(line.startsWith('n')&&pid!==null&&command!==null){const m=/:(\d+)$/u.exec(line.slice(1));if(m)rows.push({pid,command,port:Number(m[1])})}}return rows}
let all=[],tls=0;for(let i=0;i<240;i++){try{process.kill(start.pid,0)}catch{throw new Error('GUIDE_PREVIEW_BIND32_SUPERVISOR_EXITED')};all=listeners();if(ports.every(p=>all.filter(r=>r.port===p).length===1)){const c=spawnSync('/usr/bin/curl',['--silent','--show-error','--output','/dev/null','--write-out','%{http_code}','https://localhost:3100/help'],{encoding:'utf8'});tls=Number(c.stdout);if(c.status===0&&tls===200)break}await wait(500)}
const head=run('/usr/bin/git',['rev-parse','HEAD'],{cwd:W}),clean=run('/usr/bin/git',['status','--porcelain=v1'],{cwd:W})==='';const ps=run('/bin/ps',['-o','pid=,ppid=,pgid=,command=','-p',String(start.pid)]);const m=/^(\d+)\s+(\d+)\s+(\d+)\s+(.+)$/u.exec(ps);const cwd=run('/usr/sbin/lsof',['-a','-p',String(start.pid),'-d','cwd','-Fn']).split('\n').find(x=>x.startsWith('n'))?.slice(1)??null;const preview=all.filter(r=>ports.includes(r.port));const unrelatedMissing=before.unrelatedListeners.filter(b=>!all.some(a=>a.pid===b.pid&&a.command===b.command&&a.port===b.port));
if(head!==revision||!clean||m===null||Number(m[1])!==start.pid||Number(m[2])!==1||Number(m[3])!==start.pid||!m[4].includes('pnpm dev:auth:up')||cwd!==W||preview.length!==ports.length||tls!==200||unrelatedMissing.length!==0)throw new Error('GUIDE_PREVIEW_BIND32_SUPPORTED_STACK_NOT_READY');
const custody={schemaVersion:1,node:'GUIDE_RUNTIME8',revision,pid:start.pid,pgid:start.pid,commandMarker:'pnpm dev:auth:up',runtimeLogPath:`${R}/logs/GUIDE_RUNTIME8-stack.log`,ports:{ui:3100,api:3101,postgres:55433,redis:7177,auxiliary:8988,relayStart:8890,relayEnd:8896},startedAtUtc:start.startedAtUtc,detached:true,ordinarySystemTls:{path:'/help',customCa:false,insecure:false,status:200}};
await writeFile(`${R}/evidence/GUIDE_PREVIEW_BIND32-runtime-custody.json`,`${JSON.stringify(custody,null,2)}\n`,{flag:'wx',mode:0o600});
const ready={schemaVersion:1,node:'GUIDE_RUNTIME8',observedAtUtc:new Date().toISOString(),revision,pid:start.pid,ppid:1,pgid:start.pid,cwd,commandMarker:'pnpm dev:auth:up',previewListeners:preview,unrelatedListenersPreserved:before.unrelatedListeners,ordinarySystemTls:{url:'https://localhost:3100/help',customCa:false,insecure:false,status:200},apiKbVersionConfirmation:'DEFERRED_TO_SINGLE_FRESH_STATUS_CAPACITY_GATE'};
await writeFile(`${R}/evidence/GUIDE_PREVIEW_BIND32-readiness.json`,`${JSON.stringify(ready,null,2)}\n`,{flag:'wx',mode:0o600});console.log(JSON.stringify({pid:start.pid,ports:preview.length,tls:200,unrelatedPreserved:before.unrelatedListeners.length}));
