import { createHash } from "node:crypto";
import { readdir,readFile,stat,writeFile } from "node:fs/promises";
import { join } from "node:path";

const root="/Users/vladmihaimiron/Documents/DebateAIRO/dialectical-engine",R=`${root}/.hermes/reports/support-conversation-20260914`,E=`${R}/evidence`,P=`${R}/probes/GUIDE_FOOTERLESS_FIX39`,L=`${R}/logs`,A=`${R}/agent-reports`;
const manifestPath=`${E}/GUIDE_FOOTERLESS_FIX39-manifest.json`,receiptPath=`${E}/GUIDE_FOOTERLESS_FIX39-receipt.json`,sha=b=>createHash("sha256").update(b).digest("hex");
const paths=[`${root}/.hermes/planning/support-conversation-20260914/packets/GUIDE_FOOTERLESS_FIX39.md`,`${E}/GUIDE_FOOTERLESS_FIX39-inputs.json`,`${E}/GUIDE_FOOTERLESS_FIX39-freeze-resume.json`,`${E}/GUIDE_LIVE31-receipt.json`,`${E}/GUIDE_CAPTURE_FIX38-receipt.json`,`${E}/GUIDE_FOOTERLESS_FIX39.md`,`${A}/GUIDE_FOOTERLESS_FIX39.md`];
for(const name of await readdir(P))paths.push(join(P,name));for(const name of await readdir(E))if(name.startsWith("GUIDE_FOOTERLESS_FIX39-")&&!name.endsWith("-manifest.json")&&!name.endsWith("-receipt.json"))paths.push(join(E,name));for(const name of await readdir(L))if(name.startsWith("GUIDE_FOOTERLESS_FIX39-"))paths.push(join(L,name));
const artifacts=[];for(const absolute of [...new Set(paths)].sort()){const s=await stat(absolute);if(!s.isFile())continue;const b=await readFile(absolute);artifacts.push({absolute,sha256:sha(b),bytes:b.byteLength});}
const base={schemaVersion:1,node:"GUIDE_FOOTERLESS_FIX39",ticket:"t_37ac3d2f",revision:"0d34f82f4a2188d0ce1db04655b693798ffd2169",verdict:"PASS_FOOTERLESS_HELPER_UNBOUND_REVIEW_REQUIRED",artifacts};await writeFile(manifestPath,`${JSON.stringify(base,null,2)}\n`,{flag:"wx",mode:0o600});const mb=await readFile(manifestPath);const receipt={...base,artifacts:[...artifacts,{absolute:manifestPath,sha256:sha(mb),bytes:mb.byteLength}],disposition:{controls:{passed:9,total:9},operationalTraffic:0,productChange:false,liveBinding:null,runtime9Touched:false,checkpointAcceptance:false}};await writeFile(receiptPath,`${JSON.stringify(receipt,null,2)}\n`,{flag:"wx",mode:0o600});const rb=await readFile(receiptPath);console.log(JSON.stringify({verdict:receipt.verdict,artifacts:receipt.artifacts.length,manifestSha256:sha(mb),receiptSha256:sha(rb),receiptBytes:rb.byteLength}));
