import type{Pool}from"pg";import{z}from"zod";import{canonicalDecimal,canonicalRegisterJson,type CanonicalJsonAst}from"./register-publication.js";
const backupSchema=z.object({kind:z.literal("BACKUP_EMAIL_VERIFICATION_POLICY"),policy_version:z.literal(1),proof:z.literal("AUTHENTICATED_SELF_PASSWORD_CURRENT_TOTP_AND_BOUND_EMAIL"),maximum_elapsed_ms:z.literal(1800000),per_source_across_accounts:z.literal(20),source_window_ms:z.literal(300000),proof_failures_per_attempt:z.literal(5),preserve_credentials:z.literal(true),ordinary_only:z.literal(true)}).strict();
const mfaSchema=z.object({kind:z.literal("MFA_RECOVERY_POLICY"),policy_version:z.literal(1),proof:z.literal("CURRENT_PASSWORD_AND_ISSUED_PRIOR_VERIFIED_BOUND_EMAIL"),tier_qualification:z.literal("FRESH_PROOF_PAIR_WITH_ACCOUNT_RISK_CHECKS"),email_challenge_ttl_ms:z.literal(1800000),replacement_ttl_ms:z.literal(300000),recognized_context_required:z.literal(false),recognized_context_lookback_ms:z.literal(2592000000),risk_retention_ms:z.literal(7776000000),maximum_risk_signals:z.literal(128),adverse_kinds:z.tuple([z.literal("SESSION_CONTEXT_CHANGED"),z.literal("RECOVERY_PROOF_FAILED")]),adverse_rule:z.literal("AFTER_LATEST_COMPLETED_LOGIN_OR_ANY_WITHOUT_LOGIN"),per_source_across_accounts:z.literal(20),source_window_ms:z.literal(300000),proof_failures_per_attempt:z.literal(5),cancel_cooldown_ms:z.literal(86400000),failure_cooldown_ms:z.literal(300000),preserve_password:z.literal(true),ordinary_only:z.literal(true)}).strict();
export type BackupEmailPolicy=z.infer<typeof backupSchema>;export type MfaRecoveryPolicy=z.infer<typeof mfaSchema>;
function ast(value:unknown):CanonicalJsonAst{if(typeof value==="number")return canonicalDecimal(String(value));if(value===null||typeof value==="string"||typeof value==="boolean")return value;if(Array.isArray(value))return value.map(ast);if(typeof value==="object"&&value)return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,ast(v)]));throw TypeError("EMAIL_RECOVERY_POLICY_INVALID");}
function row(key:string,value:unknown){const valueAst=ast(value);return Object.freeze({rowKey:key,valueAst,value:JSON.parse(canonicalRegisterJson(valueAst)),sourceRef:"approved-email-mfa-recovery-brief.json; Root explicit issued verified bound email plus current password recovery facet and global contest cooldown"});}
export const BACKUP_EMAIL_POLICY_REGISTER_ROW=row("backupEmailVerificationPolicy",{kind:"BACKUP_EMAIL_VERIFICATION_POLICY",policy_version:1,proof:"AUTHENTICATED_SELF_PASSWORD_CURRENT_TOTP_AND_BOUND_EMAIL",maximum_elapsed_ms:1800000,per_source_across_accounts:20,source_window_ms:300000,proof_failures_per_attempt:5,preserve_credentials:true,ordinary_only:true});
export const MFA_RECOVERY_POLICY_REGISTER_ROW=row("mfaRecoveryPolicy",{kind:"MFA_RECOVERY_POLICY",policy_version:1,proof:"CURRENT_PASSWORD_AND_ISSUED_PRIOR_VERIFIED_BOUND_EMAIL",tier_qualification:"FRESH_PROOF_PAIR_WITH_ACCOUNT_RISK_CHECKS",email_challenge_ttl_ms:1800000,replacement_ttl_ms:300000,recognized_context_required:false,recognized_context_lookback_ms:2592000000,risk_retention_ms:7776000000,maximum_risk_signals:128,adverse_kinds:["SESSION_CONTEXT_CHANGED","RECOVERY_PROOF_FAILED"],adverse_rule:"AFTER_LATEST_COMPLETED_LOGIN_OR_ANY_WITHOUT_LOGIN",per_source_across_accounts:20,source_window_ms:300000,proof_failures_per_attempt:5,cancel_cooldown_ms:86400000,failure_cooldown_ms:300000,preserve_password:true,ordinary_only:true});
export function backupEmailPolicyFromValue(v:unknown):BackupEmailPolicy{const p=backupSchema.safeParse(v);if(!p.success)throw TypeError("BACKUP_EMAIL_POLICY_INVALID");return Object.freeze(p.data);}
export function mfaRecoveryPolicyFromValue(v:unknown):MfaRecoveryPolicy{const p=mfaSchema.safeParse(v);if(!p.success)throw TypeError("MFA_RECOVERY_POLICY_INVALID");return Object.freeze(p.data);}
async function read<T>(pool:Pool,version:number,key:string,parse:(v:unknown)=>T):Promise<T|null>{if(!Number.isSafeInteger(version)||version<1)throw TypeError("EMAIL_RECOVERY_REGISTER_INVALID");const rows=(await pool.query<{value_json:unknown;sealed:boolean;row_count:number;n:string}>(`SELECT r.value_json,v.sealed,v.row_count,(SELECT count(*)::text FROM register.register_row x WHERE x.register_version=v.register_version) AS n FROM register.register_row r JOIN register.register_version v USING(register_version) WHERE r.register_version=$1 AND r.row_key=$2`,[version,key])).rows;if(rows.length===0)return null;if(rows.length!==1||!rows[0]!.sealed||rows[0]!.row_count!==Number(rows[0]!.n))throw TypeError("EMAIL_RECOVERY_REGISTER_UNSEALED");return parse(rows[0]!.value_json);}
export const readBackupEmailPolicy=(p:Pool,v:number)=>read(p,v,"backupEmailVerificationPolicy",backupEmailPolicyFromValue);
export const readMfaRecoveryPolicy=(p:Pool,v:number)=>read(p,v,"mfaRecoveryPolicy",mfaRecoveryPolicyFromValue);
